"use strict";

// Ordered list of wiki pages — imported from the per-page modules.
// Order matches navigation in views/home.html and the welcome page
// at pages/welcome.js. Adding a new page is an explicit edit here.

module.exports = [
  require("./" + "welcome"),
  require("./" + "database"),
  require("./" + "object-store"),
  require("./" + "queue-cache"),
  require("./" + "auth"),
  require("./" + "access-control"),
  require("./" + "crypto-vault"),
  require("./" + "network-crypto"),
  require("./" + "routing"),
  require("./" + "middleware"),
  require("./" + "outbound-http"),
  require("./" + "network-config"),
  require("./" + "safe-parsers"),
  require("./" + "websockets"),
  require("./" + "api-contracts"),
  require("./" + "mail"),
  require("./" + "notifications"),
  require("./" + "file-upload"),
  require("./" + "guard-overview"),
  require("./" + "guard-content"),
  require("./" + "guard-structured-data"),
  require("./" + "guard-identifiers"),
  require("./" + "guard-protocols"),
  require("./" + "guard-execution"),
  require("./" + "guard-binary"),
  require("./" + "guard-aggregate"),
  require("./" + "observability"),
  require("./" + "testing"),
  require("./" + "i18n-locale"),
  require("./" + "format-helpers"),
  require("./" + "ai-governance"),
  require("./" + "regulatory-reporting"),
  require("./" + "compliance-patterns"),
  require("./" + "cluster"),
  require("./" + "reliability"),
  require("./" + "ops-hardening"),
  require("./" + "backup-restore"),
  require("./" + "quality-contract"),
];
