"use strict";

module.exports = {
  slug:  "auth",
  title: "Authentication",
  body: [
  '<h1>Authentication</h1>',
  '<p>blamejs ships an authentication stack across five verb-shaped primitives — <code>b.auth.password</code>, <code>b.auth.passkey</code>, <code>b.auth.totp</code>, <code>b.auth.jwt</code>, <code>b.auth.oauth</code> — plus <code>b.session</code> for cookie-bound state and <code>b.auth.lockout</code> for brute-force defense. Each composes; pick the ones the app needs and ignore the rest. Authorization (RBAC, API keys, break-glass) lives at <a href="/access-control">Access Control</a>.</p>',
  '<p>The password / passkey / totp / jwt / session primitives are <strong>module-level functions</strong> — operators call <code>b.auth.password.hash(plain, opts)</code> directly without an intermediate <code>create()</code> factory. <code>b.auth.oauth</code> and <code>b.auth.lockout</code> use <code>create()</code> because they hold per-instance config (per-provider client config; per-namespace cache + ladder).</p>',

  '<h2 id="passwords">Passwords <a class="anchor" href="#passwords">#</a></h2>',
  '<p>Passwords go through Argon2id. The output is a PHC-format string (<code>$argon2id$v=19$m=65536,t=3,p=4$&lt;salt&gt;$&lt;digest&gt;</code>) that captures the algorithm + parameters + salt + digest in one column.</p>',
  '<h3>b.auth.password.hash(plain, opts) / .verify(stored, plain) / .needsRehash(stored, opts)</h3>',
  '<pre><code class="language-javascript">// hash opts (and needsRehash opts):',
  '{',
  '  memoryCost:   number,                    // default: 65536 (KiB; = 64 MiB)',
  '  timeCost:     number,                    // default: 3',
  '  parallelism:  number,                    // default: 4',
  '}',
  '',
  '// verify takes no opts — params are recovered from the stored PHC string.</code></pre>',
  '<pre><code class="language-javascript">// Register',
  'var stored = await b.auth.password.hash("hunter2");',
  '// → "$argon2id$v=19$m=65536,t=3,p=4$..."',
  '',
  '// Login (NOTE arg order: stored first, plaintext second)',
  'var ok = await b.auth.password.verify(stored, "hunter2");',
  '',
  '// Roll-forward parameters: rehash on next successful login',
  'if (ok && b.auth.password.needsRehash(stored)) {',
  '  await db.updateUser({ passwordHash: await b.auth.password.hash("hunter2") });',
  '}</code></pre>',
  '<p>The <code>verify</code> path is timing-safe and <strong>tolerates malformed input by returning false</strong> rather than throwing — login flows treat false as "credentials didn\'t match" without wrapping in try/catch. Plaintext is capped at 4096 UTF-8 bytes (sanity, not security). The Argon2 native module is prebuilt for eight platforms under <code>lib/vendor/argon2/prebuilds/</code>; nothing compiles at install time.</p>',

  '<h2 id="passkeys">Passkeys <a class="anchor" href="#passkeys">#</a></h2>',
  '<p>WebAuthn / FIDO2 sign-in lives behind <code>b.auth.passkey</code>. Four module-level functions for the two ceremonies:</p>',
  '<h3>b.auth.passkey.startRegistration(opts) / .verifyRegistration(opts)</h3>',
  '<pre><code class="language-javascript">// startRegistration:',
  '{',
  '  rpName:                  string,         // required: true — display name',
  '  rpId:                    string,         // required: true — origin host (no scheme/port)',
  '  userName:                string,         // required: true',
  '  userDisplayName:         string,         // default: opts.userName',
  '  attestationType:         "none" | "direct" | "enterprise",',
  '                                           // default: "none"',
  '  excludeCredentials:      Credential[],   // default: []',
  '  authenticatorSelection:  { residentKey, userVerification,',
  '                             authenticatorAttachment, requireResidentKey },',
  '                                           // default: { residentKey: "preferred",',
  '                                           //            userVerification: "preferred" }',
  '  hints:                   string[],       // default: ["client-device", "hybrid"]',
  '  timeout:                 number,         // default: vendor default (60000)',
  '}',
  '',
  '// verifyRegistration:',
  '{',
  '  response:           RegistrationResponse,// required: true (from browser)',
  '  expectedChallenge:  string,              // required: true (the value from start)',
  '  expectedOrigin:     string,              // required: true (full origin)',
  '  expectedRPID:       string,              // required: true',
  '}</code></pre>',
  '<h3>b.auth.passkey.startAuthentication(opts) / .verifyAuthentication(opts)</h3>',
  '<pre><code class="language-javascript">// startAuthentication:',
  '{',
  '  rpId:              string,               // required: true',
  '  userVerification:  "required" | "preferred" | "discouraged",',
  '                                           // default: "preferred"',
  '  allowCredentials:  Credential[],         // default: [] — discoverable creds',
  '}',
  '',
  '// verifyAuthentication:',
  '{',
  '  response:           AuthenticationResponse,// required: true',
  '  expectedChallenge:  string,                // required: true',
  '  expectedOrigin:     string,                // required: true',
  '  expectedRPID:       string,                // required: true',
  '  credential:         { id, publicKey, counter, transports? },',
  '                                             // required: true — DB lookup',
  '}</code></pre>',
  '<pre><code class="language-javascript">// 1. Server starts registration',
  'var opts = await b.auth.passkey.startRegistration({',
  '  rpName:    "Wiki",',
  '  rpId:      "wiki.example.com",',
  '  userName:  "alice",',
  '});',
  'req.session.passkeyChallenge = opts.challenge;   // remember for verify',
  'res.json(opts);                                  // browser calls navigator.credentials.create',
  '',
  '// 2. Browser POSTs the attestation back',
  'var verified = await b.auth.passkey.verifyRegistration({',
  '  response:           req.body,',
  '  expectedChallenge:  req.session.passkeyChallenge,',
  '  expectedOrigin:     "https://wiki.example.com",',
  '  expectedRPID:       "wiki.example.com",',
  '});',
  '// store verified.registrationInfo.credential.{id, publicKey, counter}</code></pre>',
  '<p>The wrapper threads through to the vendored SimpleWebAuthn (<code>lib/vendor/simplewebauthn-server.cjs</code>); the framework owns the namespace + AuthError shape, the vendor owns CBOR / attestation / signature work. The wrapper does NOT touch sessions, audit, or the DB — the route owns that wiring.</p>',

  '<h2 id="totp">TOTP <a class="anchor" href="#totp">#</a></h2>',
  '<p>RFC 6238 second-factor codes. Generate a shared secret per user, hand them the otpauth URI for their authenticator app, store the secret sealed in the DB, then verify codes on each login.</p>',
  '<h3>b.auth.totp.generateSecret(opts?) / .generate(secret, opts?) / .verify(secret, code, opts?) / .uri(secret, account, opts) / .generateBackupCodes(opts?)</h3>',
  '<pre><code class="language-javascript">// generateSecret opts:',
  '{',
  '  bytes:        number,                    // default: 128 (HMAC-SHA-512 block size; min 20)',
  '}',
  '',
  '// generate / verify opts:',
  '{',
  '  stepSeconds:  number,                    // default: 30',
  '  digits:       number,                    // default: 8',
  '  algorithm:    "sha256" | "sha512",       // default: "sha512" — SHA-1 NOT supported',
  '  driftSteps:   number,                    // verify only — default: 1 (±1 step = ±30s)',
  '  lastUsedStep: number,                    // verify only — replay defense within drift',
  '  now:          number,                    // test-clock injection (epoch ms)',
  '}',
  '',
  '// uri opts:',
  '{',
  '  issuer:       string,                    // required: true',
  '  digits:       number,                    // default: 8',
  '  stepSeconds:  number,                    // default: 30',
  '  algorithm:    "sha256" | "sha512",       // default: "sha512"',
  '}</code></pre>',
  '<pre><code class="language-javascript">// Enrollment',
  'var secret  = b.auth.totp.generateSecret();   // base32, 128 bytes by default',
  'var otpauth = b.auth.totp.uri(secret, "alice@example.com", { issuer: "Wiki" });',
  '// otpauth://totp/Wiki:alice@example.com?secret=...&issuer=Wiki&algorithm=SHA512&digits=8',
  '// store `secret` sealed in the DB; render `otpauth` as a QR code (operator-supplied)',
  '',
  '// Backup codes — operator wires a one-shot store',
  'var codes = b.auth.totp.generateBackupCodes();',
  '',
  '// Verification',
  'var step = b.auth.totp.verify(secret, "12345678", { driftSteps: 1, lastUsedStep: user.lastUsedStep });',
  '// step === false on no-match; otherwise the matched step number — caller persists it.',
  'if (step !== false) { await db.updateUser({ lastUsedStep: step }); }</code></pre>',
  '<p><strong>Algorithm posture.</strong> blamejs rejects SHA-1 outright at the compute path — the otpauth URI surfaces <code>algorithm=SHA512&amp;digits=8</code> for authenticators that honor it (Authy, 1Password, Bitwarden, Microsoft Authenticator, Aegis). Authenticators that ignore the URI hint and always hash with SHA-1 (older Google Authenticator builds, some hardware tokens) will silently produce non-matching codes — operators standardizing on those clients should choose a different authenticator app, not weaken the framework. SHA-256 is supported as a backward-compatible step-down.</p>',
  '<p><strong>Replay defense.</strong> <code>verify()</code> returns the matched <em>step number</em> (not boolean true). Operators persist <code>lastUsedStep</code> per user so a code that already verified once can\'t verify a second time within the drift window. False on no-match.</p>',

  '<h2 id="jwt">JWT <a class="anchor" href="#jwt">#</a></h2>',
  '<p><code>b.auth.jwt</code> issues and verifies signed tokens. Default is post-quantum: <strong>SLH-DSA-SHAKE-256f</strong> (FIPS 205, hash-only, Cat-5 PQC). Opt-in <strong>ML-DSA-87</strong> (FIPS 204, lattice-based, Cat-5) for high-throughput paths where the ~80× SLH-DSA sign-time penalty matters more than the conservative-PQC argument. <strong>No classical algorithms</strong> (no EdDSA, no RSA, no ECDSA) — the framework defaults rule them out.</p>',
  '<p>Caveat: SLH-DSA signatures are ~50 KB. A base64url-encoded JWT is ~67 KB on the wire — fine for stored long-lived tokens, license attestations, or refresh tokens; not for high-frequency request-bearer tokens. ML-DSA-87 brings this to ~6 KB encoded.</p>',
  '<h3>b.auth.jwt.sign(claims, opts) / .verify(token, opts) / .decode(token)</h3>',
  '<pre><code class="language-javascript">// sign opts:',
  '{',
  '  algorithm:     "SLH-DSA-SHAKE-256f" | "ML-DSA-87",',
  '                                           // default: "SLH-DSA-SHAKE-256f"',
  '  privateKey:    string | KeyObject,       // required: true — PEM or KeyObject',
  '  kid:           string,                   // default: null — header rotation hint',
  '  typ:           string,                   // default: "JWT"',
  '  issuer:        string,                   // → claims.iss override',
  '  audience:      string | string[],        // → claims.aud override',
  '  subject:       string,                   // → claims.sub override',
  '  expiresInSec:  number,                   // → claims.exp = now + N',
  '  notBeforeSec:  number,                   // → claims.nbf = now + N',
  '  jti:           string,                   // → claims.jti override (NOT auto-minted)',
  '}',
  '',
  '// verify opts:',
  '{',
  '  publicKey:           string | KeyObject, // required: true',
  '  algorithms:          string[],           // default: ["SLH-DSA-SHAKE-256f"]',
  '  issuer:              string | string[],  // any-of match',
  '  audience:            string | string[],  // any-of match',
  '  subject:             string,             // exact match',
  '  clockToleranceSec:   number,             // default: 0',
  '}</code></pre>',
  '<pre><code class="language-javascript">// Sign — each call carries its own key (no built-in key registry)',
  'var token = await b.auth.jwt.sign(',
  '  { sub: "u-42", role: "editor" },',
  '  {',
  '    privateKey:    env("JWT_PRIVATE_KEY_PEM"),',
  '    issuer:        "https://wiki.example.com",',
  '    audience:      "https://api.example.com",',
  '    expiresInSec:  3600,',
  '    kid:           "k1",',
  '  });',
  '',
  '// Verify',
  'var claims = await b.auth.jwt.verify(token, {',
  '  publicKey:          env("JWT_PUBLIC_KEY_PEM"),',
  '  issuer:             "https://wiki.example.com",',
  '  audience:           "https://api.example.com",',
  '  clockToleranceSec:  30,',
  '});',
  '// throws AuthError("auth-jwt/expired" | "auth-jwt/invalid-signature" | "auth-jwt/aud-mismatch" | ...)',
  '',
  '// Decode without verifying — for inspection / debugging only',
  'var { header, payload } = b.auth.jwt.decode(token);</code></pre>',
  '<p>There is no built-in key registry — each <code>sign</code> / <code>verify</code> call carries its own <code>privateKey</code> / <code>publicKey</code>. Operators rolling keys keep both old and new public keys around and pass <code>algorithms</code> with both algos when accepting tokens mid-rotation. Strict NumericDate enforcement on <code>exp</code> / <code>nbf</code> / <code>iat</code> — a stringified number bypasses no checks; the verifier rejects as malformed.</p>',

  '<h2 id="oauth">OAuth 2.0 / OIDC <a class="anchor" href="#oauth">#</a></h2>',
  '<p><code>b.auth.oauth.create()</code> returns a <strong>single-provider client</strong>. Apps wiring multiple IdPs call <code>create()</code> per provider and dispatch on the route.</p>',
  '<h3>b.auth.oauth.create(opts)</h3>',
  '<pre><code class="language-javascript">{',
  '  clientId:         string,                // required: true',
  '  clientSecret:     string,                // default: null — public clients omit',
  '  redirectUri:      string,                // required: true',
  '  provider:         "google" | "microsoft" | "github" | "apple" | "generic" | ...,',
  '                                           // default: null — preset selector',
  '  issuer:           string,                // override preset / required for generic',
  '  scope:            string[],              // default: preset default or ["openid"]',
  '  pkce:             boolean,               // default: true',
  '  isOidc:           boolean,               // default: preset value or true',
  '  clockSkewMs:      number,                // default: framework default',
  '  discoveryCacheMs: number,                // default: framework default',
  '  jwksCacheMs:      number,                // default: discoveryCacheMs',
  '  acceptedAlgorithms: string[],            // default: framework default list',
  '  allowHttp:        boolean,               // default: false — localhost dev only',
  '  responseMode:     string,                // default: preset value',
  '  // Endpoint overrides (omit when preset supplies them):',
  '  authorizationEndpoint: string,',
  '  tokenEndpoint:         string,',
  '  userinfoEndpoint:      string,',
  '  jwksUri:               string,',
  '}</code></pre>',
  '<pre><code class="language-javascript">var google = b.auth.oauth.create({',
  '  provider:     "google",',
  '  clientId:     env("GOOGLE_CLIENT_ID"),',
  '  clientSecret: env("GOOGLE_CLIENT_SECRET"),',
  '  redirectUri:  "https://wiki.example.com/auth/google/callback",',
  '});',
  '',
  'router.get("/auth/google", async function (req, res) {',
  '  var url = await google.startAuthorization({ req, res });',
  '  res.redirect(url);',
  '});',
  '',
  'router.get("/auth/google/callback", async function (req, res) {',
  '  var profile = await google.handleCallback({ req });',
  '  // profile.sub / .email / .name / .picture from userinfo',
  '});</code></pre>',
  '<p>State tokens are HMAC-bound to the session and one-shot; PKCE is on by default; <code>id_token</code> nonce is enforced on OIDC providers. The <code>generic</code> preset (or no preset) accepts explicit endpoint overrides for anything that speaks OAuth 2.0 + PKCE.</p>',

  '<h2 id="sessions">Sessions <a class="anchor" href="#sessions">#</a></h2>',
  '<p><code>b.session</code> is DB-backed server-side state. The session id (sid) is 32 random bytes returned to the caller exactly once — the DB column stores <code>sha3(\'bj-session:\' || sid)</code>, never the sid itself. <code>data</code> and <code>userId</code> are vault-sealed; <code>userIdHash</code> indexes for <code>destroyAllForUser</code> without unsealing every row. The framework owns the storage; cookie wiring is a separate operator concern (<code>b.cookies</code> / <code>b.middleware.attachUser</code>).</p>',
  '<h3>b.session.create(opts) / .verify(token) / .destroy(token) / .destroyAllForUser(userId) / .touch(token, opts) / .purgeExpired() / .count()</h3>',
  '<pre><code class="language-javascript">// create opts:',
  '{',
  '  userId:  string,                         // required: true',
  '  data:    object,                         // default: null — sealed at rest',
  '  ttlMs:   number,                         // default: C.TIME.days(7) — max C.TIME.days(3650)',
  '}',
  '',
  '// touch opts:',
  '{',
  '  extendBy:  number,                       // default: 0 — bump expiresAt by N ms',
  '}</code></pre>',
  '<pre><code class="language-javascript">// Login',
  'var { token, expiresAt } = await b.session.create({ userId: "u-42", data: { role: "editor" } });',
  'res.cookie("blamejs_sid", token, { httpOnly: true, secure: true, sameSite: "Lax" });',
  '',
  '// Per-request',
  'var session = await b.session.verify(req.cookies.blamejs_sid);',
  '// → null on missing/expired/invalid; otherwise { userId, data, createdAt, expiresAt, lastActivity }',
  '',
  '// Logout',
  'await b.session.destroy(token);',
  '',
  '// Force logout everywhere — admin tool, post-incident response',
  'await b.session.destroyAllForUser("u-42");',
  '',
  '// Sliding TTL: refresh expiresAt on activity',
  'await b.session.touch(token, { extendBy: C.TIME.hours(1) });</code></pre>',
  '<p>Cluster posture: <code>create</code>, <code>destroy</code>, <code>destroyAllForUser</code>, <code>touch</code>, <code>purgeExpired</code> are <strong>leader-only</strong> (followers throw <code>NotLeaderError</code>). <code>verify</code> and <code>count</code> run on any node. DB exfiltration alone cannot impersonate a session — the attacker would also need the original sid which only the user has.</p>',

  '<h2 id="lockout">Lockout <a class="anchor" href="#lockout">#</a></h2>',
  '<p><code>b.auth.lockout</code> tracks failed attempts per key (a username, an email, an IP — operator\'s call) and engages a cooldown when an attacker burns through <code>maxAttempts</code>. Argon2id makes <em>offline</em> brute force expensive; lockout is the <em>online</em> defense — without it an attacker can drive 250ms password verifies as fast as the network allows.</p>',
  '<h3>b.auth.lockout.create(opts)</h3>',
  '<pre><code class="language-javascript">{',
  '  namespace:         string,               // required: true — counter scope',
  '  cache:             CacheInstance,        // required: true — b.cache instance',
  '  maxAttempts:       number,               // default: 5',
  '  windowMs:          number,               // default: C.TIME.minutes(15) — counter decay',
  '  lockoutDurations:  number[] | (n) =&gt; number,',
  '                                           // default: [1m, 5m, 15m, 1h, 6h] (in ms)',
  '                                           //          clamped at the last entry',
  '  audit:             AuditTap,             // default: null',
  '  auditFailures:     boolean,              // default: true',
  '  auditEngaged:      boolean,              // default: true',
  '  auditUnlock:       boolean,              // default: true',
  '  auditSuccess:      boolean,              // default: false',
  '  observability:     ObservabilityTap,     // default: null',
  '  clock:             () =&gt; number,         // default: Date.now',
  '}</code></pre>',
  '<pre><code class="language-javascript">var loginLock = b.auth.lockout.create({',
  '  namespace: "login",',
  '  cache:     b.cache.create({ namespace: "auth.lockout.login", backend: "cluster" }),',
  '  audit:     b.audit,',
  '});',
  '',
  '// Pre-check: skip the 250ms verify when the account is already locked.',
  'var state = await loginLock.check(req.body.email);',
  'if (state.locked) {',
  '  return res.status(429).json({ lockedUntil: state.lockedUntil });',
  '}',
  '',
  'var ok = await b.auth.password.verify(stored, req.body.password);',
  'if (!ok) {',
  '  var verdict = await loginLock.recordFailure(req.body.email, { req });',
  '  return res.status(401).json({',
  '    attemptsRemaining: Math.max(0, 5 - verdict.attempts),',
  '    lockedUntil:       verdict.lockedUntil,',
  '  });',
  '}',
  'await loginLock.recordSuccess(req.body.email, { req });',
  '// ... b.session.create, etc.</code></pre>',
  '<p>The default backoff ladder is exponential: 1m → 5m → 15m → 1h → 6h, clamped at the last entry so a determined attacker stays in the slow lane indefinitely. Failures outside the counting window decay (the counter resets), but the lockNumber persists so an attacker can\'t sleep off the ladder. A successful login clears the counter and any active lockout entirely.</p>',
  '<p>State storage is a <code>b.cache</code> instance the operator passes in — memory backend for single-process apps, cluster backend for shared state across nodes. Cache backend errors fail <em>open</em>: when Redis dies, lockouts release rather than locking the operator out of their own admin account. <code>auth.lockout.cache_error</code> observability fires so ops dashboards see the outage.</p>',
  '<p>Admin unlock for support tickets is a first-class operation:</p>',
  '<pre><code class="language-javascript">router.post("/admin/users/:id/unlock",',
  '  perms.middleware("user.unlock"),',
  '  async function (req, res) {',
  '    await loginLock.unlock(req.params.id, {',
  '      req,                                           // 5 W\'s of the admin go on the audit row',
  '      reason: req.body.reason || "support ticket",  // why',
  '    });',
  '    res.json({ ok: true });',
  '  },',
  ');</code></pre>',
  '<p>The same primitive composes around any "X attempts to do Y" surface — TOTP code entry, password-reset code submission, passkey verification, second-factor brute force. Each operator-named instance keeps its own counter namespace so login and TOTP attempts decay and lock independently.</p>',
].join("\n"),
};
