"use strict";

module.exports = {
  slug:  "auth",
  title: "Authentication",
  body: [
  '<h1>Authentication</h1>',
  '<p>blamejs ships an authentication stack across five verb-shaped primitives — <code>b.auth.password</code>, <code>b.auth.passkey</code>, <code>b.auth.totp</code>, <code>b.auth.jwt</code>, <code>b.auth.oauth</code> — plus <code>b.session</code> for cookie-bound state and <code>b.auth.lockout</code> for brute-force defense. Each composes; pick the ones the app needs and ignore the rest. Authorization (RBAC, API keys, break-glass) lives at <a href="/access-control">Access Control</a>.</p>',
  '<p>The password / passkey / totp / jwt / session primitives are <strong>module-level functions</strong> — operators call <code>b.auth.password.hash(plain, opts)</code> directly without an intermediate <code>create()</code> factory. <code>b.auth.oauth</code> and <code>b.auth.lockout</code> use <code>create()</code> because they hold per-instance config (per-provider client config; per-namespace cache + ladder).</p>',

  '<h2 id="passwords">Passwords <a class="anchor" href="#passwords">#</a></h2>',
  '<p>Passwords go through Argon2id. The output is a PHC-format string (<code>$argon2id$v=19$m=65536,t=3,p=4$&lt;salt&gt;$&lt;digest&gt;</code>) that captures the algorithm + parameters + salt + digest in one column.</p>',
  '<h3>b.auth.password.hash(plain, opts) / .verify(stored, plain) / .needsRehash(stored, opts)</h3>',
  '<pre><code class="language-javascript">// hash opts (and needsRehash opts):',
  '{',
  '  memoryCost:   number,                    // default: 65536 (KiB; = 64 MiB)',
  '  timeCost:     number,                    // default: 3',
  '  parallelism:  number,                    // default: 4',
  '}',
  '',
  '// verify takes no opts — params are recovered from the stored PHC string.</code></pre>',
  '<pre><code class="language-javascript">// Register',
  'var stored = await b.auth.password.hash("hunter2");',
  '// → "$argon2id$v=19$m=65536,t=3,p=4$..."',
  '',
  '// Login (NOTE arg order: stored first, plaintext second)',
  'var ok = await b.auth.password.verify(stored, "hunter2");',
  '',
  '// Roll-forward parameters: rehash on next successful login',
  'if (ok && b.auth.password.needsRehash(stored)) {',
  '  await db.updateUser({ passwordHash: await b.auth.password.hash("hunter2") });',
  '}</code></pre>',
  '<p>The <code>verify</code> path is timing-safe and <strong>tolerates malformed input by returning false</strong> rather than throwing — login flows treat false as "credentials didn\'t match" without wrapping in try/catch. Plaintext is capped at 4096 UTF-8 bytes (sanity, not security). Argon2 routes through Node\'s built-in <code>crypto.argon2*</code> API (Node 24.14+) so no native modules are vendored or compiled at install time.</p>',

  '<h2 id="passkeys">Passkeys <a class="anchor" href="#passkeys">#</a></h2>',
  '<p>WebAuthn / FIDO2 sign-in lives behind <code>b.auth.passkey</code>. Four module-level functions for the two ceremonies:</p>',
  '<h3>b.auth.passkey.startRegistration(opts) / .verifyRegistration(opts)</h3>',
  '<pre><code class="language-javascript">// startRegistration:',
  '{',
  '  rpName:                  string,         // required: true — display name',
  '  rpId:                    string,         // required: true — origin host (no scheme/port)',
  '  userName:                string,         // required: true',
  '  userDisplayName:         string,         // default: opts.userName',
  '  attestationType:         "none" | "direct" | "enterprise",',
  '                                           // default: "none"',
  '  excludeCredentials:      Credential[],   // default: []',
  '  authenticatorSelection:  { residentKey, userVerification,',
  '                             authenticatorAttachment, requireResidentKey },',
  '                                           // default: { residentKey: "preferred",',
  '                                           //            userVerification: "preferred" }',
  '  hints:                   string[],       // default: ["client-device", "hybrid"]',
  '  timeout:                 number,         // default: vendor default (60000)',
  '}',
  '',
  '// verifyRegistration:',
  '{',
  '  response:           RegistrationResponse,// required: true (from browser)',
  '  expectedChallenge:  string,              // required: true (the value from start)',
  '  expectedOrigin:     string,              // required: true (full origin)',
  '  expectedRPID:       string,              // required: true',
  '}</code></pre>',
  '<h3>b.auth.passkey.startAuthentication(opts) / .verifyAuthentication(opts)</h3>',
  '<pre><code class="language-javascript">// startAuthentication:',
  '{',
  '  rpId:              string,               // required: true',
  '  userVerification:  "required" | "preferred" | "discouraged",',
  '                                           // default: "preferred"',
  '  allowCredentials:  Credential[],         // default: [] — discoverable creds',
  '}',
  '',
  '// verifyAuthentication:',
  '{',
  '  response:           AuthenticationResponse,// required: true',
  '  expectedChallenge:  string,                // required: true',
  '  expectedOrigin:     string,                // required: true',
  '  expectedRPID:       string,                // required: true',
  '  credential:         { id, publicKey, counter, transports? },',
  '                                             // required: true — DB lookup',
  '}</code></pre>',
  '<pre><code class="language-javascript">// 1. Server starts registration',
  'var opts = await b.auth.passkey.startRegistration({',
  '  rpName:    "Wiki",',
  '  rpId:      "wiki.example.com",',
  '  userName:  "alice",',
  '});',
  'req.session.passkeyChallenge = opts.challenge;   // remember for verify',
  'res.json(opts);                                  // browser calls navigator.credentials.create',
  '',
  '// 2. Browser POSTs the attestation back',
  'var verified = await b.auth.passkey.verifyRegistration({',
  '  response:           req.body,',
  '  expectedChallenge:  req.session.passkeyChallenge,',
  '  expectedOrigin:     "https://wiki.example.com",',
  '  expectedRPID:       "wiki.example.com",',
  '});',
  '// store verified.registrationInfo.credential.{id, publicKey, counter}</code></pre>',
  '<p>The wrapper threads through to the vendored SimpleWebAuthn (<code>lib/vendor/simplewebauthn-server.cjs</code>); the framework owns the namespace + AuthError shape, the vendor owns CBOR / attestation / signature work. The wrapper does NOT touch sessions, audit, or the DB — the route owns that wiring.</p>',

  '<h2 id="totp">TOTP <a class="anchor" href="#totp">#</a></h2>',
  '<p>RFC 6238 second-factor codes. Generate a shared secret per user, hand them the otpauth URI for their authenticator app, store the secret sealed in the DB, then verify codes on each login.</p>',
  '<h3>b.auth.totp.generateSecret(opts?) / .generate(secret, opts?) / .verify(secret, code, opts?) / .uri(secret, account, opts) / .generateBackupCodes(opts?)</h3>',
  '<pre><code class="language-javascript">// generateSecret opts:',
  '{',
  '  bytes:        number,                    // default: 128 (HMAC-SHA-512 block size; min 20)',
  '}',
  '',
  '// generate / verify opts:',
  '{',
  '  stepSeconds:  number,                    // default: 30',
  '  digits:       number,                    // default: 8',
  '  algorithm:    "sha256" | "sha512",       // default: "sha512" — SHA-1 NOT supported',
  '  driftSteps:   number,                    // verify only — default: 1 (±1 step = ±30s)',
  '  lastUsedStep: number,                    // verify only — replay defense within drift',
  '  now:          number,                    // test-clock injection (epoch ms)',
  '}',
  '',
  '// uri opts:',
  '{',
  '  issuer:       string,                    // required: true',
  '  digits:       number,                    // default: 8',
  '  stepSeconds:  number,                    // default: 30',
  '  algorithm:    "sha256" | "sha512",       // default: "sha512"',
  '}</code></pre>',
  '<pre><code class="language-javascript">// Enrollment',
  'var secret  = b.auth.totp.generateSecret();   // base32, 128 bytes by default',
  'var otpauth = b.auth.totp.uri(secret, "alice@example.com", { issuer: "Wiki" });',
  '// otpauth://totp/Wiki:alice@example.com?secret=...&issuer=Wiki&algorithm=SHA512&digits=8',
  '// store `secret` sealed in the DB; render `otpauth` as a QR code (operator-supplied)',
  '',
  '// Backup codes — operator wires a one-shot store',
  'var codes = b.auth.totp.generateBackupCodes();',
  '',
  '// Verification',
  'var step = b.auth.totp.verify(secret, "12345678", { driftSteps: 1, lastUsedStep: user.lastUsedStep });',
  '// step === false on no-match; otherwise the matched step number — caller persists it.',
  'if (step !== false) { await db.updateUser({ lastUsedStep: step }); }</code></pre>',
  '<p><strong>Algorithm posture.</strong> blamejs rejects SHA-1 outright at the compute path — the otpauth URI surfaces <code>algorithm=SHA512&amp;digits=8</code> for authenticators that honor it (Authy, 1Password, Bitwarden, Microsoft Authenticator, Aegis). Authenticators that ignore the URI hint and always hash with SHA-1 (older Google Authenticator builds, some hardware tokens) will silently produce non-matching codes — operators standardizing on those clients should choose a different authenticator app, not weaken the framework. SHA-256 is supported as a backward-compatible step-down.</p>',
  '<p><strong>Replay defense.</strong> <code>verify()</code> returns the matched <em>step number</em> (not boolean true). Operators persist <code>lastUsedStep</code> per user so a code that already verified once can\'t verify a second time within the drift window. False on no-match.</p>',

  '<h2 id="jwt">JWT <a class="anchor" href="#jwt">#</a></h2>',
  '<p><code>b.auth.jwt</code> issues and verifies signed tokens. Default is post-quantum: <strong>SLH-DSA-SHAKE-256f</strong> (FIPS 205, hash-only, Cat-5 PQC). Opt-in <strong>ML-DSA-87</strong> (FIPS 204, lattice-based, Cat-5) for high-throughput paths where the ~80× SLH-DSA sign-time penalty matters more than the conservative-PQC argument. <strong>No classical algorithms</strong> (no EdDSA, no RSA, no ECDSA) — the framework defaults rule them out.</p>',
  '<p>Caveat: SLH-DSA signatures are ~50 KB. A base64url-encoded JWT is ~67 KB on the wire — fine for stored long-lived tokens, license attestations, or refresh tokens; not for high-frequency request-bearer tokens. ML-DSA-87 brings this to ~6 KB encoded.</p>',
  '<h3>b.auth.jwt.sign(claims, opts) / .verify(token, opts) / .decode(token)</h3>',
  '<pre><code class="language-javascript">// sign opts:',
  '{',
  '  algorithm:     "SLH-DSA-SHAKE-256f" | "ML-DSA-87",',
  '                                           // default: "SLH-DSA-SHAKE-256f"',
  '  privateKey:    string | KeyObject,       // required: true — PEM or KeyObject',
  '  kid:           string,                   // default: null — header rotation hint',
  '  typ:           string,                   // default: "JWT"',
  '  issuer:        string,                   // → claims.iss override',
  '  audience:      string | string[],        // → claims.aud override',
  '  subject:       string,                   // → claims.sub override',
  '  expiresInSec:  number,                   // → claims.exp = now + N',
  '  notBeforeSec:  number,                   // → claims.nbf = now + N',
  '  jti:           string,                   // → claims.jti override (NOT auto-minted)',
  '}',
  '',
  '// verify opts:',
  '{',
  '  publicKey:           string | KeyObject, // required: true',
  '  algorithms:          string[],           // default: ["SLH-DSA-SHAKE-256f"]',
  '  issuer:              string | string[],  // any-of match',
  '  audience:            string | string[],  // any-of match',
  '  subject:             string,             // exact match',
  '  clockToleranceSec:   number,             // default: 0',
  '  replayStore:         object,             // default: null — opt-in jti replay defense',
  '                                           //                 (b.nonceStore.create() result)',
  '}</code></pre>',
  '<pre><code class="language-javascript">// Sign — each call carries its own key (no built-in key registry)',
  'var token = await b.auth.jwt.sign(',
  '  { sub: "u-42", role: "editor" },',
  '  {',
  '    privateKey:    env("JWT_PRIVATE_KEY_PEM"),',
  '    issuer:        "https://wiki.example.com",',
  '    audience:      "https://api.example.com",',
  '    expiresInSec:  3600,',
  '    kid:           "k1",',
  '  });',
  '',
  '// Verify',
  'var claims = await b.auth.jwt.verify(token, {',
  '  publicKey:          env("JWT_PUBLIC_KEY_PEM"),',
  '  issuer:             "https://wiki.example.com",',
  '  audience:           "https://api.example.com",',
  '  clockToleranceSec:  30,',
  '});',
  '// throws AuthError("auth-jwt/expired" | "auth-jwt/invalid-signature" | "auth-jwt/aud-mismatch" | ...)',
  '',
  '// Decode without verifying — for inspection / debugging only',
  'var { header, payload } = b.auth.jwt.decode(token);</code></pre>',
  '<p>There is no built-in key registry — each <code>sign</code> / <code>verify</code> call carries its own <code>privateKey</code> / <code>publicKey</code>. Operators rolling keys keep both old and new public keys around and pass <code>algorithms</code> with both algos when accepting tokens mid-rotation. Strict NumericDate enforcement on <code>exp</code> / <code>nbf</code> / <code>iat</code> — a stringified number bypasses no checks; the verifier rejects as malformed.</p>',

  '<p><strong>Replay defense (RFC 7519 §4.1.7).</strong> Bearer tokens captured by a TLS-terminating proxy, leaked through a log, or pulled from browser history can be replayed by anyone who holds the bytes. Wiring <code>replayStore</code> on <code>verify()</code> binds each token to its <code>jti</code> claim and refuses any second presentation within the token\'s exp window:</p>',
  '<pre><code class="language-javascript">var replayStore = b.nonceStore.create({ backend: "memory" });   // or "cluster"',
  '',
  '// At sign time, set a per-token jti (RFC 7519 §4.1.7).',
  'var token = await b.auth.jwt.sign(',
  '  { sub: "u-42", jti: b.crypto.generateToken(16) },',
  '  { privateKey: env("JWT_PRIVATE_KEY_PEM"), expiresInSec: 300 });',
  '',
  '// At verify time, pass the replay store. First call records the jti;',
  '// any later call with the same token throws auth-jwt/replay.',
  'var claims = await b.auth.jwt.verify(token, {',
  '  publicKey:    env("JWT_PUBLIC_KEY_PEM"),',
  '  replayStore:  replayStore,',
  '});</code></pre>',
  '<p>The token must carry a non-empty <code>jti</code> — without one, the verifier throws <code>auth-jwt/replay-no-jti</code> rather than silently letting every jti-less token through. The store contract is a single atomic <code>checkAndInsert(jti, expireAtMs)</code> method (no check-then-insert race window). For multi-node deployments, use the <code>cluster</code> backend so every node sees the same replay set.</p>',

  '<h2 id="dpop">DPoP <a class="anchor" href="#dpop">#</a></h2>',
  '<p><code>b.auth.dpop</code> implements <strong>RFC 9449 Demonstrating Proof of Possession</strong> — bearer tokens are bound to a per-client keypair, so an attacker who exfils the access token still can\'t replay it without also stealing the client\'s private key (which never leaves the client). Defense-in-depth on top of bearer auth.</p>',
  '<h3>b.auth.dpop.buildProof(opts) / .verify(proof, opts) / .thumbprint(jwk)</h3>',
  '<pre><code class="language-javascript">// buildProof opts (client-side):',
  '{',
  '  htm:          string,                    // required — HTTP method (uppercased)',
  '  htu:          string,                    // required — request URI (query/fragment stripped)',
  '  privateKey:   string | KeyObject | jwk,  // required — client\'s ephemeral private key',
  '  algorithm:    string,                    // default: auto-detect from key',
  '  accessToken:  string,                    // optional — emits ath = sha256(access_token)',
  '  nonce:        string,                    // optional — server-issued challenge',
  '  jti:          string,                    // default: random 16 bytes base64url',
  '  iat:          number,                    // default: now() — test-time injection',
  '}',
  '',
  '// verify opts (server-side):',
  '{',
  '  htm:                 string,             // required — expected method',
  '  htu:                 string,             // required — expected URI',
  '  algorithms:          string[],           // default: ES256/384/512, PS*, RS*, EdDSA, ML-DSA-87',
  '  iatWindowSec:        number,             // default: 60',
  '  accessToken:         string,             // when set, payload MUST carry matching ath',
  '  expectedThumbprint:  string,             // when set, lock proof to specific jkt',
  '  nonce:               string,             // when set, payload MUST match',
  '  replayStore:         object,             // b.nonceStore.create() — defends against jti replay',
  '}</code></pre>',
  '<pre><code class="language-javascript">var replayStore = b.nonceStore.create({ backend: "memory" });',
  '',
  '// Server middleware verifying the DPoP header on inbound requests',
  'router.use("/api", b.middleware.dpop({',
  '  replayStore:  replayStore,',
  '  algorithms:   ["ES256", "EdDSA", "ML-DSA-87"],',
  '  iatWindowSec: 60,',
  '  getAccessToken: function (req) {',
  '    var h = req.headers.authorization || "";',
  '    return h.toLowerCase().startsWith("bearer ") ? h.slice(7) : null;',
  '  },',
  '}));',
  '',
  '// Downstream handlers see req.dpop = { header, payload, jkt }.',
  '// Compare req.dpop.jkt to the cnf.jkt claim of the access token to',
  '// enforce key-bound bearer semantics (RFC 9449 §6).',
  'router.get("/api/me", function (req, res) {',
  '  if (req.dpop.jkt !== req.user.cnfJkt) {',
  '    res.writeHead(401); res.end("DPoP key does not match access token cnf.jkt");',
  '    return;',
  '  }',
  '  res.end(JSON.stringify({ user: req.user }));',
  '});</code></pre>',
  '<p>Default algorithm allowlist accepts the canonical DPoP set (RFC 9449 §4.2): ES256/384/512, PS256/384/512, RS256/384/512, EdDSA, plus <strong>ML-DSA-87</strong> for forward-PQC clients. <code>HS*</code> and <code>none</code> are refused outright at both build and verify time. SLH-DSA is omitted from DPoP because Node lacks SLH-DSA JWK round-trip and SLH-DSA\'s ~50 KB signatures + ~80x sign-time penalty make it a poor fit for per-request proofs regardless.</p>',
  '<p>Failure modes surface as <code>AuthError</code> with <code>auth-dpop/&lt;reason&gt;</code> codes: <code>missing-jwk</code> / <code>jwk-has-private</code> (private-key-component leak in proof header) / <code>refused-alg</code> (HMAC/none) / <code>htm-mismatch</code> / <code>htu-mismatch</code> / <code>iat-out-of-window</code> / <code>ath-mismatch</code> / <code>nonce-mismatch</code> / <code>replay</code> / <code>thumbprint-mismatch</code>.</p>',

  '<h2 id="aal">AAL — NIST SP 800-63-4 step-up <a class="anchor" href="#aal">#</a></h2>',
  '<p><code>b.auth.aal</code> implements the <strong>Authentication Assurance Level</strong> bands from NIST SP 800-63-4: <code>AAL1</code> (single factor), <code>AAL2</code> (multi-factor), <code>AAL3</code> (phishing-resistant multi-factor). Operators wire fresh-auth gates on sensitive routes (admin, financial, PHI) via <code>b.middleware.requireAal({ minimum })</code> — the framework rejects requests below the minimum with a 401 + <code>WWW-Authenticate: AAL-StepUp</code> challenge so the operator\'s frontend can trigger a re-auth flow.</p>',
  '<h3>b.auth.aal.fromMethods(methods) / .meets(actual, required) / b.middleware.requireAal(opts)</h3>',
  '<pre><code class="language-javascript">// b.middleware.requireAal opts:',
  '{',
  '  minimum:  "AAL1" | "AAL2" | "AAL3", // required: true',
  '  getAal:   function (req) { },       // default: req => req.user && req.user.aal',
  '  audit:    boolean,                  // default: true — emit auth.aal.{granted,denied}',
  '  realm:    string,                   // default: null — added to WWW-Authenticate',
  '}</code></pre>',
  '<pre><code class="language-javascript">// fromMethods: combine asserted authenticator methods into a band',
  'b.auth.aal.fromMethods({ password: true });                       // → "AAL1"',
  'b.auth.aal.fromMethods({ password: true, totp: true });           // → "AAL2"',
  'b.auth.aal.fromMethods({ webauthn: true });                       // → "AAL3"',
  'b.auth.aal.fromMethods({ passkey: true });                        // → "AAL3"',
  'b.auth.aal.fromMethods({ pin: true, hardware: true });            // → "AAL3"',
  '',
  '// meets: compare actual band against required minimum',
  'b.auth.aal.meets("AAL3", "AAL2");                                 // → true',
  'b.auth.aal.meets("AAL1", "AAL2");                                 // → false',
  '',
  '// requireAal middleware — gate sensitive routes by AAL',
  'router.use("/admin", b.middleware.requireAal({',
  '  minimum: "AAL2",',
  '  // getAal:  function (req) { return req.user.aal; },     // default',
  '  // realm:   "operator-portal",',
  '}));</code></pre>',
  '<p>The middleware reads <code>req.user.aal</code> by default; operators with a different shape (custom JWT claim, header, query string) pass <code>getAal(req)</code>. On insufficient assurance the response carries <code>WWW-Authenticate: AAL-StepUp realm="X", required="AAL2"</code>; the bespoke scheme name signals to the frontend that a step-up flow should be triggered (re-prompt for TOTP / passkey) without colliding with the generic <code>Bearer</code> challenge namespace. Audit events <code>auth.aal.granted</code> / <code>auth.aal.denied</code> emit on every check.</p>',
  '<p>Recognized authenticator methods: <code>password</code>, <code>pin</code> (memorized secrets), <code>totp</code>, <code>sms</code> (out-of-band; SMS is RESTRICTED per SP 800-63-4 §5.1.3.3 but still satisfies AAL2 with documented operator risk acceptance), <code>webauthn</code>, <code>passkey</code> (cryptographic multi-factor with verifier-attached UV — phishing-resistant per §5.2.5), <code>hardware</code> (single-factor cryptographic), <code>mtls</code>. The companion <code>b.auth.aal.AMR</code> constants object provides OIDC-conformant <code>amr</code> claim strings for operators emitting access tokens with AAL info (<code>"pwd"</code>, <code>"otp"</code>, <code>"fido-u2f"</code>, <code>"passkey"</code>, …).</p>',




  '<h2 id="oauth">OAuth 2.0 / OIDC <a class="anchor" href="#oauth">#</a></h2>',
  '<p><code>b.auth.oauth.create()</code> returns a <strong>single-provider client</strong>. Apps wiring multiple IdPs call <code>create()</code> per provider and dispatch on the route.</p>',
  '<h3>b.auth.oauth.create(opts)</h3>',
  '<pre><code class="language-javascript">{',
  '  clientId:         string,                // required: true',
  '  clientSecret:     string,                // default: null — public clients omit',
  '  redirectUri:      string,                // required: true',
  '  provider:         "google" | "microsoft" | "github" | "apple" | "generic" | ...,',
  '                                           // default: null — preset selector',
  '  issuer:           string,                // override preset / required for generic',
  '  scope:            string[],              // default: preset default or ["openid"]',
  '  pkce:             true,                  // OAuth 2.1 — required, no opt-out',
  '  isOidc:           boolean,               // default: preset value or true',
  '  clockSkewMs:      number,                // default: framework default',
  '  discoveryCacheMs: number,                // default: framework default',
  '  jwksCacheMs:      number,                // default: discoveryCacheMs',
  '  acceptedAlgorithms: string[],            // default: framework default list',
  '  allowHttp:        boolean,               // default: false — localhost dev only',
  '  responseMode:     string,                // default: preset value',
  '  // Endpoint overrides (omit when preset supplies them):',
  '  authorizationEndpoint: string,',
  '  tokenEndpoint:         string,',
  '  userinfoEndpoint:      string,',
  '  jwksUri:               string,',
  '}</code></pre>',
  '<pre><code class="language-javascript">var google = b.auth.oauth.create({',
  '  provider:     "google",',
  '  clientId:     env("GOOGLE_CLIENT_ID"),',
  '  clientSecret: env("GOOGLE_CLIENT_SECRET"),',
  '  redirectUri:  "https://wiki.example.com/auth/google/callback",',
  '});',
  '',
  'router.get("/auth/google", async function (req, res) {',
  '  var url = await google.startAuthorization({ req, res });',
  '  res.redirect(url);',
  '});',
  '',
  'router.get("/auth/google/callback", async function (req, res) {',
  '  var profile = await google.handleCallback({ req });',
  '  // profile.sub / .email / .name / .picture from userinfo',
  '});</code></pre>',
  '<p>State tokens are HMAC-bound to the session and one-shot; PKCE is on by default; <code>id_token</code> nonce is enforced on OIDC providers. The <code>generic</code> preset (or no preset) accepts explicit endpoint overrides for anything that speaks OAuth 2.0 + PKCE.</p>',

  '<h2 id="sessions">Sessions <a class="anchor" href="#sessions">#</a></h2>',
  '<p><code>b.session</code> is DB-backed server-side state. The session id (sid) is 32 random bytes returned to the caller exactly once — the DB column stores <code>sha3(\'bj-session:\' || sid)</code>, never the sid itself. <code>data</code> and <code>userId</code> are vault-sealed; <code>userIdHash</code> indexes for <code>destroyAllForUser</code> without unsealing every row. The framework owns the storage; cookie wiring is a separate operator concern (<code>b.cookies</code> / <code>b.middleware.attachUser</code>).</p>',
  '<h3>b.session.create(opts) / .verify(token) / .destroy(token) / .destroyAllForUser(userId) / .touch(token, opts) / .purgeExpired() / .count()</h3>',
  '<pre><code class="language-javascript">// create opts:',
  '{',
  '  userId:  string,                         // required: true',
  '  data:    object,                         // default: null — sealed at rest',
  '  ttlMs:   number,                         // default: C.TIME.days(7) — max C.TIME.days(3650)',
  '}',
  '',
  '// touch opts:',
  '{',
  '  extendBy:  number,                       // default: 0 — bump expiresAt by N ms (max C.TIME.days(3650))',
  '}</code></pre>',
  '<pre><code class="language-javascript">// Login',
  'var { token, expiresAt } = await b.session.create({ userId: "u-42", data: { role: "editor" } });',
  'res.cookie("blamejs_sid", token, { httpOnly: true, secure: true, sameSite: "Lax" });',
  '',
  '// Per-request',
  'var session = await b.session.verify(req.cookies.blamejs_sid);',
  '// → null on missing/expired/invalid; otherwise { userId, data, createdAt, expiresAt, lastActivity }',
  '',
  '// Logout',
  'await b.session.destroy(token);',
  '',
  '// Force logout everywhere — admin tool, post-incident response',
  'await b.session.destroyAllForUser("u-42");',
  '',
  '// Sliding TTL: refresh expiresAt on activity',
  'await b.session.touch(token, { extendBy: C.TIME.hours(1) });</code></pre>',
  '<p>Cluster posture: <code>create</code>, <code>destroy</code>, <code>destroyAllForUser</code>, <code>touch</code>, <code>purgeExpired</code> are <strong>leader-only</strong> (followers throw <code>NotLeaderError</code>). <code>verify</code> and <code>count</code> run on any node. DB exfiltration alone cannot impersonate a session — the attacker would also need the original sid which only the user has.</p>',

  '<h2 id="session-verify">b.session.verify(token, options) <a class="anchor" href="#session-verify">#</a></h2>',
  '<p>Verifies a presented session id, returns <code>null</code> for missing, expired, or invalid tokens, and unseals session data only after the sid hash matches.</p>',
  '<pre><code class="language-javascript">typeof b.session.verify; // "function"</code></pre>',

  '<h2 id="session-destroy">b.session.destroy(token) <a class="anchor" href="#session-destroy">#</a></h2>',
  '<p>Deletes one server-side session for logout and targeted token revocation.</p>',
  '<pre><code class="language-javascript">typeof b.session.destroy; // "function"</code></pre>',

  '<h2 id="session-destroy-all">b.session.destroyAllForUser(userId) <a class="anchor" href="#session-destroy-all">#</a></h2>',
  '<p>Revokes every active session for a user, used by password resets, offboarding, and incident response.</p>',
  '<pre><code class="language-javascript">typeof b.session.destroyAllForUser; // "function"</code></pre>',

  '<h2 id="session-touch">b.session.touch(token, options) <a class="anchor" href="#session-touch">#</a></h2>',
  '<p>Extends a session expiration window on activity while preserving the sealed session payload.</p>',
  '<pre><code class="language-javascript">typeof b.session.touch; // "function"</code></pre>',

  '<h2 id="session-purge">b.session.purgeExpired() <a class="anchor" href="#session-purge">#</a></h2>',
  '<p>Removes expired session rows during scheduled cleanup.</p>',
  '<pre><code class="language-javascript">typeof b.session.purgeExpired; // "function"</code></pre>',

  '<h2 id="session-count">b.session.count() <a class="anchor" href="#session-count">#</a></h2>',
  '<p>Returns the active session count for admin pages and operational dashboards.</p>',
  '<pre><code class="language-javascript">typeof b.session.count; // "function"</code></pre>',

  '<h2 id="lockout">Lockout <a class="anchor" href="#lockout">#</a></h2>',
  '<p><code>b.auth.lockout</code> tracks failed attempts per key (a username, an email, an IP — operator\'s call) and engages a cooldown when an attacker burns through <code>maxAttempts</code>. Argon2id makes <em>offline</em> brute force expensive; lockout is the <em>online</em> defense — without it an attacker can drive 250ms password verifies as fast as the network allows.</p>',
  '<h3>b.auth.lockout.create(opts)</h3>',
  '<pre><code class="language-javascript">{',
  '  namespace:         string,               // required: true — counter scope',
  '  cache:             CacheInstance,        // required: true — b.cache instance',
  '  maxAttempts:       number,               // default: 5',
  '  windowMs:          number,               // default: C.TIME.minutes(15) — counter decay',
  '  lockoutDurations:  number[] | (n) =&gt; number,',
  '                                           // default: [1m, 5m, 15m, 1h, 6h] (in ms)',
  '                                           //          clamped at the last entry',
  '  audit:             AuditTap,             // default: null',
  '  auditFailures:     boolean,              // default: true',
  '  auditEngaged:      boolean,              // default: true',
  '  auditUnlock:       boolean,              // default: true',
  '  auditSuccess:      boolean,              // default: false',
  '  observability:     ObservabilityTap,     // default: null',
  '  clock:             () =&gt; number,         // default: Date.now',
  '}</code></pre>',
  '<pre><code class="language-javascript">var loginLock = b.auth.lockout.create({',
  '  namespace: "login",',
  '  cache:     b.cache.create({ namespace: "auth.lockout.login", backend: "cluster" }),',
  '  audit:     b.audit,',
  '});',
  '',
  '// Pre-check: skip the 250ms verify when the account is already locked.',
  'var state = await loginLock.check(req.body.email);',
  'if (state.locked) {',
  '  return res.status(429).json({ lockedUntil: state.lockedUntil });',
  '}',
  '',
  'var ok = await b.auth.password.verify(stored, req.body.password);',
  'if (!ok) {',
  '  var verdict = await loginLock.recordFailure(req.body.email, { req });',
  '  return res.status(401).json({',
  '    attemptsRemaining: Math.max(0, 5 - verdict.attempts),',
  '    lockedUntil:       verdict.lockedUntil,',
  '  });',
  '}',
  'await loginLock.recordSuccess(req.body.email, { req });',
  '// ... b.session.create, etc.</code></pre>',
  '<p>The default backoff ladder is exponential: 1m → 5m → 15m → 1h → 6h, clamped at the last entry so a determined attacker stays in the slow lane indefinitely. Failures outside the counting window decay (the counter resets), but the lockNumber persists so an attacker can\'t sleep off the ladder. A successful login clears the counter and any active lockout entirely.</p>',
  '<p>State storage is a <code>b.cache</code> instance the operator passes in — memory backend for single-process apps, cluster backend for shared state across nodes. Cache backend errors fail <em>open</em>: when Redis dies, lockouts release rather than locking the operator out of their own admin account. <code>auth.lockout.cache_error</code> observability fires so ops dashboards see the outage.</p>',
  '<p>Admin unlock for support tickets is a first-class operation:</p>',
  '<pre><code class="language-javascript">router.post("/admin/users/:id/unlock",',
  '  perms.require("user:unlock"),',
  '  async function (req, res) {',
  '    await loginLock.unlock(req.params.id, {',
  '      req,                                           // 5 W\'s of the admin go on the audit row',
  '      reason: req.body.reason || "support ticket",  // why',
  '    });',
  '    res.json({ ok: true });',
  '  },',
  ');</code></pre>',
  '<p>The same primitive composes around any "X attempts to do Y" surface — TOTP code entry, password-reset code submission, passkey verification, second-factor brute force. Each operator-named instance keeps its own counter namespace so login and TOTP attempts decay and lock independently.</p>',

  '<h2 id="password-policy">Password policy <a class="anchor" href="#password-policy">#</a></h2>',
  '<p><code>b.auth.password.policy(opts)</code> gates weak credentials BEFORE Argon2id locks them in — minimum length, common-password denylist (the bundled <a href="https://github.com/danielmiessler/SecLists/blob/master/Passwords/Common-Credentials/10k-most-common.txt">SecLists top-10000</a> from <a href="https://github.com/danielmiessler/SecLists">Daniel Miessler / SecLists contributors</a>, CC-BY-3.0, ships at <code>lib/vendor/common-passwords-top-10000.txt</code> — thank you to the SecLists project for keeping a curated baseline freely redistributable), context-substring denial (e.g. password contains the email\'s localpart), and optional <a href="https://haveibeenpwned.com/Passwords">HaveIBeenPwned</a> k-anonymity breach check. Argon2id covers offline brute force; this primitive covers online weak / reused / phished credentials.</p>',
  '<h3>b.auth.password.policy(opts) <a class="anchor" href="#password-policy-call">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  profile:                "nist-aal2" | "pci-4.0" | "hipaa-aal2" | undefined,',
  '                                                  // operator opts into a named profile;',
  '                                                  //   per-field opts below override the profile defaults',
  '  minLength:              number,                  // default: 8 (NIST 800-63B floor)',
  '  maxLength:              number,                  // default: 4096 (Argon2 cap)',
  '  forbidCommon:           Array<string>,           // operator-supplied additional weak passwords (additive over the bundled 10k)',
  '  useBundledCommon:       boolean,                 // default: true — load the bundled SecLists top-10000 set',
  '  dictionary:             Array<string>,           // forbidden substrings (brand / product names)',
  '  denyContextSubstrings:  boolean,                 // default: true (block password containing email/username)',
  '  breachCheck:            null | "haveibeenpwned", // default: null',
  '  breachThreshold:        number,                  // default: 1 — any prior leak rejects',
  '  failClosed:             boolean,                 // default: false (HIBP outage → ok)',
  '  hibpEndpoint:           string,                  // default: "https://api.pwnedpasswords.com"',
  '  hibpTimeoutMs:          number,                  // default: 1500',
  '  mustRotateAfterMs:      null | number,           // default: null (no rotation; PCI 8.3 = 90 days)',
  '  historyMinDistance:     number,                  // default: 0 (no history; PCI 8.3.7 = 4)',
  '  complexity: {',
  '    minCategories:        number,                  // 0 = NIST default (off); 3+ = HIPAA-flavoured',
  '    categories:           ["lower","upper","digit","special"],',
  '    minRunRepeat:         number,                  // 3 = reject "aaaa…"',
  '    minSequenceLength:    number,                  // 3 = reject "abcd"/"1234"',
  '  },',
  '}</code></pre>',
  '<p>Returns <code>{ check, shouldRotate, reuseProhibited, describe }</code>. <code>check</code> gates the plaintext against every configured rule; <code>shouldRotate(passwordSetAt)</code> answers the per-account expiry check; <code>reuseProhibited(plaintext, history)</code> compares the plaintext against the last <code>historyMinDistance</code> Argon2id-hashed entries the operator passes in. Standards mapped: NIST 800-63B (default), PCI-DSS 4.0 §8.3 (<code>profile: "pci-4.0"</code>), HIPAA-flavoured (<code>profile: "hipaa-aal2"</code>). HIBP uses k-anonymity (only the first 5 hex chars of the SHA-1 hash leave the framework); SHA-1 lives in <code>lib/framework-sha1-hibp.js</code> exclusively for HIBP interop and is intentionally NOT exported on <code>b.crypto</code>.</p>',
  '<pre><code class="language-javascript">var policy = b.auth.password.policy({ profile: "pci-4.0" });',
  '',
  'router.post("/signup", async function (req, res) {',
  '  var verdict = await policy.check(req.body.password, {',
  '    email:    req.body.email,',
  '    username: req.body.username,',
  '  });',
  '  if (!verdict.ok) return res.status(400).json({ error: verdict.code, message: verdict.message });',
  '  var hash = await b.auth.password.hash(req.body.password);',
  '  // ... store hash + passwordSetAt + push onto history list ...',
  '});',
  '',
  'router.post("/change-password", async function (req, res) {',
  '  // Reuse the same policy for change flows AND check rotation + history.',
  '  if (await policy.reuseProhibited(req.body.newPassword, user.passwordHashHistory)) {',
  '    return res.status(400).json({ error: "policy/reused" });',
  '  }',
  '  var verdict = await policy.check(req.body.newPassword, { email: user.email });',
  '  if (!verdict.ok) return res.status(400).json({ error: verdict.code, message: verdict.message });',
  '  // ... hash + bump passwordSetAt + prepend to history ...',
  '});',
  '',
  '// Periodic check (e.g. on every login) — surface rotation prompt to the user',
  'if (policy.shouldRotate(user.passwordSetAt)) {',
  '  res.locals.passwordRotationDue = true;',
  '}</code></pre>',

  '<h2 id="session-fingerprint">Session anomaly detection (IP / UA fingerprint) <a class="anchor" href="#session-fingerprint">#</a></h2>',
  '<p><code>b.session.create({ req, fingerprintFields? })</code> captures a stable fingerprint (clientIp / userAgent / acceptLanguage by default; operator-extensible) and stores it HMAC\'d against the session sid in the sealed <code>data</code> column. <code>b.session.verify(token, { req })</code> recomputes the fingerprint and surfaces <code>fingerprintDrift: true</code> on mismatch. Operators audit + decide; strict mode passes <code>requireFingerprintMatch: true</code> to make drift kill the session.</p>',
  '<pre><code class="language-javascript">// Login: capture fingerprint',
  'var sess = await b.session.create({',
  '  userId: row.id,',
  '  data:   { email: row.email },',
  '  req:    req,',
  '});',
  '',
  '// Per-request: detect drift',
  'var verified = await b.session.verify(req.cookies.sid, { req: req });',
  'if (verified && verified.fingerprintDrift) {',
  '  // Audit + force step-up. Or pass requireFingerprintMatch:true to outright reject.',
  '  log.warn("session fingerprint drifted", { userId: verified.userId });',
  '}</code></pre>',
  '<p>Default mode returns the session with <code>fingerprintDrift: true</code> rather than rejecting outright — a phone roaming wifi/LTE shouldn\'t get logged out. Strict mode is for high-value sessions (admin, financial). Drift always emits <code>auth.session.fingerprint_drift</code> on the audit chain.</p>',

  '<h2 id="jwt-verify-external">b.auth.jwt.verifyExternal(token, opts) <a class="anchor" href="#jwt-verify-external">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  algorithms:  [string],                            // REQUIRED — no defaults',
  '  jwks:        [jwk, ...],                          // pre-fetched RFC 7517 keys',
  '  jwksUri:     string,                              // OR auto-fetched + TTL-cached',
  '  jwksCacheMs: number,                              // default: 10 minutes',
  '  keyResolver: async (header) => keyOrJwk,          // OR custom resolution',
  '  audience:    string | [string],                   // optional aud check',
  '  issuer:      string,                              // optional iss check',
  '  subject:     string,                              // optional sub check',
  '  clockSkewMs: number,                              // default: 30s',
  '}</code></pre>',
  '<p>Generic classical-alg JWT verifier for external IdPs (Auth0, Okta, Keycloak, Cognito, Azure AD, Google, Apple). Distinct from <code>b.auth.jwt.verify</code> which is PQC-only (ML-DSA-65/87). <code>algorithms</code> is REQUIRED with no defaults — defends the alg-confusion class (CVE-2024-54150 / CVE-2025-30144 / CVE-2026-22817 Hono). HMAC algs and <code>none</code> are explicitly refused (HMAC + JWKS public-key trust IS the alg-confusion vector). Three key-source options: pre-fetched JWKS array, auto-fetched JWKS URI (via <code>b.httpClient</code> SSRF gate + TTL cache), or operator <code>keyResolver(header)</code>. Standard claim checks (exp / nbf / iat / aud / iss / sub) with operator-tunable clockSkewMs.</p>',
  '<pre><code class="language-javascript">// Surface check — verifyExternal requires algorithms; bad input throws cleanly.',
  '// In production, pass the operator-supplied JWT + algorithms + jwks/jwksUri/keyResolver.',
  'var threw = null;',
  'try { await b.auth.jwt.verifyExternal("not-a-jwt", {}); }',
  'catch (e) { threw = e; }',
  '// threw.code === "auth-jwt-external/algorithms-required"',
  '</code></pre>',

  '<h2 id="password-params">b.auth.password.params() <a class="anchor" href="#password-params">#</a></h2>',
  '<p>Operator-audit accessor for the active Argon2id parameters. Returns <code>{ algorithm, active: { memoryCostKib, timeCost, parallelism }, owaspFloor: { memoryCostKib, timeCost, parallelism }, meetsFloor: bool }</code>. Compliance audit visibility without parsing PHC strings out of the database. The framework defaults satisfy OWASP 2026 (m ≥ 19 MiB, t ≥ 2, p ≥ 1).</p>',
  '<pre><code class="language-javascript">var p = b.auth.password.params();',
  '// p.active.memoryCostKib >= p.owaspFloor.memoryCostKib (19456 KiB / 19 MiB)',
  '// p.active.timeCost      >= p.owaspFloor.timeCost      (2)',
  '// p.active.parallelism   >= p.owaspFloor.parallelism   (1)',
  '// p.meetsFloor === true',
  '</code></pre>',

  '<h2 id="password-gate">b.auth.password.gate(n) <a class="anchor" href="#password-gate">#</a></h2>',
  '<p>Sets the process-wide Argon2id concurrency gate. Hash and verify calls acquire this semaphore before allocating Argon2 memory, preventing a login spike from turning the default 64 MiB per operation into a process OOM.</p>',
  '<pre><code class="language-javascript">// Configure once at boot based on heap and memoryCost.',
  'b.auth.password.gate(4);',
  'var params = b.auth.password.params();',
  'params.active.memoryCostKib; // active Argon2 memory setting</code></pre>',

  '<h2 id="ato-kill-switch">b.auth.atoKillSwitch.trigger(opts) <a class="anchor" href="#ato-kill-switch">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  userId:     string,  // required account/user id',
  '  reason:     string,  // required operator reason',
  '  actor:      string,  // optional admin/service actor',
  '  lockout:    object,  // optional b.auth.lockout instance',
  '  accessLock: object,  // optional b.resourceAccessLock instance',
  '}</code></pre>',
  '<p>Composite account-takeover response primitive. Operators call it from support or incident tooling to destroy every server-side session for a user and optionally engage the login lockout / access-lock controls.</p>',
  '<pre><code class="language-javascript">var action = {',
  '  userId: "u-42",',
  '  reason: "confirmed account takeover",',
  '  actor: "security-ops",',
  '};',
  '// await b.auth.atoKillSwitch.trigger(action);',
  'typeof b.auth.atoKillSwitch.trigger; // "function"</code></pre>',

  '<h2 id="step-up">Step-up authentication (RFC 9470) <a class="anchor" href="#step-up">#</a></h2>',
  '<p><code>b.auth.stepUp</code> implements RFC 9470 OAuth 2.0 Step-Up Authentication Challenge. A resource server demands a stronger or fresher authentication ceremony for sensitive routes by emitting a <code>WWW-Authenticate: Bearer error="insufficient_user_authentication", acr_values="...", max_age=...</code> challenge; clients re-trigger the IdP flow with <code>acr_values</code> / <code>max_age</code> propagated. Composes with <code>b.auth.stepUp.grant</code> for short-lived elevation tokens that bind the elevated request to the ceremony just completed.</p>',
  '<h3>b.auth.stepUp.evaluate(opts) / .buildChallenge(opts) / .parseChallenge(value) / .grant.create(opts) / .grant.verify(token, opts)</h3>',
  '<pre><code class="language-javascript">// evaluate opts:',
  '{',
  '  claims:        object,                   // required: true — verified token claims',
  '  requirement:   {',
  '    acr:                 string,           // single ACR required',
  '    acrValues:           string[],         // any-of list',
  '    maxAge:              number,           // seconds since auth_time',
  '    requiredAmr:         string[],         // every method must be present',
  '    phishingResistant:   boolean,          // any phishing-resistant amr',
  '    authorizationDetails: object[],        // RFC 9396 fine-grained',
  '  },',
  '  now:           number,                   // test-clock injection (epoch sec)',
  '}',
  '',
  '// buildChallenge opts:',
  '{',
  '  requirement:        object,              // required: true — same shape as evaluate',
  '  realm:              string,              // default: "api"',
  '  error:              string,              // default: "insufficient_user_authentication"',
  '  errorDescription:   string,              // default: human-readable RFC 9470 text',
  '  scope:              string,              // optional OAuth scope hint',
  '}</code></pre>',
  '<pre><code class="language-javascript">// 1. Sensitive route: evaluate the presented token against a requirement.',
  'var verdict = b.auth.stepUp.evaluate({',
  '  claims:      req.user.claims,',
  '  requirement: { acrValues: ["urn:mace:incommon:iap:silver"], maxAge: 300 },',
  '});',
  '',
  'if (!verdict.ok) {',
  '  // 2. Emit the RFC 9470 challenge — client re-prompts the IdP.',
  '  var challenge = b.auth.stepUp.buildChallenge({',
  '    requirement: { acrValues: ["urn:mace:incommon:iap:silver"], maxAge: 300 },',
  '    realm:       "wiki-admin",',
  '  });',
  '  res.setHeader("WWW-Authenticate", challenge);',
  '  res.writeHead(401);',
  '  res.end("step-up required");',
  '  return;',
  '}',
  '',
  '// 3. Inspect an upstream RS challenge.',
  'var parsed = b.auth.stepUp.parseChallenge(res.getHeader("WWW-Authenticate"));',
  '// → { error: "insufficient_user_authentication", acrValues: [...], maxAge: 300, ... }',
  'typeof parsed.error;</code></pre>',
  '<p>RFC 9396 helper <code>b.auth.stepUp.parseAuthorizationDetails(jsonString)</code> parses the <code>authorization_details</code> parameter when fine-grained access requests are in use; throws <code>AuthError("auth-stepUp/bad-rar")</code> on malformed payloads. The hot-path <code>evaluate</code> never throws — bad requirements come back as <code>{ ok: false, error, reason }</code> so the middleware can emit the 401 cleanly. Audit hooks <code>auth.stepup.required</code> / <code>auth.stepup.satisfied</code> emit on every check.</p>',
  '<p>Short-lived elevation grants compose on top: after the user re-authenticates, the IdP route mints a grant via <code>b.auth.stepUp.grant.create({ subject, scope, acr, amr, ttlSec })</code> and binds it to the next request via cookie or header; <code>b.auth.stepUp.grant.verify(token, { audience, scope })</code> consumes the grant and refuses replay via the elevation-grant store. <code>.grant.revoke(jti)</code> kills a grant mid-flight.</p>',

  '<h2 id="status-list">Credential status lists <a class="anchor" href="#status-list">#</a></h2>',
  '<p><code>b.auth.statusList</code> implements the IETF OAuth Token Status List draft (the canonical replacement for older SD-JWT VC and OpenID-for-Verifiable-Credentials revocation lists). An issuer publishes a JWT-wrapped, zlib-compressed bitstring at a stable URL; relying parties fetch it, check the bit at index N, and learn whether the credential whose <code>status_list</code> claim points at that URL+index is VALID (0), INVALID (1), SUSPENDED (2), or APPLICATION_SPECIFIC (3+). A million 1-bit entries collapse to ~125 KB on the wire when most bits are zero.</p>',
  '<h3>b.auth.statusList.create(opts) / .fromJwt(token, opts)</h3>',
  '<pre><code class="language-javascript">// create opts:',
  '{',
  '  size:  number,                           // required: true — number of entries',
  '  bits:  1 | 2 | 4 | 8,                    // default: 1 (per draft §6.1.1)',
  '  fill:  number,                           // default: 0 — initial status for every entry',
  '}',
  '',
  '// fromJwt opts:',
  '{',
  '  publicKey:          string | KeyObject,  // verifier public key',
  '  keyResolver:        async (header) => key,// OR custom key resolution',
  '  algorithms:         string[],            // default: framework PQC list',
  '  expectedIssuer:     string,              // optional iss check',
  '  expectedAudience:   string | string[],   // optional aud check',
  '  clockToleranceSec:  number,              // default: framework default',
  '  now:                number,              // test-clock injection (epoch ms)',
  '}</code></pre>',
  '<pre><code class="language-javascript">// Issuer side: build a list, mark some entries revoked, sign as JWT.',
  'var list = b.auth.statusList.create({ size: 1024, bits: 2 });',
  'list.set(42, b.auth.statusList.STATUS_INVALID);',
  'list.set(99, b.auth.statusList.STATUS_SUSPENDED);  // requires bits >= 2',
  '',
  '// Operator signs the list (PQC default; ML-DSA-87 / SLH-DSA-SHAKE-256f).',
  '// var jwt = await list.toJwt({',
  '//   issuer:     "https://issuer.example.com",',
  '//   subject:    "https://issuer.example.com/status/list/1",',
  '//   privateKey: env("STATUS_LIST_PRIVATE_KEY_PEM"),',
  '// });',
  '',
  '// Relying-party side: fetch the JWT, verify, query an index.',
  '// var rv = await b.auth.statusList.fromJwt(jwt, { publicKey: pem });',
  '// rv.list.get(42) === b.auth.statusList.STATUS_INVALID;',
  'typeof b.auth.statusList.create; // "function"</code></pre>',
  '<p>The compressed payload is hard-capped at 1 MiB on the wire (a million 1-bit entries compress to ~125 KB when sparse — well under the cap); operators publishing larger lists shard. The instance returned from <code>create</code> exposes <code>set(idx, status)</code> / <code>get(idx)</code> / <code>snapshot()</code> / <code>toJwt(opts)</code>; status constants <code>STATUS_VALID</code> / <code>STATUS_INVALID</code> / <code>STATUS_SUSPENDED</code> / <code>STATUS_APPLICATION_SPECIFIC</code> are exported for switch-case dispatch on the relying-party side.</p>',

  '<h2 id="sd-jwt-vc">SD-JWT VC (Selective Disclosure for Verifiable Credentials) <a class="anchor" href="#sd-jwt-vc">#</a></h2>',
  '<p><code>b.auth.sdJwtVc</code> implements the IETF SD-JWT VC draft used by the EU Digital Identity Wallet roll-out and EU AI Act Article 50 disclosure flows. An issuer mints a credential containing selectively-disclosable claims; the holder presents only the subset they choose to a verifier; the verifier validates the issuer signature plus the cryptographic binding between disclosures and the issuer\'s <code>_sd</code> digest array. Optional Key Binding JWT (KB-JWT) ties a presentation to the holder\'s ephemeral key + a verifier-supplied nonce so a captured presentation can\'t be replayed.</p>',
  '<h3>b.auth.sdJwtVc.issue(opts) / .present(opts) / .verify(presentation, opts)</h3>',
  '<pre><code class="language-javascript">// issue opts:',
  '{',
  '  issuer:               string,            // required: true',
  '  subject:              string,            // optional sub claim',
  '  vct:                  string,            // required: true — credential type URI',
  '  claims:               object,            // required: true — full claim set',
  '  selectivelyDisclosed: string[],          // claim names that go into _sd',
  '  issuerKey:            string | KeyObject,// required: true',
  '  algorithm:            "ML-DSA-87" | "ML-DSA-65" | "EdDSA" | "ES256" | "ES384",',
  '                                           // default: "ML-DSA-87"',
  '  hashAlg:              "sha-256" | "sha-512" | "sha3-256" | "sha3-512",',
  '                                           // default: "sha3-512"',
  '  ttlMs:                number,            // default: 30 days',
  '  issuedAt:             number,            // test-clock injection (epoch ms)',
  '  holderKey:            jwk,               // optional cnf-binding holder pubkey',
  '  extraHeader:          object,            // additional JWT header fields',
  '}',
  '',
  '// present opts (holder side):',
  '{',
  '  sdJwt:                string,            // required: true — issuer-minted token',
  '  disclosedClaimNames:  string[],          // subset to release to verifier',
  '  audience:             string,            // verifier identifier (KB-JWT aud)',
  '  nonce:                string,            // verifier challenge (KB-JWT nonce)',
  '  holderKey:            string | KeyObject,// holder private key for KB-JWT signing',
  '  algorithm:            string,            // default: "ML-DSA-87"',
  '  issuedAt:             number,            // test-clock injection (epoch ms)',
  '}',
  '',
  '// verify opts (verifier side):',
  '{',
  '  issuerKeyResolver:    async (header) => key,    // required: true',
  '  audience:             string,            // expected KB-JWT aud',
  '  nonce:                string,            // expected KB-JWT nonce',
  '  expectedVct:          string,            // refuse mismatched credential types',
  '  maxClockSkewSec:      number,            // default: 60',
  '  requireKeyBinding:    boolean,           // default: false — refuse without KB-JWT',
  '  now:                  number,            // test-clock injection (epoch ms)',
  '}</code></pre>',
  '<pre><code class="language-javascript">// Issuer surface — confirm the entry points exist.',
  'typeof b.auth.sdJwtVc.issue;   // "function"',
  'typeof b.auth.sdJwtVc.present; // "function"',
  'typeof b.auth.sdJwtVc.verify;  // "function"',
  '',
  '// Default crypto posture is PQC: ML-DSA-87 + sha3-512 hash for _sd digests.',
  'b.auth.sdJwtVc.DEFAULT_ALG;       // "ML-DSA-87"',
  'b.auth.sdJwtVc.DEFAULT_HASH_ALG;  // "sha3-512"',
  '// SUPPORTED_ALGS includes "ES256" for interop with non-PQC verifiers.',
  'typeof b.auth.sdJwtVc.SUPPORTED_ALGS; // "object" (frozen array)',
  '</code></pre>',
  '<p>Default posture is PQC-first per the framework rule: <code>ML-DSA-87</code> for signatures + <code>sha3-512</code> for <code>_sd</code> digests. Operators interoperating with ES256-only verifiers today pass <code>algorithm: "ES256"</code> + <code>hashAlg: "sha-256"</code> with an audited reason. The presentation format is <code>&lt;jwt&gt;~&lt;d1&gt;~&lt;d2&gt;~&lt;kbJwt?&gt;</code>; <code>verify</code> reconstructs disclosed claims by matching each disclosure\'s digest against the issuer\'s <code>_sd</code> array (any mismatch throws <code>auth-sd-jwt-vc/disclosure-mismatch</code>) and refuses replay via the KB-JWT\'s <code>sd_hash</code> binding.</p>',

  '<h2 id="access-lock">Access lock <a class="anchor" href="#access-lock">#</a></h2>',
  '<p><code>b.auth.accessLock</code> is a three-mode access posture for incident response, schema migration windows, and break-glass review. Operators flip between <code>open</code> (normal serving), <code>read-only</code> (refuse non-idempotent methods with 503), and <code>locked</code> (refuse every request except an operator-named pass-through set). A privileged role bypasses every mode so the on-call operator can always reach the unlock endpoint to restore service. Distinct from <code>b.resourceAccessLock</code> which is per-resource (row-level break-glass); accessLock is process-wide.</p>',
  '<h3>b.auth.accessLock.create(opts)</h3>',
  '<pre><code class="language-javascript">{',
  '  startMode:         "open" | "read-only" | "locked",',
  '                                           // default: "open"',
  '  unlockRoles:       string[],             // bypass set — empty = no role bypass',
  '  passthroughPaths:  Array<string | RegExp>,// always-allowed paths (health, status, unlock)',
  '  audit:             boolean,              // default: true — emit auth.access_lock.* on flip',
  '  getRole:           function (req) { },   // resolves req.user.role for the bypass check',
  '  errorMessage:      string,               // default: "service in restricted access mode"',
  '}</code></pre>',
  '<pre><code class="language-javascript">var lock = b.auth.accessLock.create({',
  '  startMode:         "open",',
  '  unlockRoles:       ["sre", "security-incident-response"],',
  '  passthroughPaths:  ["/healthz", "/readyz", "/admin/access-lock"],',
  '  getRole:           function (req) { return req.user && req.user.role; },',
  '});',
  '',
  '// Wire the middleware once at boot.',
  '// router.use(lock.middleware());',
  '',
  '// Operator-only flip endpoint, gated by permissions.',
  '// router.post("/admin/access-lock/:mode", function (req, res) {',
  '//   var verdict = lock.set(req.params.mode, { actor: req.user.id, reason: req.body.reason });',
  '//   res.json({ mode: lock.mode(), changed: verdict.changed });',
  '// });',
  '',
  'lock.mode();   // "open"',
  'lock.status(); // { mode, since, setBy, reason, passthroughPaths, unlockRoles }</code></pre>',
  '<p>Every mode flip emits <code>auth.access_lock.mode_changed</code> on the audit chain (with <code>from</code>, <code>to</code>, <code>actor</code>, <code>reason</code>) and the <code>auth.access_lock.mode_changed</code> observability metric so dashboards see the transition. In <code>read-only</code>, GET/HEAD/OPTIONS pass through and POST/PUT/PATCH/DELETE are refused with 503 + <code>Retry-After: 60</code> + <code>Cache-Control: no-store</code>. In <code>locked</code>, every request is refused except the operator-named <code>passthroughPaths</code> + any caller carrying a role in <code>unlockRoles</code>. Without <code>unlockRoles</code>, <code>locked</code> is genuinely closed and recovery requires a redeploy with a different <code>startMode</code>.</p>',

  '<h2 id="auth-time">auth_time tracker <a class="anchor" href="#auth-time">#</a></h2>',
  '<p><code>b.auth.authTime</code> is the helper module behind RFC 9470 step-up and OIDC Core 1.0 §2 <code>auth_time</code> enforcement. The <code>auth_time</code> JWT claim records when the user completed the authentication ceremony, NOT when the token was minted. A long-lived session that has been refreshed many times still carries the original <code>auth_time</code> until the user re-authenticates; step-up flows compare <code>now - auth_time</code> against the route\'s <code>max_age</code>. The module reads already-verified claims and emits scaffold claim sets for IdP code paths.</p>',
  '<h3>b.auth.authTime.readClaims(rawClaims) / .ageSec(claims, now?) / .freshEnough(claims, maxAgeSec, now?) / .buildClaims(opts) / .recommendMaxAge(opts)</h3>',
  '<pre><code class="language-javascript">// buildClaims opts:',
  '{',
  '  method:  "initial" | "refresh",          // refresh preserves prior auth_time',
  '  prevAt:  number,                         // prior auth_time when method = "refresh"',
  '  amr:     string[],                       // RFC 8176 authentication-method values',
  '  acr:     string,                         // RFC 6749 / OIDC ACR identifier',
  '  now:     number,                         // test-clock injection (epoch sec)',
  '}',
  '',
  '// recommendMaxAge opts:',
  '{',
  '  minSec:   number,                        // default: 60',
  '  maxSec:   number,                        // default: 900 (15 minutes)',
  '  default:  number,                        // default: 300 (5 minutes)',
  '}</code></pre>',
  '<pre><code class="language-javascript">// 1. Read normalized claim subset out of a verified JWT.',
  'var view = b.auth.authTime.readClaims({ auth_time: 1700000000, acr: "aal2", amr: ["pwd","otp"] });',
  '// view → { auth_time: 1700000000, acr: "aal2", amr: ["pwd","otp"] }',
  '',
  '// 2. Freshness check before serving a sensitive route.',
  'var fresh = b.auth.authTime.freshEnough(view, 300);   // require auth in last 5 min',
  '',
  '// 3. Mint claim scaffold for the IdP token endpoint.',
  'var claims = b.auth.authTime.buildClaims({',
  '  method: "initial",',
  '  amr:    ["pwd", "otp"],',
  '  acr:    "urn:mace:incommon:iap:silver",',
  '});',
  '// claims → { auth_time: <now>, amr: [...], acr: "..." }',
  '',
  '// 4. Pick a sensible max_age to feed the IdP for a step-up redirect.',
  'var maxAge = b.auth.authTime.recommendMaxAge({ default: 300 });',
  'typeof maxAge;</code></pre>',
  '<p><code>readClaims</code> normalizes <code>auth_time</code> through string-or-number coercion (some IdPs ship it as a JSON string) and returns a frozen-shape <code>{ auth_time, acr, amr }</code> view. <code>buildClaims({ method: "refresh", prevAt })</code> preserves the prior <code>auth_time</code> across token refreshes — only an actual re-auth ceremony advances it. <code>freshEnough</code> throws on a non-finite or negative <code>maxAgeSec</code> at config time; the comparison itself never throws.</p>',

  '<h2 id="fapi2">FAPI 2.0 conformance <a class="anchor" href="#fapi2">#</a></h2>',
  '<p><code>b.fapi2</code> is the OpenID Foundation FAPI 2.0 Final security-profile coordinator for financial-grade APIs. FAPI 2.0 composes existing IETF + OAuth standards (PAR, PKCE-S256, sender-constrained tokens via DPoP or mTLS, issuer-in-callback per RFC 9207, JAR for signed authorization requests) into a single profile that operators MUST satisfy to interoperate with FAPI 2.0 client deployments. The framework already ships every component primitive — FAPI 2.0 conformance is therefore a posture-coordination problem.</p>',
  '<h3>b.fapi2.assertConformance(opts)</h3>',
  '<pre><code class="language-javascript">{',
  '  senderConstraint:           "dpop" | "mtls",',
  '                                           // required: true — exactly one',
  '  parRequired:                boolean,     // default: true',
  '  pkceMethod:                 "S256",      // default: "S256" — "plain" refused',
  '  requireIssuerInCallback:    boolean,     // default: true (RFC 9207)',
  '  requireJarOnSignedRequests: boolean,     // default: true (RFC 9101)',
  '}</code></pre>',
  '<pre><code class="language-javascript">// Boot-time gate — refuses the deployment if any FAPI mandate is missing.',
  'var verdict = b.fapi2.assertConformance({',
  '  senderConstraint:        "dpop",',
  '  parRequired:             true,',
  '  requireIssuerInCallback: true,',
  '});',
  '// verdict.conformant === true',
  '// verdict.findings — five entries: pkce-s256, par-required, sender-constraint, issuer-in-callback, jar-signed-requests',
  '',
  '// Inspect an oauth client config against FAPI mandates.',
  '// b.fapi2.assertOAuthConfig({ clientId, redirectUri, dpop: true, par: true });',
  'typeof b.fapi2.assertOAuthConfig; // "function"',
  '',
  '// Returns "fapi-2.0" when b.compliance.set("fapi-2.0") was called, else null.',
  'b.fapi2.posture();',
  '</code></pre>',
  '<p><code>assertConformance</code> returns <code>{ conformant, findings }</code> with one entry per FAPI 2.0 §5 requirement; <code>conformant</code> is true only when every finding satisfies. Common boot-time wiring throws if <code>senderConstraint</code> is absent or PKCE method is anything other than <code>S256</code>. The companion <code>assertOAuthConfig(oauthOpts)</code> inspects an existing <code>b.auth.oauth.create</code> configuration object and throws <code>Fapi2Error</code> with a code naming which mandate was missed (PKCE_DISABLED / PKCE_NOT_S256 / NO_SENDER_CONSTRAINT / BOTH_SENDER_CONSTRAINTS / PAR_DISABLED). <code>posture()</code> returns <code>"fapi-2.0"</code> when <code>b.compliance.set("fapi-2.0")</code> was called for branch logic; otherwise <code>null</code>. Every assertion emits <code>fapi2.posture_asserted</code> on the audit chain.</p>',

  '<h2 id="credential-hash-verify">b.credentialHash.verify(secret, envelope) <a class="anchor" href="#credential-hash-verify">#</a></h2>',
  '<p><code>b.credentialHash.verify</code> checks a presented secret (API key, shared bearer token, webhook signing secret) against a stored envelope-versioned digest. Tolerant on the verify path — any malformed envelope, unknown algorithm byte, or truncated payload returns <code>false</code> rather than throwing, so route handlers can write <code>if (!await b.credentialHash.verify(s, row.hash)) return res.status(401)</code> without try/catch ceremony. Timing-safe comparison via <code>b.crypto.timingSafeEqual</code>.</p>',
  '<pre><code class="language-javascript">// Lookup-time verify on a request-bearer credential.',
  'var stored = await b.credentialHash.hash("sk_live_a1b2c3d4...");',
  'var ok     = await b.credentialHash.verify("sk_live_a1b2c3d4...", stored);',
  '// ok === true',
  '',
  'var bad    = await b.credentialHash.verify("sk_live_wrong", stored);',
  '// bad === false (timing-safe)',
  '',
  '// Rejects malformed input symmetrically — no exception, just false.',
  'var malformed = await b.credentialHash.verify("anything", "not-a-valid-envelope");',
  '// malformed === false',
  'typeof b.credentialHash.verify;</code></pre>',
  '<p>The envelope encodes the algorithm in byte 1, so old credentials remain verifiable when <code>ACTIVE.CRED_HASH</code> rotates to a stronger primitive. Both ends enforce a 16-byte (128-bit) minimum payload — a truncated envelope can\'t verify with a brute-forceable digest. Per-call observability event <code>credentialHash.verify</code> emits with <code>{ outcome: "success" | "failure", reason?, algo }</code> labels.</p>',

  '<h2 id="credential-hash-needs-rehash">b.credentialHash.needsRehash(envelope, opts?) <a class="anchor" href="#credential-hash-needs-rehash">#</a></h2>',
  '<p><code>b.credentialHash.needsRehash</code> is the rotation gate: returns <code>true</code> when a stored envelope was signed with an algorithm or parameter set that no longer matches the active default. Operators call it on every successful verify and rehash transparently — the same drain-by-organic-traffic pattern as <code>b.auth.password.needsRehash</code>. An unrecognized envelope migrates aggressively (returns <code>true</code>) so storage corruption surfaces as a forced rotation, not a silent stale digest.</p>',
  '<pre><code class="language-javascript">// opts:',
  '{',
  '  algo:    "shake256" | "argon2id",        // override the framework active default',
  '  params:  object,                         // algo-specific params (Argon2 m/t/p, SHAKE256 length)',
  '}</code></pre>',
  '<pre><code class="language-javascript">// On every successful verify, drain old algorithms.',
  'var stored = await b.credentialHash.hash("sk_live_secret");',
  'var stale  = b.credentialHash.needsRehash(stored);',
  '// stale === false when stored was signed by the active algorithm',
  '',
  '// When the active algorithm rotates, every prior envelope returns true:',
  '// var stale = b.credentialHash.needsRehash(rowFromYearsAgo); // true',
  '// await db.update({ credentialHash: await b.credentialHash.hash(plain) });',
  '',
  '// Inspect the envelope without verifying — operator-side rotation report.',
  'var info = b.credentialHash.inspect(stored);',
  '// info.algoName === "shake256" — current active default',
  'typeof b.credentialHash.needsRehash;</code></pre>',
  '<p>For Argon2id-stored entries, <code>needsRehash</code> defers the parameter-lag check to <code>b.auth.password.needsRehash</code> so the threshold lives in one place — when the framework\'s OWASP floor moves up (memoryCost / timeCost / parallelism), both password and credential-hash callers drain their backlogs through the same code path. The <code>opts.algo</code> override lets operators lock a specific column to <code>argon2id</code> for low-entropy operator-supplied secrets while leaving the rest of the framework on the high-throughput SHAKE256 active.</p>',

  '<h2 id="session-rotate">b.session.rotate(oldToken, opts?) <a class="anchor" href="#session-rotate">#</a></h2>',
  '<p><code>b.session.rotate</code> mints a fresh sid for the same user, atomically replacing the old sid in the row. Standard pattern: call after every authentication-state change (anonymous → logged-in, MFA verified, role escalation, password change) so any sid an attacker might have planted pre-login becomes invalid immediately. The old + new tokens never coexist — the moment the underlying UPDATE commits, only the new token verifies. Defends against session-fixation (CWE-384, OWASP A07).</p>',
  '<pre><code class="language-javascript">// opts:',
  '{',
  '  data:    object,                         // optional replacement session data (re-sealed)',
  '  ttlMs:   number,                         // optional new TTL — preserves expiresAt when absent',
  '  reason:  string,                         // free-form audit metadata ("login" / "mfa" / ...)',
  '}</code></pre>',
  '<pre><code class="language-javascript">// Login flow — rotate the anonymous-tracking sid the moment the user authenticates.',
  '// var rotated = await b.session.rotate(req.cookies.blamejs_sid, {',
  '//   data:   { userId: row.id, email: row.email, role: row.role },',
  '//   reason: "login",',
  '// });',
  '// if (!rotated) return res.status(401).send("session expired during login");',
  '// res.cookie("blamejs_sid", rotated.token, { httpOnly: true, secure: true, sameSite: "Lax" });',
  '',
  '// MFA / step-up — re-rotate after the elevated ceremony so the new privilege',
  '// state lives under a sid never seen on the wire under the old privilege.',
  '// await b.session.rotate(req.cookies.blamejs_sid, { reason: "mfa" });',
  '',
  'typeof b.session.rotate; // "function"</code></pre>',
  '<p>Returns <code>{ token, expiresAt }</code> on success or <code>null</code> when the old token doesn\'t exist / has expired (operators distinguish login-during-expiry by checking for null). Cluster-leader-only; followers throw <code>NotLeaderError</code>. Audit emits <code>auth.session.rotate</code> with the operator-supplied <code>reason</code> on every successful rotation — post-incident review traces which sid covered which privilege state.</p>',

  '<h2 id="session-device-binding">Device-Bound Sessions</h2>',
  '<h3>b.sessionDeviceBinding.create(opts) <a class="anchor" href="#session-device-binding-create">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  bindingStore:      object,    // required-or-storeInSession b.cache-shaped get/set/del store',
  '  storeInSession:    boolean,   // default: false — store fingerprint in session.data instead',
  '  session:           object,    // required when storeInSession=true',
  '  audit:             object,    // optional b.audit instance',
  '  requireBoundKey:   boolean,   // default: false — refuse when boundKeyResolver returns null',
  '  boundKeyResolver:  function,  // optional (req) -> Buffer/string/null cryptographic key',
  '  fingerprintExtras: function,  // optional (req) -> string included in fingerprint',
  '  ipPrefixBits:      object,    // default { v4: 24, v6: 48 } subnet tolerance',
  '  ttlMs:             number,    // default: 7 days',
  '  observability:     object,    // optional sink',
  '  clock:             function,  // optional injectable clock',
  '}</code></pre>',
  '<p>Computes a SHAKE256 fingerprint over <code>User-Agent</code>, sorted <code>Accept-Language</code>, sorted <code>Accept-Encoding</code>, the request IP under a /24 (IPv4) or /48 (IPv6) prefix, and an optional cryptographic bound key (DPoP <code>jkt</code>, mTLS cert SPKI hash, FIDO2 attestation). Operators call <code>bind(token, req)</code> once after session creation, then <code>verify(token, req)</code> on every authenticated request. Drift returns <code>{ ok: false, reason: "drift" }</code> and emits <code>session.device.drift</code> + <code>session.device.refused</code> audit rows. Under <code>requireBoundKey: true</code> sessions cannot bind without a resolved key and verify refuses anyone presenting the same session token from a request without that key.</p>',
  '<pre><code class="language-javascript">var memStore = (function () {',
  '  var d = new Map();',
  '  return { get: function (k) { return Promise.resolve(d.get(k)); },',
  '           set: function (k, v) { d.set(k, v); return Promise.resolve(); },',
  '           del: function (k) { d.delete(k); return Promise.resolve(); } };',
  '}());',
  'var binding = b.sessionDeviceBinding.create({ bindingStore: memStore });',
  'typeof binding.bind;    // "function"',
  'typeof binding.verify;  // "function"</code></pre>',

].join("\n"),
};
