"use strict";

module.exports = {
  slug:  "backup-restore",
  title: "Backup & Restore",
  body: [
  '<h1>Backup &amp; Restore</h1>',
  '<p>End-to-end encrypted backup bundles plus a first-deploy operator checklist. Backups go to local disk or any of the object-store backends; the bundle layout is operator-readable enough to inspect without decrypting.</p>',

  '<h2 id="backup">Backup</h2>',

  '<h3>b.backup.create(opts) <a class="anchor" href="#backup-create">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  dataDir:       string,                       // required — must exist on disk',
  '  storage:       storageBackend,               // required — see b.backup.localStorage(...) or any object-store backend',
  '  passphrase:    string | Buffer,              // required — wraps the vault key in the bundle',
  '  files:         [{ path, glob? }],            // required — operator-declared file include list',
  '  vaultKeyJson:  string | () => string,        // required — operator-supplied vault key payload',
  '  audit:         auditInstance,                // optional — emits backup.created / .failed',
  '  requireFlush:  boolean,                      // default: false — fail-closed on db flush error',
  '  residencyTag:  string | null,                // optional — destination region tag (e.g. "eu", "us")',
  '  allowCrossBorder: boolean,                   // default: false — explicit cross-border opt-in',
  '  legalBasis:    string | null,                // optional — recorded in audit chain when cross-border',
  '}</code></pre>',
  '<p>Under <code>gdpr</code> / <code>uk-gdpr</code> / <code>dpdp</code> / <code>pipl-cn</code> / <code>lgpd-br</code> / <code>appi-jp</code> / <code>pdpa-sg</code> postures, the framework refuses to create a backup pipeline whose <code>residencyTag</code> mismatches the DB residency tag (Article 46 cross-border transfer category). Operators opt in via <code>allowCrossBorder: true</code> with a documented <code>legalBasis</code> (SCCs / BCRs / adequacy decision). Undeclared <code>residencyTag</code> under regulated posture emits an audit warning rather than refusing — single-region deployments where DB and backup share the same region are the common case.</p>',
  '<p>Snapshots the framework DB plus any operator-declared collections to a configured backup location. Bundles are end-to-end encrypted at the <em>file</em> layer — every blob is independently authenticated, and the bundle\'s vault key is wrapped under the operator\'s backup passphrase so the bundle alone is opaque on disk. By default the pre-snapshot DB flush is best-effort — a flush failure logs and the snapshot proceeds against whatever\'s on disk. Operators on encrypted-at-rest with hard freshness requirements (compliance, audit, point-in-time recovery) opt in to fail-closed via <code>requireFlush: true</code>: a flush failure aborts the backup so a stale snapshot never lands in storage. Operators wire <code>b.backup.recommendedFiles()</code> for the standard framework-managed file set.</p>',
  '<pre><code class="language-javascript">// Live use binds storage + passphrase + vaultKeyJson — example shows the call shape.',
  '// var bk = b.backup.create({',
  '//   dataDir:      "./data",',
  '//   storage:      b.backup.localStorage({ rootDir: "./bundles" }),',
  '//   passphrase:   process.env.BLAMEJS_BACKUP_PASSPHRASE,',
  '//   files:        b.backup.recommendedFiles(),',
  '//   vaultKeyJson: function () { return fs.readFileSync("./data/vault.key.enc", "utf8"); },',
  '// });',
  '// var bundleId = await bk.snapshot();',
  'b.backup.create;',
  'b.backup.recommendedFiles;',
  'b.backup.localStorage;</code></pre>',

  '<h3>b.backup.runInWorker(opts) <a class="anchor" href="#backup-run-in-worker">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  workerScript: string, // required worker module path',
  '  args:         object, // passed as workerData',
  '  timeoutMs:    number, // optional hard timeout',
  '}</code></pre>',
  '<p>Dispatches backup or restore work to a worker thread so CPU-heavy encryption and checksum walks do not block the request loop. The operator supplies the worker module; the primitive owns timeout and error propagation.</p>',
  '<pre><code class="language-javascript">var workerPlan = {',
  '  workerScript: "./backup-worker.js",',
  '  args: { mode: "full" },',
  '  timeoutMs: b.constants.TIME.minutes(30),',
  '};',
  '// var result = await b.backup.runInWorker(workerPlan);',
  'typeof b.backup.runInWorker; // "function"</code></pre>',

  '<h3>b.backup.scheduleTest(opts) <a class="anchor" href="#backup-schedule-test">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  cron:        string,        // required — POSIX 5-field cron expression',
  '  restoreTo:   string,        // required — operator-controlled staging dir',
  '  verify:      async (input) => any,   // required — operator verification hook',
  '  notify:      async (event) => any,   // optional — paged on pass/fail',
  '  posture:     "hipaa" | "pci-dss" | "dora" | string, // optional — recorded in audit',
  '  expectedFingerprint: string, // optional — pin a specific audit-sign fingerprint',
  '  cleanup:     boolean,       // default true — remove staging dir post-drill',
  '  timezone:    string,        // optional — IANA TZ for the cron schedule',
  '  name:        string,        // optional — scheduler task name',
  '}</code></pre>',
  '<p>Periodic backup-restore drill required by HIPAA §164.308(a)(7)(ii)(D), PCI DSS 4.0.1 12.10.2, and DORA Article 24. The framework picks the latest bundle, restores it under the operator-supplied <code>restoreTo</code> directory, verifies the manifest signature with <code>b.backup.verifyManifestSignature</code>, then hands off to the operator&#39;s <code>verify</code> hook for deployment-specific checks (file presence, schema match, audit-chain re-verification). Pass via <code>verify()</code> emits <code>backup.test.passed</code>; throw or signature failure emits <code>backup.test.failed</code>. Operators wire the <code>notify</code> hook to page their on-call on either outcome.</p>',
  '<pre><code class="language-javascript">// var bk = b.backup.create({ scheduler: b.scheduler, ... });',
  '// bk.scheduleTest({',
  '//   cron:      "0 3 * * 0",          // weekly Sunday 03:00',
  '//   restoreTo: "/var/backup-test",',
  '//   verify:    async function ({ outDir, manifest }) { /* operator checks */ },',
  '//   notify:    async function ({ outcome }) { /* page ops */ },',
  '//   posture:   "hipaa",',
  '// });',
  'typeof b.backup.create; // "function"</code></pre>',

  '<h3>b.backup.verifyManifestSignature(target, opts) <a class="anchor" href="#backup-verify-manifest-signature">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  expectedFingerprint: string,  // optional — pin the audit-sign fingerprint',
  '}</code></pre>',
  '<p>Verifies the ML-DSA-87 (or SLH-DSA-SHAKE-256f) signature on a backup bundle&#39;s manifest. <code>target</code> is either the bundle directory path, a parsed manifest object, or <code>{ manifest }</code>. Returns <code>{ ok, fingerprint?, reason? }</code>. The signature covers the manifest&#39;s canonical bytes without the signature field, so a tampered <code>files[]</code> entry, vaultKeyEnc, or metadata fails verification. Operators tracking key rotation pass <code>expectedFingerprint</code> to refuse bundles signed under a stale historical key.</p>',
  '<pre><code class="language-javascript">// var verification = b.backup.verifyManifestSignature("/restore/bundle-2026-...");',
  '// verification.ok ? "signature verifies" : "rejected: " + verification.reason;',
  'typeof b.backup.verifyManifestSignature; // "function"</code></pre>',

  '<h3>b.drRunbook.emit(opts) <a class="anchor" href="#dr-runbook-emit">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  outDir:    string,        // required — output directory',
  '  posture:   "hipaa" | "pci-dss" | "gdpr" | "soc2" | "dora", // required',
  '  services:  [{ name, rtoMs, rpoMs }],  // optional service-level objectives',
  '  rtoMs:     number,        // optional — service-wide RTO',
  '  rpoMs:     number,        // optional — service-wide RPO',
  '  contacts:  { role: contact },  // optional — incident commander, privacy officer',
  '  budr:      object,        // optional — b.budr instance for posture deadlines',
  '  cluster:   object,        // optional — b.cluster instance for topology section',
  '  backup:    object,        // optional — b.backup instance for backup-config section',
  '  filename:  string,        // optional — defaults to runbook-<posture>.md',
  '}</code></pre>',
  '<p>Emits a posture-appropriate disaster-recovery runbook in Markdown. Composes b.budr breach-disclosure deadlines, b.cluster topology, b.backup configuration, role-recovery contacts, and posture-specific required sections (HIPAA §164.308(a)(7); PCI DSS 12.10; GDPR Art. 33; SOC 2 CC7.4 / CC9.1; DORA Art. 11/12/24). The output is plain Markdown — operators commit it under <code>docs/dr/</code> and version it with their service so re-emitting changes ship through code review.</p>',
  '<pre><code class="language-javascript">var runbookPlan = {',
  '  outDir:  "./docs/dr",',
  '  posture: "hipaa",',
  '  rtoMs:   b.constants.TIME.hours(4),',
  '  rpoMs:   b.constants.TIME.minutes(15),',
  '  contacts: { incidentCommander: "alice@example.com" },',
  '};',
  '// var out = await b.drRunbook.emit(runbookPlan);',
  'typeof b.drRunbook.emit; // "function"</code></pre>',

  '<h3>b.auditTools.forensicSnapshot(opts) <a class="anchor" href="#audit-forensic-snapshot">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  out:        string,   // required output directory',
  '  passphrase: string,   // required bundle passphrase',
  '  since:      number,   // required Unix ms lower bound',
  '  audit:      object,   // optional audit source',
  '}</code></pre>',
  '<p>Post-compromise evidence composer. It exports a sealed audit bundle, checkpoint metadata, and chain verification evidence for an investigation window. Because it writes files, examples should wire a real isolated output directory in operator tooling.</p>',
  '<pre><code class="language-javascript">var snapshotPlan = {',
  '  out: "./forensics/inc-42",',
  '  passphrase: "operator-supplied-secret",',
  '  since: Date.UTC(2026, 4, 1),',
  '};',
  '// var snap = await b.auditTools.forensicSnapshot(snapshotPlan);',
  'typeof b.auditTools.forensicSnapshot; // "function"</code></pre>',

  '<h3>b.auditTools.withRecordedAtIso(row) <a class="anchor" href="#audit-recorded-at-iso">#</a></h3>',
  '<p>Pure helper that decorates an audit row with an ISO-8601 version of its recorded timestamp for export formats and forensic reports.</p>',
  '<pre><code class="language-javascript">var row = b.auditTools.withRecordedAtIso({ recordedAt: Date.UTC(2026, 4, 1) });',
  'row.recordedAtIso; // "2026-05-01T00:00:00.000Z"</code></pre>',

  '<h3 id="backup-format">Encryption format <a class="anchor" href="#backup-format">#</a></h3>',
  '<table>',
  '  <thead><tr><th>Layer</th><th>Algorithm</th><th>Notes</th></tr></thead>',
  '  <tbody>',
  '    <tr><td>KDF</td><td>Argon2id (RFC 9106)</td><td>Memory-hard derivation; the only KDF the framework uses to stretch operator passphrases.</td></tr>',
  '    <tr><td>AEAD per file</td><td>XChaCha20-Poly1305 (RFC 8439 ext.)</td><td>Each <code>files/&lt;path&gt;.enc</code> blob carries its own 24-byte random nonce; the Poly1305 tag authenticates the ciphertext + nonce as a unit. Tampering a single byte in a blob fails its tag check on restore.</td></tr>',
  '    <tr><td>Vault-key wrap</td><td>XChaCha20-Poly1305 + Argon2id</td><td>The operator\'s vault keypair is encrypted into <code>manifest.json</code>\'s <code>vaultKeyEnc</code> under the same passphrase. Restoring without the passphrase is impossible.</td></tr>',
  '    <tr><td>Per-file integrity</td><td>SHA3-512 of plaintext</td><td>The manifest carries a SHA3-512 of each plaintext file. Restore verifies the digest after decryption.</td></tr>',
  '    <tr><td>Chain</td><td>SHA3-512 prev-hash chain</td><td>Sequential bundles carry a hash of the previous bundle\'s manifest; deletion / reordering of an archive in object storage is detectable on restore.</td></tr>',
  '  </tbody>',
  '</table>',
  '<pre><code class="language-text">&lt;bundleDir&gt;/',
  '  manifest.json          ← public metadata + base64 vaultKeyEnc + per-file sha3-512',
  '  files/',
  '    &lt;relativePath&gt;.enc  ← XChaCha20-Poly1305(blob), nonce-prefixed</code></pre>',

  '<h3 id="backup-cli">CLI surface <a class="anchor" href="#backup-cli">#</a></h3>',
  '<pre><code class="language-bash"># What does this bundle contain? (no passphrase needed — manifest only)',
  'blamejs backup inspect --bundle ./bundles/2026-04-29T12-00-00Z-abc/',
  '',
  '# Decrypt + verify into a temp dir, discard the result',
  'BLAMEJS_BACKUP_PASSPHRASE="..." blamejs backup verify \\',
  '  --bundle ./bundles/2026-04-29T12-00-00Z-abc/',
  '',
  '# Decrypt + verify into a fresh staging directory the operator can inspect',
  '# before promoting any file into the live data dir',
  'BLAMEJS_BACKUP_PASSPHRASE="..." blamejs backup extract \\',
  '  --bundle ./bundles/2026-04-29T12-00-00Z-abc/ \\',
  '  --to    ./restore-staging</code></pre>',
  '<p><code>extract</code> refuses to write into an existing directory — the framework never auto-promotes a restore into a live data dir. That decision is the operator\'s, made after looking at what came out of the bundle.</p>',

  '<h2 id="restore">Restore</h2>',

  '<h3>b.restore.create(opts) <a class="anchor" href="#restore-create">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  dataDir:         string,                     // required — target data dir to restore into',
  '  storage:         storageBackend,             // required — bundle source',
  '  passphrase:      string | Buffer,            // required — unwraps the vault key in the bundle',
  '  rollbackRoot:    string,                     // optional — where pre-restore copies of the data dir live',
  '  audit:           auditInstance,              // optional — emits restore.applied / .rolled-back / .failed',
  '  maxPulledBytes:  number,                     // default: C.BYTES.gib(4) — total bundle pull cap',
  '  maxPulledFiles:  number,                     // default: 100000 — total file count cap',
  '}</code></pre>',
  '<p>Implements the live-restore path: pull a bundle, stage it next to the live data dir, swap atomically, and roll back on failure. The framework refuses to restore into a running process — operators stop the app first, run restore, then start the app against the restored data dir. Pulled-bundle footprint is bounded — both against the storage-reported size before pull AND against the actually-pulled bytes / file-count after (defense-in-depth in case a backend lied). The companion modules <code>b.restoreBundle</code> + <code>b.restoreRollback</code> handle the bundle-level + filesystem-level steps respectively.</p>',
  '<pre><code class="language-javascript">// Live use binds storage + passphrase — example shows the call shape.',
  '// var rs = b.restore.create({',
  '//   dataDir:    "./data",',
  '//   storage:    b.backup.localStorage({ rootDir: "./bundles" }),',
  '//   passphrase: process.env.BLAMEJS_BACKUP_PASSPHRASE,',
  '// });',
  '// await rs.apply(bundleId);',
  'b.restore.create;',
  'b.restoreBundle;',
  'b.restoreRollback;</code></pre>',
  '<pre><code class="language-bash">blamejs restore apply \\',
  '  --data-dir   ./data \\',
  '  --bundle     ./bundles/2026-04-29T12-00-00Z-abc/ \\',
  '  --passphrase "$BACKUP_PASSPHRASE"</code></pre>',

  '<h3>b.backupBundle.create(opts) <a class="anchor" href="#backup-bundle-create">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  dataDir:          string,                    // required — must exist on disk',
  '  outDir:           string,                    // required — bundle directory; must NOT exist',
  '  passphrase:       string | Buffer,           // required — wraps every blob and the vault key',
  '  vaultKeyJson:     string,                    // required — vault keypair JSON, encrypted into the manifest',
  '  files:            [{ relativePath, kind, required? }], // required — explicit include list',
  '  metadata:         object,                    // optional — operator-supplied manifest annotations',
  '  progressCallback: function (event) { ... },  // optional — phase callbacks',
  '}</code></pre>',
  '<p>Lower-level bundle producer underneath <code>b.backup</code>. Walks <code>files</code> under <code>dataDir</code>, encrypts each blob with XChaCha20-Poly1305 under a fresh per-file Argon2id-derived key, computes a SHA3-512 of the plaintext, and writes <code>manifest.json</code> + <code>files/&lt;relativePath&gt;.enc</code>. <code>vaultKeyJson</code> is encrypted into <code>manifest.vaultKeyEnc</code> under the operator passphrase — a restorer on a different machine can recover the vault keypair from the bundle alone. Per-file salts ensure recovery of one file\'s key gives zero leverage on other files. Refuses to write into an existing <code>outDir</code>; the framework never auto-merges into a half-built bundle.</p>',
  '<pre><code class="language-javascript">var bundlePlan = {',
  '  dataDir:      "./data",',
  '  outDir:       "./bundles/2026-04-29T12-00-00Z-abc",',
  '  passphrase:   process.env.BLAMEJS_BACKUP_PASSPHRASE,',
  '  vaultKeyJson: "{...}",',
  '  files: [',
  '    { relativePath: "db.enc",     kind: "raw", required: true },',
  '    { relativePath: "db.key.enc", kind: "raw", required: true },',
  '  ],',
  '  metadata: { reason: "scheduled-daily" },',
  '};',
  '// var result = await b.backupBundle.create(bundlePlan);',
  'typeof b.backupBundle.create; // "function"</code></pre>',

  '<h3>b.restoreBundle.extract(opts) <a class="anchor" href="#restore-bundle-extract">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  bundleDir:        string,                    // required — must exist',
  '  stagingDir:       string,                    // required — must NOT exist',
  '  passphrase:       string | Buffer,           // required — unwraps the vault key + every blob',
  '  filter:           function (entry) { ... },  // optional — pull a subset of manifest entries',
  '  progressCallback: function (event) { ... },  // optional — phase callbacks',
  '}</code></pre>',
  '<p>Decrypts a bundle into a staging directory the operator inspects before promoting. Reads <code>manifest.json</code>, recovers the vault keypair (always, even with a filter — operators may need to unseal sealed values from a partial restore), then for each manifest entry verifies <code>encryptedSize</code> against the on-disk blob, decrypts via XChaCha20-Poly1305, verifies the SHA3-512 of the plaintext matches the manifest, and writes the recovered file under <code>stagingDir</code>. A wrong passphrase, tampered ciphertext, size mismatch, or checksum mismatch all abort with no plaintext leaked and the partial staging dir cleaned up. Refuses to merge into an existing <code>stagingDir</code>.</p>',
  '<pre><code class="language-javascript">var extractPlan = {',
  '  bundleDir:  "./bundles/2026-04-29T12-00-00Z-abc",',
  '  stagingDir: "./restore-staging",',
  '  passphrase: process.env.BLAMEJS_BACKUP_PASSPHRASE,',
  '};',
  '// var r = await b.restoreBundle.extract(extractPlan);',
  '// r.fileCount;     // number of recovered files',
  '// r.vaultKeyJson;  // decrypted vault keypair JSON',
  'typeof b.restoreBundle.extract; // "function"</code></pre>',

  '<h3>b.restoreBundle.inspect(opts) <a class="anchor" href="#restore-bundle-inspect">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  bundleDir: string, // required — must exist',
  '}</code></pre>',
  '<p>Reads and parses <code>manifest.json</code> from a bundle directory and returns it without decrypting any blob — no passphrase needed. Drives dashboards and pre-flight UI: list files, sizes, checksums, kinds, timestamps, the prev-hash chain pointer. Useful before launching a real <code>extract</code> to confirm the operator has the right bundle and the manifest has not been tampered. Cheap enough to run on every bundle in a backup tree without operator intervention.</p>',
  '<pre><code class="language-javascript">// var manifest = b.restoreBundle.inspect({',
  '//   bundleDir: "./bundles/2026-04-29T12-00-00Z-abc",',
  '// });',
  '// manifest.files.length; // number of bundled files',
  '// manifest.createdAt;    // bundle creation timestamp',
  'typeof b.restoreBundle.inspect; // "function"</code></pre>',

  '<h3>b.restoreRollback.swap(opts) <a class="anchor" href="#restore-rollback-swap">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  stagingDir:    string,  // required — freshly-extracted bundle',
  '  dataDir:       string,  // required — live data dir to replace',
  '  rollbackRoot:  string,  // optional — defaults to <dataDir>.rollbacks',
  '  marker:        object,  // optional — operator metadata (bundleId, reason)',
  '}</code></pre>',
  '<p>Atomic two-rename swap: move <code>dataDir</code> aside into a versioned rollback path, then rename <code>stagingDir</code> into <code>dataDir</code>. Filesystem renames are atomic on POSIX (and on Windows when nothing has the dir open) so the operation either fully completes or the previous <code>dataDir</code> is recoverable. Writes a sibling <code>.marker.json</code> file carrying the bundle id and reason so a later <code>list</code> / audit is informative without rifling through rollback contents. Refuses to operate if a rollback dir at the swap timestamp already exists. Operators stop the framework process before swapping — open file handles see stale data after a directory rename.</p>',
  '<pre><code class="language-javascript">var swapPlan = {',
  '  stagingDir:   "./restore-staging",',
  '  dataDir:      "./data",',
  '  rollbackRoot: "./data.rollbacks",',
  '  marker:       { bundleId: "2026-04-29T12-00-00Z-abc", reason: "scheduled-restore" },',
  '};',
  '// var r = b.restoreRollback.swap(swapPlan);',
  '// r.rollbackPath; // previous dataDir, renamed atomically',
  'typeof b.restoreRollback.swap; // "function"</code></pre>',

  '<h3>b.restoreRollback.rollback(opts) <a class="anchor" href="#restore-rollback-rollback">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  dataDir:      string, // required — live data dir to revert',
  '  rollbackPath: string, // required — must exist; produced by an earlier swap',
  '  rollbackRoot: string, // optional — for discarded-* sidelining',
  '}</code></pre>',
  '<p>Reverses an earlier swap. Moves the current <code>dataDir</code> aside under <code>rollbackRoot/discarded-&lt;timestamp&gt;</code> (so a botched restore is itself recoverable) and renames the named rollback path back into <code>dataDir</code>. Cleans up the rollback\'s marker file on success. As with <code>swap</code>, the framework process must be stopped first — directory rename does not invalidate open file handles.</p>',
  '<pre><code class="language-javascript">var rollbackPlan = {',
  '  dataDir:      "./data",',
  '  rollbackPath: "./data.rollbacks/2026-04-29T12-00-00-000Z",',
  '};',
  '// var r = await b.restoreRollback.rollback(rollbackPlan);',
  '// r.discardedAt; // path the bad dataDir was moved to',
  'typeof b.restoreRollback.rollback; // "function"</code></pre>',

  '<h3>b.restoreRollback.list(opts) <a class="anchor" href="#restore-rollback-list">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  dataDir:      string, // optional — used to derive default rollbackRoot',
  '  rollbackRoot: string, // optional — defaults to <dataDir>.rollbacks',
  '}</code></pre>',
  '<p>Lists every available rollback under <code>rollbackRoot</code>, newest first, with the marker payload attached when present. Skips <code>discarded-*</code> directories — those are not restore points, just sidelined bad data. Drives operator UI before a <code>rollback</code> call so the operator picks the right point in time, and feeds an audit report of what swaps actually happened on disk.</p>',
  '<pre><code class="language-javascript">// var rollbacks = b.restoreRollback.list({',
  '//   dataDir: "./data",',
  '// });',
  '// rollbacks[0].rollbackPath; // newest rollback',
  '// rollbacks[0].marker;       // operator metadata recorded at swap time',
  'typeof b.restoreRollback.list; // "function"</code></pre>',

  '<h3>b.restoreRollback.purge(opts) <a class="anchor" href="#restore-rollback-purge">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  dataDir:      string, // optional — used to derive default rollbackRoot',
  '  rollbackRoot: string, // optional — defaults to <dataDir>.rollbacks',
  '  keep:         number, // default: 0 — number of newest rollbacks to retain',
  '}</code></pre>',
  '<p>Reclaims rollback storage. Always sweeps every <code>discarded-*</code> directory unconditionally — those are never restore points. Then keeps the newest <code>keep</code> rollback dirs and removes the rest along with their marker files. Operators wire this into a retention schedule (e.g. keep three most-recent rollbacks alongside the bundle retention window) so a long-running deployment does not silently grow rollback storage.</p>',
  '<pre><code class="language-javascript">var purgePlan = {',
  '  dataDir: "./data",',
  '  keep:    3,',
  '};',
  '// var r = b.restoreRollback.purge(purgePlan);',
  '// r.deleted.length; // number of dirs removed',
  'typeof b.restoreRollback.purge; // "function"</code></pre>',

  '<h2 id="first-deploy">First-deploy checklist <a class="anchor" href="#first-deploy">#</a></h2>',
  '<p>The minimum-viable posture for a real deployment. The framework\'s defaults handle most of the security story; this list is the operator-side glue that turns those defaults into a defensible production app. <a href="https://github.com/blamejs/blamejs/blob/main/SECURITY.md">SECURITY.md</a> in the repo carries the full version.</p>',

  '<h3 id="first-deploy-vault">Vault &amp; passphrases <a class="anchor" href="#first-deploy-vault">#</a></h3>',
  '<ul>',
  '  <li>Set <code>BLAMEJS_VAULT_PASSPHRASE</code> to a strong CSPRNG-generated value (≥ 32 chars).</li>',
  '  <li>Set <code>BLAMEJS_AUDIT_SIGNING_PASSPHRASE</code> to a different, equally-strong value.</li>',
  '  <li>Store both in a secret manager (1Password, AWS Secrets Manager, sops-encrypted file, etc.) — never in git, never in shell history, never in the same secret entry as the database backup passphrase.</li>',
  '  <li>Schedule a quarterly rotation: <code>blamejs vault rotate</code> and <code>blamejs audit verify-chain</code> after each rotation.</li>',
  '</ul>',

  '<h3 id="first-deploy-image">Image &amp; runtime <a class="anchor" href="#first-deploy-image">#</a></h3>',
  '<ul>',
  '  <li>Pin to a specific image tag (<code>ghcr.io/blamejs/blamejs-wiki:vX.Y.Z</code>); <code>:latest</code> is forbidden in any production compose / k8s manifest.</li>',
  '  <li>Verify the cosign signature before pulling: see the <code>release verification</code> section of DEPLOY.md. Pin to the published SHA3-512 digest if your registry supports it.</li>',
  '  <li>Run as the image\'s built-in non-root user (UID 65532). Don\'t override <code>--user 0:0</code> for "convenience" — that surfaces as a permission incident months later.</li>',
  '  <li>Persistent volume mounted at <code>/data</code>, writable by UID 65532. Bind-mount permissions are the most common deploy-day bug; verify <code>ls -ln</code> on the host volume before first boot.</li>',
  '</ul>',

  '<h3 id="first-deploy-network">Network <a class="anchor" href="#first-deploy-network">#</a></h3>',
  '<ul>',
  '  <li>Inbound 80 + 443 open to the public internet, with the rest of the perimeter locked down. Caddy or your platform\'s ingress terminates TLS.</li>',
  '  <li>DNS A / AAAA records pointing at the host (or load balancer). Caddy issues the cert from Let\'s Encrypt on first boot — don\'t carry around a self-signed cert across deploys.</li>',
  '  <li>Confirm the SSRF gate is on by default (it is). Operators with a legitimate internal-mesh call use <code>allowInternal: true | CIDR[]</code> per call rather than disabling the gate globally.</li>',
  '</ul>',

  '<h3 id="first-deploy-app">App config <a class="anchor" href="#first-deploy-app">#</a></h3>',
  '<ul>',
  '  <li>Set <code>WIKI_ADMIN_PASSWORD</code> to a stable strong value. Without it the wiki generates a fresh dev password on every boot and prints it to stdout — fine for a laptop, embarrassing in a logging pipeline.</li>',
  '  <li>Set <code>BLAMEJS_DEPRECATIONS=throw</code> in CI (not production). Production keeps the default <code>warn</code> so a deprecation surfaces in logs without taking down a running app.</li>',
  '  <li>Audit every <code>{{{ raw }}}</code> template output — those skip HTML escape. Operator-supplied content goes through <code>htmlEscape</code> by default.</li>',
  '  <li>Use <code>b.permissions</code> for every state-changing route. Don\'t gate on <code>req.user</code> truthiness alone.</li>',
  '</ul>',

  '<h3 id="first-deploy-backup">Backup <a class="anchor" href="#first-deploy-backup">#</a></h3>',
  '<ul>',
  '  <li>Schedule nightly backups via <code>b.backup</code>. Off-site at least one bundle (different region / cloud / physical location).</li>',
  '  <li>Test restore quarterly: <code>blamejs backup verify --bundle &lt;latest&gt;</code> followed by an <code>extract</code> round-trip into a staging environment.</li>',
  '  <li>Retain bundles per your compliance window. The chain\'s prev-hash makes silent deletion of an old bundle detectable on the next verify.</li>',
  '</ul>',

  '<h3 id="first-deploy-pipeline">CI / pipeline <a class="anchor" href="#first-deploy-pipeline">#</a></h3>',
  '<ul>',
  '  <li>Branch protection on <code>main</code> requiring the lint summary CI check (ESLint + Hadolint + ShellCheck) and at least one review.</li>',
  '  <li><code>node bench/run.js --compare</code> as a soft CI gate so a regression in <code>b.crypto.encryptPacked</code> doesn\'t silently land.</li>',
  '  <li><code>blamejs api-snapshot compare --file ./api-snapshot.json</code> as a hard CI gate so a removed-or-renamed public method fails the build before it tags a release.</li>',
  '</ul>',

  '<aside class="callout callout-tip">',
  '  <p class="callout-title">Tip</p>',
  '  <p>Walk this list once before the first production tag. The runtime defaults are doing most of the work — your job is to set the few things the framework can\'t set on your behalf (passphrases, the backup schedule, branch protection) and to verify the volume + image + DNS plumbing actually fires the way the docs say it does.</p>',
  '</aside>',
].join("\n"),
};
