"use strict";

module.exports = {
  slug:  "cluster",
  title: "Cluster Mode",
  body: [
  '<h1>Cluster Mode</h1>',
  '<p>The primitives that show up the moment an app moves past one Node process: external durable databases for app data, cluster coordination via fenced leases, a cluster-aware scheduler, and a boot-time NTP sanity check.</p>',

  '<h2 id="external-db">External database <a class="anchor" href="#external-db">#</a></h2>',
  '<p>Framework state (audit_log, consent_log, sessions, queue, cache) stays in <code>b.db</code>\'s local SQLite. <strong>App data</strong> — domain tables for the operator\'s product — goes into <code>b.externalDb</code> when the operator wants Postgres / MySQL / MongoDB / libsql / etc. The framework adds pooling, retry, circuit-breaker, classification routing, residency enforcement, and audit hooks; the <em>driver</em> is operator-supplied (zero-runtime-dep rule).</p>',
  '<h3>b.externalDb.init(opts)</h3>',
  '<pre><code class="language-javascript">{',
  '  backends:        { [name]: BackendConfig }, // required: true',
  '  defaultBackend:  string,                    // default: first registered',
  '}',
  '',
  '// BackendConfig (operator-supplied — bring-your-own-client):',
  '{',
  '  connect:    async () =&gt; client,            // required: true',
  '  query:      async (client, sql, params) =&gt; { rows, rowCount },',
  '                                              // required: true',
  '  close:      async (client) =&gt; void,        // default: noop',
  '  ping:       async (client) =&gt; boolean,     // default: null — health probe',
  '  beginTx:    async (client) =&gt; void,        // default: client.query("BEGIN")',
  '  commit:     async (client) =&gt; void,        // default: client.query("COMMIT")',
  '  rollback:   async (client) =&gt; void,        // default: client.query("ROLLBACK")',
  '  pool:       { min, max, idleTimeoutMs },   // default: { min:1, max:10, idleTimeoutMs:60000 }',
  '  classifications:  string[],                 // default: [] — data-class allowlist',
  '  residencyTag:     string,                   // default: null — "EU" / "US" / ...',
  '  retry:      RetryOpts,                      // default: framework defaults',
  '  breaker:    BreakerOpts,                    // default: framework defaults',
  '}</code></pre>',
  '<pre><code class="language-javascript">// Operator brings their own pg client; framework adds pooling + reliability.',
  'var pg = require("pg");',
  'b.externalDb.init({',
  '  backends: {',
  '    primary: {',
  '      connect:  async () =&gt; { var c = new pg.Client({ connectionString: env("DB_URL") }); await c.connect(); return c; },',
  '      query:    async (c, sql, params) =&gt; { var r = await c.query(sql, params); return { rows: r.rows, rowCount: r.rowCount }; },',
  '      close:    async (c) =&gt; { await c.end(); },',
  '      pool:     { min: 2, max: 20 },',
  '      residencyTag: "US",',
  '    },',
  '  },',
  '});',
  '',
  '// App-data queries route through b.externalDb (NOT b.db.from):',
  'var { rows } = await b.externalDb.query("SELECT * FROM products WHERE id = $1", [id]);',
  '',
  '// Multi-statement transaction (rollback on throw):',
  'await b.externalDb.transaction(async function (tx) {',
  '  await tx.query("INSERT INTO orders (id, total) VALUES ($1, $2)", [orderId, 99]);',
  '  await tx.query("UPDATE inventory SET qty = qty - 1 WHERE sku = $1", [sku]);',
  '});</code></pre>',

  '<h2 id="external-db-query">b.externalDb.query(sql, params, options) <a class="anchor" href="#external-db-query">#</a></h2>',
  '<p>Runs one app-data query through the configured external backend. The wrapper adds pool checkout, retry, circuit-breaker protection, classification/residency routing, role-aware backend selection, and audit metadata without logging SQL unless the operator explicitly opts in.</p>',
  '<pre><code class="language-javascript">typeof b.externalDb.query; // "function"</code></pre>',

  '<h2 id="external-db-transaction">b.externalDb.transaction(fn, options) <a class="anchor" href="#external-db-transaction">#</a></h2>',
  '<p>Runs a multi-statement external database transaction with begin, commit, rollback, optional statement timeout, session GUC binding, and deadlock retry policy. The callback receives a transaction client exposing <code>query(sql, params)</code>.</p>',
  '<pre><code class="language-javascript">typeof b.externalDb.transaction; // "function"</code></pre>',

  '<h2 id="external-db-health">b.externalDb.healthCheck(backendName) <a class="anchor" href="#external-db-health">#</a></h2>',
  '<p>Checks one backend, or every backend when no name is supplied. Backends with a configured <code>ping</code> hook use it; otherwise the framework reports pool and backend metadata from the configured wrapper.</p>',
  '<pre><code class="language-javascript">typeof b.externalDb.healthCheck; // "function"</code></pre>',

  '<h2 id="external-db-list">b.externalDb.listBackends() <a class="anchor" href="#external-db-list">#</a></h2>',
  '<p>Returns configured backend descriptors for diagnostics, admin pages, cluster provider setup, and migration tooling.</p>',
  '<pre><code class="language-javascript">typeof b.externalDb.listBackends; // "function"</code></pre>',

  '<h2 id="external-db-shutdown">b.externalDb.shutdown() <a class="anchor" href="#external-db-shutdown">#</a></h2>',
  '<p>Drains idle pool clients, rejects queued acquisitions, and stops pool reapers during application shutdown.</p>',
  '<pre><code class="language-javascript">typeof b.externalDb.shutdown; // "function"</code></pre>',

  '<h2 id="external-db-configure-pool">b.externalDb.configurePool(backendName, options) <a class="anchor" href="#external-db-configure-pool">#</a></h2>',
  '<p>Resizes an initialized backend pool at runtime. Allowed controls are <code>min</code>, <code>max</code>, and <code>idleTimeoutMs</code>; bad backend names and malformed values fail synchronously.</p>',
  '<pre><code class="language-javascript">typeof b.externalDb.configurePool; // "function"</code></pre>',

  '<h2 id="external-db-run-as">b.externalDb.runAs(role, fn) <a class="anchor" href="#external-db-run-as">#</a></h2>',
  '<p>Binds a database role outside an HTTP request so jobs, schedulers, and CLIs use the same role-aware backend routing as <code>b.middleware.dbRoleFor</code>.</p>',
  '<pre><code class="language-javascript">typeof b.externalDb.runAs; // "function"</code></pre>',

  '<h2 id="external-db-current-role">b.externalDb.currentRole() <a class="anchor" href="#external-db-current-role">#</a></h2>',
  '<p>Returns the role currently bound in the external database role context, or <code>null</code> when no role is active.</p>',
  '<pre><code class="language-javascript">typeof b.externalDb.currentRole; // "function"</code></pre>',

  '<h2 id="cluster">Cluster coordination <a class="anchor" href="#cluster">#</a></h2>',
  '<p>Cluster mode flips on when the operator calls <code>cluster.init()</code>. The primary effect: every replica goes through a lease-based coordination layer for the things only one node should do at a time — schedule ticks, migration application, key rotation, audit-chain compaction.</p>',
  '<h3>b.cluster.init(opts)</h3>',
  '<pre><code class="language-javascript">{',
  '  nodeId:              string,                // required: true — unique per replica',
  '  role:                "leader" | "follower", // default: "leader"',
  '  leaseTtl:            number,                // default: C.TIME.seconds(30) — min 5s',
  '  heartbeatInterval:   number,                // default: C.TIME.seconds(10) — min 1s,',
  '                                              //          must be < leaseTtl',
  '  provider:            ClusterProvider,       // default: built-in DB-row provider',
  '}</code></pre>',
  '<pre><code class="language-javascript">// await b.externalDb.init({ backends: { primary: pgBackend } });',
  '// await b.cluster.init({',
  '//   nodeId:             process.env.HOSTNAME || "node-1",',
  '//   leaseTtl:           C.TIME.seconds(30),',
  '//   heartbeatInterval:  C.TIME.seconds(10),',
  '// });',
  '//',
  '// // Anywhere that requires the leader (session writes, key rotation, etc):',
  '// await b.cluster.requireLeader();      // throws NotLeaderError on a follower',
  'typeof b.cluster.init; // "function"',
  'typeof b.cluster.requireLeader; // "function"</code></pre>',
  '<p>Leases carry a fencing token — every leaseholder gets a monotonic value; if the lease lapses and a different node picks it up, the new fencing token is strictly greater, and any write the previous holder issues with the old token is rejected by the storage layer. Nothing about a delayed network packet from a former leader can corrupt state.</p>',
  '<p>Vault-key consistency: every node records a hash of its vault keypair on first boot and rejects participation if its hash doesn\'t match the cluster\'s recorded fingerprint. Prevents the silent-corruption shape where a node booted with a different key seals new writes the rest of the cluster can\'t unseal.</p>',

  '<h2 id="cluster-state">b.cluster.isLeader() / isClusterMode() / requireLeader() <a class="anchor" href="#cluster-state">#</a></h2>',
  '<p>Runtime leadership gates. Mutating primitives call <code>requireLeader</code> when only the active leader may write.</p>',
  '<pre><code class="language-javascript">typeof b.cluster.isLeader; // "function"',
  'typeof b.cluster.isClusterMode; // "function"',
  'typeof b.cluster.requireLeader; // "function"</code></pre>',

  '<h2 id="cluster-introspection">b.cluster.currentLeader() / currentNodeId() / fencingToken() <a class="anchor" href="#cluster-introspection">#</a></h2>',
  '<p>Read-only cluster state for diagnostics, admin pages, and audit metadata.</p>',
  '<pre><code class="language-javascript">typeof b.cluster.currentLeader; // "function"',
  'typeof b.cluster.currentNodeId; // "function"',
  'typeof b.cluster.fencingToken; // "function"</code></pre>',

  '<h2 id="cluster-current-node">b.cluster.currentNodeId() <a class="anchor" href="#cluster-current-node">#</a></h2>',
  '<p>Returns the configured node id for the current process. Operators use it in diagnostics and audit metadata when multiple replicas are online.</p>',
  '<pre><code class="language-javascript">typeof b.cluster.currentNodeId; // "function"</code></pre>',

  '<h2 id="cluster-fencing-token">b.cluster.fencingToken() <a class="anchor" href="#cluster-fencing-token">#</a></h2>',
  '<p>Returns the current fencing token held by this process, or the neutral value when cluster mode is not active.</p>',
  '<pre><code class="language-javascript">typeof b.cluster.fencingToken; // "function"</code></pre>',

  '<h2 id="cluster-routing">b.cluster.endpoint() / externalDbBackend() / dialect() <a class="anchor" href="#cluster-routing">#</a></h2>',
  '<p>Coordination backend descriptors used by admin tooling and cluster-aware primitives.</p>',
  '<pre><code class="language-javascript">typeof b.cluster.endpoint; // "function"',
  'typeof b.cluster.externalDbBackend; // "function"',
  'typeof b.cluster.dialect; // "function"</code></pre>',

  '<h2 id="cluster-external-backend">b.cluster.externalDbBackend() <a class="anchor" href="#cluster-external-backend">#</a></h2>',
  '<p>Returns the externalDb backend name used for cluster coordination when the built-in database provider is active.</p>',
  '<pre><code class="language-javascript">typeof b.cluster.externalDbBackend; // "function"</code></pre>',

  '<h2 id="cluster-dialect">b.cluster.dialect() <a class="anchor" href="#cluster-dialect">#</a></h2>',
  '<p>Returns the coordination backend dialect marker for provider-specific SQL and diagnostics.</p>',
  '<pre><code class="language-javascript">typeof b.cluster.dialect; // "function"</code></pre>',

  '<h2 id="cluster-transitions">b.cluster.onTransition(fn) / discoveryHandler(request) <a class="anchor" href="#cluster-transitions">#</a></h2>',
  '<p>Transition hooks and discovery endpoint helper for operators that expose cluster state to health or admin planes.</p>',
  '<pre><code class="language-javascript">typeof b.cluster.onTransition; // "function"',
  'typeof b.cluster.discoveryHandler; // "function"</code></pre>',

  '<h2 id="cluster-discovery">b.cluster.discoveryHandler(request) <a class="anchor" href="#cluster-discovery">#</a></h2>',
  '<p>Returns a cluster-state response object for operator-controlled discovery and health endpoints.</p>',
  '<pre><code class="language-javascript">typeof b.cluster.discoveryHandler; // "function"</code></pre>',

  '<h2 id="cluster-is-mode">b.cluster.isClusterMode() <a class="anchor" href="#cluster-is-mode">#</a></h2>',
  '<p>Reports whether cluster mode has been initialized for this process.</p>',
  '<pre><code class="language-javascript">typeof b.cluster.isClusterMode; // "function"</code></pre>',

  '<h2 id="cluster-require-leader">b.cluster.requireLeader() <a class="anchor" href="#cluster-require-leader">#</a></h2>',
  '<p>Throws when the current process is not the active leader, letting mutating primitives enforce single-writer behavior.</p>',
  '<pre><code class="language-javascript">typeof b.cluster.requireLeader; // "function"</code></pre>',

  '<h2 id="cluster-shutdown">b.cluster.shutdown() <a class="anchor" href="#cluster-shutdown">#</a></h2>',
  '<p>Stops heartbeat work and releases leadership on process shutdown.</p>',
  '<pre><code class="language-javascript">typeof b.cluster.shutdown; // "function"</code></pre>',

  '<h3 id="cluster-providers">Custom providers <a class="anchor" href="#cluster-providers">#</a></h3>',
  '<p>The default coordination provider is a row-based lease over <code>b.externalDb</code>. Operators with a different coordination substrate (etcd, Consul, ZooKeeper, k8s lease object) implement the <code>{ acquireLease, renewLease, releaseLease, ensureSchema }</code> interface and pass it via <code>cluster.init({ provider: customProvider })</code>.</p>',

  '<h2 id="scheduler">Scheduler <a class="anchor" href="#scheduler">#</a></h2>',
  '<p><code>b.scheduler.create()</code> returns a scheduler instance. Tasks are registered before <code>start()</code>; in cluster mode, each tick goes through the leader gate so a job runs <em>exactly once globally</em> regardless of how many replicas are awake.</p>',
  '<h3>b.scheduler.create(opts)</h3>',
  '<pre><code class="language-javascript">{',
  '  jobs:             JobsInstance,             // default: null — required for spec.job tasks',
  '  cluster:          ClusterInstance,          // default: null — single-process if absent',
  '  audit:            boolean,                  // default: true — emit scheduler.* on chain',
  '  maxJobMs:         number,                   // default: framework default',
  '  tickRetentionMs:  number,                   // default: framework default',
  '  pruneIntervalMs:  number,                   // default: framework default',
  '}</code></pre>',
  '<h3>scheduler.schedule(spec) / .start() / .stop()</h3>',
  '<pre><code class="language-javascript">// Spec — set exactly one of cron/every AND exactly one of job/run:',
  '{',
  '  name:         string,                       // required: true — unique per scheduler',
  '  cron:         string,                       // 5-field cron expression',
  '  every:        number,                       // OR — fire every N ms (min 1000)',
  '  timezone:     string,                       // default: null (UTC) — IANA tz name',
  '  job:          string,                       // jobs.enqueue this name on each fire',
  '  run:          () =&gt; Promise,                // OR — invoke this fn directly',
  '  payload:      any,                          // default: null — passed to job/run',
  '  enqueueOpts:  object,                       // default: null — forwarded to jobs.enqueue',
  '}</code></pre>',
  '<pre><code class="language-javascript">// var scheduler = b.scheduler.create({ cluster: b.cluster });',
  '//',
  '// scheduler.schedule({',
  '//   name:  "session-purge",',
  '//   cron:  "*/5 * * * *",',
  '//   run:   async function () { await b.session.purgeExpired(); },',
  '// });',
  '//',
  '// scheduler.schedule({',
  '//   name:  "audit-chain-checkpoint",',
  '//   cron:  "0 2 * * *",',
  '//   timezone: "America/New_York",',
  '//   run:   async function () { await b.audit.checkpoint(); },',
  '// });',
  '//',
  '// scheduler.schedule({',
  '//   name:   "metric-rollup",',
  '//   every:  C.TIME.minutes(1),                  // interval in ms',
  '//   run:    rollupFn,',
  '// });',
  '//',
  '// await scheduler.start();',
  '',
  '// Compute a future firing time without scheduling — positional args:',
  '// var next = b.scheduler.nextCronFire("0 9 * * *", new Date(), "America/New_York");',
  '// → Date',
  'typeof b.scheduler.create; // "function"',
  'typeof b.scheduler.nextCronFire; // "function"</code></pre>',
  '<p>Cron parser: 5-field POSIX with named months / weekdays, <code>*/N</code> step, <code>L</code> for last-of-month, ranges, lists. Malformed expressions throw at <code>schedule()</code> time so a typo fails at boot rather than silently never firing. Defining tasks after <code>start()</code> throws — register everything first.</p>',

  '<h2 id="ntp">NTP check <a class="anchor" href="#ntp">#</a></h2>',
  '<p><code>b.ntpCheck</code> samples the host clock against a small set of NTP servers at boot and on a schedule. A drift larger than the configured threshold (default 5 seconds) refuses the boot and logs a clear cause — token expiries, audit timestamps, and lease fencing all assume monotonic, well-synced wall-clock time, and a misconfigured VM with a bad clock is one of the most common production-data corruption vectors.</p>',
  '<pre><code class="language-javascript">var ntp = await b.ntpCheck.run({',
  '  servers:        ["time.cloudflare.com", "pool.ntp.org"],',
  '  thresholdMs:    C.TIME.seconds(5),',
  '  timeoutMs:      C.TIME.seconds(2),',
  '});',
  '// ntp.driftMs / ntp.server / ntp.passed</code></pre>',
  '<p>Override the strict-fail behavior with <code>BLAMEJS_NTP_STRICT=0</code> for environments where boot must proceed despite an NTP failure (logged as a warning instead of fatal). Skip the check entirely with <code>BLAMEJS_SKIP_NTP_CHECK=1</code> — only for genuinely offline / air-gapped deployments where the operator has a different clock-sync mechanism.</p>',

  '<h2 id="ntp-query-single">b.ntpCheck.querySingle(server, options) <a class="anchor" href="#ntp-query-single">#</a></h2>',
  '<p>Queries one NTP server and returns the measured offset sample used by drift checks.</p>',
  '<pre><code class="language-javascript">typeof b.ntpCheck.querySingle; // "function"</code></pre>',

  '<h2 id="ntp-check-drift">b.ntpCheck.checkDrift(options) <a class="anchor" href="#ntp-check-drift">#</a></h2>',
  '<p>Checks clock drift against the configured server list and threshold policy.</p>',
  '<pre><code class="language-javascript">typeof b.ntpCheck.checkDrift; // "function"</code></pre>',

  '<h2 id="ntp-boot-check">b.ntpCheck.bootCheck(options) <a class="anchor" href="#ntp-boot-check">#</a></h2>',
  '<p>Runs the boot-time drift gate that can refuse startup when the host clock is outside the configured fatal threshold.</p>',
  '<pre><code class="language-javascript">typeof b.ntpCheck.bootCheck; // "function"</code></pre>',

  '<h2 id="ntp-monitor">b.ntpCheck.monitor(options) <a class="anchor" href="#ntp-monitor">#</a></h2>',
  '<p>Starts a background clock-drift monitor for long-running processes.</p>',
  '<pre><code class="language-javascript">typeof b.ntpCheck.monitor; // "function"</code></pre>',

  '<h2 id="ntp-thresholds-set">b.ntpCheck.setThresholds(options) <a class="anchor" href="#ntp-thresholds-set">#</a></h2>',
  '<p>Updates warn and fatal drift thresholds for deployments with stricter or looser time-synchronization requirements.</p>',
  '<pre><code class="language-javascript">typeof b.ntpCheck.setThresholds; // "function"</code></pre>',

  '<h2 id="ntp-thresholds-get">b.ntpCheck.getThresholds() <a class="anchor" href="#ntp-thresholds-get">#</a></h2>',
  '<p>Returns the active drift thresholds for diagnostics and admin views.</p>',
  '<pre><code class="language-javascript">typeof b.ntpCheck.getThresholds; // "function"</code></pre>',
].join("\n"),
};
