"use strict";

module.exports = {
  slug:  "crypto-vault",
  title: "Crypto & Vault",
  body: [
  '<h1>Crypto &amp; Vault</h1>',
  '<p>Cryptography in blamejs is post-quantum from the start. There are no classical-only fallbacks — the active KEM is hybrid (ML-KEM-1024 + P-384 ECDH), the cipher is XChaCha20-Poly1305, the KDF is SHAKE256, the password hash is Argon2id, and the signature scheme is SLH-DSA-SHAKE-256f by default with ML-DSA-87 still verifying for legacy rows. Old algorithms aren\'t deprecated; they were never present.</p>',
  '<p>Network-layer cryptography (TLS gates, mTLS) lives at <a href="/network-crypto">Network Crypto</a>. This page covers data-at-rest sealing, signatures, and ECIES.</p>',

  '<h2 id="envelope">The storage envelope <a class="anchor" href="#envelope">#</a></h2>',
  '<p>Every encrypted blob starts with a four-byte header that identifies the algorithms used. This is what makes algorithm agility possible: any component can be swapped without rewriting existing data, because <code>b.crypto.decrypt()</code> dispatches on the header bytes, not on a guess at the active default.</p>',
  '<pre><code class="language-text">byte 0   0xE1     envelope magic',
  'byte 1   KEM ID',
  'byte 2   cipher ID',
  'byte 3   KDF ID',
  'byte 4+  ciphertext + tag</code></pre>',
  '<table>',
  '  <thead><tr><th>Field</th><th>ID</th><th>Algorithm</th><th>Status</th></tr></thead>',
  '  <tbody>',
  '    <tr><td>KEM</td><td><code>0x02</code></td><td>ML-KEM-1024</td><td>Supported (standalone)</td></tr>',
  '    <tr><td>KEM</td><td><code>0x03</code></td><td>ML-KEM-1024 + P-384 ECDH hybrid</td><td><strong>Active default</strong></td></tr>',
  '    <tr><td>Cipher</td><td><code>0x02</code></td><td>XChaCha20-Poly1305</td><td>Active default</td></tr>',
  '    <tr><td>KDF</td><td><code>0x02</code></td><td>SHAKE256</td><td>Active default</td></tr>',
  '  </tbody>',
  '</table>',
  '<p>Adding a new KEM (HQC-256, FrodoKEM, the next standardized scheme) means assigning the next ID, implementing the encapsulate / decapsulate path, setting <code>ACTIVE_KEM</code> to the new ID for new writes, and keeping the old ID\'s case in <code>decrypt()</code>. Existing data continues to read; new writes use the new algorithm.</p>',

  '<h2 id="vault">Vault</h2>',
  '<p>The vault holds the operator\'s master keypair. Every sealed column, signed audit row, and webhook signature traces back to a key that lives here. Two modes: <em>plaintext</em> (the keypair sits on disk in clear; useful for development and a demo, never for production) and <em>wrapped</em> (the private key is encrypted under a passphrase-derived key — Argon2id stretches the passphrase to a wrapping key; the encrypted key file is what lives on disk). The wrapped path is the default. Operators supply the passphrase via <code>BLAMEJS_VAULT_PASSPHRASE</code>; the framework refuses to boot in wrapped mode without it. Plaintext-mode boots print a warning on every start: <code>WARNING: PLAINTEXT mode — vault.key is unprotected on disk</code>.</p>',

  '<h3>b.vault.seal(plaintext) / b.vault.unseal(sealed) <a class="anchor" href="#vault-seal">#</a></h3>',
  '<p>Seal an arbitrary byte buffer with the active vault keypair (envelope-versioned, KEM + cipher + KDF IDs in the leading bytes). Unseal the matching wire shape. <code>seal</code> returns a string with the framework\'s <code>vault:</code> prefix; <code>unseal</code> verifies the prefix + envelope header, decrypts, and returns the original Buffer. Throws on tamper, wrong key, or unsupported envelope version.</p>',
  '<pre><code class="language-javascript">var sealed = await b.vault.seal(Buffer.from("super secret"));',
  '// → "vault:<base64-encoded-envelope>"',
  '',
  'var plaintext = await b.vault.unseal(sealed);',
  '// → Buffer "super secret"</code></pre>',

  '<h2 id="vault-init">b.vault.init(options) <a class="anchor" href="#vault-init">#</a></h2>',
  '<p>Initializes the vault keypair, mode, data directory, passphrase source, and wrapped/plaintext boot posture.</p>',
  '<pre><code class="language-javascript">typeof b.vault.init; // "function"</code></pre>',

  '<h2 id="vault-unseal">b.vault.unseal(sealed) <a class="anchor" href="#vault-unseal">#</a></h2>',
  '<p>Unseals a <code>vault:</code> envelope and returns the original plaintext buffer after prefix, header, and authentication checks pass.</p>',
  '<pre><code class="language-javascript">typeof b.vault.unseal; // "function"</code></pre>',

  '<h2 id="vault-mode">b.vault.getMode() <a class="anchor" href="#vault-mode">#</a></h2>',
  '<p>Returns the active vault mode for diagnostics and production posture checks.</p>',
  '<pre><code class="language-javascript">typeof b.vault.getMode; // "function"</code></pre>',

  '<h2 id="vault-keys-json">b.vault.getKeysJson() <a class="anchor" href="#vault-keys-json">#</a></h2>',
  '<p>Returns the serialized key metadata used by vault status and migration tooling.</p>',
  '<pre><code class="language-javascript">typeof b.vault.getKeysJson; // "function"</code></pre>',

  '<h2 id="vault-passphrase-current">b.vault.getCurrentPassphrase() <a class="anchor" href="#vault-passphrase-current">#</a></h2>',
  '<p>Returns the currently resolved passphrase for wrapped-mode operations that need to verify boot configuration.</p>',
  '<pre><code class="language-javascript">typeof b.vault.getCurrentPassphrase; // "function"</code></pre>',

  '<h2 id="vault-seal-pem">b.vault.sealPemFile(path, options) <a class="anchor" href="#vault-seal-pem">#</a></h2>',
  '<p>Seals an operator PEM file at rest using the active vault envelope, preserving the original file path workflow while removing plaintext key material.</p>',
  '<pre><code class="language-javascript">typeof b.vault.sealPemFile; // "function"</code></pre>',

  '<h2 id="vault-aad">b.vault.aad.seal(plaintext, aad) <a class="anchor" href="#vault-aad">#</a></h2>',
  '<p>Additional-authenticated-data vault namespace for sealing values that must be bound to a table, column, tenant, or other context.</p>',
  '<pre><code class="language-javascript">typeof b.vault.aad.seal; // "function"</code></pre>',

  '<h3 id="vault-cli">Sealing the vault from the CLI <a class="anchor" href="#vault-cli">#</a></h3>',
  '<pre><code class="language-bash"># Inspect what\'s on disk',
  'blamejs vault status --data-dir ./data',
  '',
  '# Wrap a plaintext vault.key under a passphrase',
  'BLAMEJS_VAULT_PASSPHRASE="…" blamejs vault seal --data-dir ./data',
  '',
  '# Reverse — write plaintext back, e.g. for an audit or migration',
  'BLAMEJS_VAULT_PASSPHRASE="…" blamejs vault unseal --data-dir ./data',
  '',
  '# Change the passphrase on an existing sealed file',
  'blamejs vault rotate \\',
  '  --data-dir ./data \\',
  '  --passphrase "$OLD" \\',
  '  --new-passphrase "$NEW"</code></pre>',
  '<p>Each operation is crash-safe — writes go through <code>.tmp</code> + <code>fsync</code> + atomic rename, and <code>seal</code>/<code>unseal</code> re-read the temp file to confirm the bytes match before the rename.</p>',

  '<h2 id="field-crypto">Field-level crypto</h2>',
  '<p><code>b.cryptoField</code> wires the envelope into <code>b.db</code>. Declare which fields seal and which derive a hash for indexed lookups; <code>b.db.from(table)</code>\'s reads + writes pick up the registration automatically.</p>',

  '<h3>b.cryptoField.registerTable(name, opts) <a class="anchor" href="#crypto-field-register">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  sealedFields:   [string],                  // column names to vault-seal on write + unseal on read',
  '  derivedHashes:  {                          // derive an index-friendly hash from a sealed column',
  '    "<derivedColumn>": {',
  '      from:       string,                    // source column name',
  '      normalize:  (v) => string,             // optional pre-hash normalization',
  '    },',
  '  },',
  '  hashNamespaces: { "<column>": string },    // optional — override namespace per column',
  '}</code></pre>',
  '<p>Registers a table\'s sealed-field schema with the global registry. After registration, every read through <code>b.db.from(name)</code> auto-unseals; every write auto-seals. Derived hash columns let operators look up a sealed value by its hash — fresh per-row nonces mean direct sealed-column equality lookups would always miss; the derived hash is what the index actually serves. Namespacing prevents rainbow attacks across columns.</p>',
  '<pre><code class="language-javascript">b.cryptoField.registerTable("emails", {',
  '  sealedFields:  ["body", "subject"],',
  '  derivedHashes: {',
  '    recipientHash: { from: "recipient",',
  '                     normalize: function (v) { return String(v).toLowerCase(); } },',
  '  },',
  '});',
  '// b.db.from("emails").insert({...}) now seals body+subject and computes recipientHash.',
  'b.cryptoField.getSealedFields;</code></pre>',

  '<h2 id="signatures">Signatures</h2>',
  '<p>Outbound webhooks, the audit chain checkpoint, and any operator-issued signed message use <code>b.webhook.signer</code> (and the matching <code>b.webhook.verifier</code> for inbound). HMAC-SHA3-512 by default for shared-secret deliveries; SLH-DSA-SHAKE-256f via <code>algo: "pqc-pem"</code> for asymmetric signing. Multi-key rotation: keep retired <code>kid</code>s in the verifier map until you\'re sure no in-flight delivery is signed by them. The full signer + verifier surface is documented at <a href="/outbound-http#webhook">Outbound HTTP → Webhook</a>; the signed string is deterministic and prefix-bound (key-ID, algorithm, nonce, then the body) to defend against algorithm-substitution and key-substitution attacks.</p>',

  '<h2 id="ecies">API payload encryption (ECIES) <a class="anchor" href="#ecies">#</a></h2>',
  '<p><code>b.middleware.apiEncrypt</code> encrypts entire request and response bodies for clients that establish a session over the wire. The <code>_ek</code> field carries a one-byte protocol version, a 24-byte nonce, and the wrapped session key; sessions are ephemeral and don\'t need backward-compat in the decrypt path the way storage envelopes do.</p>',
  '<table>',
  '  <thead><tr><th>Version</th><th>KEM</th><th>ECDH</th><th>KDF</th><th>Wrapping cipher</th></tr></thead>',
  '  <tbody>',
  '    <tr><td><code>0x01</code></td><td>ML-KEM-1024</td><td>P-384</td><td>HKDF-SHA3-512</td><td>XChaCha20-Poly1305</td></tr>',
  '  </tbody>',
  '</table>',
  '<p>Adding the next protocol version is the same dance as adding a KEM ID to the storage envelope: assign the next byte, implement the path, update both server and client to handle it. Old clients that only understand <code>0x01</code> will throw <code>Unsupported ECIES protocol version</code> against a server that has moved on; rolling forward is an explicit version-pinning decision.</p>',
  '<p><code>b.nonceStore</code> is the replay-defense backing store the middleware uses — every <code>_ek</code> nonce is recorded with an expiry and refused on second sight. Memory backend single-process; cluster backend shares state across replicas.</p>',

  '<h2 id="mlkem768-x25519">b.crypto.encryptMlkem768X25519(plaintext, recipient) / generateMlkem768X25519KeyPair() <a class="anchor" href="#mlkem768-x25519">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  // recipient shape:',
  '  mlkemPublicKey:    pemString,                  // ML-KEM-768',
  '  x25519PublicKey:   pemString,                  // X25519',
  '}</code></pre>',
  '<p>Second hybrid envelope for TLS-interop with peers using the IETF / Cloudflare / Chrome standardized <code>X25519MLKEM768</code> hybrid (TLS 1.3 codepoint <code>0x11EC</code>). Smaller envelope (~1.1 KB vs ~1.6 KB for the framework default ML-KEM-1024 + P-384). Generation produces <code>{ mlkemPublicKey, mlkemPrivateKey, x25519PublicKey, x25519PrivateKey }</code>. Decryption goes through the existing <code>b.crypto.decrypt(envelope, privateKeys)</code> — the envelope-magic dispatch handles KEM ID <code>0x04</code>; pass <code>{ privateKey: mlkemPrivateKey, x25519PrivateKey }</code>. <code>b.crypto.SUPPORTED_KEM_ALGORITHMS</code> exposes every accepted hybrid for compliance audit. <code>ACTIVE.KEM</code> stays on ML-KEM-1024 + P-384; this hybrid is opt-in for cross-system interop.</p>',
  '<pre><code class="language-javascript">var pair = b.crypto.generateMlkem768X25519KeyPair();',
  'var envelope = b.crypto.encryptMlkem768X25519("hello world", {',
  '  mlkemPublicKey:  pair.mlkemPublicKey,',
  '  x25519PublicKey: pair.x25519PublicKey,',
  '});',
  'var plaintext = b.crypto.decrypt(envelope, {',
  '  privateKey:       pair.mlkemPrivateKey,',
  '  x25519PrivateKey: pair.x25519PrivateKey,',
  '});',
  '// plaintext === "hello world"',
  '</code></pre>',

  '<h2 id="cert-peer">b.crypto.encryptEnvelopeAsCertPeer / decryptEnvelopeAsCertPeer <a class="anchor" href="#cert-peer">#</a></h2>',
  '<pre><code class="language-javascript">// encrypt — recipient identified by their TLS cert + ML-KEM-1024 pubkey',
  'b.crypto.encryptEnvelopeAsCertPeer(plaintext, {',
  '  peerCertDer:    Buffer | Uint8Array,    // peer\'s TLS cert (DER)',
  '  peerKemPubkey:  pemString,                // peer\'s ML-KEM-1024 pubkey PEM',
  '});',
  '',
  '// decrypt — this operator\'s cert priv + KEM secret',
  'b.crypto.decryptEnvelopeAsCertPeer(envelope, {',
  '  certPrivateKey: KeyObject | pemString,   // operator\'s cert P-384 priv',
  '  kemSecret:      pemString,                // operator\'s ML-KEM-1024 priv PEM',
  '});</code></pre>',
  '<p>Cert-bound envelope variants of <code>encrypt</code> / <code>decrypt</code>. The default <code>encrypt</code> path sources the recipient from a published framework keypair (operator owns both halves). The cert-peer variants source the recipient\'s ECDH P-384 half from a TLS peer cert plus a peer-supplied ML-KEM-1024 pubkey. Wire format is unchanged — the envelope dispatches on the same version bytes and KEM ID.</p>',
  '<p>Use cases beyond the upcoming <code>b.middleware.apiEncrypt({ recipient: "peer-cert" })</code> strategy: sealed-storage records with peer recipients (operator A seals to operator B\'s TLS cert + KEM pubkey), cross-service messages between cert-identified peers without a shared framework keypair, audit log entries tagged with peer recipients.</p>',
  '<p>Validation throws at the boundary: <code>crypto/cert-key-not-ecdh-p384</code> when the cert\'s SPKI is not <code>id-ecPublicKey</code> over <code>secp384r1</code>; <code>crypto/peer-cert-missing</code> / <code>crypto/peer-kem-pubkey-missing</code> / <code>crypto/cert-private-key-missing</code> / <code>crypto/kem-secret-missing</code> on missing keys.</p>',

  '<h2 id="crypto-digests">b.crypto.sha3Hash(data) / hmacSha3(key, data) / kdf(input, outputLength) <a class="anchor" href="#crypto-digests">#</a></h2>',
  '<p>Framework digest helpers for SHA3-512, HMAC-SHA3-512, and SHAKE256 derivation. Operator code uses these instead of reaching directly into <code>node:crypto</code> so hash choices stay aligned with framework policy.</p>',
  '<pre><code class="language-javascript">var digest = b.crypto.sha3Hash("hello");',
  'var mac = b.crypto.hmacSha3("key", "hello");',
  'var derived = b.crypto.kdf("input", 32);',
  'digest.length > 0 && mac.length > 0 && derived.length === 32;</code></pre>',

  '<h2 id="crypto-namespace-hash">b.crypto.namespaceHash(prefix, value, opts?) <a class="anchor" href="#crypto-namespace-hash">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  // opts is reserved for future extension (algorithm selection).',
  '  // Current surface is fixed to SHA3-512 — no operator demand for',
  '  // SHAKE256 variable-length output here, since the indexed column',
  '  // shape is fixed-width hex.',
  '}</code></pre>',
  '<p>App-namespaced SHA3-512 hash for indexable derived-hash columns (<code>emailHash</code>, <code>certFpHash</code>, <code>externalIdHash</code>). Returns a hex string — stable, indexable, fixed-width across every database backend the framework supports. Distinct from <code>b.credentialHash.hash</code>, which produces an envelope-versioned base64 designed for credential <em>storage</em> with algorithm rotation; <code>namespaceHash</code> is for read-only lookup columns. The prefix is the namespace label (operator-supplied, bounded to 64 UTF-8 bytes, NUL/CR/LF refused) and is concatenated with a colon before the value, so identical values under different namespaces hash differently.</p>',
  '<pre><code class="language-javascript">var emailHash = b.crypto.namespaceHash("bj-email", "user@example.com");',
  'emailHash.length === 128;   // SHA3-512 hex',
  '',
  '// Different namespace → different hash for the same value:',
  'var tokenHash = b.crypto.namespaceHash("bj-token", "user@example.com");',
  'tokenHash !== emailHash;</code></pre>',

  '<h2 id="crypto-hash-stream">b.crypto.hashFile(path, algorithm?) / hashStream(readable, algorithm?) <a class="anchor" href="#crypto-hash-stream">#</a></h2>',
  '<p>Streaming digest helpers that hash data from disk or an arbitrary <code>Readable</code> without loading the whole payload into memory. Default algorithm is SHA3-512; the allowlist accepts SHA3 / SHAKE family plus SHA-512 for interop. Both resolve with the raw digest as a Buffer.</p>',
  '<pre><code class="language-javascript">var fs = require("fs");',
  'var path = require("path");',
  'var os = require("os");',
  'var tmp = path.join(os.tmpdir(), "blamejs-wiki-hash.txt");',
  'fs.writeFileSync(tmp, "hello");',
  'var fileDigest = await b.crypto.hashFile(tmp);',
  'var streamDigest = await b.crypto.hashStream(fs.createReadStream(tmp));',
  'fs.unlinkSync(tmp);',
  'fileDigest.length === 64 && streamDigest.length === 64;</code></pre>',

  '<h2 id="crypto-hash-stream-only">b.crypto.hashStream(readable, algorithm?) <a class="anchor" href="#crypto-hash-stream-only">#</a></h2>',
  '<p>Streams an arbitrary <code>Readable</code> through the framework digest algorithm and resolves with the raw digest Buffer. Pairs with <code>b.crypto.hashFile</code> for callers that already hold a stream (network response body, decompressed entry, in-memory generator).</p>',
  '<pre><code class="language-javascript">// var { Readable } = require("stream");',
  '// var d = await b.crypto.hashStream(Readable.from([Buffer.from("hi")]));',
  '// d.length === 64;',
  'typeof b.crypto.hashStream; // "function"</code></pre>',

  '<h2 id="crypto-random">b.crypto.generateBytes(byteLength) / generateToken(byteLength?) <a class="anchor" href="#crypto-random">#</a></h2>',
  '<p>CSPRNG helpers for binary keys and URL/session/API-token material. Tokens encode random bytes as hex; pass the byte length, not the final string length.</p>',
  '<pre><code class="language-javascript">var bytes = b.crypto.generateBytes(16);',
  'var token = b.crypto.generateToken(16);',
  'bytes.length === 16 && token.length === 32;</code></pre>',

  '<h2 id="crypto-timing-safe">b.crypto.timingSafeEqual(a, b) <a class="anchor" href="#crypto-timing-safe">#</a></h2>',
  '<p>Timing-safe byte comparison with framework-shaped behavior around unequal lengths. Use for MACs, nonces, hashes, and replay ids.</p>',
  '<pre><code class="language-javascript">b.crypto.timingSafeEqual(Buffer.from("aa"), Buffer.from("aa")); // true',
  'b.crypto.timingSafeEqual(Buffer.from("aa"), Buffer.from("ab")); // false</code></pre>',

  '<h2 id="crypto-sri">b.crypto.sri(content, opts?) <a class="anchor" href="#crypto-sri">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  algorithm: string, // default framework SRI algorithm',
  '}</code></pre>',
  '<p>Generates Subresource Integrity strings for bundled assets. Arrays of content produce a space-separated integrity set for multi-file emission.</p>',
  "<pre><code class=\"language-javascript\">var integrity = b.crypto.sri('console.log(1)');",
  "integrity.indexOf('-') > 0; // true</code></pre>",

  '<h2 id="crypto-keypairs">b.crypto.generateEncryptionKeyPair() / generateSigningKeyPair(algorithm?) <a class="anchor" href="#crypto-keypairs">#</a></h2>',
  '<p>Keypair factories for the framework storage envelope and PQC signature paths. Operators use these when provisioning external recipients or rotating signing material outside the vault.</p>',
  '<pre><code class="language-javascript">typeof b.crypto.generateEncryptionKeyPair; // "function"',
  'typeof b.crypto.generateSigningKeyPair; // "function"</code></pre>',

  '<h2 id="crypto-sign">b.crypto.sign(data, privateKeyPem) / verify(data, signature, publicKeyPem) <a class="anchor" href="#crypto-sign">#</a></h2>',
  '<p>PQC signing helpers used below JWT, webhook, and audit-signing surfaces. Higher-level primitives own most application wiring; these remain available for custom signed artifacts.</p>',
  '<pre><code class="language-javascript">typeof b.crypto.sign; // "function"',
  'typeof b.crypto.verify; // "function"</code></pre>',

  '<h2 id="crypto-envelope">b.crypto.encrypt(plaintext, publicKeys) / decrypt(ciphertext, privateKeys) <a class="anchor" href="#crypto-envelope">#</a></h2>',
  '<p>Storage-envelope encryption and decryption. The ciphertext carries version bytes so decrypt dispatches by envelope header rather than by whichever algorithm is active today.</p>',
  '<pre><code class="language-javascript">typeof b.crypto.encrypt; // "function"',
  'typeof b.crypto.decrypt; // "function"</code></pre>',

  '<h2 id="crypto-packed">b.crypto.encryptPacked(buffer, key, aad?) / decryptPacked(packed, key, aad?) <a class="anchor" href="#crypto-packed">#</a></h2>',
  '<p>Symmetric packed-buffer helper for bundle internals and operator code that already owns a high-entropy key. Associated data binds context into the authentication tag.</p>',
  '<pre><code class="language-javascript">var key = b.crypto.generateBytes(32);',
  'var packed = b.crypto.encryptPacked(Buffer.from("hello"), key, "ctx");',
  'b.crypto.decryptPacked(packed, key, "ctx").toString("utf8"); // "hello"</code></pre>',

  '<h2 id="crypto-mlkem768-x25519-functions">b.crypto.generateMlkem768X25519KeyPair() / encryptMlkem768X25519() / decryptMlkem768X25519() <a class="anchor" href="#crypto-mlkem768-x25519-functions">#</a></h2>',
  '<p>Helper trio for the X25519MLKEM768 hybrid used by TLS interop peers. This is separate from the framework default ML-KEM-1024 + P-384 storage envelope.</p>',
  '<pre><code class="language-javascript">typeof b.crypto.generateMlkem768X25519KeyPair; // "function"',
  'typeof b.crypto.encryptMlkem768X25519; // "function"',
  'typeof b.crypto.decryptMlkem768X25519; // "function"</code></pre>',

  '<h2 id="crypto-cert-fingerprint">b.crypto.hashCertFingerprint(pemOrDer) / isCertRevoked(pemOrDer, denyList) <a class="anchor" href="#crypto-cert-fingerprint">#</a></h2>',
  '<p>Certificate fingerprint helpers for mTLS revocation, trust-store checks, and cert-peer encryption workflows.</p>',
  '<pre><code class="language-javascript">typeof b.crypto.hashCertFingerprint; // "function"',
  'typeof b.crypto.isCertRevoked; // "function"</code></pre>',

  '<h2 id="crypto-decrypt">b.crypto.decrypt(envelope, privateKey) <a class="anchor" href="#crypto-decrypt">#</a></h2>',
  '<p>Envelope decrypt dispatcher. It reads the envelope header and routes to the matching active or legacy algorithm without callers guessing the KEM or symmetric mode.</p>',
  '<pre><code class="language-javascript">typeof b.crypto.decrypt; // "function"</code></pre>',

  '<h2 id="crypto-decrypt-packed">b.crypto.decryptPacked(packed, key, aad) <a class="anchor" href="#crypto-decrypt-packed">#</a></h2>',
  '<p>Low-level packed XChaCha20-Poly1305 decrypt helper used by sealed fields and break-glass cell encryption when the caller already owns key and AAD material.</p>',
  '<pre><code class="language-javascript">typeof b.crypto.decryptPacked; // "function"</code></pre>',

  '<h2 id="crypto-token">b.crypto.generateToken(byteLength) <a class="anchor" href="#crypto-token">#</a></h2>',
  '<p>Generates URL-safe random tokens from framework byte counts. Use it for nonces, ids, and bearer material where string transport is required.</p>',
  '<pre><code class="language-javascript">var token = b.crypto.generateToken(16);',
  'typeof token; // "string"</code></pre>',

  '<h2 id="crypto-hmac">b.crypto.hmacSha3(key, data) <a class="anchor" href="#crypto-hmac">#</a></h2>',
  '<p>Computes a SHA-3 HMAC for operator data that needs keyed integrity without exposing raw comparison material.</p>',
  '<pre><code class="language-javascript">var mac = b.crypto.hmacSha3("key", "payload");',
  'typeof mac; // "string"</code></pre>',

  '<h2 id="crypto-kdf">b.crypto.kdf(input, outputLength) <a class="anchor" href="#crypto-kdf">#</a></h2>',
  '<p>Framework KDF wrapper for deriving fixed-length keys from contextual input. Callers pass the output length in bytes.</p>',
  '<pre><code class="language-javascript">var derived = b.crypto.kdf("context", 32);',
  'Buffer.isBuffer(derived); // true</code></pre>',

  '<h2 id="crypto-signing-keypair">b.crypto.generateSigningKeyPair() <a class="anchor" href="#crypto-signing-keypair">#</a></h2>',
  '<p>Creates the framework signing keypair used by signed audit checkpoints and other detached-signature workflows.</p>',
  '<pre><code class="language-javascript">typeof b.crypto.generateSigningKeyPair; // "function"</code></pre>',

  '<h2 id="crypto-verify">b.crypto.verify(data, signature, publicKey) <a class="anchor" href="#crypto-verify">#</a></h2>',
  '<p>Verifies framework detached signatures with the matching public key representation.</p>',
  '<pre><code class="language-javascript">typeof b.crypto.verify; // "function"</code></pre>',

  '<h2 id="crypto-cert-peer-encrypt">b.crypto.encryptEnvelopeAsCertPeer(plaintext, peer) <a class="anchor" href="#crypto-cert-peer-encrypt">#</a></h2>',
  '<p>Encrypts an envelope to a certificate-identified peer for service-to-service and cross-operator messages where the peer certificate anchors identity.</p>',
  '<pre><code class="language-javascript">typeof b.crypto.encryptEnvelopeAsCertPeer; // "function"</code></pre>',

  '<h2 id="crypto-cert-peer-decrypt">b.crypto.decryptEnvelopeAsCertPeer(envelope, keys) <a class="anchor" href="#crypto-cert-peer-decrypt">#</a></h2>',
  '<p>Decrypts a certificate-peer envelope with the recipient key material and certificate binding checks.</p>',
  '<pre><code class="language-javascript">typeof b.crypto.decryptEnvelopeAsCertPeer; // "function"</code></pre>',

  '<h2 id="crypto-mlkem768-decrypt">b.crypto.decryptMlkem768X25519(envelope, privateKeys) <a class="anchor" href="#crypto-mlkem768-decrypt">#</a></h2>',
  '<p>Decrypts the ML-KEM-768 + X25519 hybrid envelope used for TLS-interop peers that standardize on the smaller hybrid.</p>',
  '<pre><code class="language-javascript">typeof b.crypto.decryptMlkem768X25519; // "function"</code></pre>',

  '<h2 id="crypto-cert-revoked">b.crypto.isCertRevoked(pemOrDer, denyList) <a class="anchor" href="#crypto-cert-revoked">#</a></h2>',
  '<p>Checks a certificate fingerprint against an operator denylist for mTLS revocation and peer-encryption trust decisions.</p>',
  '<pre><code class="language-javascript">typeof b.crypto.isCertRevoked; // "function"</code></pre>',

  '<h2 id="pqc-software">b.pqcSoftware.runKnownAnswerTest() <a class="anchor" href="#pqc-software">#</a></h2>',
  '<p>Self-consistency check for the vendored pure-JS post-quantum bundle. It keygens, encapsulates, decapsulates, and timing-safe-compares the ML-KEM-1024 shared secret so stripped or corrupted vendor bundles fail at boot rather than mid-request.</p>',
  '<pre><code class="language-javascript">var kat = b.pqcSoftware.runKnownAnswerTest();',
  'if (!kat.ok) {',
  '  // fail boot in production; reason names the missing/corrupt bundle path',
  '  kat.reason;',
  '}',
  'b.pqcSoftware.listAlgorithms().indexOf("ml_kem_1024") >= 0;</code></pre>',

  '<h2 id="pqc-software-availability">b.pqcSoftware.isAvailable() / listAlgorithms() <a class="anchor" href="#pqc-software-availability">#</a></h2>',
  '<p>Runtime availability checks for the vendored pure-JS post-quantum bundle. Locked-down deployments that strip <code>lib/vendor</code> can detect the missing fallback explicitly.</p>',
  '<pre><code class="language-javascript">var available = b.pqcSoftware.isAvailable();',
  'var algorithms = b.pqcSoftware.listAlgorithms();',
  'Array.isArray(algorithms) && typeof available === "boolean";</code></pre>',

  '<h2 id="pqc-software-list">b.pqcSoftware.listAlgorithms() <a class="anchor" href="#pqc-software-list">#</a></h2>',
  '<p>Returns the vendored post-quantum algorithm names available through the pure-JS fallback bundle. A stripped deployment returns an empty list instead of crashing at import time.</p>',
  '<pre><code class="language-javascript">var names = b.pqcSoftware.listAlgorithms();',
  'Array.isArray(names); // true</code></pre>',

  '<h2 id="pqc-software-kems">b.pqcSoftware.ml_kem_512 / ml_kem_768 / ml_kem_1024 / DEFAULT_KEM <a class="anchor" href="#pqc-software-kems">#</a></h2>',
  '<p>FIPS 203 ML-KEM algorithm objects from the vendored bundle. The framework default is ML-KEM-1024; lower levels exist for interop and test vectors.</p>',
  '<pre><code class="language-javascript">typeof b.pqcSoftware.DEFAULT_KEM.keygen; // "function"',
  'typeof b.pqcSoftware.ml_kem_1024.encapsulate; // "function"</code></pre>',

  '<h2 id="pqc-software-ml-dsa">b.pqcSoftware.ml_dsa_44 / ml_dsa_65 / ml_dsa_87 / DEFAULT_LATTICE_SIG <a class="anchor" href="#pqc-software-ml-dsa">#</a></h2>',
  '<p>FIPS 204 ML-DSA lattice-signature objects. The default pins to ML-DSA-87 for cat-5 posture.</p>',
  '<pre><code class="language-javascript">typeof b.pqcSoftware.DEFAULT_LATTICE_SIG.sign; // "function"',
  'typeof b.pqcSoftware.ml_dsa_87.verify; // "function"</code></pre>',

  '<h2 id="pqc-software-slh-dsa">b.pqcSoftware.slh_dsa_* / DEFAULT_HASH_SIG <a class="anchor" href="#pqc-software-slh-dsa">#</a></h2>',
  '<p>FIPS 205 SLH-DSA hash-signature objects for SHA2 and SHAKE variants. The default is SLH-DSA-SHAKE-256f.</p>',
  '<pre><code class="language-javascript">typeof b.pqcSoftware.DEFAULT_HASH_SIG.sign; // "function"',
  'typeof b.pqcSoftware.slh_dsa_shake_256f.verify; // "function"</code></pre>',

  '<h2 id="pqc-ml-kem-512">b.pqcSoftware.ml_kem_512.keygen() <a class="anchor" href="#pqc-ml-kem-512">#</a></h2>',
  '<p>FIPS 203 ML-KEM-512 accessor. Use for interoperability tests or deployments that deliberately choose category-1 KEM parameters.</p>',
  '<pre><code class="language-javascript">typeof b.pqcSoftware.ml_kem_512.keygen; // "function"',
  'typeof b.pqcSoftware.ml_kem_512.encapsulate; // "function"</code></pre>',

  '<h2 id="pqc-ml-kem-768">b.pqcSoftware.ml_kem_768.keygen() <a class="anchor" href="#pqc-ml-kem-768">#</a></h2>',
  '<p>FIPS 203 ML-KEM-768 accessor. This is the pure-JS counterpart for peers that standardize on the category-3 KEM profile.</p>',
  '<pre><code class="language-javascript">typeof b.pqcSoftware.ml_kem_768.keygen; // "function"',
  'typeof b.pqcSoftware.ml_kem_768.decapsulate; // "function"</code></pre>',

  '<h2 id="pqc-ml-kem-1024">b.pqcSoftware.ml_kem_1024.keygen() <a class="anchor" href="#pqc-ml-kem-1024">#</a></h2>',
  '<p>FIPS 203 ML-KEM-1024 accessor and the framework default KEM. It is the pure-JS fallback for the category-5 hybrid encryption paths.</p>',
  '<pre><code class="language-javascript">typeof b.pqcSoftware.ml_kem_1024.keygen; // "function"',
  'typeof b.pqcSoftware.ml_kem_1024.encapsulate; // "function"</code></pre>',

  '<h2 id="pqc-ml-dsa-44">b.pqcSoftware.ml_dsa_44.keygen() <a class="anchor" href="#pqc-ml-dsa-44">#</a></h2>',
  '<p>FIPS 204 ML-DSA-44 accessor for category-2 lattice signatures.</p>',
  '<pre><code class="language-javascript">typeof b.pqcSoftware.ml_dsa_44.keygen; // "function"',
  'typeof b.pqcSoftware.ml_dsa_44.sign; // "function"</code></pre>',

  '<h2 id="pqc-ml-dsa-65">b.pqcSoftware.ml_dsa_65.keygen() <a class="anchor" href="#pqc-ml-dsa-65">#</a></h2>',
  '<p>FIPS 204 ML-DSA-65 accessor for category-3 lattice signatures.</p>',
  '<pre><code class="language-javascript">typeof b.pqcSoftware.ml_dsa_65.keygen; // "function"',
  'typeof b.pqcSoftware.ml_dsa_65.verify; // "function"</code></pre>',

  '<h2 id="pqc-ml-dsa-87">b.pqcSoftware.ml_dsa_87.keygen() <a class="anchor" href="#pqc-ml-dsa-87">#</a></h2>',
  '<p>FIPS 204 ML-DSA-87 accessor and the framework default lattice-signature profile.</p>',
  '<pre><code class="language-javascript">typeof b.pqcSoftware.ml_dsa_87.keygen; // "function"',
  'typeof b.pqcSoftware.ml_dsa_87.sign; // "function"</code></pre>',

  '<h2 id="pqc-slh-sha2-128">b.pqcSoftware.slh_dsa_sha2_128f.keygen() <a class="anchor" href="#pqc-slh-sha2-128">#</a></h2>',
  '<p>FIPS 205 SLH-DSA SHA2-128f accessor for stateless hash-based signatures.</p>',
  '<pre><code class="language-javascript">typeof b.pqcSoftware.slh_dsa_sha2_128f.keygen; // "function"',
  'typeof b.pqcSoftware.slh_dsa_sha2_128f.sign; // "function"</code></pre>',

  '<h2 id="pqc-slh-sha2-192">b.pqcSoftware.slh_dsa_sha2_192f.keygen() <a class="anchor" href="#pqc-slh-sha2-192">#</a></h2>',
  '<p>FIPS 205 SLH-DSA SHA2-192f accessor for higher-strength SHA2 hash signatures.</p>',
  '<pre><code class="language-javascript">typeof b.pqcSoftware.slh_dsa_sha2_192f.keygen; // "function"',
  'typeof b.pqcSoftware.slh_dsa_sha2_192f.verify; // "function"</code></pre>',

  '<h2 id="pqc-slh-sha2-256">b.pqcSoftware.slh_dsa_sha2_256f.keygen() <a class="anchor" href="#pqc-slh-sha2-256">#</a></h2>',
  '<p>FIPS 205 SLH-DSA SHA2-256f accessor for category-5 SHA2 hash signatures.</p>',
  '<pre><code class="language-javascript">typeof b.pqcSoftware.slh_dsa_sha2_256f.keygen; // "function"',
  'typeof b.pqcSoftware.slh_dsa_sha2_256f.sign; // "function"</code></pre>',

  '<h2 id="pqc-slh-shake-128">b.pqcSoftware.slh_dsa_shake_128f.keygen() <a class="anchor" href="#pqc-slh-shake-128">#</a></h2>',
  '<p>FIPS 205 SLH-DSA SHAKE-128f accessor for SHAKE-based stateless signatures.</p>',
  '<pre><code class="language-javascript">typeof b.pqcSoftware.slh_dsa_shake_128f.keygen; // "function"',
  'typeof b.pqcSoftware.slh_dsa_shake_128f.verify; // "function"</code></pre>',

  '<h2 id="pqc-slh-shake-192">b.pqcSoftware.slh_dsa_shake_192f.keygen() <a class="anchor" href="#pqc-slh-shake-192">#</a></h2>',
  '<p>FIPS 205 SLH-DSA SHAKE-192f accessor for category-3 SHAKE hash signatures.</p>',
  '<pre><code class="language-javascript">typeof b.pqcSoftware.slh_dsa_shake_192f.keygen; // "function"',
  'typeof b.pqcSoftware.slh_dsa_shake_192f.sign; // "function"</code></pre>',

  '<h2 id="pqc-slh-shake-256">b.pqcSoftware.slh_dsa_shake_256f.keygen() <a class="anchor" href="#pqc-slh-shake-256">#</a></h2>',
  '<p>FIPS 205 SLH-DSA SHAKE-256f accessor and the framework default hash-signature profile.</p>',
  '<pre><code class="language-javascript">typeof b.pqcSoftware.slh_dsa_shake_256f.keygen; // "function"',
  'typeof b.pqcSoftware.slh_dsa_shake_256f.verify; // "function"</code></pre>',

  '<h2 id="vault-derived-salt">b.vault.getDerivedHashSalt() <a class="anchor" href="#vault-derived-salt">#</a></h2>',
  '<p>Returns the process-local salt used by derived hashes for sealed-column lookups. Operators rarely call it directly; it exists so migrations and diagnostics can confirm that indexed sealed fields are using the same namespace material as the active vault.</p>',
  '<pre><code class="language-javascript">var salt = b.vault.getDerivedHashSalt();',
  'Buffer.isBuffer(salt) || typeof salt === "string";</code></pre>',

  '<h2 id="nonce-store-create">b.nonceStore.create(opts) <a class="anchor" href="#nonce-store-create">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  backend:          "memory" | "cluster" | { checkAndInsert, purgeExpired, close },',
  '  sweepIntervalMs:  number,                  // memory backend only — periodic eviction cadence',
  '}</code></pre>',
  '<p>Returns a replay-protection store that the api-encrypt middleware (and any operator surface needing first-time-only semantics for a request-supplied nonce) plugs into. The store exposes <code>checkAndInsert(nonce, expireAt)</code> — atomic check-and-insert that resolves <code>true</code> on first sighting and <code>false</code> on a replay — plus <code>purgeExpired()</code> and <code>close()</code>. The <em>memory</em> backend is single-process accuracy only; the <em>cluster</em> backend uses <code>INSERT ... ON CONFLICT DO NOTHING</code> against a framework table so the primary-key race makes the check atomic across replicas. Operators can also pass a custom backend object (Redis SETNX, Memcached add, etc.) for cross-process accuracy without a SQL hop.</p>',
  '<pre><code class="language-javascript">var store = b.nonceStore.create({ backend: "memory" });',
  'var fresh = await store.checkAndInsert("nonce-abc", Date.now() + 60000); // true',
  'var replay = await store.checkAndInsert("nonce-abc", Date.now() + 60000); // false',
  'await store.purgeExpired();',
  'store.close();</code></pre>',

  '<h2 id="vault-wrap-wrap">b.vaultWrap.wrap(plaintext, passphrase, opts?) <a class="anchor" href="#vault-wrap-wrap">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  memoryCost:   number,                       // Argon2id KiB; default 64 MiB-in-KiB',
  '  timeCost:     number,                       // Argon2id iterations; default 3',
  '  parallelism:  number,                       // Argon2id lanes; default 4',
  '  saltLength:   number,                       // bytes; default 16',
  '  salt:         Buffer,                       // override (testing / deterministic vectors)',
  '  nonce:        Buffer,                       // override (testing / deterministic vectors)',
  '}</code></pre>',
  '<p>Pure (no filesystem I/O) passphrase-derived AEAD wrap for the framework vault keypair. Argon2id stretches the passphrase into a 32-byte wrapping key; XChaCha20-Poly1305 with a fresh 24-byte nonce encrypts the plaintext; the entire format header (magic <code>0xE2</code>, version, KDF id, Argon2 parameters, salt, cipher id, nonce, ciphertext length) is bound as AEAD associated data so a header-byte flip fails verification — defeating downgrade-in-header attacks on KDF parameters or cipher id. Passphrase argument is a Buffer for byte-exactness on binary passphrases.</p>',
  '<pre><code class="language-javascript">// var sealed = await b.vaultWrap.wrap(',
  '//   Buffer.from("vault keypair JSON"),',
  '//   Buffer.from(process.env.BLAMEJS_VAULT_PASSPHRASE),',
  '// );',
  '// sealed[0]; // 0xE2 — wrapped vault magic byte',
  'typeof b.vaultWrap.wrap; // "function"</code></pre>',

  '<h2 id="vault-wrap-unwrap">b.vaultWrap.unwrap(sealed, passphrase) <a class="anchor" href="#vault-wrap-unwrap">#</a></h2>',
  '<p>Inverse of <code>b.vaultWrap.wrap</code>. Parses the format header, re-derives the wrapping key under the supplied passphrase, and decrypts the AEAD ciphertext. Any failure path — wrong passphrase, tampered header, tampered ciphertext — surfaces as a single uniform <code>"Passphrase rejected or wrapped file corrupted"</code> error: callers cannot distinguish which failure mode triggered, which removes the side-channel between bad-passphrase and tamper that an attacker could otherwise exploit.</p>',
  '<pre><code class="language-javascript">// var plaintext = await b.vaultWrap.unwrap(',
  '//   sealedBuffer,',
  '//   Buffer.from(process.env.BLAMEJS_VAULT_PASSPHRASE),',
  '// );',
  '// Buffer.isBuffer(plaintext); // true',
  'typeof b.vaultWrap.unwrap; // "function"</code></pre>',

  '<h2 id="vault-passphrase-source-from-env">b.vaultPassphraseSource.fromEnv(opts?) <a class="anchor" href="#vault-passphrase-source-from-env">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  envVars: {',
  '    value:   string,                          // override; default "BLAMEJS_VAULT_PASSPHRASE"',
  '    file:    string,                          // override; default "BLAMEJS_VAULT_PASSPHRASE_FILE"',
  '    source:  string,                          // override; default "BLAMEJS_VAULT_PASSPHRASE_SOURCE"',
  '  },',
  '}</code></pre>',
  '<p>Reads the vault passphrase from <code>BLAMEJS_VAULT_PASSPHRASE</code> (or the override) as a Buffer, then strips the variable from <code>process.env</code> so later env-dump surfaces (crash dumps, observability sinks, child-process inheritance) cannot resurface it. Returns a Buffer rather than a string so binary passphrases stay byte-exact and no extra UTF-8 string allocation lingers in the heap. Throws when the variable is missing, empty, or exceeds the 4 KiB sanity cap.</p>',
  '<pre><code class="language-javascript">process.env.BLAMEJS_VAULT_PASSPHRASE = "correct horse battery staple";',
  'var passphrase = await b.vaultPassphraseSource.fromEnv();',
  'Buffer.isBuffer(passphrase); // true',
  'process.env.BLAMEJS_VAULT_PASSPHRASE; // undefined — stripped after read</code></pre>',

  '<h2 id="vault-passphrase-source-from-file">b.vaultPassphraseSource.fromFile(filePath, opts?) <a class="anchor" href="#vault-passphrase-source-from-file">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  envVars: {',
  '    file:    string,                          // override; default "BLAMEJS_VAULT_PASSPHRASE_FILE" (used in error messages)',
  '  },',
  '}</code></pre>',
  '<p>Reads the vault passphrase from a file path (typically pointed at by <code>BLAMEJS_VAULT_PASSPHRASE_FILE</code>) and trims trailing newlines so an editor-saved file with a final <code>\\n</code> matches the same passphrase entered any other way. Returns a Buffer; validates non-empty and within the 4 KiB sanity cap.</p>',
  '<pre><code class="language-javascript">// var passphrase = await b.vaultPassphraseSource.fromFile("/run/secrets/vault-passphrase");',
  '// Buffer.isBuffer(passphrase) && passphrase.length > 0;',
  'typeof b.vaultPassphraseSource.fromFile; // "function"</code></pre>',

  '<h2 id="vault-passphrase-source-from-stdin">b.vaultPassphraseSource.fromStdin(promptText?) <a class="anchor" href="#vault-passphrase-source-from-stdin">#</a></h2>',
  '<p>Interactive passphrase entry on a TTY. Puts stdin in raw mode so each keypress arrives without echoing, accumulates per-byte chunks into the passphrase Buffer, handles backspace by zeroing the popped chunk, treats Ctrl-C as cancellation, and zeroes every per-byte chunk after concatenation so only the returned Buffer holds the secret. Throws when stdin is not a TTY (use a file or env source for non-interactive boots).</p>',
  '<pre><code class="language-javascript">// Inside an interactive boot path:',
  '// var passphrase = await b.vaultPassphraseSource.fromStdin("Vault passphrase: ");',
  '// Buffer.isBuffer(passphrase);',
  'typeof b.vaultPassphraseSource.fromStdin; // "function"</code></pre>',

  '<h2 id="vault-passphrase-ops-seal">b.vaultPassphraseOps.seal(opts) <a class="anchor" href="#vault-passphrase-ops-seal">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  dataDir:        string,                     // framework data directory (must exist)',
  '  passphrase:     Buffer,                     // operator passphrase bytes',
  '  keepPlaintext:  boolean,                    // default false — delete vault.key after sealing',
  '}</code></pre>',
  '<p>Wraps an existing plaintext <code>vault.key</code> at <code>dataDir</code> into <code>vault.key.sealed</code> under the supplied passphrase. Crash-safe: writes to <code>vault.key.sealed.tmp</code>, fsyncs, re-reads and round-trip-verifies the bytes unwrap back to the original plaintext, then atomically renames into place. Any verification mismatch aborts with the original <code>vault.key</code> untouched. Pre-flight refuses when <code>vault.key</code> is missing, the sealed file already exists, or a stale <code>.tmp</code> from a prior crash is still on disk.</p>',
  '<pre><code class="language-javascript">// await b.vaultPassphraseOps.seal({',
  '//   dataDir:    "./data",',
  '//   passphrase: Buffer.from(process.env.BLAMEJS_VAULT_PASSPHRASE),',
  '// });',
  '// → { sealedPath: "./data/vault.key.sealed", plaintextDeleted: true }',
  'typeof b.vaultPassphraseOps.seal; // "function"</code></pre>',

  '<h2 id="vault-passphrase-ops-unseal">b.vaultPassphraseOps.unseal(opts) <a class="anchor" href="#vault-passphrase-ops-unseal">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  dataDir:    string,',
  '  passphrase: Buffer,',
  '}</code></pre>',
  '<p>Reverse of <code>seal</code>. Reads <code>vault.key.sealed</code>, unwraps under the passphrase, writes the plaintext to <code>vault.key.tmp</code>, fsyncs and re-reads to confirm the bytes match, then atomically renames into <code>vault.key</code> and deletes the sealed file. Pre-flight refuses when the sealed file is missing or a plaintext <code>vault.key</code> already exists. Use sparingly — for audit, migration, or reverting to plaintext mode.</p>',
  '<pre><code class="language-javascript">// await b.vaultPassphraseOps.unseal({',
  '//   dataDir:    "./data",',
  '//   passphrase: Buffer.from(process.env.BLAMEJS_VAULT_PASSPHRASE),',
  '// });',
  '// → { plaintextPath: "./data/vault.key" }',
  'typeof b.vaultPassphraseOps.unseal; // "function"</code></pre>',

  '<h2 id="vault-passphrase-ops-rotate">b.vaultPassphraseOps.rotate(opts) <a class="anchor" href="#vault-passphrase-ops-rotate">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  dataDir:        string,',
  '  oldPassphrase:  Buffer,',
  '  newPassphrase:  Buffer,',
  '}</code></pre>',
  '<p>Changes the passphrase on an already-sealed vault. Unwraps with <code>oldPassphrase</code>, re-wraps under <code>newPassphrase</code>, round-trip-verifies the new sealed bytes decrypt back to the same keypair AND that the old passphrase no longer unwraps the new bytes (so a no-op rotation is detected and refused), then atomically swaps the file. Underlying keypair is unchanged — only the Argon2id-stretched wrapping key and XChaCha20-Poly1305 nonce/key rotate.</p>',
  '<pre><code class="language-javascript">// await b.vaultPassphraseOps.rotate({',
  '//   dataDir:       "./data",',
  '//   oldPassphrase: Buffer.from(process.env.OLD_PASSPHRASE),',
  '//   newPassphrase: Buffer.from(process.env.NEW_PASSPHRASE),',
  '// });',
  '// → { sealedPath: "./data/vault.key.sealed" }',
  'typeof b.vaultPassphraseOps.rotate; // "function"</code></pre>',

  '<h2 id="vault-rotate-rotate">b.vaultRotate.rotate(opts) <a class="anchor" href="#vault-rotate-rotate">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  dataDir:           string,                  // source data directory (read-only throughout)',
  '  stagingDir:        string,                  // destination — must not already exist',
  '  oldKeys:           keypair,                 // current vault keypair',
  '  newKeys:           keypair,                 // replacement vault keypair',
  '  mode:              "plaintext" | "wrapped", // default "plaintext"',
  '  newPassphrase:     Buffer,                  // required when mode === "wrapped"',
  '  rowBatchSize:      number,                  // SQLite batch size; default 1000',
  '  tables:            [string],                // restrict rotation to these tables',
  '  paths: {                                    // override framework filenames',
  '    encryptedDb:      string,',
  '    dbKeySealed:      string,',
  '    vaultKeyPlain:    string,',
  '    vaultKeySealed:   string,',
  '    additionalSealed: [{ relativePath, required }],',
  '    verbatimFiles:    [{ relativePath, required }],',
  '    verbatimDirs:     [{ relativePath, required }],',
  '  },',
  '  progressCallback:  (event) => void,         // phase / row-count events',
  '}</code></pre>',
  '<p>Vault keypair rotation pipeline. Walks every sealed column in every registered table, decrypts under <code>oldKeys</code> and re-encrypts under <code>newKeys</code> with batched SQLite transactions; re-seals <code>db.key.enc</code> and any operator-supplied additional sealed files; emits a fully-rotated copy of <code>dataDir</code> at <code>stagingDir</code>. The source <code>dataDir</code> is read-only throughout, so a failure leaves it untouched. Caller does the atomic swap (rename or symlink flip) after verifying staging. Round-trip-verifies the staged DB before returning; throws if any sampled row fails to decrypt under <code>newKeys</code> or still decrypts under <code>oldKeys</code>.</p>',
  '<pre><code class="language-javascript">// var result = await b.vaultRotate.rotate({',
  '//   dataDir:    "./data",',
  '//   stagingDir: "./data.rotated",',
  '//   oldKeys:    oldKeypair,',
  '//   newKeys:    newKeypair,',
  '// });',
  '// result.tablesProcessed >= 0 && result.totalRowsProcessed >= 0;',
  'typeof b.vaultRotate.rotate; // "function"</code></pre>',

  '<h2 id="vault-rotate-verify">b.vaultRotate.verify(opts) <a class="anchor" href="#vault-rotate-verify">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  keys:           keypair,                    // keypair to attempt decryption with',
  '  db:             sqliteHandle,               // node:sqlite handle on the rotated DB',
  '  oldKeys:        keypair,                    // optional — flag rows that still decrypt under oldKeys',
  '  sampleMin:      number,                    // minimum rows per table; default 5',
  '  samplePercent:  number,                    // fraction of rows; default 0.01',
  '  tables:         [string],                  // restrict verification to these tables',
  '}</code></pre>',
  '<p>Read-only diagnostic over a rotated database. For every registered table, samples rows (max of <code>sampleMin</code> or <code>samplePercent</code> of the row count), attempts to decrypt every sealed column under <code>keys</code>, and records failures. When <code>oldKeys</code> is supplied, also flags any sampled row that STILL decrypts under the old keypair — that is a regression: rotation didn\'t take effect for that row. Use after the rotation pipeline ships, after a backup restore, or as a post-deploy smoke test.</p>',
  '<pre><code class="language-javascript">// var result = b.vaultRotate.verify({',
  '//   keys:    newKeypair,',
  '//   oldKeys: oldKeypair,',
  '//   db:      sqliteHandle,',
  '// });',
  '// result.ok && result.failures.length === 0 && result.regressions.length === 0;',
  'typeof b.vaultRotate.verify; // "function"</code></pre>',

].join("\n"),
};
