"use strict";

module.exports = {
  slug:  "database",
  title: "Database",
  body: [
  '<h1>Database</h1>',
  '<p>Structured-data storage lives in <code>b.db</code>: a SQLite wrapper on top of <code>node:sqlite</code> with sealed-by-default columns, the audit chain, the consent chain, and a small set of helpers operators don\'t need to write themselves. Files written outside the DB use <code>b.atomicFile</code>; field-level cryptography is handled by <code>b.cryptoField</code>.</p>',

  '<h2 id="db">Database <a class="anchor" href="#db">#</a></h2>',
  '<p>Plain Node 24.14+ — no native node-gyp build, no separate driver. Sealed columns use the storage envelope (KEM 0x03 hybrid, cipher 0x02 XChaCha20-Poly1305, KDF 0x02 SHAKE256), so any sealed value carries the ciphersuite that produced it. Rotating the vault key reseals on next write; reads continue to work against either generation.</p>',

  '<h3>b.db.init(opts)</h3>',
  '<pre><code class="language-javascript">{',
  '  dataDir:  string,                          // required: true',
  '  schema:   Array&lt;TableDef&gt;,                  // required: true',
  '  atRest:   "encrypted" | "plain",            // default: "encrypted"',
  '  tmpDir:   string,                           // default: $BLAMEJS_TMPDIR or platform tmp',
  '}',
  '',
  '// TableDef:',
  '{',
  '  name:                    string,            // required: true',
  '  columns:                 { [colName]: { type, primaryKey?,',
  '                                            notNull?, unique?, default?,',
  '                                            references? } },',
  '                                              // required: true',
  '  indexes:                 Array&lt;{ name, columns, unique? }&gt;,',
  '                                              // default: []',
  '  sealedFields:            string[],          // default: [] — vault-sealed at rest',
  '  derivedHashes:           { [hashCol]: { from: srcCol } },',
  '                                              // default: {} — SHA3 hash for indexed lookup',
  '  subjectField:            string,            // default: null — for subject.export/erase',
  '  personalDataCategories:  object,            // default: {} — GDPR data-category tags',
  '}</code></pre>',
  '<pre><code class="language-javascript">await b.db.init({',
  '  dataDir: "./data",',
  '  schema: [',
  '    {',
  '      name: "users",',
  '      columns: {',
  '        _id:       { type: "TEXT", primaryKey: true },',
  '        email:     { type: "TEXT", notNull: true },',
  '        emailHash: { type: "TEXT", notNull: true, unique: true },',
  '        name:      { type: "TEXT" },',
  '        createdAt: { type: "INTEGER", notNull: true },',
  '      },',
  '      sealedFields:   ["email", "name"],',
  '      derivedHashes:  { emailHash: { from: "email" } },',
  '      indexes:        [{ name: "idx_users_created", columns: ["createdAt"] }],',
  '    },',
  '  ],',
  '});</code></pre>',

  '<h3>b.db.from(tableName) — Query builder</h3>',
  '<p>Chainable; every call but the terminal verb returns the same Query for further refinement.</p>',
  '<pre><code class="language-javascript">// Query methods:',
  '//   .where(field, op?, value)              // op-form or shorthand 2-arg',
  '//   .where({ field: value, ... })           // object-form, AND of equalities',
  '//   .select(["col1", "col2"])               // optional projection',
  '//   .orderBy(field, "asc" | "desc")',
  '//   .limit(n).offset(n)',
  '//',
  '// Terminal methods (sync — node:sqlite is synchronous):',
  '//   .first() / .all() / .count()',
  '//   .insertOne(row) / .insertMany(rows)',
  '//   .updateOne(changes) / .updateMany(changes)',
  '//   .deleteOne() / .deleteMany()',
  '//   .stream()                               // → Readable in object mode',
  '',
  'await b.db.from("users").insertOne({',
  '  _id:       "u-42",',
  '  email:     "alice@example.com",   // sealed in transit to disk',
  '  name:      "Alice",                // sealed',
  '  createdAt: Date.now(),',
  '});',
  '// On disk: emailHash = SHA3-512("alice@example.com"); email/name vault-sealed.',
  '',
  '// where() against a sealed column auto-rewrites to the derived-hash column:',
  'var alice = b.db.from("users")',
  '  .where({ email: "alice@example.com" })   // → WHERE emailHash = ?',
  '  .first();',
  '// row comes back unsealed: { _id, email, name, ... }</code></pre>',
  '<p>Sealed columns without a derived hash <strong>throw</strong> on <code>where()</code> — every encryption uses a fresh nonce, so a direct ciphertext lookup would always return zero rows. Failing loudly is safer than the silent zero-row trap.</p>',

  '<h3>Other surface</h3>',
  '<pre><code class="language-javascript">// b.db.prepare(sql)              — node:sqlite Statement (raw escape hatch)',
  '// b.db.runSql(sql)               — multi-statement DDL',
  '// b.db.transaction(fn)           — wraps fn in BEGIN/COMMIT (rollback on throw)',
  '// b.db.hashFor(table, value)     — derived hash for a table+value (manual lookup keying)',
  '// b.db.stream(sql, ...params, { table })  — Readable; opts.table enables auto-unseal',
  '// b.db.flushToDisk()             — re-encrypt tmpfs SQLite to <dataDir>/db.enc now',
  '// b.db.close()                   — graceful shutdown',
  '',
  'await b.db.transaction(function () {',
  '  b.db.from("users").insertOne({ _id: "u-x", email: "x@example.test", emailHash: "h" });',
  '});</code></pre>',
  '<p>Large reads stream — <code>b.db.stream("SELECT * FROM audit_log WHERE actorUserIdHash = ?", hash, { table: "audit_log" })</code> returns a Node Readable that yields rows lazily, with sealed columns auto-unsealed per row. The <code>{ table }</code> option opts into the unseal step; raw / aggregate queries omit it.</p>',

  '<h2 id="db-prepare">b.db.prepare(sql) <a class="anchor" href="#db-prepare">#</a></h2>',
  '<p>Raw SQLite statement escape hatch for framework-adjacent code that cannot fit through <code>b.db.from(table)</code>. Prefer the query builder for ordinary app data.</p>',
  '<pre><code class="language-javascript">typeof b.db.prepare; // "function"</code></pre>',

  '<h2 id="db-run-sql">b.db.runSql(sql) / exec(sql) <a class="anchor" href="#db-run-sql">#</a></h2>',
  '<p>DDL and multi-statement execution helpers used by migrations and boot-time schema setup.</p>',
  '<pre><code class="language-javascript">typeof b.db.runSql; // "function"',
  'typeof b.db.exec; // "function"</code></pre>',

  '<h2 id="db-transaction">b.db.transaction(fn) <a class="anchor" href="#db-transaction">#</a></h2>',
  '<p>Synchronous transaction wrapper. It commits when <code>fn</code> returns and rolls back when <code>fn</code> throws.</p>',
  '<pre><code class="language-javascript">typeof b.db.transaction; // "function"</code></pre>',

  '<h2 id="db-stream">b.db.stream(sql, params, options) <a class="anchor" href="#db-stream">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  table:       string,                  // optional — auto-unseal sealed columns per row',
  '  streamLimit: number,                  // default: db.init({ streamLimit }) (1_000_000)',
  '}</code></pre>',
  '<p>Readable stream for large result sets. Passing a <code>table</code> option enables sealed-column unseal on each emitted row. The <code>streamLimit</code> option (or <code>db.init({ streamLimit })</code>) caps the maximum rows the stream emits before destroying with a thrown <code>db/stream-limit-exceeded</code> error — guards against an accidentally-unbounded export OOM-ing the host. The same ceiling applies to the chainable <code>b.db.from(table).stream({ streamLimit })</code> form.</p>',
  '<pre><code class="language-javascript">// Default ceiling — typical exports finish well under the cap',
  '// b.db.stream("SELECT * FROM audit_log WHERE actorUserIdHash = ?", hash, { table: "audit_log" })',
  '//   .on("data", function (row) { /* ... */ })',
  '//   .on("error", function (err) { /* db/stream-limit-exceeded surfaces here */ })',
  '//   .on("end",   function ()    { /* drained */ });',
  '// Per-call bump for an audited export path',
  '// b.db.from("audit_log").where({ kind: "subject.erased" })',
  '//   .stream({ streamLimit: 5_000_000 });',
  'typeof b.db.stream; // "function"</code></pre>',

  '<h2 id="db-hash-for">b.db.hashFor(table, value) <a class="anchor" href="#db-hash-for">#</a></h2>',
  '<p>Computes the derived lookup hash for a table-scoped sealed value. Operators use it for manual joins or diagnostics around sealed lookup columns.</p>',
  '<pre><code class="language-javascript">typeof b.db.hashFor; // "function"</code></pre>',

  '<h2 id="db-flush-close">b.db.flushToDisk() / close() <a class="anchor" href="#db-flush-close">#</a></h2>',
  '<p>Persistence and shutdown helpers. <code>flushToDisk</code> forces encrypted-at-rest state to disk; <code>close</code> drains and closes the active database handle.</p>',
  '<pre><code class="language-javascript">typeof b.db.flushToDisk; // "function"',
  'typeof b.db.close; // "function"</code></pre>',

  '<h2 id="db-introspection">b.db.getMode() / getDbPath() / getDataResidency() / getTableMetadata(table) <a class="anchor" href="#db-introspection">#</a></h2>',
  '<p>Read-only runtime introspection helpers for diagnostics, health endpoints, and admin tooling.</p>',
  '<pre><code class="language-javascript">typeof b.db.getMode; // "function"',
  'typeof b.db.getDbPath; // "function"',
  'typeof b.db.getDataResidency; // "function"',
  'typeof b.db.getTableMetadata; // "function"</code></pre>',

  '<h2 id="db-integrity">b.db.integrityCheck() / integrityMonitor(options) <a class="anchor" href="#db-integrity">#</a></h2>',
  '<p>SQLite and framework-chain integrity checks. The monitor variant runs periodically and emits operator-visible evidence when checks fail.</p>',
  '<pre><code class="language-javascript">typeof b.db.integrityCheck; // "function"',
  'typeof b.db.integrityMonitor; // "function"</code></pre>',

  '<h2 id="db-purge-audit-chain">b.db.purgeAuditChain(options) <a class="anchor" href="#db-purge-audit-chain">#</a></h2>',
  '<p>Administrative retention primitive for scoped audit-chain purges. Operators should pair it with exported evidence and retention policy approvals.</p>',
  '<pre><code class="language-javascript">typeof b.db.purgeAuditChain; // "function"</code></pre>',

  '<h2 id="db-declare-worm">b.db.declareWorm(opts) <a class="anchor" href="#db-declare-worm">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  tables:  string[],                 // required: true',
  '  posture: string | null,            // optional — recorded for audit',
  '}</code></pre>',
  '<p>Installs row-level WORM (write-once-read-many) <code>BEFORE-DELETE</code> + <code>BEFORE-UPDATE</code> triggers on operator-named business-record tables. Per SEC Rule 17a-4(f), FINRA Rule 4511, and 21 CFR Part 11 §11.10(c). Idempotent. Under <code>sec-17a-4</code> / <code>finra-4511</code> / <code>fda-21cfr11</code> postures the framework refuses to boot unless at least one table is declared.</p>',
  '<pre><code class="language-javascript">typeof b.db.declareWorm; // "function"</code></pre>',

  '<h2 id="db-declare-dual-control">b.db.declareRequireDualControl(opts) <a class="anchor" href="#db-declare-dual-control">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  tables:  string[],                 // required: true',
  '  m:       number,                   // default: 2',
  '  n:       number,                   // default: m',
  '  posture: string | null,            // optional',
  '}</code></pre>',
  '<p>Marks tables as requiring an m-of-n dual-control grant for hard erase. <code>b.db.eraseHard</code> consults the gate and refuses without a consumed grant from <code>b.dualControl.consume()</code>.</p>',
  '<pre><code class="language-javascript">typeof b.db.declareRequireDualControl; // "function"</code></pre>',

  '<h2 id="db-erase-hard">b.db.eraseHard(table, rowId, opts) <a class="anchor" href="#db-erase-hard">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  reason:           string,                 // required: true',
  '  subjectId:        string | null,          // legal-hold consult key',
  '  dualControlGrant: object | null,          // consumed grant for gated tables',
  '}</code></pre>',
  '<p>Crypto-erases sealed columns, deletes the row, and runs <code>REINDEX &lt;table&gt;</code> so the deleted row\'s index entries are rebuilt and B-tree residual pages drop. Consults legal-hold; refuses under active hold. Refuses without a consumed dual-control grant when the table is gated.</p>',
  '<pre><code class="language-javascript">typeof b.db.eraseHard; // "function"</code></pre>',

  '<h3>b.db.vacuumAfterErase(opts) <a class="anchor" href="#db-vacuum-after-erase">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  mode:  "incremental" | "full", // required',
  '  pages: number,                 // incremental only',
  '}</code></pre>',
  '<p>Post-erasure compaction primitive for privacy workflows. After subject erasure removes rows from SQLite, operators call an incremental or full vacuum so deleted content is not left in freelist pages longer than necessary.</p>',
  '<pre><code class="language-javascript">var vacuumPlan = { mode: "incremental", pages: 1000 };',
  '// await b.db.vacuumAfterErase(vacuumPlan);',
  'typeof b.db.vacuumAfterErase; // "function"</code></pre>',

  '<h2 id="migrations">Migrations <a class="anchor" href="#migrations">#</a></h2>',
  '<p><code>b.migrations</code> applies versioned schema files at boot, holds a cluster-wide advisory lock so only one replica runs the wave, and refuses to start the app if a migration goes from "applied" to "missing on disk".</p>',
  '<h3>Migration file shape</h3>',
  '<pre><code class="language-javascript">{',
  '  up:           (db) =&gt; void,              // required: true — synchronous DDL/DML',
  '  description:  string,                    // default: filename',
  '}</code></pre>',
  '<pre><code class="language-javascript">// migrations/0007-page-publish-state.js',
  'module.exports = {',
  '  up: function (database) {',
  '    database.run("ALTER TABLE pages ADD COLUMN publishedAt INTEGER");',
  '    database.run("CREATE INDEX idx_pages_published ON pages(publishedAt)");',
  '  },',
  '};</code></pre>',
  '<p>No <code>down</code> by default — operators that want reversible migrations write the inverse as the next migration, which keeps the audit trail honest. Each applied migration writes a row to <code>_blamejs_migrations</code> with a SHA3-512 of the file content; if the file changes after application, boot refuses with a checksum mismatch.</p>',

  '<h2 id="migrations-create">b.migrations / b.migrations.create(opts) <a class="anchor" href="#migrations-create">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  dir:           string,   // required: true — migrations directory',
  '  db:            object,   // default: b.db — sqlite handle to run against',
  '  staleAfterMs:  number,   // default: 0 — advisory-lock takeover threshold',
  '}</code></pre>',
  '<p><code>b.migrations.create</code> returns a runner with <code>up()</code> / <code>down({ steps })</code> / <code>status()</code> / <code>dir</code>. <code>up()</code> applies pending migrations under the cluster-wide advisory lock and records each in <code>_blamejs_migrations</code>; <code>down()</code> rolls back the most-recent N applied migrations using each file\'s <code>down(db)</code> function and refuses when a migration omits <code>down</code>. <code>status()</code> returns <code>{ applied, pending, total }</code> for dashboards. The top-level <code>b.migrations</code> module also exposes <code>MigrationError</code>, <code>MIGRATIONS_TABLE</code>, <code>LOCK_TABLE</code>, and the filename grammar regex for tooling.</p>',
  '<pre><code class="language-javascript">var migrations = b.migrations.create({ dir: "./migrations" });',
  '// await migrations.up();        // → { applied: [...], skipped: [...] }',
  '// await migrations.down({ steps: 1 }); // → { reverted: [...] }',
  'typeof b.migrations.create; // "function"',
  'typeof b.migrations.MigrationError; // "function"</code></pre>',

  '<h2 id="external-db-pool">b.externalDb.Pool <a class="anchor" href="#external-db-pool">#</a></h2>',
  '<p><code>b.externalDb.Pool</code> is the per-backend connection pool the framework instantiates internally for every backend registered via <code>b.externalDb.init</code>. Operators rarely construct one directly — <code>b.externalDb.query</code> and <code>b.externalDb.transaction</code> acquire and release through the pool automatically — but the class is exposed so framework-adjacent code can build a pool against a custom <code>connect</code> / <code>close</code> pair, run diagnostics, or reuse the LRU + reaper + waiter-queue behavior outside the registered-backend table. Instances expose <code>acquire()</code> / <code>release(client)</code> / <code>destroy(client)</code> / <code>drain()</code> / <code>stats()</code> and emit <code>externaldb.pool.acquire_wait</code> metrics when the pool is at <code>max</code>.</p>',
  '<pre><code class="language-javascript">typeof b.externalDb.Pool; // "function"</code></pre>',

  '<h3 id="external-db-assert-role-hardening">b.externalDb.assertRoleHardening(opts) <a class="anchor" href="#external-db-assert-role-hardening">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  declaredRoles: string[],   // required — roles the operator expects to exist',
  '  backend:       string,     // default: defaultBackend',
  '  mode:          "audit" | "throw",   // default: "audit"',
  '  ignoreSystem:  boolean,    // default: true — skip postgres / pg_* / rds_* / azure_* / cloudsqlsuperuser',
  '}</code></pre>',
  '<p>Boot-time guard against role enumeration / unrecognized-role drift. Reads <code>pg_roles</code>, compares against <code>declaredRoles</code>, and emits <code>db.role.hardening.unrecognized</code> on every drift. Operators using <code>mode: "throw"</code> refuse boot when unrecognized roles appear — closes the "leftover migration role" / "ALTER ROLE outside change-management" forensic gap. Returns <code>{ declared, observed, unrecognized, missing }</code>. Non-Postgres dialects emit <code>db.role.hardening.skipped</code> and return empty arrays.</p>',
  '<pre><code class="language-javascript">// At boot — refuses to start when pg_roles surfaces a role we did not declare',
  '// await b.externalDb.assertRoleHardening({',
  '//   backend:       "main",',
  '//   declaredRoles: ["app_user", "analytics_user", "admin"],',
  '//   mode:          "throw",',
  '// });',
  'typeof b.externalDb.assertRoleHardening; // "function"</code></pre>',

  '<h3 id="safe-jsonpath">b.safeJsonPath.validateExpression(expr, opts?) / b.safeJsonPath.validatePointer(pointer, opts?) / b.safeJsonPath.validateKey(key, opts?) / b.safeJsonPath.validateContainment(value, opts?) <a class="anchor" href="#safe-jsonpath">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  maxBytes:     number,   // expression / key cap; defaults: 2 KiB / 1 KiB',
  '  maxSegments:  number,   // pointer-array cap; default: 64',
  '  maxDepth:     number,   // bracket-nesting cap; default: 8',
  '  maxNodes:     number,   // containment-shape node cap; default: 1024',
  '}</code></pre>',
  '<p>Strict-allowlist validators for Postgres SQL/JSON paths. <code>validateExpression</code> refuses filter predicates (<code>?(...)</code>), recursive descent (<code>$..</code>), script-shape (<code>(@.x.y)</code>), JS-source hints, and bracket depth bombs — operators with legitimate filter needs build the predicate themselves with bound parameters and pass the result through their own safe-string accessor. <code>validatePointer</code> validates an array of segments for <code>#&gt;</code> / <code>#&gt;&gt;</code>; <code>validateKey</code> validates the operand for <code>-&gt;</code> / <code>-&gt;&gt;</code> / <code>?</code>; <code>validateContainment</code> walks the value side of <code>where(field, "@&gt;", value)</code> and refuses any string leaf or key carrying NUL / control / bidi / zero-width characters. Wired automatically by <code>b.db.from(table).where(field, "@&gt;", value)</code> and the <code>?</code> / <code>?|</code> / <code>?&amp;</code> JSONB key operators.</p>',
  '<pre><code class="language-javascript">// Validates the JSONB containment shape — refuses NUL in any string leaf',
  'b.safeJsonPath.validateContainment({ roles: ["admin"], region: "us-east" });',
  '',
  '// Refuses operator-supplied filter predicates outright',
  'try { b.safeJsonPath.validateExpression("$.users[?(@.role == \\"admin\\")]"); }',
  'catch (e) { e.code; /* "safe-jsonpath/filter-expr-refused" */ }',
  '',
  '// JSONB containment via the chainable Query — value side runs through validateContainment',
  '// var rows = b.db.from("orders")',
  '//   .where("metadata", "@>", { tier: "gold" })',
  '//   .all();',
  'typeof b.safeJsonPath.validateExpression; // "function"</code></pre>',

  '<h2 id="seeders">Seeders <a class="anchor" href="#seeders">#</a></h2>',
  '<p><code>b.seeders</code> is for content the framework or app needs at boot: default roles, country lists, the wiki\'s own landing pages.</p>',
  '<h3>Seeder file shape</h3>',
  '<pre><code class="language-javascript">{',
  '  description:  string,                    // required: true',
  '  envs:         string[],                  // default: inferred from path',
  '  rerunnable:   boolean,                   // default: false — UPSERT on every boot',
  '  dependsOn:    string[],                  // default: [] — sibling seed names',
  '  run:          (db, ctx) =&gt; Promise,      // required: true',
  '}</code></pre>',
  '<p>Rerunnable seeders UPSERT on every boot — useful while iterating on copy. One-shot seeders apply once and record their fingerprint. Forward-only: seeders have no <code>down()</code> inverse — operators reset by truncating the seeded tables themselves.</p>',
  '<p><code>ctx</code> carries <code>{ env, runner, clock }</code> so seeds can invoke other framework primitives without re-importing them. Cycles in <code>dependsOn</code> + missing deps are caught at load.</p>',

  '<h2 id="atomic-file">Atomic file writes <a class="anchor" href="#atomic-file">#</a></h2>',
  '<p><code>b.atomicFile</code> is the crash-safe file-write primitive every framework component that touches disk uses. Write to <code>&lt;target&gt;.tmp</code>, <code>fsync</code> the file, atomically <code>rename</code> over the target. A power-loss mid-write leaves either the OLD bytes or the NEW bytes intact, never a half-written file.</p>',
  '<h3>Surface</h3>',
  '<pre><code class="language-javascript">b.atomicFile.writeJson(path, value)        // → byteCount',
  'b.atomicFile.writeBuffer(path, buf)         // → byteCount',
  'b.atomicFile.readJson(path)                 // → parsed value | null',
  'b.atomicFile.readSync(path)                 // → Buffer',
  'b.atomicFile.lock(path, fn)                 // serialize fn() per-path</code></pre>',
  '<pre><code class="language-javascript">await b.atomicFile.writeJson("./data/feature-flags.json", flags);',
  'await b.atomicFile.writeBuffer("./data/binary.bin", Buffer.from(payload));',
  '',
  '// Lock-and-modify pattern for read-modify-write workflows',
  'await b.atomicFile.lock("./data/counter.json", async function () {',
  '  var counter = await b.atomicFile.readJson("./data/counter.json") || { n: 0 };',
  '  counter.n += 1;',
  '  await b.atomicFile.writeJson("./data/counter.json", counter);',
  '});</code></pre>',

  '<h2 id="atomic-file-write">b.atomicFile.write(path, data, opts?) / writeSync(path, data, opts?) <a class="anchor" href="#atomic-file-write">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  mode:     number,  // optional file mode',
  '  retry:    object,  // optional filesystem retry policy',
  '  tmpSuffix:string,  // optional temp-file suffix override',
  '}</code></pre>',
  '<p>Crash-safe byte write. Data is written to a temp file, fsynced, renamed over the target, and the containing directory is fsynced where the platform supports it.</p>',
  '<pre><code class="language-javascript">var writePlan = { path: "./data/cache.bin", data: Buffer.from("payload") };',
  '// await b.atomicFile.write(writePlan.path, writePlan.data);',
  'typeof b.atomicFile.write; // "function"</code></pre>',

  '<h2 id="atomic-file-read">b.atomicFile.read(path, opts?) / readSync(path, opts?) <a class="anchor" href="#atomic-file-read">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  maxBytes: number, // optional read cap',
  '  encoding: string, // optional text encoding',
  '  retry:    object,',
  '}</code></pre>',
  '<p>Bounded file read helpers used anywhere operator-controlled paths are read through the framework. Pass <code>maxBytes</code> when the caller does not already control file size.</p>',
  '<pre><code class="language-javascript">var readPlan = { path: "./data/cache.bin", maxBytes: b.constants.BYTES.mib(1) };',
  '// var buf = await b.atomicFile.read(readPlan.path, { maxBytes: readPlan.maxBytes });',
  'typeof b.atomicFile.readSync; // "function"</code></pre>',

  '<h2 id="atomic-file-read-sync">b.atomicFile.readSync(path, options) <a class="anchor" href="#atomic-file-read-sync">#</a></h2>',
  '<p>Synchronous bounded read for boot-time code paths that cannot await but still need the atomic-file size and encoding checks.</p>',
  '<pre><code class="language-javascript">typeof b.atomicFile.readSync; // "function"</code></pre>',

  '<h2 id="atomic-file-json">b.atomicFile.writeJson(path, value, opts?) / readJson(path, opts?) <a class="anchor" href="#atomic-file-json">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  maxBytes: number, // readJson cap',
  '  spaces:   number, // writeJson formatting',
  '  retry:    object,',
  '}</code></pre>',
  '<p>JSON variants of the atomic read/write flow. They pair with <code>b.safeJson</code> so persisted framework metadata keeps the same prototype-pollution and size guarantees as request parsing.</p>',
  '<pre><code class="language-javascript">var jsonPlan = { path: "./data/settings.json", value: { enabled: true } };',
  '// await b.atomicFile.writeJson(jsonPlan.path, jsonPlan.value);',
  'typeof b.atomicFile.readJson; // "function"</code></pre>',

  '<h2 id="atomic-file-read-json">b.atomicFile.readJson(path, options) <a class="anchor" href="#atomic-file-read-json">#</a></h2>',
  '<p>Reads and parses persisted JSON through the same bounded, safe parser path used for request JSON.</p>',
  '<pre><code class="language-javascript">typeof b.atomicFile.readJson; // "function"</code></pre>',

  '<h2 id="atomic-file-lock">b.atomicFile.lock(path, fn, opts?) <a class="anchor" href="#atomic-file-lock">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  timeoutMs: number, // optional wait budget',
  '  retry:     object,',
  '}</code></pre>',
  '<p>Per-path lock for read-modify-write workflows. Concurrent callers for the same path serialize through the lock while unrelated paths proceed independently.</p>',
  '<pre><code class="language-javascript">var lockPlan = { path: "./data/counter.json" };',
  '// await b.atomicFile.lock(lockPlan.path, async function () { return true; });',
  'typeof b.atomicFile.lock; // "function"</code></pre>',

  '<h2 id="atomic-file-dirs">b.atomicFile.ensureDir(path) / listDir(path, opts?) <a class="anchor" href="#atomic-file-dirs">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  filter:   function, // optional listDir name predicate',
  '  maxFiles: number,',
  '}</code></pre>',
  '<p>Directory helpers used by backup, vault, bundle, and seeder code paths. They centralize safe mkdir and bounded directory listing instead of open-coding filesystem calls.</p>',
  '<pre><code class="language-javascript">var dirPlan = { path: "./data/uploads" };',
  '// await b.atomicFile.ensureDir(dirPlan.path);',
  'typeof b.atomicFile.listDir; // "function"</code></pre>',

  '<h2 id="atomic-file-list-dir">b.atomicFile.listDir(path, options) <a class="anchor" href="#atomic-file-list-dir">#</a></h2>',
  '<p>Lists a directory with optional filtering and max-file bounds so maintenance jobs do not accidentally scan unbounded trees.</p>',
  '<pre><code class="language-javascript">typeof b.atomicFile.listDir; // "function"</code></pre>',

  '<h2 id="atomic-file-copy">b.atomicFile.copy(src, dst, opts?) / copyDirRecursive(src, dst, opts?) <a class="anchor" href="#atomic-file-copy">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  overwrite: boolean,',
  '  retry:     object,',
  '  filter:    function, // recursive directory copy',
  '}</code></pre>',
  '<p>Copy helpers for restore staging and bundle extraction. Directory recursion stays inside the declared source and destination paths and keeps per-file writes crash-safe.</p>',
  '<pre><code class="language-javascript">var copyPlan = { src: "data-a-text", dst: "data-b-text" };',
  '// await b.atomicFile.copy(copyPlan.src, copyPlan.dst);',
  'typeof b.atomicFile.copyDirRecursive; // "function"</code></pre>',

  '<h2 id="atomic-file-copy-dir">b.atomicFile.copyDirRecursive(src, dst, options) <a class="anchor" href="#atomic-file-copy-dir">#</a></h2>',
  '<p>Copies a directory tree through crash-safe per-file writes for restore staging and bundle extraction workflows.</p>',
  '<pre><code class="language-javascript">typeof b.atomicFile.copyDirRecursive; // "function"</code></pre>',

  '<h2 id="atomic-file-maintenance">b.atomicFile.cleanOrphans(path, opts?) / exists(path) / pathTimestamp(date?) <a class="anchor" href="#atomic-file-maintenance">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  olderThanMs: number,',
  '  limit:       number,',
  '}</code></pre>',
  '<p>Maintenance helpers for temp-file cleanup, existence checks, and sortable path timestamps used by backup and restore workflows.</p>',
  '<pre><code class="language-javascript">var stamp = b.atomicFile.pathTimestamp(new Date(Date.UTC(2026, 4, 1)));',
  'stamp.indexOf("2026") === 0; // true',
  'typeof b.atomicFile.cleanOrphans; // "function"</code></pre>',

  '<h2 id="atomic-file-exists">b.atomicFile.exists(path) <a class="anchor" href="#atomic-file-exists">#</a></h2>',
  '<p>Checks whether a path exists without leaking filesystem exceptions into callers that only need a boolean.</p>',
  '<pre><code class="language-javascript">typeof b.atomicFile.exists; // "function"</code></pre>',

  '<h2 id="atomic-file-path-timestamp">b.atomicFile.pathTimestamp(date) <a class="anchor" href="#atomic-file-path-timestamp">#</a></h2>',
  '<p>Builds sortable timestamp strings for backup, restore, and audit snapshot paths.</p>',
  '<pre><code class="language-javascript">var stamp = b.atomicFile.pathTimestamp(new Date(Date.UTC(2026, 4, 1)));',
  'stamp.indexOf("2026") === 0; // true</code></pre>',

  '<h2 id="atomic-file-fsync">b.atomicFile.fsync(fd) / fsyncDir(path) <a class="anchor" href="#atomic-file-fsync">#</a></h2>',
  '<p>Low-level durability helpers exposed for operator code that already owns a file descriptor but wants the same platform-aware fsync behavior the framework uses internally.</p>',
  '<pre><code class="language-javascript">typeof b.atomicFile.fsync; // "function"',
  'typeof b.atomicFile.fsyncDir; // "function"</code></pre>',

  '<h2 id="atomic-file-fsync-dir">b.atomicFile.fsyncDir(path) <a class="anchor" href="#atomic-file-fsync-dir">#</a></h2>',
  '<p>Fsyncs a containing directory where the platform supports it, closing the durability gap after atomic rename.</p>',
  '<pre><code class="language-javascript">typeof b.atomicFile.fsyncDir; // "function"</code></pre>',

  '<h2 id="atomic-file-write-sync">b.atomicFile.writeSync(path, data, options) <a class="anchor" href="#atomic-file-write-sync">#</a></h2>',
  '<p>Synchronous crash-safe write for boot-time code paths that cannot await the async writer.</p>',
  '<pre><code class="language-javascript">typeof b.atomicFile.writeSync; // "function"</code></pre>',

  '<h2 id="crypto-field">Field-level crypto <a class="anchor" href="#crypto-field">#</a></h2>',
  '<p><code>b.cryptoField</code> is the middleware <code>b.db</code> uses internally to seal and unseal columns. Operators rarely call it directly, but it\'s reachable when a feature stores ciphertext outside the DB and wants the same envelope shape. Full envelope details live at <a href="/crypto-vault#envelope">Crypto &amp; Vault → envelope</a>.</p>',

  '<h2 id="crypto-field-seal-row">b.cryptoField.sealRow(table, row) <a class="anchor" href="#crypto-field-seal-row">#</a></h2>',
  '<p>Seals configured fields on a row before storage, preserving lookup hashes for fields declared with derived indexes.</p>',
  '<pre><code class="language-javascript">typeof b.cryptoField.sealRow; // "function"</code></pre>',

  '<h2 id="crypto-field-unseal-row">b.cryptoField.unsealRow(table, row) <a class="anchor" href="#crypto-field-unseal-row">#</a></h2>',
  '<p>Unseals configured fields on a row after retrieval while leaving unsealed columns untouched.</p>',
  '<pre><code class="language-javascript">typeof b.cryptoField.unsealRow; // "function"</code></pre>',

  '<h2 id="crypto-field-erase-row">b.cryptoField.eraseRow(table, row) <a class="anchor" href="#crypto-field-erase-row">#</a></h2>',
  '<p>Erases sealed fields and derived lookup hashes for retention, DSR, and right-to-erasure flows.</p>',
  '<pre><code class="language-javascript">typeof b.cryptoField.eraseRow; // "function"</code></pre>',

  '<h2 id="crypto-field-compute-derived">b.cryptoField.computeDerived(table, field, value) <a class="anchor" href="#crypto-field-compute-derived">#</a></h2>',
  '<p>Computes the deterministic lookup hash for a sealed field that has a hash namespace configured.</p>',
  '<pre><code class="language-javascript">typeof b.cryptoField.computeDerived; // "function"</code></pre>',

  '<h2 id="crypto-field-lookup-hash">b.cryptoField.lookupHash(table, field, value) <a class="anchor" href="#crypto-field-lookup-hash">#</a></h2>',
  '<p>Convenience helper for building lookup predicates against derived-hash columns without unsealing every row.</p>',
  '<pre><code class="language-javascript">typeof b.cryptoField.lookupHash; // "function"</code></pre>',

  '<h2 id="crypto-field-schema">b.cryptoField.getSchema(table) <a class="anchor" href="#crypto-field-schema">#</a></h2>',
  '<p>Returns the registered sealed-field schema for diagnostics, migrations, and admin tooling.</p>',
  '<pre><code class="language-javascript">typeof b.cryptoField.getSchema; // "function"</code></pre>',

  '<h2 id="crypto-field-sealed-fields">b.cryptoField.getSealedFields(table) <a class="anchor" href="#crypto-field-sealed-fields">#</a></h2>',
  '<p>Returns the configured sealed column names for a table.</p>',
  '<pre><code class="language-javascript">typeof b.cryptoField.getSealedFields; // "function"</code></pre>',

  '<h2 id="ddl-change-control">DDL Change Control</h2>',
  '<p>Formal multi-approver workflow for any schema change under SOX 404 and PCI DSS Req 6.5 / 10.7. The framework hashes the proposed SQL, requires N independent approvers, refuses application outside the configured window, and emits audit events at every stage.</p>',

  '<h3>b.ddlChangeControl.create(opts) <a class="anchor" href="#ddl-change-control-create">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  audit:       object,    // required b.audit reference',
  '  approvers:   number,    // minimum approver count (default 2)',
  '  windowSpec:  string,    // "always" or "Mon-Fri 09:00-17:00 UTC"',
  '  posture:     string,    // sox-404 / pci-dss / soc2',
  '  signWith:    function,  // optional ML-DSA-87 signer',
  '  verifyWith:  function,  // optional verifier',
  '  store:       object,    // optional durable backing store',
  '  selfApproval: boolean,  // refused under regulated postures',
  '  now:         function,  // optional clock injection',
  '}</code></pre>',
  '<p>Returns <code>{ propose, approve, reject, applyApproved, list, get }</code>. Audit emissions on namespace <code>ddl</code>: <code>ddl.change.proposed</code>, <code>.approved</code>, <code>.rejected</code>, <code>.applied</code>, <code>.apply_refused</code>.</p>',
  '<pre><code class="language-javascript">typeof b.ddlChangeControl.create; // "function"</code></pre>',

  '<h2 id="audit-segregation">Audit Segregation of Duties</h2>',
  '<p>SOX 404 and SOC 2 CC1.3 require that the actor recorded on an audit row matches the SQL identity that wrote it. The framework provides an in-process bound-emit wrapper plus generated Postgres trigger DDL that the database itself enforces against.</p>',

  '<h3>b.audit.bindActor(actorId, opts?) <a class="anchor" href="#audit-bind-actor">#</a></h3>',
  '<p>Returns a wrapped emitter whose <code>safeEmit</code> and <code>record</code> refuse any event whose actor mismatches the bound identity. Operators inside <code>b.middleware.dbRoleFor</code> scopes get role-equivalent checks via the optional <code>roleEquivalent(actor, role)</code> opt.</p>',
  '<pre><code class="language-javascript">typeof b.audit.bindActor; // "function"</code></pre>',

  '<h3>b.audit.generateActorBindingTriggerSql(opts?) <a class="anchor" href="#audit-trigger-sql">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  column:        string,   // default actorUserId',
  '  tableName:     string,   // default _blamejs_audit_log',
  '  allowRoles:    array,    // SQL roles allowed to insert any actor',
  '  roleMappingFn: string,   // optional Postgres function name',
  '}</code></pre>',
  '<p>Returns <code>{ up, down, functionName, triggerName }</code> Postgres DDL the operator applies via <code>b.externalDb.migrate</code> under <code>sox-404</code> / <code>soc2-cc1.3</code> posture so the database refuses INSERTs whose actor does not match <code>current_user</code>.</p>',
  '<pre><code class="language-javascript">var sql = b.audit.generateActorBindingTriggerSql({ allowRoles: ["blamejs_service"] });',
  'typeof sql.up; // "string"</code></pre>',

  '<h3>b.audit.assertSegregation(opts) <a class="anchor" href="#audit-assert-segregation">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  db:            object,   // required externalDb-shaped query() handle',
  '  functionName:  string,',
  '  triggerName:   string,',
  '}</code></pre>',
  '<p>Boot-time check the operator wires under regulated postures. Returns <code>{ ok }</code> when the trigger function and trigger row are present in the database; throws <code>AuditSegregationError</code> with the missing pieces enumerated when not.</p>',
  '<pre><code class="language-javascript">typeof b.audit.assertSegregation; // "function"</code></pre>',

  '<h2 id="migrations-history">Schema-version history</h2>',
  '<p>Every <code>b.externalDb.migrate.up</code> wave appends a signed row to <code>_blamejs_schema_version_history</code> carrying <code>version</code>, <code>ranAt</code>, <code>ranBy</code>, <code>schemaIntrospectionHash</code>, and an ML-DSA-87 / SLH-DSA-SHAKE-256f signature from the audit-signing keypair. Tampered rows do not verify.</p>',

  '<h3>b.externalDb.migrate.create(opts).history(opts?) <a class="anchor" href="#migrate-history">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  dir:              string,    // required — path to migrations directory',
  '  backend:          string,    // default: externalDb default backend',
  '  audit:            AuditTap,  // default: null',
  '  staleAfterMs:     number,    // default: 0 — force-replace stale lock after N ms',
  '  schemaIntrospect: function,  // optional async (xdb) => hash',
  '  ranBy:            string,    // optional override for the writer label',
  '  signHistory:      boolean,   // default true',
  '}</code></pre>',
  '<p>Returns the list of history rows with <code>{ verified, verifyReason }</code> per row. Emits <code>migrations.history.appended</code> on every write, <code>migrations.history.verified</code> on every read, <code>migrations.history.tamper_detected</code> when a row signature fails to verify.</p>',
  '<pre><code class="language-javascript">typeof b.externalDb.migrate.create; // "function"</code></pre>',

  '<h2 id="tenant-quota-create">b.tenantQuota.create(opts) <a class="anchor" href="#tenant-quota-create">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  db:                 object,    // required — the b.db namespace',
  '  tenantField:        string,    // required — column name carrying the tenant id',
  '  defaultBytesCap:    number,    // optional — default byte cap per tenant (default 1 GiB)',
  '  perTenantBytesCap:  { [tenantId]: number }, // optional overrides',
  '  tables:             [string],  // optional — tables to walk; defaults to every table declaring tenantField',
  '  audit:              boolean,   // default true — emit tenant.quota.exceeded',
  '  cacheTtlMs:         number,    // default 30s — per-tenant byte-usage cache',
  '}</code></pre>',
  '<p>Per-tenant DB storage cap. Returns <code>{ assert, snapshot, list, invalidate }</code>: <code>assert(tenantId)</code> throws when usage exceeds the configured cap (operators call this before INSERT/UPDATE); <code>snapshot(tenantId)</code> returns <code>{ bytesUsed, bytesCap, percent }</code>; <code>list()</code> returns the snapshot for every observed tenant. The framework caches per-tenant totals for <code>cacheTtlMs</code> so a hot path doesn&#39;t pay the SUM on every assert. Maps to SOC 2 CC6.1 (logical access controls) + ISO 27001 A.8.1.5 (information classification). Audit emission: <code>tenant.quota.exceeded</code>.</p>',
  '<pre><code class="language-javascript">var quotaPlan = {',
  '  db:                 b.db,',
  '  tenantField:        "tenantId",',
  '  defaultBytesCap:    b.constants.BYTES.gib(1),',
  '  perTenantBytesCap:  { "tenant-vip": b.constants.BYTES.gib(10) },',
  '};',
  '// var quota = b.tenantQuota.create(quotaPlan);',
  '// await quota.assert("tenant-acme");',
  'typeof b.tenantQuota.create; // "function"</code></pre>',

  '<h2 id="tenant-quota-budget">b.tenantQuota.budget(opts) <a class="anchor" href="#tenant-quota-budget">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  db:                       object,   // optional — the b.db namespace',
  '  tenantField:              string,   // required — column name carrying the tenant id',
  '  perTenantQpsCap:          number,   // default 100 — calls per second per tenant',
  '  perTenantTotalRowsRead:   number,   // default 50000 — rows read per window',
  '  window:                   number,   // default 60s — sliding-window size',
  '  audit:                    boolean,  // default true — emit tenant.budget.exceeded',
  '}</code></pre>',
  '<p>Per-tenant query budget — replaces the framework&#39;s global <code>maxRowsPerQuery</code> for tenant-scoped scenarios. Returns <code>{ observe, snapshot, reset }</code>; <code>observe(tenantId, { rowsRead })</code> increments the sliding-window counters and throws <code>TenantQuotaError</code> when either the QPS-equivalent call total or rows-read total exceeds the configured cap. Audit emission: <code>tenant.budget.exceeded</code>.</p>',
  '<pre><code class="language-javascript">var budgetPlan = {',
  '  tenantField:            "tenantId",',
  '  perTenantQpsCap:        100,',
  '  perTenantTotalRowsRead: 50000,',
  '  window:                 b.constants.TIME.minutes(1),',
  '};',
  '// var budget = b.tenantQuota.budget(budgetPlan);',
  '// budget.observe("tenant-acme", { rowsRead: 12 });',
  'typeof b.tenantQuota.budget; // "function"</code></pre>',

  '<h2 id="tenant-quota-instrument">b.tenantQuota.instrumentQuery(opts) <a class="anchor" href="#tenant-quota-instrument">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  rows:        [object],     // required — query result rows',
  '  tenantField: string,       // required — column carrying the tenant id',
  '  tenantId:    string,       // required — operator-claimed tenant for this query',
  '  table:       string,       // optional — for audit-emission metadata',
  '  audit:       boolean,      // default true — emit db.tenant.crossover',
  '}</code></pre>',
  '<p>Tenant-isolation breach detection. Operators wrap query results so the framework verifies every row&#39;s <code>tenantField</code> matches the operator-claimed <code>tenantId</code>. Mismatches emit <code>db.tenant.crossover</code> on both the audit chain and the observability bus, surfacing RLS-bypass / row-policy mistakes that would otherwise be silent.</p>',
  '<pre><code class="language-javascript">// var rows = b.db.from("orders").where({ tenantId: "tenant-acme" }).all();',
  '// var check = b.tenantQuota.instrumentQuery({',
  '//   rows: rows, tenantField: "tenantId", tenantId: "tenant-acme",',
  '// });',
  'typeof b.tenantQuota.instrumentQuery; // "function"</code></pre>',

  '<h2 id="db-export-csv">b.db.exportCsv(opts) <a class="anchor" href="#db-export-csv">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  table:           string,            // required',
  '  where:           object,            // optional WHERE clause object',
  '  columns:         [string],          // optional projection (defaults to every column)',
  '  bom:             boolean,           // optional UTF-8 BOM prefix',
  '  format:          "rfc4180",         // RFC 4180 strict — only supported format',
  '  signWith:        b.auditSign,       // optional ML-DSA-87 signer',
  '  timestampFields: [string],          // optional ms-int → ISO-8601 cast',
  '}</code></pre>',
  '<p>RFC 4180 strict CSV export of a single table. CRLF line endings, double-quote escaping, optional UTF-8 BOM. Sealed columns auto-unseal via the <code>b.cryptoField</code> registration. Returns <code>{ csv, bytes, bytesWritten, sha3_512, signature?, manifest, rowCount }</code> — the SHA3-512 plaintext digest pins integrity, and an operator-supplied <code>signWith</code> (typically <code>b.auditSign</code>) attaches a detached ML-DSA-87 signature over the CSV bytes. Emits <code>db.export.csv</code>.</p>',
  '<pre><code class="language-javascript">var exportPlan = {',
  '  table:           "orders",',
  '  where:           { status: "shipped" },',
  '  bom:             true,',
  '  signWith:        b.auditSign,',
  '  timestampFields: ["createdAt"],',
  '};',
  '// var out = b.db.exportCsv(exportPlan);',
  'typeof b.db.exportCsv; // "function"</code></pre>',

  '<h2 id="local-db-thin">b.localDb.thin(opts) <a class="anchor" href="#local-db-thin">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  file:      string,                              // required absolute path',
  '  schemaSql: string,                              // required CREATE TABLE / INDEX script run at open',
  '  recovery:  "refuse" | "rename-and-recreate",   // default: "refuse"',
  '  pragmas:   object,                              // optional extra PRAGMA overrides (bare-identifier names only)',
  '  audit:     boolean,                             // default: true',
  '}</code></pre>',
  '<p>Lightweight <code>node:sqlite</code> wrapper for desktop-daemon-shaped local state. The full <code>b.db</code> stack &mdash; vault-sealed columns, audit chain, framework schema bootstrap, derived-hash lookup, encrypted-at-rest tmpfs &mdash; is overkill for a daemon keeping a hundred-row registry on the operator&#39;s laptop. <code>b.localDb.thin</code> keeps the parts a daemon does need: WAL journal mode with a 5-second busy timeout, boot-time <code>PRAGMA integrity_check</code>, optional corrupt-rename-and-recreate recovery, an LRU-bounded prepared-statement cache, and audit emits on open / recover / close. Returns <code>{ db, prepare, run, query, close, file, recovered, recoveredTo }</code>; <code>prepare</code> caches the compiled statement keyed by the SQL string, and <code>run(sql, ...params)</code> / <code>query(sql, ...params)</code> are convenience wrappers that bind through the cache. Throws <code>LocalDbThinError</code> on bad opts, on integrity-check failure when <code>recovery: "refuse"</code>, on rename-recovery I/O failure, and on prepare/run/query after <code>close()</code>. Operators with PHI / PCI / governed schemas go straight to <code>b.db</code>.</p>',
  '<pre><code class="language-javascript">// var fs = require("node:fs");',
  '// var os = require("node:os");',
  '// var path = require("node:path");',
  '// var dir = fs.mkdtempSync(path.join(os.tmpdir(), "wiki-localdb-thin-"));',
  '// var thin = b.localDb.thin({',
  '//   file:      path.join(dir, "daemon.db"),',
  '//   schemaSql: "CREATE TABLE IF NOT EXISTS notes (id INTEGER PRIMARY KEY, body TEXT NOT NULL);",',
  '//   recovery:  "rename-and-recreate",',
  '//   audit:     false,',
  '// });',
  '// thin.run("INSERT INTO notes (body) VALUES (?)", "alpha");',
  '// var rows = thin.query("SELECT body FROM notes ORDER BY id");',
  '// rows[0].body; // "alpha"',
  '// thin.close();',
  '// fs.rmSync(dir, { recursive: true, force: true });',
  'typeof b.localDb.thin; // "function"</code></pre>',

  '<h2 id="db-table-metadata-jsonschema">b.db.getTableMetadata({ format }) <a class="anchor" href="#db-table-metadata-jsonschema">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  table:  string,                          // required when format is provided',
  '  format: "blamejs" | "json-schema-2020-12", // default "blamejs"',
  '}</code></pre>',
  '<p>Reflective schema introspection. The default <code>blamejs</code> form returns the framework&#39;s internal metadata snapshot (PK/FK/sealed/derived fields, subject mapping). The <code>json-schema-2020-12</code> form emits a JSON Schema 2020-12 representation of the table — sealed fields gain <code>x-blamejs-sealed: true</code>, derived-hash columns gain <code>x-blamejs-derived-from</code>, and the <code>$schema</code> URI explicitly names the 2020-12 dialect so generated validators round-trip.</p>',
  '<pre><code class="language-javascript">// b.db.getTableMetadata("orders");                                      // internal-shape',
  '// var schema = b.db.getTableMetadata({ table: "orders", format: "json-schema-2020-12" });',
  'typeof b.db.getTableMetadata; // "function"</code></pre>',
].join("\n"),
};
