"use strict";

module.exports = {
  slug:  "format-helpers",
  title: "Format Helpers",
  body: [
  '<h1>Format Helpers</h1>',
  '<p>Small, focused primitives for the data-shape concerns most apps eventually need: CSV parse / serialize, UUID generation, slug derivation, time-zone-aware datetime, ZIP archive creation, cursor pagination, and HTML form rendering with CSRF + validation.</p>',

  '<h2 id="csv">CSV</h2>',

  '<h3>b.csv.parse(input, opts?) <a class="anchor" href="#csv-parse">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  header:                 boolean,            // default: true — first row is field names',
  '  delimiter:              string,             // default: ","',
  '  quote:                  string,             // default: \'"\'',
  '  eol:                    "\\r\\n" | "\\n",    // default: auto-detect',
  '  maxBytes:               number,             // default: C.BYTES.mib(16)',
  '  maxRows:                number,             // default: 1_000_000',
  '  maxFieldBytes:          number,             // default: C.BYTES.mib(1)',
  '}</code></pre>',
  '<p>RFC 4180 parser. With <code>header: true</code> returns an array of objects; with <code>header: false</code> an array of arrays. Bad inputs (multi-char delimiter, delimiter equal to quote, non-string-non-buffer input) throw at the call site instead of producing silently malformed output.</p>',
  '<pre><code class="language-javascript">var rows = b.csv.parse("name,age\\nalice,30\\nbob,25");',
  '// → [ { name: "alice", age: "30" }, { name: "bob", age: "25" } ]',
  '',
  'var noHeader = b.csv.parse("1,2,3\\n4,5,6", { header: false });',
  '// → [ ["1","2","3"], ["4","5","6"] ]</code></pre>',

  '<h3>b.csv.stringify(rows, opts?) <a class="anchor" href="#csv-stringify">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  header:       boolean,           // default: true — emit header row',
  '  delimiter:    string,            // default: ","',
  '  quote:        string,            // default: \'"\'',
  '  eol:          "\\r\\n" | "\\n",   // default: "\\r\\n"',
  '  alwaysQuote:  boolean,           // default: false — only quote when needed',
  '}</code></pre>',
  '<p><code>b.csv</code> is for <strong>trusted-source-only</strong> emission — it performs RFC 4180 quote/delimiter escaping and bounds anti-DoS limits on parse (<code>maxBytes</code> / <code>maxRows</code> / <code>maxFieldBytes</code>). It does NOT defend against the broader CSV-injection threat catalog (Excel/Sheets formula triggers, Unicode bidi overrides, dangerous-function denylist, homoglyphs, control-byte injection, BOM mid-stream, CSV-bombs). Any path that emits or accepts user-supplied cells MUST route through <code>b.guardCsv</code> — see the <a href="/guard-content#guard-csv">guard-csv</a> section.</p>',
  '<pre><code class="language-javascript">b.csv.stringify([{ name: "Alice", note: "said \\"hi\\"" }]);',
  '// → \'name,note\\r\\nAlice,"said ""hi"""\\r\\n\'',
  '',
  '// User-supplied cells go through b.guardCsv, NOT b.csv:',
  'b.guardCsv.serialize([{ name: "=cmd|x" }], { profile: "strict" });',
  '// → strict profile prepends TAB so spreadsheets disarm the formula trigger.</code></pre>',

  '<h2 id="uuid">UUID</h2>',

  '<h3>b.uuid.v4() / b.uuid.v7() / b.uuid.parse(s) / b.uuid.isValid(s) <a class="anchor" href="#uuid-helpers">#</a></h3>',
  '<p>RFC 4122 v4 (random) + RFC 9562 v7 (time-sortable). v7 encodes a 48-bit Unix-millisecond timestamp in the first 48 bits, then 74 random bits — IDs generated within the same millisecond sort by their random suffix; across milliseconds they sort by time. B-tree index locality is dramatically better than v4 for INSERT-heavy tables.</p>',
  '<pre><code class="language-javascript">b.uuid.v4();',
  '// → "f47ac10b-58cc-4372-a567-0e02b2c3d479"',
  '',
  'b.uuid.v7();',
  '// → "01941bf3-9c4a-7d8e-9c11-3a4b5c6d7e8f"',
  '//     ^^^^^^^^^^^^^^^^^                  → unix ms (sortable)',
  '//                       7                 → version',
  '//                        ^^^^^^^^^^^^^^^^ → 74 random bits',
  '',
  'b.uuid.parse("f47ac10b-58cc-4372-a567-0e02b2c3d479");',
  '// → { version: 4, bytes: Buffer<...> }',
  '',
  'b.uuid.isValid("not-a-uuid");   // → false</code></pre>',

  '<h3 id="uuid-v7">b.uuid.v7(opts?) <a class="anchor" href="#uuid-v7">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  now:  number,                                // default: Date.now() — operator override for deterministic fixtures',
  '}</code></pre>',
  '<p>RFC 9562 §5.7 time-ordered UUID. Bytes 0-5 are a 48-bit big-endian Unix-millisecond timestamp; bytes 6-7 hold the version nibble (7) plus 12 random bits; bytes 8-15 hold the RFC 4122 variant + 62 random bits. IDs sort by creation time even lexicographically — B-tree index inserts stay near the right edge instead of scattering across the index, so v7 is the right default for any UUID landing in a sortable column (jobs queue, audit-chain extensions, anything where insertion order matters for index locality). Entropy comes from <code>b.crypto.generateBytes</code> — the same source as <code>crypto.randomUUID()</code>. Pass <code>opts.now</code> to fix the timestamp for deterministic test fixtures.</p>',
  '<pre><code class="language-javascript">b.uuid.v7();',
  '// → "01941bf3-9c4a-7d8e-9c11-3a4b5c6d7e8f"',
  '',
  '// Deterministic fixture — same ms produces the same time prefix:',
  'var fixed = b.uuid.v7({ now: Date.UTC(2026, 0, 1) });',
  'fixed.charAt(14) === "7";   // version nibble',
  '',
  '// v7 sorts by time even as plain strings:',
  'var a = b.uuid.v7({ now: 1700000000000 });',
  'var c = b.uuid.v7({ now: 1700000001000 });',
  'a < c;   // true</code></pre>',

  '<h2 id="template">Template</h2>',

  '<h3 id="template-render">b.template.render(view, data?) <a class="anchor" href="#template-render">#</a></h3>',
  '<pre><code class="language-javascript">// First arg: view name (no extension) — resolves under <cwd>/views/<view>.html.',
  '// Second arg: data scope object made available to the template.',
  '//',
  '// For a custom views directory, use b.template.create({ viewsDir }) and call',
  '// .render(view, data?) on the engine instance.</code></pre>',
  '<p>Convenience renderer using a default singleton engine rooted at <code>&lt;cwd&gt;/views</code>. The framework\'s template language is eval-free — no dynamic code generation, no <code>eval</code>, no <code>vm.runInThisContext</code> — so an operator who renders <code>req.query.template</code> can\'t reach arbitrary JS. Tag syntax: <code>{{ expr }}</code> (HTML-escaped output), <code>{{{ expr }}}</code> (raw output for operator-trusted HTML), <code>{{&gt; name }}</code> (partial under <code>views/partials/&lt;name&gt;.html</code>), <code>{% extends "name" %}</code> + <code>{% block name %}…{% endblock %}</code> for layout inheritance, <code>{% if %}</code>/<code>{% else %}</code>/<code>{% endif %}</code>, <code>{% for ident in expr %}…{% endfor %}</code>. View names containing <code>..</code> or <code>\\0</code> are rejected; resolved paths outside <code>viewsDir</code> are rejected; layout / partial recursion is bounded at depth 16. Function calls in expressions invoke functions the operator passed in <code>data</code> — the interpreter ships zero built-ins.</p>',
  '<pre><code class="language-javascript">// Direct call uses <cwd>/views as the views dir.',
  'typeof b.template.render;       // "function"',
  '',
  '// Custom views dir — preferred for any non-trivial app:',
  '// var engine = b.template.create({ viewsDir: __dirname + "/views" });',
  '// var html = engine.render("welcome", { name: "Alice", isAdmin: true });',
  '// typeof html === "string";        // true',
  '',
  '// Helpers come from data, not built-ins:',
  '// var html = engine.render("invoice", { row: row, fmt: { date: b.time.format } });',
  '// In the template:  {{ fmt.date(row.createdAt, { dateStyle: "long" }) }}',
  'typeof b.template.create;       // "function"</code></pre>',

  '<h2 id="sandbox">Sandbox</h2>',

  '<h3 id="sandbox-run">b.sandbox.run(opts) <a class="anchor" href="#sandbox-run">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  source:     string,                          // required — operator-supplied JS source',
  '  input:      any,                             // optional — JSON-serializable, passed to source as `input`',
  '  timeoutMs:  number,                          // default: 250 — max 10000',
  '  maxBytes:   number,                          // default: 64 MiB — floor 4 MiB, cap 1 GiB',
  '  allowed:    [string],                        // optional — allowlist of extra globals (JSON / Math / Date / Map / Set / RegExp / typed-arrays / ...)',
  '}</code></pre>',
  '<p>Isolates operator-supplied transforms in a fresh <code>worker_threads.Worker</code> with strict resource limits and a hand-built scope. The bootstrap deletes <code>require</code> / <code>process</code> / <code>Buffer</code> / <code>setTimeout</code> / <code>setImmediate</code> / <code>setInterval</code> / <code>queueMicrotask</code> / <code>global</code> off <code>globalThis</code> before compiling source, so filesystem / network / child_process / worker re-entry are unreachable. Heap caps are derived from <code>maxBytes</code>; v8 kills the worker on overflow. Result size is capped at <code>maxBytes / 4</code>. The <code>allowed</code> list is intersected against <code>b.sandbox.KNOWN_SAFE_BUILTINS</code> at the host before being shipped to the worker — anything outside the allowlist refuses at the call site. JS-language primitives (Object / Array / String / Number / Boolean / Symbol / Promise / Error / TypeError / RangeError / RegExp) survive regardless. Returns <code>{ result, runtimeMs, peakBytes }</code> on success; throws <code>SandboxError</code> on timeout / oversized result / runtime error / heap-cap kill. Audit emits <code>sandbox.run</code> on success and <code>sandbox.run.refused</code> on every failure path.</p>',
  '<pre><code class="language-javascript">// var rv = await b.sandbox.run({',
  '//   source:    "return { upper: input.name.toUpperCase(), len: input.name.length };",',
  '//   input:     { name: "alice" },',
  '//   timeoutMs: 1000,',
  '//   allowed:   ["JSON", "Math"],',
  '// });',
  '// rv.result;                       // → { upper: "ALICE", len: 5 }',
  '// typeof rv.runtimeMs === "number"; // → true',
  '',
  '// Compose with b.template — operator-supplied helpers run in the sandbox:',
  '// var engine = b.template.create({',
  '//   viewsDir:        __dirname + "/views",',
  '//   sandbox:         true,',
  '//   sandboxHelpers:  { titleCase: "return input[0].toUpperCase() + input.slice(1);" },',
  '//   sandboxOpts:     { timeoutMs: 100, allowed: ["JSON"] },',
  '// });',
  'typeof b.sandbox.run; // "function"</code></pre>',

  '<h2 id="slug">Slug</h2>',

  '<h3>b.slug(input, opts?) <a class="anchor" href="#slug">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  maxLength:        number,                   // default: 80',
  '  preserveUnicode:  boolean,                  // default: false — keep non-ASCII letters',
  '  separator:        string,                   // default: "-"',
  '  reserved:         [string],                 // default: b.slug.RESERVED',
  '}</code></pre>',
  '<p>URL-safe identifier derivation. Strips diacritics, lowercases, collapses whitespace + punctuation to <code>-</code>, truncates at a word boundary so a slug never ends mid-word. Reserved-word collision (<code>"api"</code>, <code>"admin"</code>) gets a <code>-1</code> suffix automatically.</p>',
  '<pre><code class="language-javascript">b.slug("Café résumé!");                  // → "cafe-resume"',
  'b.slug("Это пример", { preserveUnicode: true });  // → "это-пример"',
  '',
  'b.slug.RESERVED;   // → ["api", "admin", "static", ...] — operator-extensible</code></pre>',

  '<h3>b.slug.unique(input, exists, opts?) <a class="anchor" href="#slug-unique">#</a></h3>',
  '<p>Returns a unique slug derived from <code>input</code>, calling <code>exists(candidate)</code> until one is free. Adds <code>-2</code>, <code>-3</code>, … suffixes on collision. Useful for collision handling at insert time.</p>',
  '<pre><code class="language-javascript">var seen = new Set(["welcome", "welcome-2"]);',
  'var unique = await b.slug.unique("Welcome", async function (candidate) {',
  '  return seen.has(candidate);',
  '});',
  '// → "welcome-3"</code></pre>',

  '<h2 id="time">Time</h2>',

  '<h3>b.time.toParts(date, opts?) / b.time.format(date, opts?) <a class="anchor" href="#time-toparts">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  timezone:    string,                        // default: "UTC" — IANA tz name',
  '  locale:      string,                        // default: "en-US"',
  '  // .format-only: passes through to Intl.DateTimeFormat:',
  '  dateStyle?:  "full" | "long" | "medium" | "short",',
  '  timeStyle?:  "full" | "long" | "medium" | "short",',
  '}</code></pre>',
  '<p>Timezone-aware datetime arithmetic on top of <code>Intl.DateTimeFormat</code>. No vendored tz data — the runtime\'s ICU shape is current enough.</p>',
  '<pre><code class="language-javascript">var anchor = new Date(Date.UTC(2026, 3, 30, 14, 32, 0));   // Apr 30 2026 14:32 UTC',
  '',
  'b.time.toParts(anchor, { timezone: "America/New_York" });',
  '// → { year: 2026, month: 4, day: 30, hour: 10, minute: 32, weekday: 4, weekdayName: "Thu", ... }',
  '',
  'b.time.format(anchor, { timezone: "America/New_York", dateStyle: "long" });',
  '// → "April 30, 2026"</code></pre>',

  '<h3>b.time.addDays(date, n, opts?) / .addMonths(date, n, opts?) / .startOfDay(date, opts?) / .endOfDay(date, opts?) / .diffDays(d1, d2, opts?) / .parseISO(s) / .tzOffsetMs(date, tz) <a class="anchor" href="#time-arith">#</a></h3>',
  '<p>DST-safe arithmetic: <code>addDays</code> preserves the wall-clock hour across DST transitions; <code>addMonths</code> clamps overflow (Jan 31 + 1 month → Feb 28 / 29). <code>startOfDay / endOfDay</code> snap to local midnight in the given timezone. <code>tzOffsetMs(date, tz)</code> returns the offset between UTC and the named tz at that instant (negative for west-of-UTC).</p>',
  '<pre><code class="language-javascript">var anchor = new Date(Date.UTC(2026, 3, 30, 14, 32, 0));',
  'b.time.addDays(anchor, 7, { timezone: "America/New_York" });',
  'b.time.addMonths(new Date("2026-01-31T00:00:00Z"), 1);   // Feb clamp',
  'b.time.startOfDay(anchor, { timezone: "America/New_York" });',
  'b.time.parseISO("2026-04-30T14:32:00-04:00");',
  'b.time.tzOffsetMs(anchor, "America/New_York");           // → -14400000 (UTC-4 EDT)</code></pre>',

  '<h2 id="time-format">b.time.format(date, options) <a class="anchor" href="#time-format">#</a></h2>',
  '<p>Formats a date with the runtime ICU timezone and locale data, returning the same operator-facing string shape as <code>Intl.DateTimeFormat</code>.</p>',
  '<pre><code class="language-javascript">typeof b.time.format; // "function"</code></pre>',

  '<h2 id="time-add-months">b.time.addMonths(date, n, options) <a class="anchor" href="#time-add-months">#</a></h2>',
  '<p>Adds calendar months and clamps overflow days so end-of-month arithmetic remains predictable.</p>',
  '<pre><code class="language-javascript">var feb = b.time.addMonths(new Date("2026-01-31T00:00:00Z"), 1);',
  'feb instanceof Date; // true</code></pre>',

  '<h2 id="time-start-day">b.time.startOfDay(date, options) <a class="anchor" href="#time-start-day">#</a></h2>',
  '<p>Snaps a date to local midnight in the requested timezone.</p>',
  '<pre><code class="language-javascript">typeof b.time.startOfDay; // "function"</code></pre>',

  '<h2 id="time-end-day">b.time.endOfDay(date, options) <a class="anchor" href="#time-end-day">#</a></h2>',
  '<p>Snaps a date to the end of the local day in the requested timezone.</p>',
  '<pre><code class="language-javascript">typeof b.time.endOfDay; // "function"</code></pre>',

  '<h2 id="time-diff-days">b.time.diffDays(d1, d2, options) <a class="anchor" href="#time-diff-days">#</a></h2>',
  '<p>Returns calendar-day distance with timezone-aware day boundaries instead of raw millisecond division.</p>',
  '<pre><code class="language-javascript">typeof b.time.diffDays; // "function"</code></pre>',

  '<h2 id="time-parse-iso">b.time.parseISO(s) <a class="anchor" href="#time-parse-iso">#</a></h2>',
  '<p>Parses an ISO timestamp and fails closed for malformed input rather than accepting JavaScript date coercion surprises.</p>',
  '<pre><code class="language-javascript">b.time.parseISO("2026-04-30T14:32:00Z") instanceof Date; // true</code></pre>',

  '<h2 id="time-offset">b.time.tzOffsetMs(date, timezone) <a class="anchor" href="#time-offset">#</a></h2>',
  '<p>Returns the offset between UTC and the named timezone at a specific instant, including DST changes.</p>',
  '<pre><code class="language-javascript">typeof b.time.tzOffsetMs; // "function"</code></pre>',

  '<h2 id="time-iso-no-ms">b.time.toIso8601NoMs(date) <a class="anchor" href="#time-iso-no-ms">#</a></h2>',
  '<p>Serializes a date to an ISO-8601 timestamp without milliseconds for stable operator logs and filenames.</p>',
  '<pre><code class="language-javascript">typeof b.time.toIso8601NoMs; // "function"</code></pre>',

  '<h2 id="archive">Archive</h2>',

  '<h3>b.archive.zip() <a class="anchor" href="#archive-zip">#</a></h3>',
  '<p>ZIP creation for "download my data" / log archives / plain-zip exports. <code>b.backup</code> produces sealed encrypted bundles; <code>b.archive</code> produces operator-readable ZIP files. Format support: stored + deflate (auto-fallback to STORE when deflate doesn\'t shrink), UTF-8 file names (EFS bit), per-file mtime. Path-traversal defense: backslashes normalized to forward slashes; leading slashes stripped; <code>..</code> segments rejected at <code>addFile()</code> time.</p>',
  '<pre><code class="language-javascript">var archive = b.archive.zip();',
  'archive.addFile("readme.txt",     "Hello\\n");',
  'archive.addFile("data/users.csv", Buffer.from("a,b\\n1,2\\n"));         // deflate by default',
  'archive.addFile("avatars/me.png", Buffer.alloc(64), { method: "store" });  // already-compressed',
  '',
  'var zipBytes = archive.toBuffer();',
  'var digest   = archive.digest();                 // SHA3-512 hex, for integrity logs',
  '',
  'archive.entryCount;   // → 3',
  'zipBytes.length > 0;</code></pre>',

  '<h3>b.archive.zip().addFile(name, contentOrStream) — streaming sources <a class="anchor" href="#archive-zip-streaming-sources">#</a></h3>',
  '<p><code>addFile</code> accepts a Node <code>Readable</code> as content in addition to <code>Buffer</code> / string. Streaming entries are not finalized until <code>toStream()</code> runs; they cannot be combined with <code>toBuffer()</code> (which throws <code>archive/streaming-entry</code> if any entry has a Readable source). The local-file-header for a streaming entry is written with the data-descriptor flag (APPNOTE 4.4.4 bit 3) and a 16-byte descriptor follows the deflated bytes — operators reading the archive with stdlib unzip do not need to know it was produced by streaming.</p>',
  '<pre><code class="language-javascript">// var archive = b.archive.zip();',
  '// archive.addFile("logs/2026-q1.ndjson", fs.createReadStream("/var/log/app/q1.ndjson"));',
  '// archive.addFile("logs/2026-q2.ndjson", fs.createReadStream("/var/log/app/q2.ndjson"));',
  '// archive.addFile("manifest.json", JSON.stringify(meta));   // mix Buffer + Readable freely',
  'typeof b.archive.zip; // "function"',
  '</code></pre>',

  '<h3>b.archive.zip().toStream(writable, opts) <a class="anchor" href="#archive-zip-tostream">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  audit:  b.audit,                       // optional — emits archive.zip.streamed.completed / .aborted',
  '}</code></pre>',
  '<p>Pipes the assembled archive into the operator-supplied <code>Writable</code> (HTTP <code>res</code>, <code>fs.createWriteStream</code>, anything Writable-shaped). When <code>writable</code> is omitted, <code>toStream()</code> returns a <code>Readable</code> the operator can pipe themselves. Atomic finalize: the central directory is written only after every entry succeeds; if any source <code>Readable</code> emits <code>error</code>, the destination is destroyed with <code>archive/aborted</code> and no central directory ever lands — consumers see a broken pipe instead of a half-archive that pretends to be complete. Backpressure is honored on every chunk write. Use this for multi-GB exports where <code>toBuffer()</code> would OOM.</p>',
  '<pre><code class="language-javascript">// Stream a multi-GB export directly to the HTTP response:',
  '// res.setHeader("Content-Type", "application/zip");',
  '// res.setHeader("Content-Disposition", \'attachment; filename="export.zip"\');',
  '// var archive = b.archive.zip();',
  '// archive.addFile("logs.ndjson", fs.createReadStream("/var/log/big.ndjson"));',
  '// await archive.toStream(res, { audit: b.audit });',
  '',
  '// Or get a Readable and pipe it yourself:',
  '// var rs = await b.archive.zip().toStream();',
  '// rs.pipe(somewhere);',
  'typeof b.archive.zip().toStream; // "function"</code></pre>',

  '<h2 id="pagination">Pagination</h2>',

  '<h3>b.pagination.cursor(query, opts) <a class="anchor" href="#pagination-cursor">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  secret:        string,                      // required — HMAC-SHA3-512 cursor signing key',
  '  orderBy:       string | [string|{column,direction}],  // required — sort key(s)',
  '  direction:     "asc" | "desc",              // default: "asc"',
  '  limit:         number,                      // default: 20',
  '  cursor:        string,                      // optional — opaque cursor from prior page',
  '}</code></pre>',
  '<p>Cursor-based pagination with HMAC-signed cursors so the client can\'t forge or replay a position from a different table or sort. Takes a db Query (the chainable <code>b.db.from(table)</code> shape) and returns <code>{ items, nextCursor, hasMore }</code>. The cursor is <code>state JSON + HMAC-SHA3-512 tag</code>, base64-url encoded. Tampering, replay across tables, or forging a higher-priv-row cursor all fail at HMAC verification. <code>orderBy</code> identifiers are validated against <code>^[A-Za-z_][A-Za-z0-9_]*$</code> at the call site — closes the SQL-injection shape that would otherwise let a user-supplied query parameter sneak into the ORDER BY clause.</p>',
  '<pre><code class="language-javascript">// Live use: var page = await b.pagination.cursor(',
  '//   b.db.from("users").where({ status: "active" }),',
  '//   { secret: env("CURSOR_SECRET"), orderBy: "createdAt", limit: 20 }',
  '// );',
  '// → { items: [...], nextCursor: "...", hasMore: true }',
  'b.pagination.cursor;',
  '',
  '// Standalone helpers (signature: state-then-secret):',
  'var enc = b.pagination.encodeCursor({ pos: 42 }, "wiki-validator-cursor-secret-32-chars-pad");',
  'b.pagination.decodeCursor(enc, "wiki-validator-cursor-secret-32-chars-pad");',
  '// → { v: 1, pos: 42 }</code></pre>',

  '<h2 id="forms">Forms</h2>',

  '<h3>b.forms.render(spec, opts?) <a class="anchor" href="#forms-render">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  csrfToken:    string,                       // optional — auto-emits a hidden input',
  '  values:       object,                       // optional — pre-populate fields',
  '  errors:       object,                       // optional — per-field error messages',
  '  classes:      object,                       // optional — operator css class overrides',
  '}</code></pre>',
  '<p>HTML form rendering. The spec describes action / method / fields; the renderer auto-includes a CSRF hidden input when <code>opts.csrfToken</code> is supplied. Field types: <code>text</code>, <code>email</code>, <code>password</code>, <code>number</code>, <code>checkbox</code>, <code>radio</code>, <code>textarea</code>, <code>select</code>, <code>hidden</code>, <code>submit</code>. Every value passes through <code>escapeAttribute</code> so user-supplied attribute payloads can\'t hijack the form.</p>',
  '<pre><code class="language-javascript">var spec = {',
  '  action: "/users",',
  '  method: "POST",',
  '  fields: [',
  '    { name: "email",      type: "email",    required: true },',
  '    { name: "name",       type: "text",     required: true, minLength: 2, maxLength: 80 },',
  '    { name: "role",       type: "select",   options: ["viewer", "editor"], required: true },',
  '    { name: "newsletter", type: "checkbox" },',
  '    { name: "_submit",    type: "submit",   label: "Save" },',
  '  ],',
  '};',
  'var html = b.forms.render(spec, { csrfToken: "csrf-stub" });',
  'html.indexOf("<form") !== -1;   // true</code></pre>',

  '<h3>b.forms.validate(spec, body) <a class="anchor" href="#forms-validate">#</a></h3>',
  '<p>Validates the POST body against the same spec. Returns <code>{ valid, values, errors? }</code>: <code>valid: true</code> + populated <code>values</code> on success; <code>valid: false</code> + per-field <code>errors</code> on failure (alongside whatever <code>values</code> were extractable).</p>',
  '<pre><code class="language-javascript">var spec = {',
  '  action: "/x", method: "POST",',
  '  fields: [',
  '    { name: "email", type: "email", required: true },',
  '    { name: "name",  type: "text",  required: true, minLength: 2 },',
  '  ],',
  '};',
  'var rv = b.forms.validate(spec, { email: "alice@example.com", name: "Alice" });',
  '// → { valid: true, values: { email: "alice@example.com", name: "Alice" } }',
  'rv.valid;</code></pre>',

  '<h3>b.forms.generateCsrfToken() / b.forms.verifyCsrfToken(submitted, expected) <a class="anchor" href="#forms-csrf">#</a></h3>',
  '<p>Most operators don\'t call these directly — <a href="/middleware#csrf">b.middleware.csrfProtect</a> handles the issuance, cookie storage, and POST-time verification. Reach for the primitive when wiring a non-cookie token flow (session-stored token, custom header).</p>',
  '<pre><code class="language-javascript">var token = b.forms.generateCsrfToken();',
  '// → 64 hex chars (32 random bytes via b.crypto.generateToken)',
  '',
  'var ok = b.forms.verifyCsrfToken(token, token);',
  '// → true (timing-safe via b.crypto.timingSafeEqual)</code></pre>',

  '<h2 id="arg-parser">Arg Parser</h2>',

  '<h3>b.argParser.create(opts) <a class="anchor" href="#arg-parser-create">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  programName:  string,            // shown in --help output',
  '  description:  string,            // optional one-line description',
  '  flags:        Array<FlagSpec>,   // top-level flags applied to every command',
  '  commands:     Array<CommandSpec>,// declarative subcommands',
  '}',
  '',
  '// FlagSpec',
  '{',
  '  name:         string,            // long form (--name); ASCII identifier',
  '  alias:        string,            // single-letter shortcut (-n); optional',
  '  type:         "string" | "number" | "boolean" | "list",  // default "string"',
  '  default:      any,               // value when the flag is absent from argv',
  '  required:     boolean,           // throws if absent and no default',
  '  description:  string,            // shown in --help',
  '}',
  '',
  '// CommandSpec',
  '{',
  '  name:         string,            // identifier (no spaces)',
  '  description:  string,            // shown in --help',
  '  flags:        Array<FlagSpec>,   // command-scoped flags; shadow same-named top-level',
  '  handler:      function (parsed, positionals) { ... },  // operator-supplied',
  '}</code></pre>',
  '<p>Reusable command-line argument parser for tools that sit on top of the framework. The same engine that powers <code>blamejs</code> on the command line is exposed as a primitive so operators can build their own CLIs against the same spec — typed flag coercion, declarative <code>--help</code> rendering, and prototype-pollution-safe argv handling without rolling their own loop. Returns <code>{ parse(argv, opts?), help(commandName?) }</code>. <code>parse(argv)</code> returns <code>{ command, flags, positionals, helpRequested, handler? }</code>; the <code>flags</code> object has a null prototype so spreading it into a plain object is safe. Bad input — unknown flag, unknown command, missing required, type-coercion failure, prototype-polluting flag name (<code>__proto__</code> / <code>constructor</code> / <code>prototype</code>) — throws an <code>ArgParserError</code>. <code>--</code> ends flag parsing (every following token is positional). <code>--help</code> / <code>-h</code> at any position returns a <code>helpRequested: true</code> result with the rendered <code>helpText</code>; pass <code>{ exit: true }</code> to write the help string and call <code>process.exit(0)</code> instead (the form bin shims use).</p>',
  '<pre><code class="language-javascript">var ap = b.argParser.create({',
  '  programName: "mycli",',
  '  description: "operator tooling on top of blamejs",',
  '  flags: [',
  '    { name: "verbose", alias: "v", type: "boolean", description: "Verbose output" },',
  '  ],',
  '  commands: [',
  '    {',
  '      name: "deploy",',
  '      description: "Deploy a build artifact",',
  '      flags: [',
  '        { name: "env",  type: "string", required: true, description: "Target environment" },',
  '        { name: "tag",  type: "list",                   description: "Repeatable label" },',
  '        { name: "size", type: "number", default: 10 },',
  '      ],',
  '      handler: function (parsed, positionals) {',
  '        // parsed.flags = { env, tag: [...], size, verbose }',
  '        // positionals are non-flag tokens (and everything after `--`)',
  '      },',
  '    },',
  '  ],',
  '});',
  '',
  'var r = ap.parse(["deploy", "--env=prod", "--tag", "v1", "--tag", "v2", "-v"]);',
  '// → { command: "deploy", flags: { env: "prod", tag: ["v1","v2"], size: 10, verbose: true }, positionals: [] }',
  '',
  'console.log(ap.help());           // top-level usage',
  'console.log(ap.help("deploy"));   // per-command usage',
  '',
  '// `--help` / `-h` at any position returns helpRequested: true.',
  '// Pass { exit: true } when invoked from a bin/ shim to print + exit.',
  'ap.parse(process.argv.slice(2), { exit: true });</code></pre>',
].join("\n"),
};
