"use strict";

module.exports = {
  slug:  "format-helpers",
  title: "Format Helpers",
  body: [
  '<h1>Format Helpers</h1>',
  '<p>Small, focused primitives for the data-shape concerns most apps eventually need: CSV parse / serialize, UUID generation, slug derivation, time-zone-aware datetime, ZIP archive creation, cursor pagination, and HTML form rendering with CSRF + validation.</p>',

  '<h2 id="csv">CSV <a class="anchor" href="#csv">#</a></h2>',
  '<p><code>b.csv</code> is RFC 4180 parse + stringify with Excel formula-injection prevention default ON.</p>',
  '<pre><code class="language-javascript">var rows = b.csv.parse("name,age\\nalice,30\\nbob,25");',
  '// → [ { name: "alice", age: "30" }, { name: "bob", age: "25" } ]',
  '',
  'var noHeader = b.csv.parse("1,2,3\\n4,5,6", { header: false });',
  '// → [ ["1","2","3"], ["4","5","6"] ]',
  '',
  '// Stringify — formula-prone cells get a "\'" prefix so Excel/Sheets',
  '// don\'t execute them on open',
  'b.csv.stringify([{ a: "=SUM(A1:A10)" }]);',
  '// → "a\\r\\n\'=SUM(A1:A10)\\r\\n"',
  '',
  '// Disable for true RFC 4180 strict output',
  'b.csv.stringify([{ a: "=A1" }], { preventFormulaInjection: false });</code></pre>',
  '<p>Defaults: <code>maxBytes</code>=16 MiB, <code>maxRows</code>=1M, <code>maxFieldBytes</code>=1 MiB, <code>delimiter</code>=<code>,</code>, <code>quote</code>=<code>"</code>, <code>eol</code>=<code>\\r\\n</code>. Operators with TSV / European semicolon-CSV pass <code>{ delimiter: "\\t" }</code> or <code>{ delimiter: ";" }</code>. Bad inputs (multi-char delimiter, delimiter equal to quote, non-string-non-buffer input) throw at the call site instead of producing silently malformed output.</p>',

  '<h2 id="uuid">UUID <a class="anchor" href="#uuid">#</a></h2>',
  '<p>RFC 4122 v4 (random) + RFC 9562 v7 (time-sortable). v7 encodes a 48-bit Unix-millisecond timestamp in the first 48 bits, then 74 random bits — IDs generated within the same millisecond sort by their random suffix; across milliseconds they sort by time. B-tree index locality is dramatically better than v4 for INSERT-heavy tables.</p>',
  '<pre><code class="language-javascript">b.uuid.v4();',
  '// → "f47ac10b-58cc-4372-a567-0e02b2c3d479"',
  '',
  'b.uuid.v7();',
  '// → "01941bf3-9c4a-7d8e-9c11-3a4b5c6d7e8f"',
  '//     ^^^^^^^^^^^^^^^^^                  → unix ms (sortable)',
  '//                       7                 → version',
  '//                        ^^^^^^^^^^^^^^^^ → 74 random bits',
  '',
  'b.uuid.parse("f47ac10b-58cc-4372-a567-0e02b2c3d479");',
  '// → { version: 4, bytes: Buffer<...> }',
  '',
  'b.uuid.isValid("not-a-uuid");   // → false</code></pre>',

  '<h2 id="slug">Slug <a class="anchor" href="#slug">#</a></h2>',
  '<p>URL-safe identifier derivation. Strips diacritics, lowercases, collapses whitespace + punctuation to <code>-</code>, truncates at a word boundary so a slug never ends mid-word.</p>',
  '<pre><code class="language-javascript">b.slug("Café résumé!");                  // → "cafe-resume"',
  'b.slug("Это пример", { preserveUnicode: true });  // → "это-пример"',
  '',
  '// Unique-per-existing-set (for collision handling on insert):',
  'await b.slug.unique("Welcome", async function (candidate) {',
  '  return existingSlugs.has(candidate);',
  '});',
  '// → "welcome", or "welcome-2", or "welcome-3", …',
  '',
  'b.slug.RESERVED;   // → ["api", "admin", "static", ...] — operator-extensible</code></pre>',
  '<p>Truncation respects word boundaries by default — a slug capped at 50 chars in the middle of <code>responsibilities</code> gets backed up to the previous space. Reserved-word collision (<code>"api"</code>, <code>"admin"</code>) gets a <code>-1</code> suffix automatically.</p>',

  '<h2 id="time">Time <a class="anchor" href="#time">#</a></h2>',
  '<p><code>b.time</code> is timezone-aware datetime arithmetic on top of <code>Intl.DateTimeFormat</code>. No vendored tz data — the runtime\'s ICU shape is current enough.</p>',
  '<pre><code class="language-javascript">var anchor = new Date(Date.UTC(2026, 3, 30, 14, 32, 0));   // Apr 30 2026 14:32 UTC',
  '',
  'b.time.toParts(anchor, { timezone: "America/New_York" });',
  '// → { year: 2026, month: 4, day: 30, hour: 10, minute: 32, weekday: 4, weekdayName: "Thu", ... }',
  '',
  'b.time.format(anchor, { timezone: "America/New_York", dateStyle: "long" });',
  '// → "April 30, 2026"',
  '',
  '// DST-safe — preserves the wall-clock hour across the transition',
  'b.time.addDays(anchor, 7, { timezone: "America/New_York" });',
  '',
  '// addMonths clamps overflow: Jan 31 + 1 month → Feb 28 / 29',
  'b.time.addMonths(new Date("2026-01-31"), 1);',
  '',
  'b.time.startOfDay(anchor, { timezone: "America/New_York" });',
  'b.time.endOfDay(anchor, { timezone: "America/New_York" });',
  'b.time.diffDays(d1, d2, { timezone: "UTC" });',
  'b.time.parseISO("2026-04-30T14:32:00-04:00");',
  'b.time.tzOffsetMs(anchor, "America/New_York");   // → -14400000 (UTC-4 EDT)</code></pre>',

  '<h2 id="archive">Archive <a class="anchor" href="#archive">#</a></h2>',
  '<p>ZIP creation for "download my data" / log archives / plain-zip exports. <code>b.backup</code> produces sealed encrypted bundles; <code>b.archive</code> produces operator-readable ZIP files.</p>',
  '<pre><code class="language-javascript">var archive = b.archive.zip();',
  'archive.addFile("readme.txt",     "Hello\\n");',
  'archive.addFile("data/users.csv", csvBytes);                       // deflate by default',
  'archive.addFile("avatars/me.png", pngBuf, { method: "store" });    // already-compressed',
  '',
  'var zipBytes = archive.toBuffer();',
  'archive.writeTo("/tmp/export.zip");           // sync to disk',
  'var sha256 = archive.digest();                 // for integrity logs',
  '',
  'archive.entryCount;   // → 3</code></pre>',
  '<p>Format support: stored + deflate (auto-fallback to STORE when deflate doesn\'t shrink), UTF-8 file names (EFS bit), per-file mtime. Path-traversal defense: backslashes normalized to forward slashes; leading slashes stripped; <code>..</code> segments rejected at <code>addFile()</code> time. ZIP64, ZIP-native password encryption, streaming write, and reading are intentionally out-of-scope — operators with those needs reach for a different toolset.</p>',

  '<h2 id="pagination">Pagination <a class="anchor" href="#pagination">#</a></h2>',
  '<p>Cursor-based pagination with HMAC-signed cursors so the client can\'t forge or replay a position from a different table or sort.</p>',
  '<pre><code class="language-javascript">var pager = b.pagination.create({',
  '  secret:        env("CURSOR_SECRET"),',
  '  defaultLimit:  20,',
  '  maxLimit:      100,',
  '});',
  '',
  'router.get("/users", async function (req, res) {',
  '  var page = pager.parse(req.query, {',
  '    table:   "users",',
  '    orderBy: "createdAt",      // identifier-safe (regex-validated)',
  '  });',
  '',
  '  var rows = await users.find({',
  '    after: page.cursor,',
  '    limit: page.limit + 1,     // +1 to detect "has more"',
  '  });',
  '',
  '  res.json(pager.serialize(rows, page));',
  '  // → { items: [...], nextCursor: "...", hasMore: true }',
  '});</code></pre>',
  '<p>The cursor is <code>state JSON + HMAC-SHA3-512 tag</code>, base64-url encoded. Tampering, replay across tables, or forging a higher-priv-row cursor all fail at HMAC verification. The <code>orderBy</code> identifier is validated against <code>^[A-Za-z_][A-Za-z0-9_]*$</code> at the call site — closes the SQL-injection shape that would otherwise let a user-supplied query parameter sneak into the ORDER BY clause.</p>',

  '<h2 id="forms">Forms <a class="anchor" href="#forms">#</a></h2>',
  '<p><code>b.forms</code> is HTML form rendering + server-side validation + CSRF token primitives. The renderer and validator share a spec — change it once, both sides update.</p>',
  '<pre><code class="language-javascript">var spec = {',
  '  action: "/users",',
  '  method: "POST",',
  '  fields: [',
  '    { name: "email",    type: "email",    required: true },',
  '    { name: "name",     type: "text",     required: true, minLength: 2, maxLength: 80 },',
  '    { name: "role",     type: "select",   options: ["viewer", "editor"], required: true },',
  '    { name: "newsletter", type: "checkbox" },',
  '    { name: "_submit",  type: "submit",   label: "Save" },',
  '  ],',
  '};',
  '',
  '// Render server-side — auto-includes the CSRF hidden input',
  'res.send(b.forms.render(spec, { csrfToken: req.csrfToken }));',
  '',
  '// Validate the POST body against the SAME spec',
  'var v = b.forms.validate(spec, req.body);',
  '// → { valid: true,  values: { email, name, role, newsletter } }      OR',
  '// → { valid: false, errors: { email: "required", ... }, values: {...} }</code></pre>',
  '<p>Field types: <code>text</code>, <code>email</code>, <code>password</code>, <code>number</code>, <code>checkbox</code>, <code>radio</code>, <code>textarea</code>, <code>select</code>, <code>hidden</code>, <code>submit</code>. Every value passes through <code>escapeAttribute</code> in the renderer so user-supplied attribute payloads can\'t hijack the form.</p>',

  '<h3 id="csrf-tokens">CSRF tokens <a class="anchor" href="#csrf-tokens">#</a></h3>',
  '<pre><code class="language-javascript">var token = b.forms.generateCsrfToken();',
  '// → 64 hex chars (32 random bytes via b.crypto.generateToken)',
  '',
  'var ok = b.forms.verifyCsrfToken(submitted, expected);',
  '// → true / false (timing-safe via b.crypto.timingSafeEqual)</code></pre>',
  '<p>Most operators don\'t call these directly — <a href="/middleware#csrf">b.middleware.csrfProtect</a> handles the issuance, cookie storage, and POST-time verification. Reach for the primitive when wiring a non-cookie token flow (session-stored token, custom header).</p>',
].join("\n"),
};
