"use strict";

module.exports = {
  slug:  "guard-binary",
  title: "Guard Binary and Containers",
  body: [
  "<h1>Guard Binary and Containers</h1>",
  "<p>Binary and container guards defend files where extension, declared media type, and basic magic bytes are not enough. This page contains the full documentation for the archive, image, and PDF guards.</p>",
  "<ul>",
  "  <li><a href=\"#guard-archive\">Archive content safety</a></li>",
  "  <li><a href=\"#guard-image\">Image safety</a></li>",
  "  <li><a href=\"#guard-pdf\">PDF safety</a></li>",
  "</ul>",
  "<h2 id=\"guard-archive\">Archive content safety <a class=\"anchor\" href=\"#guard-archive\">#</a></h2>",
  "<p><code>b.guardArchive</code> validates archive metadata BEFORE extraction. Threat catalog grounded in multiple 2025-2026 CVEs (CVE-2025-3445 mholt/archiver Zip Slip, CVE-2025-32779 EDDI, CVE-2025-62156 Argo Workflows, CVE-2025-66945 Zdir, CVE-2025-45582 GNU Tar, CVE-2025-11001/11002 7-Zip, CVE-2025-4138/4517 Python tarfile, CVE-2026-26960 node-tar hardlink-via-symlink-chain). Auto-registers into <code>b.guardAll</code>.</p>",
  "<p><strong>Scope.</strong> This primitive validates archive METADATA (entry list + sizes + flags + types). It does NOT include a pure-JS unzip / untar implementation — the framework's no-deps rule argues against shipping a parser for every archive format. Operators use their archive library to enumerate entries, then validate the list before extracting.</p>",
  "<h2 id=\"guard-archive-validate-entries\">b.guardArchive.validateEntries(entries, opts) <a class=\"anchor\" href=\"#guard-archive-validate-entries\">#</a></h2>",
  "<pre><code class=\"language-javascript\">{",
  "  profile:                    \"strict\" | \"balanced\" | \"permissive\",",
  "  compliancePosture:          \"hipaa\" | \"pci-dss\" | \"gdpr\" | \"soc2\",",
  "  traversalPolicy:            \"reject\" | \"allow\",",
  "  absolutePathPolicy:         \"reject\" | \"allow\",",
  "  symlinkPolicy:              \"reject\" | \"audit\" | \"allow\",",
  "  hardlinkPolicy:             \"reject\" | \"audit\" | \"allow\",",
  "  encryptionPolicy:           \"reject\" | \"audit\" | \"allow\",",
  "  nestedArchivePolicy:        \"reject\" | \"audit\" | \"allow\",",
  "  duplicateNamePolicy:        \"reject\" | \"audit\" | \"allow\",",
  "  caseInsensitiveCollisionPolicy: \"reject\" | \"audit\" | \"allow\",",
  "  sparseEntryPolicy:          \"reject\" | \"audit\" | \"allow\",",
  "  filenameProfile:            \"strict\" | \"balanced\" | \"permissive\",",
  "  maxEntries:                 number,",
  "  maxTotalBytes:              number,",
  "  maxEntryBytes:              number,",
  "  maxCompressionRatio:        number,    // per-entry uncompressed/compressed cap",
  "  maxAggregateRatio:          number,    // archive-wide ratio cap",
  "  maxNestedDepth:             number,    // recursion depth for nested archives",
  "}</code></pre>",
  "<p>Entries are operator-supplied descriptors of shape <code>{ name, size, compressedSize, isSymlink, isHardlink, linkTarget, isDirectory, isEncrypted, attrs }</code>. Returns <code>{ ok, issues }</code>. Issue kinds: <code>zip-slip</code>, <code>absolute-path</code>, <code>symlink-reject</code> / <code>symlink-escape</code>, <code>hardlink-reject</code> / <code>hardlink-escape</code>, <code>compression-ratio-bomb</code>, <code>aggregate-ratio-bomb</code>, <code>total-size-cap</code>, <code>entry-size-cap</code>, <code>entry-count-cap</code>, <code>nested-archive</code>, <code>duplicate-entry-name</code>, <code>case-insensitive-collision</code>, <code>encryption-claim-mismatch</code>, <code>sparse-entry</code>, <code>bad-input</code>, <code>bad-entry</code>, <code>bad-entry-name</code>. Per-entry filename validation routes through <code>b.guardFilename</code>; its issues are forwarded with archive-context location prefix.</p>",
  "<pre><code class=\"language-javascript\">// Operator parses the archive's central directory (or tar header)",
  "// using their archive library. We pass the resulting entry list:",
  "var entries = [",
  "  { name: \"README.md\",    size: 1000, compressedSize: 500 },",
  "  { name: \"../etc/passwd\", size: 100, compressedSize: 50 },     // zip slip",
  "  { name: \"bomb.txt\",      size: 10000000000, compressedSize: 1000 }, // ratio bomb",
  "];",
  "var rv = b.guardArchive.validateEntries(entries, { profile: \"strict\" });",
  "// rv.ok === false; rv.issues includes zip-slip + compression-ratio-bomb",
  "</code></pre>",
  "<h2 id=\"guard-archive-inspect-magic\">b.guardArchive.inspectMagic(buffer) <a class=\"anchor\" href=\"#guard-archive-inspect-magic\">#</a></h2>",
  "<p>Reads the first bytes of a buffer and returns the detected archive format. Supports zip / gzip / bzip2 / xz / 7z / rar4 / rar5 / lzma / zstd / tar (via \"ustar\" magic at byte 257). Returns <code>{ format, magic }</code> or <code>null</code> if not recognized. Operators compare against the declared content-type / extension to detect format-claim mismatches.</p>",
  "<pre><code class=\"language-javascript\">var buf = Buffer.from([0x50, 0x4B, 0x03, 0x04, 0x00, 0x00]);",
  "var fmt = b.guardArchive.inspectMagic(buf);",
  "// → { format: \"zip\", magic: [0x50, 0x4B, 0x03, 0x04] }",
  "</code></pre>",
  "<h2 id=\"guard-archive-check-extraction-path\">b.guardArchive.checkExtractionPath(entryName, extractionRoot) <a class=\"anchor\" href=\"#guard-archive-check-extraction-path\">#</a></h2>",
  "<p>Single-entry helper — returns <code>{ ok, reason }</code> for one (entryName, extractionRoot) pair. Anchored for callers that already enumerate entries and want a per-call boolean check. Refuses traversal sequences (<code>..</code>), absolute paths, empty names, and null bytes. Operators should additionally call <code>path.resolve(extractionRoot, entryName)</code> and verify the result starts with <code>path.resolve(extractionRoot)</code> at runtime.</p>",
  "<pre><code class=\"language-javascript\">var ok = b.guardArchive.checkExtractionPath(\"safe/file.txt\", \"/extract\");",
  "// → { ok: true }",
  "",
  "var bad = b.guardArchive.checkExtractionPath(\"../escape.exe\", \"/extract\");",
  "// → { ok: false, reason: \"entry name contains .. component (zip slip)\" }",
  "</code></pre>",
  "<h2 id=\"guard-archive-gate\">b.guardArchive.gate(opts) <a class=\"anchor\" href=\"#guard-archive-gate\">#</a></h2>",
  "<pre><code class=\"language-javascript\">{",
  "  profile:               \"strict\" | \"balanced\" | \"permissive\",",
  "  compliancePosture:     \"hipaa\" | \"pci-dss\" | \"gdpr\" | \"soc2\",",
  "  mode:                  \"enforce\" | \"warn-only\" | \"shadow\" | \"audit-only\" | \"log-only\" | \"canary\",",
  "  audit:                 b.audit,",
  "  observability:         b.observability,",
  "  forensicEvidenceStore: { put }, forensicSnippetBytes: number,",
  "  cache:                 b.cache, cacheTtlMs: number,",
  "  maxRuntimeMs:          number,",
  "  beforeCheck/afterCheck/onIssue/onSanitize/onRefuse/onAudit: hooks,",
  "}</code></pre>",
  "<p>Returns a <code>b.gateContract</code>-shaped gate. Context expects <code>ctx.entries</code> (operator-parsed entry list) — distinct from content-byte gates which use <code>ctx.bytes</code>. When <code>ctx.bytes</code> is provided WITHOUT entries, the gate runs <code>inspectMagic</code> for format detection and refuses with a <code>no-entry-list</code> issue (the gate cannot enumerate entries without a parser).</p>",
  "<pre><code class=\"language-javascript\">var archiveGate = b.guardArchive.gate({ profile: \"strict\", audit: b.audit });",
  "// b.fileUpload.create({ contentSafety: archiveGate }) wires this in.",
  "</code></pre>",
  "<h2 id=\"guard-archive-threat-catalog\">Threat catalog <a class=\"anchor\" href=\"#guard-archive-threat-catalog\">#</a></h2>",
  "<ul>",
  "<li><strong>Zip slip / path traversal</strong> — entry names with <code>..</code> sequences (CVE-2025-3445 / 32779 / 62156 / 66945 / 45582 / 11002 class).</li>",
  "<li><strong>Absolute paths</strong> — entries with leading <code>/</code> / <code>\\</code> / drive-letter prefix.</li>",
  "<li><strong>Symlink escape</strong> — symlink entries whose <code>linkTarget</code> resolves outside the extraction root.</li>",
  "<li><strong>Hardlink escape</strong> — hardlink entries pointing outside extraction root (CVE-2026-26960 node-tar class).</li>",
  "<li><strong>Symlink-chained traversal</strong> — two-step bypass: pre-extract a symlink, then write through it.</li>",
  "<li><strong>Decompression-ratio bombs</strong> — per-entry compressedSize/size ratio cap (default 100:1 strict, 1000:1 permissive).</li>",
  "<li><strong>Aggregate ratio bomb</strong> — archive-wide sum-of-uncompressed / sum-of-compressed cap.</li>",
  "<li><strong>Total-size cap</strong> — sum of all entry sizes (anti-DoS).</li>",
  "<li><strong>File-count cap</strong> — number of entries.</li>",
  "<li><strong>Per-entry-size cap</strong> — single-entry uncompressed size limit.</li>",
  "<li><strong>Nested-archive depth</strong> — refuses entries that are themselves archives unless <code>maxNestedDepth &gt; 0</code>; archive-extension catalog drives detection.</li>",
  "<li><strong>Per-entry-name validation</strong> — composes <code>b.guardFilename</code> for each entry name (path traversal / null-byte / Windows reserved names / NTFS ADS / RTLO bidi / overlong UTF-8 / shell-exec extensions / double-extension).</li>",
  "<li><strong>Duplicate entry names</strong> — second entry with same name silently overwrites the first; refused.</li>",
  "<li><strong>Case-insensitive collision</strong> — <code>README.txt</code> + <code>readme.txt</code> in same archive collides on Windows / macOS HFS+ / APFS-non-case-sensitive.</li>",
  "<li><strong>Encryption-claim mismatch</strong> — archive contains both encrypted and unencrypted entries.</li>",
  "<li><strong>Sparse entries</strong> — tar-shape sparse entries claim large size with zero data.</li>",
  "<li><strong>Format-claim mismatch</strong> — declared content-type / extension doesn't match magic-byte detected format.</li>",
  "</ul>",
  "<h2 id=\"guard-archive-profiles\">Profiles <a class=\"anchor\" href=\"#guard-archive-profiles\">#</a></h2>",
  "<p><strong>strict</strong> — every threat refused; no symlinks; no hardlinks; no nested archives; 100 entry max; 100 MiB total; 100:1 ratio cap; case-insensitive collision refused.</p>",
  "<p><strong>balanced</strong> — symlinks within extraction-root allowed; no hardlinks; nested-depth 2; 10000 entries; 1 GiB total; 100:1 per-entry / 1000:1 aggregate; case-collision audited.</p>",
  "<p><strong>permissive</strong> — symlinks + hardlinks within root allowed; nested-depth 4; 100000 entries; 10 GiB total; 1000:1 ratio.</p>",
  "<h2 id=\"guard-archive-compliance\">Compliance postures <a class=\"anchor\" href=\"#guard-archive-compliance\">#</a></h2>",
  "<p><strong>hipaa</strong> / <strong>pci-dss</strong> / <strong>soc2</strong> — strict overlay + forensic snapshots.</p>",
  "<p><strong>gdpr</strong> — balanced overlay + 128-byte forensic snapshots.</p>",
  "<h2 id=\"guard-image\">Image safety <a class=\"anchor\" href=\"#guard-image\">#</a></h2>",
  "<p><code>b.guardImage</code> validates image-format inputs without vendoring a full decoder. The framework's stance: operators bring their own decoder (sharp, jimp, libvips wrappers, etc.); guardImage closes the magic-byte vs declared-Content-Type mismatch class, the polyglot file class, and operator-supplied metadata bounds (oversized dimensions, frame count). KIND=\"metadata\" — consumes <code>ctx.metadata</code> shape: <code>{ bytes?, declaredMime?, width?, height?, frames? }</code>. Threat catalog: magic-byte vs declared-MIME mismatch; polyglot file (multiple format magic bytes); unknown / no magic-byte match; SVG bytes routed through guardImage instead of guardSvg (bypass class); oversized dimensions; excessive frame count; oversized bytes.</p>",
  "<h2 id=\"guard-image-validate\">b.guardImage.validate(metadata, opts) <a class=\"anchor\" href=\"#guard-image-validate\">#</a></h2>",
  "<pre><code class=\"language-javascript\">{",
  "  profile:                \"strict\" | \"balanced\" | \"permissive\",",
  "  compliancePosture:      \"hipaa\" | \"pci-dss\" | \"gdpr\" | \"soc2\",",
  "  mismatchPolicy:         \"reject\" | \"allow\",       // refused at every profile",
  "  polyglotPolicy:         \"reject\" | \"allow\",       // refused at every profile",
  "  unknownMagicPolicy:     \"reject\" | \"audit\" | \"allow\",",
  "  svgRoutingPolicy:       \"reject\" | \"allow\",       // refused at every profile",
  "  dimensionsPolicy:       \"reject\" | \"audit\" | \"allow\",",
  "  framesPolicy:           \"reject\" | \"audit\" | \"allow\",",
  "  maxWidth:               number,                    // strict 8192 / balanced 16384 / permissive 65536",
  "  maxHeight:              number,                    // same scaling",
  "  maxFrames:              number,                    // strict 60 / balanced 200 / permissive 1000",
  "  maxBytes:               number,                    // strict 32 MiB / balanced 64 / permissive 256",
  "}</code></pre>",
  "<p>Validates an image metadata object. Returns <code>{ ok, issues }</code>. Issue kinds: <code>bad-input</code>, <code>image-cap</code>, <code>polyglot</code>, <code>svg-routing</code>, <code>mime-mismatch</code>, <code>unknown-magic</code>, <code>width-cap</code>, <code>height-cap</code>, <code>frames-cap</code>.</p>",
  "<pre><code class=\"language-javascript\">var pngBytes = Buffer.from([0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A]);",
  "b.guardImage.validate(",
  "  { bytes: pngBytes, declaredMime: \"image/png\", width: 100, height: 100 },",
  "  { profile: \"strict\" }",
  ");",
  "// → { ok: true, issues: [] }",
  "",
  "// Drive-by mismatch — declared image/png but bytes are JPEG.",
  "var jpgBytes = Buffer.from([0xFF, 0xD8, 0xFF]);",
  "b.guardImage.validate(",
  "  { bytes: jpgBytes, declaredMime: \"image/png\" },",
  "  { profile: \"strict\" }",
  ");",
  "// → ok=false; mime-mismatch",
  "</code></pre>",
  "<h2 id=\"guard-image-inspect-magic\">b.guardImage.inspectMagic(bytes) <a class=\"anchor\" href=\"#guard-image-inspect-magic\">#</a></h2>",
  "<p>Operator helper: returns the array of detected MIME types (canonical lowercase) without running the full validate / gate flow. Useful when the operator wants to drive their own dispatch and only needs the magic-byte detection result.</p>",
  "<pre><code class=\"language-javascript\">b.guardImage.inspectMagic(Buffer.from([0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A]));",
  "// → [\"image/png\"]",
  "b.guardImage.inspectMagic(Buffer.from([0xFF, 0xD8, 0xFF]));",
  "// → [\"image/jpeg\"]</code></pre>",
  "<h2 id=\"guard-image-sanitize\">b.guardImage.sanitize(metadata, opts) <a class=\"anchor\" href=\"#guard-image-sanitize\">#</a></h2>",
  "<pre><code class=\"language-javascript\">{",
  "  profile:           \"strict\" | \"balanced\" | \"permissive\",",
  "  compliancePosture: \"hipaa\" | \"pci-dss\" | \"gdpr\" | \"soc2\",",
  "}</code></pre>",
  "<p>Image bytes can't be repaired without re-encoding (which the framework refuses to do — operators bring their own decoder). <code>sanitize</code> either passes through valid metadata or throws.</p>",
  "<pre><code class=\"language-javascript\">var meta = {",
  "  bytes: Buffer.from([0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A]),",
  "  declaredMime: \"image/png\", width: 100, height: 100,",
  "};",
  "var safe = b.guardImage.sanitize(meta, { profile: \"strict\" });",
  "// safe === meta when validation passes; throws otherwise.</code></pre>",
  "<h2 id=\"guard-image-gate\">b.guardImage.gate(opts) <a class=\"anchor\" href=\"#guard-image-gate\">#</a></h2>",
  "<pre><code class=\"language-javascript\">{",
  "  profile:               \"strict\" | \"balanced\" | \"permissive\",",
  "  compliancePosture:     \"hipaa\" | \"pci-dss\" | \"gdpr\" | \"soc2\",",
  "  mode:                  \"enforce\" | \"warn-only\" | \"shadow\" | \"audit-only\" | \"log-only\" | \"canary\",",
  "  audit:                 b.audit,",
  "  observability:         b.observability,",
  "  forensicEvidenceStore: { put }, forensicSnippetBytes: number,",
  "  cache:                 b.cache, cacheTtlMs: number,",
  "  maxRuntimeMs:          number,",
  "}</code></pre>",
  "<p>Returns a <code>b.gateContract</code>-shaped gate. Reads <code>ctx.metadata</code>; empty / missing metadata resolves to <code>{ ok: true, action: \"serve\" }</code>.</p>",
  "<pre><code class=\"language-javascript\">var imgGate = b.guardImage.gate({ profile: \"strict\", audit: b.audit });",
  "",
  "app.post(\"/api/upload-image\", b.middleware.bodyParser({ raw: true }),",
  "  async function (req, res) {",
  "    var bytes = req.body;",
  "    var meta = await operatorDecoder.metadata(bytes); // sharp / jimp / etc.",
  "    var rv = await imgGate.check({",
  "      metadata: { bytes: bytes, declaredMime: req.headers[\"content-type\"],",
  "                  width: meta.width, height: meta.height, frames: meta.pages },",
  "    });",
  "    if (!rv.ok) return res.status(400).json({ refused: rv.issues });",
  "    // ... persist and re-encode ...",
  "  });</code></pre>",
  "<h2 id=\"guard-image-threat-catalog\">Threat catalog <a class=\"anchor\" href=\"#guard-image-threat-catalog\">#</a></h2>",
  "<ul>",
  "<li><strong>Magic-byte vs declared-MIME mismatch</strong> — <code>Content-Type: image/png</code> with JPEG bytes is the canonical drive-by content-type confusion class; downstream decoders dispatch on declared type and may pick the wrong format.</li>",
  "<li><strong>Polyglot file</strong> — buffer matches multiple format magic bytes (PHP-in-JPEG / JS-in-PNG class).</li>",
  "<li><strong>Unknown magic-byte</strong> — buffer doesn't match any known image format. Strict refuses; balanced + permissive audit.</li>",
  "<li><strong>SVG routing via image</strong> — operator-routes SVG bytes through guardImage instead of guardSvg (bypass class). Strict + balanced + permissive all refuse — operators MUST pass SVG through <code>b.guardSvg</code> directly.</li>",
  "<li><strong>Oversized dimensions</strong> — operator passes width / height; refused against maxWidth / maxHeight.</li>",
  "<li><strong>Excessive frame count</strong> — animated GIF / WebP / APNG / AVIF image sequences refused above maxFrames.</li>",
  "<li><strong>Oversized bytes</strong> — total buffer cap.</li>",
  "</ul>",
  "<h2 id=\"guard-image-profiles\">Profiles <a class=\"anchor\" href=\"#guard-image-profiles\">#</a></h2>",
  "<p><strong>strict</strong> — refuse mismatch + polyglot + unknown-magic + svg-routing + dimension overflow + frames overflow; max 8192 × 8192, 60 frames, 32 MiB.</p>",
  "<p><strong>balanced</strong> — mismatch + polyglot + svg-routing still refused; audit unknown-magic + dimensions + frames; max 16384 × 16384, 200 frames, 64 MiB.</p>",
  "<p><strong>permissive</strong> — universal-refuse class still refused (mismatch / polyglot / svg-routing); audit dimensions + frames; max 65536 × 65536, 1000 frames, 256 MiB.</p>",
  "<h2 id=\"guard-image-compliance\">Compliance postures <a class=\"anchor\" href=\"#guard-image-compliance\">#</a></h2>",
  "<p><strong>hipaa</strong> / <strong>pci-dss</strong> / <strong>soc2</strong> — strict overlay + forensic snapshots (256 / 256 / 512 bytes).</p>",
  "<p><strong>gdpr</strong> — balanced overlay + 128-byte forensic snippets.</p>",
  "<h2 id=\"guard-pdf\">PDF safety <a class=\"anchor\" href=\"#guard-pdf\">#</a></h2>",
  "<p><code>b.guardPdf</code> validates PDF inputs without vendoring a full parser. Operators bring their own PDF library (pdf-lib, pdfjs-dist, vendored mupdf) and feed structural metadata to the guard for policy enforcement. KIND=\"metadata\" — consumes <code>ctx.metadata</code> shape: <code>{ bytes?, hasJavaScript?, hasOpenAction?, hasLaunchAction?, hasEmbeddedFiles?, isEncrypted?, pageCount?, embeddedFileCount?, polyglotDetected? }</code>. Threat catalog: magic-byte missing, JavaScript action (RCE class — Adobe / Foxit / nitro CVEs), Launch action (universal refuse), OpenAction trigger, embedded-file presence, encrypted PDF, polyglot, oversized bytes / page / embedded-file counts.</p>",
  "<h2 id=\"guard-pdf-validate\">b.guardPdf.validate(metadata, opts) <a class=\"anchor\" href=\"#guard-pdf-validate\">#</a></h2>",
  "<pre><code class=\"language-javascript\">{",
  "  profile:                   \"strict\" | \"balanced\" | \"permissive\",",
  "  compliancePosture:         \"hipaa\" | \"pci-dss\" | \"gdpr\" | \"soc2\",",
  "  magicPolicy:               \"reject\" | \"audit\" | \"allow\",",
  "  javascriptPolicy:          \"reject\" | \"allow\",  // refused at every profile (RCE class)",
  "  openActionPolicy:          \"reject\" | \"audit\" | \"allow\",",
  "  launchActionPolicy:        \"reject\" | \"allow\",  // refused at every profile (RCE class)",
  "  embeddedFilePolicy:        \"reject\" | \"audit\" | \"allow\",",
  "  encryptedPolicy:           \"reject\" | \"audit\" | \"allow\",",
  "  polyglotPolicy:            \"reject\" | \"allow\",  // refused at every profile",
  "  pageCountPolicy:           \"reject\" | \"audit\" | \"allow\",",
  "  embeddedFileCountPolicy:   \"reject\" | \"audit\" | \"allow\",",
  "  maxPageCount:              number,                // strict 500 / balanced 5000 / permissive 50000",
  "  maxEmbeddedFileCount:      number,                // strict 0 / balanced 10 / permissive 100",
  "  maxBytes:                  number,                // strict 64 MiB / balanced 128 / permissive 512",
  "}</code></pre>",
  "<p>Validates a PDF metadata object. Returns <code>{ ok, issues }</code>. Issue kinds: <code>bad-input</code>, <code>pdf-cap</code>, <code>magic-missing</code>, <code>polyglot</code>, <code>javascript-action</code>, <code>launch-action</code>, <code>open-action</code>, <code>embedded-file</code>, <code>embedded-file-count</code>, <code>encrypted</code>, <code>page-count</code>.</p>",
  "<pre><code class=\"language-javascript\">var pdfBytes = Buffer.from([0x25, 0x50, 0x44, 0x46, 0x2D, 0x31, 0x2E, 0x37]);",
  "",
  "b.guardPdf.validate(",
  "  { bytes: pdfBytes, hasJavaScript: false, pageCount: 1 },",
  "  { profile: \"strict\" }",
  ");",
  "// → { ok: true, issues: [] }",
  "",
  "// JavaScript action — universal refuse (RCE class).",
  "b.guardPdf.validate(",
  "  { bytes: pdfBytes, hasJavaScript: true },",
  "  { profile: \"strict\" }",
  ");",
  "// → ok=false; javascript-action",
  "",
  "// Launch action — universal refuse.",
  "b.guardPdf.validate(",
  "  { bytes: pdfBytes, hasLaunchAction: true },",
  "  { profile: \"strict\" }",
  ");",
  "// → ok=false; launch-action",
  "</code></pre>",
  "<h2 id=\"guard-pdf-inspect-magic\">b.guardPdf.inspectMagic(bytes) <a class=\"anchor\" href=\"#guard-pdf-inspect-magic\">#</a></h2>",
  "<p>Operator helper: returns <code>true</code> when the buffer starts with the <code>%PDF-</code> magic header. Useful for operator-side dispatch before invoking a vendored parser.</p>",
  "<pre><code class=\"language-javascript\">var pdfBytes = Buffer.from([0x25, 0x50, 0x44, 0x46, 0x2D, 0x31, 0x2E, 0x37]);",
  "b.guardPdf.inspectMagic(pdfBytes); // → true",
  "b.guardPdf.inspectMagic(Buffer.from([0xFF, 0xD8, 0xFF])); // → false</code></pre>",
  "<h2 id=\"guard-pdf-sanitize\">b.guardPdf.sanitize(metadata, opts) <a class=\"anchor\" href=\"#guard-pdf-sanitize\">#</a></h2>",
  "<pre><code class=\"language-javascript\">{",
  "  profile:           \"strict\" | \"balanced\" | \"permissive\",",
  "  compliancePosture: \"hipaa\" | \"pci-dss\" | \"gdpr\" | \"soc2\",",
  "}</code></pre>",
  "<p>PDF metadata can't be repaired without re-encoding the document (which the framework refuses to do — operators bring their own parser). <code>sanitize</code> either passes through valid metadata or throws.</p>",
  "<pre><code class=\"language-javascript\">var meta = {",
  "  bytes: Buffer.from([0x25, 0x50, 0x44, 0x46, 0x2D, 0x31, 0x2E, 0x37]),",
  "  hasJavaScript: false, pageCount: 1,",
  "};",
  "var safe = b.guardPdf.sanitize(meta, { profile: \"strict\" });</code></pre>",
  "<h2 id=\"guard-pdf-gate\">b.guardPdf.gate(opts) <a class=\"anchor\" href=\"#guard-pdf-gate\">#</a></h2>",
  "<pre><code class=\"language-javascript\">{",
  "  profile:               \"strict\" | \"balanced\" | \"permissive\",",
  "  compliancePosture:     \"hipaa\" | \"pci-dss\" | \"gdpr\" | \"soc2\",",
  "  mode:                  \"enforce\" | \"warn-only\" | \"shadow\" | \"audit-only\" | \"log-only\" | \"canary\",",
  "  audit:                 b.audit,",
  "  observability:         b.observability,",
  "  forensicEvidenceStore: { put }, forensicSnippetBytes: number,",
  "  cache:                 b.cache, cacheTtlMs: number,",
  "  maxRuntimeMs:          number,",
  "}</code></pre>",
  "<p>Returns a <code>b.gateContract</code>-shaped gate. Reads <code>ctx.metadata</code>; empty / missing metadata resolves to <code>{ ok: true, action: \"serve\" }</code>.</p>",
  "<pre><code class=\"language-javascript\">var pdfGate = b.guardPdf.gate({ profile: \"strict\", audit: b.audit });",
  "",
  "app.post(\"/api/upload-pdf\", b.middleware.bodyParser({ raw: true }),",
  "  async function (req, res) {",
  "    var bytes = req.body;",
  "    var meta = await operatorPdfParser.metadata(bytes); // pdf-lib / mupdf / etc.",
  "    var rv = await pdfGate.check({",
  "      metadata: { bytes: bytes,",
  "                  hasJavaScript:    meta.hasJavaScript,",
  "                  hasOpenAction:    meta.hasOpenAction,",
  "                  hasLaunchAction:  meta.hasLaunchAction,",
  "                  hasEmbeddedFiles: meta.embeddedFileCount > 0,",
  "                  embeddedFileCount: meta.embeddedFileCount,",
  "                  isEncrypted:      meta.isEncrypted,",
  "                  pageCount:        meta.pageCount },",
  "    });",
  "    if (!rv.ok) return res.status(400).json({ refused: rv.issues });",
  "  });</code></pre>",
  "<h2 id=\"guard-pdf-threat-catalog\">Threat catalog <a class=\"anchor\" href=\"#guard-pdf-threat-catalog\">#</a></h2>",
  "<ul>",
  "<li><strong>Magic-byte missing</strong> — buffer doesn't start with <code>%PDF-</code>.</li>",
  "<li><strong>JavaScript action (`/JS` / `/JavaScript`)</strong> — RCE class in vulnerable readers (Adobe / Foxit / nitro CVEs). Universally refused.</li>",
  "<li><strong>LaunchAction (`/Launch`)</strong> — invokes external program. Universally refused.</li>",
  "<li><strong>OpenAction</strong> — runs on document open; drive-by class when paired with JavaScript / Launch.</li>",
  "<li><strong>Embedded files</strong> — `/EmbeddedFile` may carry executable payloads.</li>",
  "<li><strong>Encrypted PDF</strong> — many AV / sandbox tools can't scan encrypted documents; operators may want to refuse.</li>",
  "<li><strong>Polyglot</strong> — buffer carries non-PDF magic-byte signatures (operator-supplied via <code>polyglotDetected: true</code>).</li>",
  "<li><strong>Oversized bytes / pages / embedded-file count</strong> — DoS and storage caps.</li>",
  "</ul>",
  "<h2 id=\"guard-pdf-profiles\">Profiles <a class=\"anchor\" href=\"#guard-pdf-profiles\">#</a></h2>",
  "<p><strong>strict</strong> — refuse JavaScript + Launch + OpenAction + embedded files (max 0) + polyglot + magic-missing; max 500 pages, 64 MiB.</p>",
  "<p><strong>balanced</strong> — RCE class still refused (JavaScript / Launch / polyglot); audit OpenAction / embedded files / encrypted; max 5000 pages, 10 embedded files, 128 MiB.</p>",
  "<p><strong>permissive</strong> — RCE class still refused (JavaScript / Launch / polyglot); audit OpenAction / embedded files; allow encrypted; max 50000 pages, 100 embedded files, 512 MiB.</p>",
  "<h2 id=\"guard-pdf-compliance\">Compliance postures <a class=\"anchor\" href=\"#guard-pdf-compliance\">#</a></h2>",
  "<p><strong>hipaa</strong> / <strong>pci-dss</strong> / <strong>soc2</strong> — strict overlay + forensic snapshots (512 / 512 / 1024 bytes).</p>",
  "<p><strong>gdpr</strong> — balanced overlay + 256-byte forensic snippets.</p>",
  "<h2 id=\"guard-helper-surface\">Shared helper surface <a class=\"anchor\" href=\"#guard-helper-surface\">#</a></h2>",
  "<p>Every guard in this category also exposes the shared helper surface used by operators and by <code>b.guardAll</code>: profile composition, compliance posture lookup, and local rule-pack registration.</p>",
  "<h2 id=\"archive-build-profile\">b.guardArchive.buildProfile(profileOptions) <a class=\"anchor\" href=\"#archive-build-profile\">#</a></h2>",
  "<p><code>b.guardArchive.buildProfile</code> composes one of the guard's named profiles with additional operator extensions, overrides, and removals. Use it when a deployment wants to inspect the exact policy object that will feed validation or gate creation before wiring it into a host primitive.</p>",
  "<pre><code class=\"language-javascript\">var profile = b.guardArchive.buildProfile({",
  "  baseProfile: \"strict\",",
  "  overrides: { mode: \"enforce\" },",
  "});",
  "typeof profile; // \"object\"</code></pre>",
  "<h2 id=\"archive-compliance-posture\">b.guardArchive.compliancePosture(name) <a class=\"anchor\" href=\"#archive-compliance-posture\">#</a></h2>",
  "<p><code>b.guardArchive.compliancePosture</code> returns the guard-specific policy overlay for a named posture such as <code>soc2</code>, <code>gdpr</code>, <code>hipaa</code>, or <code>pci-dss</code>. Unknown posture names fail immediately so compliance wiring cannot silently fall back to a weaker profile.</p>",
  "<pre><code class=\"language-javascript\">var posture = b.guardArchive.compliancePosture(\"soc2\");",
  "typeof posture; // \"object\"</code></pre>",
  "<h2 id=\"archive-load-rule-pack\">b.guardArchive.loadRulePack(pack) <a class=\"anchor\" href=\"#archive-load-rule-pack\">#</a></h2>",
  "<p><code>b.guardArchive.loadRulePack</code> registers an operator rule pack for this guard and returns the accepted pack. Rule packs give deployments a stable place to add local detection rules without forking the framework primitive.</p>",
  "<pre><code class=\"language-javascript\">var pack = b.guardArchive.loadRulePack({",
  "  id: \"docs-archive-rule-pack\",",
  "  rules: [],",
  "});",
  "pack.id; // \"docs-archive-rule-pack\"</code></pre>",
  "<h2 id=\"image-build-profile\">b.guardImage.buildProfile(profileOptions) <a class=\"anchor\" href=\"#image-build-profile\">#</a></h2>",
  "<p><code>b.guardImage.buildProfile</code> composes one of the guard's named profiles with additional operator extensions, overrides, and removals. Use it when a deployment wants to inspect the exact policy object that will feed validation or gate creation before wiring it into a host primitive.</p>",
  "<pre><code class=\"language-javascript\">var profile = b.guardImage.buildProfile({",
  "  baseProfile: \"strict\",",
  "  overrides: { mode: \"enforce\" },",
  "});",
  "typeof profile; // \"object\"</code></pre>",
  "<h2 id=\"image-compliance-posture\">b.guardImage.compliancePosture(name) <a class=\"anchor\" href=\"#image-compliance-posture\">#</a></h2>",
  "<p><code>b.guardImage.compliancePosture</code> returns the guard-specific policy overlay for a named posture such as <code>soc2</code>, <code>gdpr</code>, <code>hipaa</code>, or <code>pci-dss</code>. Unknown posture names fail immediately so compliance wiring cannot silently fall back to a weaker profile.</p>",
  "<pre><code class=\"language-javascript\">var posture = b.guardImage.compliancePosture(\"soc2\");",
  "typeof posture; // \"object\"</code></pre>",
  "<h2 id=\"image-load-rule-pack\">b.guardImage.loadRulePack(pack) <a class=\"anchor\" href=\"#image-load-rule-pack\">#</a></h2>",
  "<p><code>b.guardImage.loadRulePack</code> registers an operator rule pack for this guard and returns the accepted pack. Rule packs give deployments a stable place to add local detection rules without forking the framework primitive.</p>",
  "<pre><code class=\"language-javascript\">var pack = b.guardImage.loadRulePack({",
  "  id: \"docs-image-rule-pack\",",
  "  rules: [],",
  "});",
  "pack.id; // \"docs-image-rule-pack\"</code></pre>",
  "<h2 id=\"pdf-build-profile\">b.guardPdf.buildProfile(profileOptions) <a class=\"anchor\" href=\"#pdf-build-profile\">#</a></h2>",
  "<p><code>b.guardPdf.buildProfile</code> composes one of the guard's named profiles with additional operator extensions, overrides, and removals. Use it when a deployment wants to inspect the exact policy object that will feed validation or gate creation before wiring it into a host primitive.</p>",
  "<pre><code class=\"language-javascript\">var profile = b.guardPdf.buildProfile({",
  "  baseProfile: \"strict\",",
  "  overrides: { mode: \"enforce\" },",
  "});",
  "typeof profile; // \"object\"</code></pre>",
  "<h2 id=\"pdf-compliance-posture\">b.guardPdf.compliancePosture(name) <a class=\"anchor\" href=\"#pdf-compliance-posture\">#</a></h2>",
  "<p><code>b.guardPdf.compliancePosture</code> returns the guard-specific policy overlay for a named posture such as <code>soc2</code>, <code>gdpr</code>, <code>hipaa</code>, or <code>pci-dss</code>. Unknown posture names fail immediately so compliance wiring cannot silently fall back to a weaker profile.</p>",
  "<pre><code class=\"language-javascript\">var posture = b.guardPdf.compliancePosture(\"soc2\");",
  "typeof posture; // \"object\"</code></pre>",
  "<h2 id=\"pdf-load-rule-pack\">b.guardPdf.loadRulePack(pack) <a class=\"anchor\" href=\"#pdf-load-rule-pack\">#</a></h2>",
  "<p><code>b.guardPdf.loadRulePack</code> registers an operator rule pack for this guard and returns the accepted pack. Rule packs give deployments a stable place to add local detection rules without forking the framework primitive.</p>",
  "<pre><code class=\"language-javascript\">var pack = b.guardPdf.loadRulePack({",
  "  id: \"docs-pdf-rule-pack\",",
  "  rules: [],",
  "});",
  "pack.id; // \"docs-pdf-rule-pack\"</code></pre>",
  ].join("\n"),
};
