"use strict";

module.exports = {
  slug:  "mail",
  title: "Mail",
  body: [
  '<h1>Mail</h1>',
  '<p><code>b.mail</code> is the outbound mail primitive: provider-pluggable transports, multipart MIME, attachments + inline images, DKIM signing, calendar invites. <code>b.mailBounce</code> handles inbound bounce / complaint / delivery callbacks from Postmark, SES, and Resend.</p>',

  '<h2 id="basics">Basics <a class="anchor" href="#basics">#</a></h2>',
  '<h3>b.mail.create(opts)</h3>',
  '<pre><code class="language-javascript">{',
  '  transport:  Transport | (message) =&gt; Promise,',
  '                                            // default: console transport (logs the message)',
  '  defaults:   {                             // default: {} — merged into every send',
  '    from:        string,                    //   RFC 5322 mailbox',
  '    replyTo:     string,',
  '    headers:     object,',
  '    // ...any other message field',
  '  },',
  '  audit:      boolean,                      // default: true — emit mail.send.* on chain',
  '}</code></pre>',
  '<h3>mail.send(message)</h3>',
  '<pre><code class="language-javascript">{',
  '  to:           string | string[],         // required: true',
  '  cc:           string | string[],         // default: null',
  '  bcc:          string | string[],         // default: null',
  '  from:         string,                    // default: defaults.from',
  '  replyTo:      string,                    // default: defaults.replyTo',
  '  subject:      string,                    // required: true',
  '  text:         string,                    // text or html required',
  '  html:         string,                    // text or html required',
  '  attachments:  Array&lt;Attachment&gt;,         // default: []',
  '  calendar:     { method, icalText },      // default: null',
  '  headers:      object,                    // default: {} — extra headers',
  '}</code></pre>',
  '<pre><code class="language-javascript">var mail = b.mail.create({',
  '  transport: b.mail.transports.smtp({',
  '    host:     "smtp.example.com",',
  '    port:     587,',
  '    secure:   "starttls",',
  '    username: env("SMTP_USER"),',
  '    password: env("SMTP_PASS"),',
  '  }),',
  '  defaults: { from: "noreply@wiki.example.com" },',
  '});',
  '',
  'await mail.send({',
  '  to:      "alice@example.com",',
  '  subject: "Welcome",',
  '  text:    "Welcome to the wiki",',
  '  html:    welcomeTemplate(user),',
  '});</code></pre>',
  '<p>Transports: SMTP (with STARTTLS), Postmark, SES, Resend, generic HTTP, and a <code>log</code>-only transport for development. All share the same <code>send</code> shape. Templates and i18n integrate via <code>b.template</code> + <code>b.i18n</code>.</p>',

  '<h2 id="attachments">Attachments &amp; inline images <a class="anchor" href="#attachments">#</a></h2>',
  '<p>Pass an <code>attachments</code> array on any <code>send()</code> call. Each entry is <code>{ filename, content, contentType?, contentDisposition?, cid? }</code> where <code>content</code> is a Buffer or string. The builder emits <code>multipart/mixed</code> wrapping the body, base64-encodes each attachment with line wrapping per RFC 2045, and sets <code>Content-Disposition: attachment</code> by default. Setting <code>cid</code> auto-switches that part to <code>Content-Disposition: inline</code> with a matching <code>Content-ID</code> header so HTML bodies reference it via <code>&lt;img src="cid:logo-1"&gt;</code>. Mixing <code>text</code> + <code>html</code> + attachments wraps the body parts in an inner <code>multipart/alternative</code> so plain-text-only clients still render. The Resend transport forwards attachments natively as base64 with <code>content_id</code>.</p>',
  '<pre><code class="language-javascript">await mail.send({',
  '  to:      "alice@example.com",',
  '  subject: "Your weekly report",',
  '  text:    "See attached.",',
  '  html:    \'&lt;p&gt;See &lt;img src="cid:logo-1"&gt; for context.&lt;/p&gt;\',',
  '  attachments: [',
  '    { filename: "report.pdf", content: pdfBuffer, contentType: "application/pdf" },',
  '    { filename: "logo.png",   content: pngBuffer, contentType: "image/png", cid: "logo-1" },',
  '  ],',
  '});</code></pre>',

  '<h2 id="dkim">DKIM signing <a class="anchor" href="#dkim">#</a></h2>',
  '<p><code>b.mail.dkim</code> generates a <code>DKIM-Signature</code> header on outbound mail per RFC 6376 (default <code>rsa-sha256</code>) or RFC 8463 (opt-in <code>ed25519-sha256</code>). The signer is wired into the SMTP transport via <code>dkimSigner</code>; vendor-API transports (Resend, generic HTTP) rely on the provider\'s own sender-domain authentication. The <code>a=</code> tag carries the algorithm identifier so future post-quantum DKIM (when an SLH-DSA / ML-DSA variant is standardized) slots into the same envelope without breaking the public surface.</p>',
  '<h3>b.mail.dkim.create(opts)</h3>',
  '<pre><code class="language-javascript">{',
  '  domain:            string,               // required: true',
  '  selector:          string,               // required: true — published at <selector>._domainkey.<domain>',
  '  privateKey:        string | KeyObject,   // required: true — PEM or KeyObject',
  '  algorithm:         "rsa-sha256" | "ed25519-sha256",',
  '                                           // default: "rsa-sha256"',
  '  headersToSign:     string[],             // default: ["from","to","subject","date","message-id"]',
  '  canonicalization:  "relaxed/relaxed" | "simple/simple" | ...,',
  '                                           // default: "relaxed/relaxed"',
  '  bodyLength:        number,               // default: null — sign first N bytes (l= tag)',
  '}</code></pre>',
  '<pre><code class="language-javascript">var signer = b.mail.dkim.create({',
  '  domain:     "example.com",',
  '  selector:   "s1",',
  '  privateKey: env("DKIM_PRIVATE_KEY"),  // PEM string or KeyObject',
  '  algorithm:  "rsa-sha256",             // or "ed25519-sha256"',
  '});',
  '',
  'var mail = b.mail.create({',
  '  transport: b.mail.transports.smtp({',
  '    host:       "smtp.example.com",',
  '    port:       587,',
  '    dkimSigner: signer,',
  '  }),',
  '});</code></pre>',
  '<p>Selectors are published in DNS as TXT records at <code>&lt;selector&gt;._domainkey.&lt;domain&gt;</code>. Headers signed by default: <code>from</code>, <code>to</code>, <code>subject</code>, <code>date</code>, <code>message-id</code>. Override via <code>headersToSign</code>. Default canonicalization is <code>relaxed/relaxed</code> (most compatible).</p>',

  '<h2 id="calendar">Calendar invites <a class="anchor" href="#calendar">#</a></h2>',
  '<p>Pass <code>calendar: { method, icalText }</code> on any <code>send()</code>. The builder adds a <code>text/calendar; method=...</code> body part (alongside <code>text</code> / <code>html</code> in <code>multipart/alternative</code>) so Outlook, Gmail, and Apple Mail render it as an invite rather than a generic <code>.ics</code> attachment. Operators construct the iCalendar body per RFC 5545; the framework only validates that it begins with <code>BEGIN:VCALENDAR</code>.</p>',
  '<pre><code class="language-javascript">await mail.send({',
  '  to:      "alice@example.com",',
  '  subject: "Sync at 2pm",',
  '  text:    "RSVP plain-text fallback.",',
  '  calendar: {',
  '    method:   "REQUEST",  // or "CANCEL", "REPLY", ...',
  '    icalText: "BEGIN:VCALENDAR\\r\\nVERSION:2.0\\r\\nMETHOD:REQUEST\\r\\n..."',
  '  },',
  '});</code></pre>',

  '<h2 id="bounce">Bounce intake <a class="anchor" href="#bounce">#</a></h2>',
  '<p><code>b.mailBounce.handler(opts)</code> returns Express-style middleware that accepts inbound webhook callbacks from Postmark, SES, Resend, or a custom parser, normalizes their wildly different event shapes into one internal <code>BounceEvent</code>, runs an operator-supplied <code>verify</code> check, emits <code>system.mail.bounce</code> on the audit chain, and calls the operator <code>onBounce</code> callback. Suppression-tracking is the operator\'s data store — the framework normalizes the event but does NOT itself maintain a suppression table.</p>',
  '<h3>b.mailBounce.handler(opts)</h3>',
  '<pre><code class="language-javascript">{',
  '  vendor:    "postmark" | "ses" | "resend" | "custom",',
  '                                           // required: true',
  '  verify:    (req, body) =&gt; boolean,       // default: null — return false to reject 401',
  '  onBounce:  (event) =&gt; Promise,           // default: null — operator-side suppression update',
  '  parser:    (body) =&gt; BounceEvent,        // required when vendor === "custom"',
  '  audit:     boolean,                      // default: true',
  '}',
  '',
  '// BounceEvent (normalized output of every parser):',
  '{',
  '  vendor:     string,',
  '  type:       "bounce" | "complaint" | "delivery",',
  '  subType:    "hard" | "soft" | "abuse" | string | null,',
  '  recipient:  string,',
  '  messageId:  string | null,',
  '  reason:     string | null,',
  '  timestamp:  string,                      // ISO 8601',
  '  raw:        any,                         // original payload',
  '}</code></pre>',
  '<pre><code class="language-javascript">router.post("/webhooks/postmark/bounce",',
  '  b.middleware.bodyParser.raw(),',
  '  b.mailBounce.handler({',
  '    vendor:   "postmark",',
  '    verify:   function (req) {',
  '      // Postmark recommends Basic Auth on the webhook URL.',
  '      return req.headers.authorization === expectedBasic;',
  '    },',
  '    onBounce: async function (event) {',
  '      await db.users.markBounced(event.recipient, event.subType);',
  '    },',
  '  }),',
  ');</code></pre>',
].join("\n"),
};
