"use strict";

module.exports = {
  slug:  "mail",
  title: "Mail",
  body: [
  '<h1>Mail</h1>',
  '<p><code>b.mail</code> is the outbound mail primitive: provider-pluggable transports, multipart MIME, attachments + inline images, DKIM signing, calendar invites. <code>b.mailBounce</code> handles inbound bounce / complaint / delivery callbacks from Postmark, SES, and Resend.</p>',

  '<h2 id="basics">Basics <a class="anchor" href="#basics">#</a></h2>',
  '<h3>b.mail.create(opts)</h3>',
  '<pre><code class="language-javascript">{',
  '  transport:  Transport | (message) =&gt; Promise,',
  '                                            // default: console transport (logs the message)',
  '                                            //   b.mail.transports.console({ redactBcc: true }) prints',
  '                                            //   "Bcc: <N recipients — redacted>" instead of addresses',
  '                                            //   when dev logs are piped into a shared sink.',
  '  defaults:   {                             // default: {} — merged into every send',
  '    from:        string,                    //   RFC 5322 mailbox',
  '    replyTo:     string,',
  '    headers:     object,',
  '    // ...any other message field',
  '  },',
  '  audit:      boolean,                      // default: true — emit mail.send.* on chain',
  '  commercial: boolean,                      // default: false — CAN-SPAM Act §7704(a)(5) posture',
  '  postalAddress: {                          // required when commercial:true',
  '    street:     string,                     //   non-empty, no CR/LF/NUL',
  '    city:       string,',
  '    region:     string,',
  '    postalCode: string,',
  '    country:    string,',
  '  } | string,                               // string form: pre-rendered address block',
  '  footerSeparator: string,                  // default: "\\n\\n----\\n" (text) / "<hr>" (html)',
  '  footerHtml:      string,                  // optional html footer override; must contain country + postalCode',
  '  regulated:  boolean,                      // alias for commercial:true',
  '}</code></pre>',
  '<h3>mail.send(message)</h3>',
  '<pre><code class="language-javascript">{',
  '  to:           string | string[],         // required: true',
  '  cc:           string | string[],         // default: null',
  '  bcc:          string | string[],         // default: null',
  '  from:         string,                    // default: defaults.from',
  '  replyTo:      string,                    // default: defaults.replyTo',
  '  subject:      string,                    // required: true',
  '  text:         string,                    // text or html required',
  '  html:         string,                    // text or html required',
  '  attachments:  Array&lt;Attachment&gt;,         // default: []',
  '  calendar:     { method, icalText },      // default: null',
  '  headers:      object,                    // default: {} — extra headers',
  '}</code></pre>',
  '<pre><code class="language-javascript">var mail = b.mail.create({',
  '  transport: b.mail.transports.smtp({',
  '    host:     "smtp.example.com",',
  '    port:     587,',
  '    secure:   "starttls",',
  '    username: env("SMTP_USER"),',
  '    password: env("SMTP_PASS"),',
  '  }),',
  '  defaults: { from: "noreply@wiki.example.com" },',
  '});',
  '',
  'await mail.send({',
  '  to:      "alice@example.com",',
  '  subject: "Welcome",',
  '  text:    "Welcome to the wiki",',
  '  html:    welcomeTemplate(user),',
  '});</code></pre>',
  '<p>Transports: SMTP (with STARTTLS), Resend, generic HTTP, and <code>console</code> / <code>memory</code> for development. All share the same <code>send</code> shape. Templates and i18n integrate via <code>b.template</code> + <code>b.i18n</code>.</p>',

  '<h2 id="canspam">Commercial-mail posture (CAN-SPAM) <a class="anchor" href="#canspam">#</a></h2>',
  '<p>Operators sending commercial-content mail under US jurisdiction comply with <strong>15 USC §7704(a)</strong> (CAN-SPAM Act) by passing <code>commercial: true</code> + <code>postalAddress: {...}</code> to <code>b.mail.create</code>. The framework enforces the two non-deferrable obligations:</p>',
  '<ul>',
  '<li><strong>§7704(a)(5) — physical postal address.</strong> Refuses <code>create()</code> when <code>postalAddress</code> is missing / blank / shape-incomplete (typo-surfacing throw at config time, not silent shipping with a missing footer). Auto-appends a <code>----\\n&lt;address&gt;\\n----</code> block to the text part and an <code>&lt;hr&gt;&lt;br&gt;-separated</code> address to the html part of every send. Operators with branded layouts pass <code>footerHtml</code> — the framework refuses the override if it does not include the country + postalCode strings.</li>',
  '<li><strong>§7704(a)(3)/(4) — clear opt-out.</strong> Refuses <code>send()</code> with <code>mail/canspam-no-unsubscribe</code> when the message lacks either <code>unsubscribe: { url|mailto, oneClick? }</code> (RFC 8058, framework-wired via <code>b.mail.unsubscribe</code>) OR a pre-set <code>List-Unsubscribe</code> header. Audit emit <code>mail.canspam.refused</code> on every refusal.</li>',
  '</ul>',
  '<pre><code class="language-javascript">var mail = b.mail.create({',
  '  transport: b.mail.transports.memory(),',
  '  defaults:  { from: "shop@example.com" },',
  '  commercial: true,                          // CAN-SPAM §7704(a) posture',
  '  postalAddress: {                           // §7704(a)(5) — required',
  '    street:     "123 Main St",',
  '    city:       "Springfield",',
  '    region:     "IL",',
  '    postalCode: "62701",',
  '    country:    "US",',
  '  },',
  '});',
  '',
  '// Send WITH unsubscribe (RFC 8058 one-click) — passes both gates.',
  'await mail.send({',
  '  to:          "buyer@example.com",',
  '  subject:     "Spring sale",',
  '  text:        "Save 20% this week.",',
  '  html:        "<p>Save 20% this week.</p>",',
  '  unsubscribe: { url: "https://example.com/unsub?u=12345", oneClick: true },',
  '});',
  '// → text body now ends with "...this week.\\n\\n----\\n123 Main St\\n…\\nUS\\n"',
  '// → html body now ends with "...this week.</p><hr>123 Main St<br>...<br>US"',
  '</code></pre>',

  '<h2 id="eai">Internationalized email (RFC 6531) <a class="anchor" href="#eai">#</a></h2>',
  '<p><code>b.mail.send</code> accepts <strong>EAI / SMTPUTF8</strong> addresses out of the box — IDN domains are converted to Punycode (RFC 3492) for the address-shape gate, and the SMTP transport detects the peer\'s <code>SMTPUTF8</code> EHLO extension before deciding whether to emit ` SMTPUTF8` on <code>MAIL FROM</code>. When a message has non-ASCII content but the peer does NOT advertise <code>SMTPUTF8</code>, the transport refuses with <code>mail/smtp-failed: eai-required-not-supported</code> rather than emit a mangled wire (some peers silently corrupt headers downstream).</p>',
  '<h3>b.mail.toAscii(domain) / b.mail.toUnicode(domain)</h3>',
  '<pre><code class="language-javascript">b.mail.toAscii("münchen.example");           // → "xn--mnchen-3ya.example"',
  'b.mail.toUnicode("xn--mnchen-3ya.example");  // → "münchen.example"',
  '',
  '// Send to an IDN address — works against any SMTPUTF8-advertising peer',
  '// (Gmail, Microsoft 365, all RFC-6531-conformant MTAs).',
  'var mail = b.mail.create({',
  '  transport: b.mail.transports.memory(),',
  '  defaults:  { from: "sender@example.com" },',
  '});',
  'await mail.send({',
  '  to:      "müller@münchen.example",',
  '  subject: "Hallo Welt",',
  '  text:    "Sehr geehrte Damen und Herren …",',
  '});</code></pre>',
  '<p>The <code>toAscii</code> / <code>toUnicode</code> wrappers thread through Node\'s built-in <code>url.domainToASCII</code> / <code>domainToUnicode</code> so operators have one obvious place to reach for IDN handling outside <code>send()</code> (DNS lookup, log scrubbing, audit normalization). Local parts may legitimately contain Unicode under RFC 6531 §3.3; the framework still refuses CRLF/NUL bytes anywhere in the address (header injection / SMTP smuggling defense).</p>',

  '<h2 id="attachments">Attachments &amp; inline images <a class="anchor" href="#attachments">#</a></h2>',
  '<p>Pass an <code>attachments</code> array on any <code>send()</code> call. Each entry is <code>{ filename, content, contentType?, contentDisposition?, cid? }</code> where <code>content</code> is a Buffer or string. The builder emits <code>multipart/mixed</code> wrapping the body, base64-encodes each attachment with line wrapping per RFC 2045, and sets <code>Content-Disposition: attachment</code> by default. Setting <code>cid</code> auto-switches that part to <code>Content-Disposition: inline</code> with a matching <code>Content-ID</code> header so HTML bodies reference it via <code>&lt;img src="cid:logo-1"&gt;</code>. Mixing <code>text</code> + <code>html</code> + attachments wraps the body parts in an inner <code>multipart/alternative</code> so plain-text-only clients still render. The Resend transport forwards attachments natively as base64 with <code>content_id</code>.</p>',
  '<pre><code class="language-javascript">await mail.send({',
  '  to:      "alice@example.com",',
  '  subject: "Your weekly report",',
  '  text:    "See attached.",',
  '  html:    \'&lt;p&gt;See &lt;img src="cid:logo-1"&gt; for context.&lt;/p&gt;\',',
  '  attachments: [',
  '    { filename: "report.pdf", content: pdfBuffer, contentType: "application/pdf" },',
  '    { filename: "logo.png",   content: pngBuffer, contentType: "image/png", cid: "logo-1" },',
  '  ],',
  '});</code></pre>',

  '<h2 id="dkim">DKIM signing <a class="anchor" href="#dkim">#</a></h2>',
  '<p><code>b.mail.dkim</code> generates a <code>DKIM-Signature</code> header on outbound mail per RFC 6376 (default <code>rsa-sha256</code>) or RFC 8463 (opt-in <code>ed25519-sha256</code>). The signer is wired into the SMTP transport via <code>dkimSigner</code>; vendor-API transports (Resend, generic HTTP) rely on the provider\'s own sender-domain authentication. The <code>a=</code> tag carries the algorithm identifier so future post-quantum DKIM (when an SLH-DSA / ML-DSA variant is standardized) slots into the same envelope without breaking the public surface.</p>',
  '<h3>b.mail.dkim.create(opts)</h3>',
  '<pre><code class="language-javascript">{',
  '  domain:            string,               // required: true',
  '  selector:          string,               // required: true — published at <selector>._domainkey.<domain>',
  '  privateKey:        string | KeyObject,   // required: true — PEM or KeyObject',
  '  algorithm:         "rsa-sha256" | "ed25519-sha256",',
  '                                           // default: "rsa-sha256"',
  '  headersToSign:     string[],             // default: ["from","to","subject","date","message-id"]',
  '  canonicalization:  "relaxed/relaxed" | "simple/simple" | ...,',
  '                                           // default: "relaxed/relaxed"',
  '  bodyLength:        number,               // default: null — sign first N bytes (l= tag)',
  '  audit:             AuditTap,              // default: null',
  '}</code></pre>',
  '<pre><code class="language-javascript">var signer = b.mail.dkim.create({',
  '  domain:     "example.com",',
  '  selector:   "s1",',
  '  privateKey: env("DKIM_PRIVATE_KEY"),  // PEM string or KeyObject',
  '  algorithm:  "rsa-sha256",             // or "ed25519-sha256"',
  '});',
  '',
  'var mail = b.mail.create({',
  '  transport: b.mail.transports.smtp({',
  '    host:       "smtp.example.com",',
  '    port:       587,',
  '    dkimSigner: signer,',
  '  }),',
  '});</code></pre>',
  '<p>Selectors are published in DNS as TXT records at <code>&lt;selector&gt;._domainkey.&lt;domain&gt;</code>. Headers signed by default: <code>from</code>, <code>to</code>, <code>subject</code>, <code>date</code>, <code>message-id</code>. Override via <code>headersToSign</code>. Default canonicalization is <code>relaxed/relaxed</code> (most compatible).</p>',

  '<h2 id="calendar">Calendar invites <a class="anchor" href="#calendar">#</a></h2>',
  '<p>Pass <code>calendar: { method, icalText }</code> on any <code>send()</code>. The builder adds a <code>text/calendar; method=...</code> body part (alongside <code>text</code> / <code>html</code> in <code>multipart/alternative</code>) so Outlook, Gmail, and Apple Mail render it as an invite rather than a generic <code>.ics</code> attachment. Operators construct the iCalendar body per RFC 5545; the framework only validates that it begins with <code>BEGIN:VCALENDAR</code>.</p>',
  '<pre><code class="language-javascript">await mail.send({',
  '  to:      "alice@example.com",',
  '  subject: "Sync at 2pm",',
  '  text:    "RSVP plain-text fallback.",',
  '  calendar: {',
  '    method:   "REQUEST",  // or "CANCEL", "REPLY", ...',
  '    icalText: "BEGIN:VCALENDAR\\r\\nVERSION:2.0\\r\\nMETHOD:REQUEST\\r\\n..."',
  '  },',
  '});</code></pre>',

  '<h2 id="bounce">Bounce intake <a class="anchor" href="#bounce">#</a></h2>',
  '<p><code>b.mailBounce.handler(opts)</code> returns Express-style middleware that accepts inbound webhook callbacks from Postmark, SES, Resend, or a custom parser, normalizes their wildly different event shapes into one internal <code>BounceEvent</code>, runs an operator-supplied <code>verify</code> check, emits <code>system.mail.bounce</code> on the audit chain, and calls the operator <code>onBounce</code> callback. Suppression-tracking is the operator\'s data store — the framework normalizes the event but does NOT itself maintain a suppression table.</p>',
  '<h3>b.mailBounce.handler(opts)</h3>',
  '<pre><code class="language-javascript">{',
  '  vendor:    "postmark" | "ses" | "resend" | "custom",',
  '                                           // required: true',
  '  verify:    (req, body) =&gt; boolean,       // default: null — return false to reject 401',
  '  onBounce:  (event) =&gt; Promise,           // default: null — operator-side suppression update',
  '  parser:    (body) =&gt; BounceEvent,        // required when vendor === "custom"',
  '  audit:     boolean,                      // default: true',
  '}',
  '',
  '// BounceEvent (normalized output of every parser):',
  '{',
  '  vendor:     string,',
  '  type:       "bounce" | "complaint" | "delivery",',
  '  subType:    "hard" | "soft" | "abuse" | string | null,',
  '  recipient:  string,',
  '  messageId:  string | null,',
  '  reason:     string | null,',
  '  timestamp:  string,                      // ISO 8601',
  '  raw:        any,                         // original payload',
  '}</code></pre>',
  '<pre><code class="language-javascript">router.post("/webhooks/postmark/bounce",',
  '  b.middleware.bodyParser.raw(),',
  '  b.mailBounce.handler({',
  '    vendor:   "postmark",',
  '    verify:   function (req) {',
  '      // Postmark recommends Basic Auth on the webhook URL.',
  '      return req.headers.authorization === expectedBasic;',
  '    },',
  '    onBounce: async function (event) {',
  '      await db.users.markBounced(event.recipient, event.subType);',
  '    },',
  '  }),',
  ');</code></pre>',

  '<h2 id="dkim-verify">b.mail.dkim.verify(rfc822, opts) <a class="anchor" href="#dkim-verify">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  dnsLookup:  async (qname, type) => txtRecords,   // optional; defaults to node:dns/promises.resolveTxt',
  '  audit:      auditInstance,                        // default: false',
  '}</code></pre>',
  '<p>RFC 6376 DKIM-Signature verifier — counterpart to <code>b.mail.dkim.create</code>. Walks every <code>DKIM-Signature</code> header in the message, fetches the signing public key from DNS TXT at <code>&lt;selector&gt;._domainkey.&lt;domain&gt;</code>, canonicalizes the body + headers per the signature\'s <code>c=</code> tag, and verifies the cryptographic signature. Returns one result per signature: <code>{ d, s, alg, result, errors }</code> where <code>result</code> is <code>pass</code> / <code>fail</code> / <code>permerror</code> / <code>temperror</code> / <code>none</code>. Supports rsa-sha256 and ed25519-sha256.</p>',
  '<pre><code class="language-javascript">// A message with no DKIM-Signature header returns a single "none" result.',
  '// In production, pass the real inbound RFC 822 wire; results route per d=/s=.',
  'var noSigMsg = "From: a@example.com\\r\\nTo: b@example.com\\r\\n\\r\\nbody\\r\\n";',
  'var rv = await b.mail.dkim.verify(noSigMsg);',
  '// rv → [{ result: "none", errors: ["no DKIM-Signature headers"] }]',
  '</code></pre>',

  '<h2 id="spf-verify">b.mail.spf.verify(opts) <a class="anchor" href="#spf-verify">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  ip:        string,                                // sender IP (required)',
  '  mailFrom:  string,                                // SMTP MAIL FROM address',
  '  helo:      string,                                // EHLO/HELO host (fallback when no mailFrom)',
  '  dnsLookup: async (qname, type) => txtRecords,    // optional',
  '}</code></pre>',
  '<p>RFC 7208 SPF check with <code>ip4</code> / <code>ip6</code> / <code>include</code> / <code>all</code> mechanisms. Recursive include resolution with the 10-DNS-lookup ceiling per §4.6.4. Returns <code>{ result, domain, explanation, lookupCount }</code> where result is one of <code>pass</code> / <code>fail</code> / <code>softfail</code> / <code>neutral</code> / <code>none</code> / <code>temperror</code> / <code>permerror</code>. The <code>a</code> / <code>mx</code> / <code>exists</code> / <code>ptr</code> / <code>redirect</code> mechanisms surface as <code>permerror</code> with a diagnosis — operators with those wire their own resolver.</p>',
  '<pre><code class="language-javascript">// Mocked DNS that returns no SPF record — produces a "none" verdict.',
  '// In production, omit dnsLookup and node:dns/promises is used.',
  'var dnsLookup = async function () { var e = new Error(); e.code = "ENOTFOUND"; throw e; };',
  'var rv = await b.mail.spf.verify({',
  '  ip:        "192.0.2.5",',
  '  mailFrom:  "alice@example.com",',
  '  dnsLookup: dnsLookup,',
  '});',
  '// rv → { result: "none", domain: "example.com", explanation: "no SPF record at example.com" }',
  '</code></pre>',

  '<h2 id="dmarc-evaluate">b.mail.dmarc.evaluate(opts) <a class="anchor" href="#dmarc-evaluate">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  from:      string,                                // From: header email address (required)',
  '  spf:       { result, domain },                    // from b.mail.spf.verify',
  '  dkim:      [{ result, d }, ...],                  // from b.mail.dkim.verify',
  '  dnsLookup: async (qname, type) => txtRecords,    // optional',
  '}</code></pre>',
  '<p>RFC 7489 DMARC alignment + policy resolution. Fetches the <code>_dmarc.&lt;domain&gt;</code> TXT record, evaluates <code>aspf</code> / <code>adkim</code> (relaxed/strict) alignment between the From-header domain and the SPF/DKIM authenticated domains, returns <code>{ result, policy, alignment, recommendedAction }</code> where <code>recommendedAction</code> is <code>deliver</code> / <code>quarantine</code> / <code>reject</code> per the published policy.</p>',
  '<pre><code class="language-javascript">// Mocked DNS returns no _dmarc record — verdict is "none".',
  'var dnsLookup = async function () { var e = new Error(); e.code = "ENOTFOUND"; throw e; };',
  'var rv = await b.mail.dmarc.evaluate({',
  '  from:      "alice@example.com",',
  '  spf:       { result: "pass", domain: "example.com" },',
  '  dkim:      [],',
  '  dnsLookup: dnsLookup,',
  '});',
  '// rv → { result: "none", recommendedAction: "deliver", policy: null, alignment: { spf: false, dkim: false } }',
  '</code></pre>',

  '<h2 id="arc-verify">b.mail.arc.verify(rfc822, opts) <a class="anchor" href="#arc-verify">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  dnsLookup: async (qname, type) => txtRecords,    // optional',
  '}</code></pre>',
  '<p>RFC 8617 ARC chain verification. Walks every <code>ARC-Seal</code> + <code>ARC-Message-Signature</code> + <code>ARC-Authentication-Results</code> hop, verifies the per-hop signatures (AMS reuses the DKIM verifier; AS verifies the chain-of-custody catenation per §5.1.2), and validates the chain <code>cv=</code> tag per §5.2. Returns <code>{ chainStatus, hopCount, cv, hops }</code> with status <code>pass</code> / <code>fail</code> / <code>none</code>.</p>',
  '<pre><code class="language-javascript">// A message with no ARC headers returns chainStatus "none".',
  'var noArcMsg = "From: a@example.com\\r\\nTo: b@example.com\\r\\n\\r\\nbody\\r\\n";',
  'var rv = await b.mail.arc.verify(noArcMsg);',
  '// rv → { chainStatus: "none", hopCount: 0, hops: [] }',
  '</code></pre>',

  '<h2 id="smtp-mtasts">b.network.smtp.mtaSts.fetch(domain) / matchMx(host, list) <a class="anchor" href="#smtp-mtasts">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  // mtaSts.fetch returns:',
  '  version: "STSv1",',
  '  mode:    "enforce" | "testing" | "none",',
  '  mx:      [string, ...],                          // wildcard-allowed (e.g. *.example.com)',
  '  max_age: number,                                  // seconds',
  '}</code></pre>',
  '<p>RFC 8461 MTA-STS policy fetch + MX matcher. <code>fetch(domain)</code> retrieves <code>https://mta-sts.&lt;domain&gt;/.well-known/mta-sts.txt</code>, parses, and TTL-caches per-process. <code>matchMx(mxHost, mxList)</code> applies the §3.2 wildcard rules (single-label only — <code>*.example.com</code> matches <code>mx.example.com</code> but not <code>a.b.example.com</code>). Operators wire this into their outbound SMTP transport before connecting.</p>',
  '<pre><code class="language-javascript">// Parse a literal policy string + run the wildcard MX matcher.',
  'var policy = b.network.smtp.mtaSts.parsePolicy(',
  '  "version: STSv1\\nmode: enforce\\nmx: mx1.example.com\\nmx: *.mail.example.com\\nmax_age: 86400\\n");',
  '// → { version: "STSv1", mode: "enforce", mx: ["mx1.example.com", "*.mail.example.com"], max_age: 86400 }',
  'var matched = b.network.smtp.mtaSts.matchMx("alpha.mail.example.com", policy.mx);',
  '// matched → true (single-label wildcard match)',
  '</code></pre>',

  '<h2 id="smtp-dane">b.network.smtp.dane.tlsa(domain, port?) <a class="anchor" href="#smtp-dane">#</a></h2>',
  '<p>DNS TYPE 52 lookup at <code>_&lt;port&gt;._tcp.&lt;domain&gt;</code> via <code>node:dns.resolveTlsa</code>. Returns <code>[{ usage, selector, mtype, dataHex }, ...]</code>. Pair with <code>b.network.smtp.dane.recordShape(rec)</code> to get human-readable RFC 6698 labels (PKIX-TA / PKIX-EE / DANE-TA / DANE-EE; Cert / SPKI; Full / SHA-256 / SHA-512). Full TLSA cert-chain verification is a follow-up patch — operators today match the leaf cert SHA-256 themselves against the published TLSA hash.</p>',
  '<pre><code class="language-javascript">// Decode an operator-supplied TLSA record into human-readable labels.',
  'var shape = b.network.smtp.dane.recordShape({',
  '  usage: 3, selector: 1, mtype: 1, dataHex: "abcd1234",',
  '});',
  '// shape → { usage:3, selector:1, mtype:1, dataHex:"abcd1234",',
  '//           usageLabel:"DANE-EE", selectorLabel:"SPKI", mtypeLabel:"SHA-256" }',
  '</code></pre>',

  '<h2 id="smtp-dane-verify">b.network.smtp.dane.verifyChain(certChain, tlsaRecords, opts?) <a class="anchor" href="#smtp-dane-verify">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  allowPkixModes: boolean,                          // default false — refuse PKIX-TA / PKIX-EE without an external PKIX validator',
  '}</code></pre>',
  '<p>RFC 6698 §2 + RFC 7672 cert-chain matcher. Walks the peer cert chain (leaf-first DER buffers — typically <code>sock.getPeerCertificate(true).raw</code>) and confirms at least one TLSA record matches per the record\'s usage / selector / mtype. SMTP outbound (RFC 7672) only honors <code>DANE-TA</code> (2) and <code>DANE-EE</code> (3); <code>PKIX-TA</code> (0) and <code>PKIX-EE</code> (1) require a full PKIX path validator + CA-bundle and are refused unless the operator opts in via <code>allowPkixModes</code>. Selector <code>Cert</code> (0) compares the full DER; selector <code>SPKI</code> (1) compares the SubjectPublicKeyInfo bytes (extracted via the framework ASN.1 walker). Matching types: <code>Full</code>, <code>SHA-256</code>, <code>SHA-512</code>. Returns <code>{ ok, matches: [{ tlsaIndex, certIndex, usage, mtype }], errors }</code>.</p>',
  '<pre><code class="language-javascript">// Pretend leaf cert + intermediate. The operator has already fetched',
  '// the TLSA record via b.network.smtp.dane.tlsa(); here we use mtype=0',
  '// (Full) so the example is hermetic (no DNS, no hashing).',
  'var leafDer = Buffer.from("predictable cert bytes for example", "utf8");',
  'var caDer   = Buffer.from("ca bytes", "utf8");',
  '',
  'var tlsaRecord = {',
  '  usage:    3,                                // DANE-EE',
  '  selector: 0,                                // Cert (full DER)',
  '  mtype:    0,                                // Full (byte-identical)',
  '  dataHex:  leafDer.toString("hex"),',
  '};',
  'var rv = b.network.smtp.dane.verifyChain([leafDer, caDer], [tlsaRecord]);',
  '// rv.ok === true; rv.matches[0].usage === "DANE-EE"; rv.matches[0].mtype === "Full"',
  '</code></pre>',

  '<h2 id="smtp-tlsrpt">b.network.smtp.tlsRpt.recordShape(opts) <a class="anchor" href="#smtp-tlsrpt">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  organization:  string,                            // required',
  '  reportingMta:  string,',
  '  contact:       string,',
  '  datestart:     string,                            // ISO; defaults to now()',
  '  dateend:       string,',
  '  policies:      [{ type, domain, mxHosts, successCount, failureCount, failures }, ...],',
  '}</code></pre>',
  '<p>RFC 8460 TLS-RPT JSON report-shape generator. Returns the canonical <code>organization-name</code> / <code>date-range</code> / <code>policies[].summary.total-{successful,failure}-session-count</code> / <code>failure-details</code> shape that operators submit to their report transport (HTTPS POST or a designated email address). The submission step itself is operator-side — wire transport credentials per the recipient\'s policy.</p>',
  '<pre><code class="language-javascript">// Build the RFC 8460 JSON report shape from operator inputs.',
  'var report = b.network.smtp.tlsRpt.recordShape({',
  '  organization: "example.com",',
  '  contact:      "tls-reports@example.com",',
  '  policies: [{ type: "sts", domain: "example.com", successCount: 100, failureCount: 2 }],',
  '});',
  '// report["organization-name"] === "example.com"; report.policies has the summary block.',
  '</code></pre>',

  '<h2 id="smtp-tlsrpt-fetch">b.network.smtp.tlsRpt.fetchPolicy(domain, opts?) <a class="anchor" href="#smtp-tlsrpt-fetch">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  dnsLookup: async function (qname, type) { /* operator-supplied resolver */ },',
  '}</code></pre>',
  '<p>Reads the RFC 8460 §3 <code>_smtp._tls.&lt;domain&gt;</code> TXT record and returns <code>{ version, rua: [string,...] }</code> where <code>rua</code> is the comma-separated list of report URIs (<code>https://</code> and <code>mailto:</code>) the recipient publishes for receiving TLS-RPT reports. Returns <code>null</code> when no record is published. <code>dnsLookup</code> is operator-supplied so the call composes with <code>b.network.dns</code> (DoH / DoT) without taking a hard dep; falls back to <code>node:dns/promises.resolveTxt</code> when omitted.</p>',
  '<pre><code class="language-javascript">// Mock dnsLookup so the example is hermetic in CI.',
  'var dnsLookup = async function () {',
  '  return [["v=TLSRPTv1; rua=mailto:tlsrpt@example.com,https://reports.example.com/v1"]];',
  '};',
  'var policy = await b.network.smtp.tlsRpt.fetchPolicy("example.com", { dnsLookup: dnsLookup });',
  '// policy → { version: "TLSRPTv1", rua: ["mailto:tlsrpt@example.com", "https://reports.example.com/v1"] }',
  '</code></pre>',

  '<h2 id="transports">b.mail.transports.smtp(opts) / .console(opts) / .memory() / .http(opts) / .resend(opts) <a class="anchor" href="#transports">#</a></h2>',
  '<pre><code class="language-javascript">// b.mail.transports.smtp opts',
  '{',
  '  host:               string,                 // required: true',
  '  port:               number,                 // default: 587 (465 implies implicit TLS)',
  '  user:               string,                 // default: null — SMTP AUTH username',
  '  pass:               string,                 // default: null — SMTP AUTH password',
  '  implicitTls:        boolean,                // default: port === 465',
  '  minTlsVersion:      "TLSv1.3" | "TLSv1.2",  // default: "TLSv1.3"',
  '  rejectUnauthorized: boolean,                // default: true',
  '  servername:         string,                 // default: host (omitted for IP literals)',
  '  ca:                 string | string[],      // default: null — extra CA PEMs',
  '  ecdhCurve:          string,                 // default: null',
  '  ehloName:           string,                 // default: "blamejs"',
  '  timeoutMs:          number,                 // default: 15s',
  '  dkimSigner:         { sign(rfc822) },       // default: null — see b.mail.dkim.create',
  '}</code></pre>',
  '<p>Outbound transport registry. Every transport returns the same <code>{ name, send(message) }</code> shape so <code>b.mail.create({ transport })</code> stays interchangeable. <code>smtp</code> speaks RFC 5321 over STARTTLS or implicit TLS (TLS 1.3 default, TLS 1.2 floor configurable for legacy peers), advertises <code>SMTPUTF8</code> when the message has non-ASCII addresses, and threads through the <code>dkimSigner</code> on the wire just before <code>DATA</code>. <code>http</code> POSTs the message JSON to a vendor-agnostic webhook endpoint; <code>resend</code> wraps the Resend REST API with attachment + <code>content_id</code> support. <code>console</code> prints the message to <code>process.stdout</code> for development (with optional Bcc redaction); <code>memory</code> keeps an in-process array so unit tests can assert on the wire shape without a real network.</p>',
  '<pre><code class="language-javascript">// In tests: capture every send into an in-process array.',
  'var transport = b.mail.transports.memory();',
  'var mail = b.mail.create({ transport: transport, defaults: { from: "noreply@example.com" } });',
  'await mail.send({ to: "a@example.com", subject: "ping", text: "hi" });',
  '// transport.outbox[0] → { to: ["a@example.com"], subject: "ping", text: "hi", from: ... }',
  '</code></pre>',

  '<h2 id="unsubscribe">b.mail.unsubscribe.buildHeaders(opts) / .handler(opts) <a class="anchor" href="#unsubscribe">#</a></h2>',
  '<pre><code class="language-javascript">// buildHeaders opts',
  '{',
  '  url:       string,                          // default: null — https URL for one-click POST',
  '  mailto:    string,                          // default: null — fallback mailto: address',
  '  oneClick:  boolean,                         // default: false — emit List-Unsubscribe-Post',
  '}',
  '',
  '// handler opts',
  '{',
  '  onUnsubscribe:  async (req, res) =&gt; void,  // required: true',
  '  maxBodyBytes:   number,                     // default: 4096',
  '}</code></pre>',
  '<p>RFC 8058 / RFC 2369 List-Unsubscribe support. <code>buildHeaders</code> returns the <code>List-Unsubscribe</code> + <code>List-Unsubscribe-Post</code> headers operators merge into <code>send()</code> via <code>headers</code> (or pass <code>unsubscribe</code> on the message, which the transport hoists into the same headers). <code>handler</code> is request-lifecycle middleware that validates the RFC 8058 §3.1 one-click POST body (<code>List-Unsubscribe=One-Click</code>, exact byte sequence), invokes the operator <code>onUnsubscribe</code> callback so the operator-side suppression list is updated, and replies <code>200</code> with empty body when the callback resolves. Bulk-sender requirements at Gmail / Yahoo / Microsoft 365 mandate this for senders >= 5k messages/day.</p>',
  '<pre><code class="language-javascript">// var headers = b.mail.unsubscribe.buildHeaders({',
  '//   url:      "https://example.com/u?token=" + perRecipientToken,',
  '//   mailto:   "unsubscribe@example.com?subject=unsub-" + perRecipientToken,',
  '//   oneClick: true,',
  '// });',
  '//',
  '// await mail.send({',
  '//   to:      "alice@example.com",',
  '//   subject: "Newsletter — May",',
  '//   html:    body,',
  '//   headers: headers,',
  '// });',
  '//',
  '// app.post("/email/unsubscribe", b.mail.unsubscribe.handler({',
  '//   onUnsubscribe: async function (req) {',
  '//     var token = new URL(req.url, "https://h").searchParams.get("token");',
  '//     await db.markUnsubscribed(token);',
  '//   },',
  '// }));',
  'typeof b.mail.unsubscribe.buildHeaders; // "function"',
  'typeof b.mail.unsubscribe.handler;      // "function"</code></pre>',

  '<h2 id="bimi">b.mail.bimi.recordShape(opts) / .fetchPolicy(domain, opts?) / .parseRecord(text) <a class="anchor" href="#bimi">#</a></h2>',
  '<pre><code class="language-javascript">// recordShape opts',
  '{',
  '  logoUrl:   string,                          // required: true — https URL of the SVG (RFC 9091 §5)',
  '  vmcUrl:    string,                          // default: null — https URL of the Verified Mark Certificate',
  '  selector:  string,                          // default: "default" (used by fetchPolicy too)',
  '}',
  '',
  '// fetchPolicy opts',
  '{',
  '  selector:   string,                         // default: "default"',
  '  dnsLookup:  async (qname, type) =&gt; txtRecords, // default: node:dns/promises.resolveTxt',
  '}</code></pre>',
  '<p>RFC 9091 BIMI helper. <code>recordShape</code> builds the <code>v=BIMI1; l=...; a=...</code> TXT record string operators publish at <code>&lt;selector&gt;._bimi.&lt;domain&gt;</code> — both URLs are checked for HTTPS scheme and refused on CR/LF/NUL/semicolon (defense-in-depth against record-separator injection). <code>parseRecord</code> reverses it into <code>{ v, l, a }</code> with a 2 KiB sanity cap. <code>fetchPolicy</code> performs the DNS lookup and returns the parsed shape — falls back to <code>resolveTxt</code> when no <code>dnsLookup</code> is supplied so <code>b.network.dns</code> (DoH/DoT) plugs in without a hard dep. The framework does NOT validate SVG / VMC contents against the §5/§6 profiles; operators feed those to their own asset pipeline. BIMI requires a passing DMARC posture (quarantine or reject) at the receiver — no-op for senders without enforced DMARC.</p>',
  '<pre><code class="language-javascript">var record = b.mail.bimi.recordShape({',
  '  logoUrl: "https://cdn.example.com/brand/bimi.svg",',
  '  vmcUrl:  "https://cdn.example.com/brand/vmc.pem",',
  '});',
  '// record → "v=BIMI1; l=https://cdn.example.com/brand/bimi.svg; a=https://cdn.example.com/brand/vmc.pem"',
  '',
  '// Hermetic example: feed parseRecord directly so no DNS is needed.',
  'var parsed = b.mail.bimi.parseRecord(record);',
  '// parsed → { v: "BIMI1", l: "https://cdn.example.com/brand/bimi.svg", a: "https://cdn.example.com/brand/vmc.pem" }',
  '</code></pre>',

  '<h2 id="auth-results">b.mail.authResults.emit(opts) <a class="anchor" href="#auth-results">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  authservId:  string,                        // required: true — RFC 8601 §2.2 authserv-id',
  '  results:     [{ method, result, reason?, domain?, selector?, from?,',
  '                  smtpMailfrom?, smtpHelo?, ip?, iprev?, tls? }, ...],',
  '                                              // required: true (empty array → "none")',
  '  version:     string | number,               // default: "1"',
  '  fold:        boolean,                       // default: true — fold multi-result lines',
  '}</code></pre>',
  '<p>RFC 8601 <code>Authentication-Results</code> header builder. Border MTAs that authenticate inbound mail (SPF / DKIM / DMARC / ARC / iprev / DANE / DNSWL / S/MIME / VBR) attach this header so downstream systems can act on the verdicts without re-running the lookups. The emitter validates every <code>method</code> + <code>result</code> against the §2.7 vocabulary — unknown method or unsupported result for a given method throws <code>mail-auth/ar-bad-method</code> / <code>mail-auth/ar-bad-result</code> at config time so a mistyped vendor name doesn\'t silently emit a malformed header. <code>reason</code> uses RFC 8601 §2.2 quoted-string escaping so receivers round-trip the original text. Property keys (<code>domain</code>, <code>selector</code>, <code>from</code>, <code>smtpMailfrom</code>, etc.) project onto the spec\'s <code>ptype.property</code> triples (<code>header.d</code>, <code>header.s</code>, <code>header.from</code>, <code>smtp.mailfrom</code>, …). Pair with the inbound <code>spf.verify</code> / <code>dkim.verify</code> / <code>dmarc.evaluate</code> / <code>arc.verify</code> primitives.</p>',
  '<pre><code class="language-javascript">// Compose verdicts from the inbound auth primitives into one header.',
  'var header = b.mail.authResults.emit({',
  '  authservId: "mx.example.com",',
  '  results: [',
  '    { method: "spf",   result: "pass", smtpMailfrom: "alice@sender.example", ip: "192.0.2.5" },',
  '    { method: "dkim",  result: "pass", domain: "sender.example", selector: "s1" },',
  '    { method: "dmarc", result: "pass", from: "alice@sender.example" },',
  '  ],',
  '});',
  '// header begins:',
  '//   "Authentication-Results: mx.example.com;\\r\\n  spf=pass smtp.mailfrom=alice@sender.example policy.ip=192.0.2.5;\\r\\n  dkim=pass header.d=sender.example header.s=s1;\\r\\n  dmarc=pass header.from=alice@sender.example"',
  '</code></pre>',

  '<h2 id="bounce-parse">b.mailBounce.parse(payload, opts) <a class="anchor" href="#bounce-parse">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  vendor:  "postmark" | "ses" | "resend",     // required unless parser supplied',
  '  parser:  (payload) =&gt; BounceEvent,          // default: null — supply for non-built-in vendors',
  '}</code></pre>',
  '<p>Lower-level entry point that backs <code>b.mailBounce.handler</code>. Takes a raw vendor webhook payload (Postmark JSON object, SES SNS notification, or Resend event) and returns the same normalized <code>BounceEvent</code> shape (<code>vendor</code> / <code>type</code> / <code>subType</code> / <code>recipient</code> / <code>messageId</code> / <code>reason</code> / <code>timestamp</code> / <code>raw</code>) that the handler emits. Useful when the operator already has the parsed JSON in hand (replay tooling, webhook-replay job, custom verify-then-parse split) and doesn\'t want the full middleware stack. Throws <code>mail-bounce/missing-vendor</code> when neither <code>vendor</code> nor <code>parser</code> is supplied; <code>mail-bounce/unknown-vendor</code> for an unrecognized built-in name. Built-ins exposed for advanced wiring at <code>b.mailBounce.vendors.{postmark,ses,resend}</code>.</p>',
  '<pre><code class="language-javascript">var event = b.mailBounce.parse({',
  '  RecordType:    "Bounce",',
  '  Type:          "HardBounce",',
  '  TypeCode:      1,',
  '  Email:         "alice@example.com",',
  '  MessageID:     "abc-123",',
  '  Description:   "550 5.1.1 user unknown",',
  '  BouncedAt:     "2026-05-08T12:00:00Z",',
  '}, { vendor: "postmark" });',
  '// event → {',
  '//   vendor: "postmark", type: "bounce", subType: "hard",',
  '//   recipient: "alice@example.com", messageId: "abc-123",',
  '//   reason: "550 5.1.1 user unknown", timestamp: "2026-05-08T12:00:00Z", raw: ...',
  '// }',
  '</code></pre>',

  '<h2 id="smtp-tlsrpt-submit">b.network.smtp.tlsRpt.submit(report, opts) <a class="anchor" href="#smtp-tlsrpt-submit">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  rua:        [string, ...],                          // required — from fetchPolicy or operator config',
  '  httpClient: object,                                 // optional override (defaults to b.httpClient)',
  '  timeoutMs:  number,                                 // default 30s',
  '  audit:      object,                                 // optional audit handler',
  '}</code></pre>',
  '<p>Submits a TLS-RPT report (typically built via <code>recordShape</code>) to the published rua endpoints. <code>https://</code> URIs receive an HTTPS <code>POST</code> with <code>Content-Type: application/tlsrpt+gzip</code> and a gzip-compressed JSON body per RFC 8460 §6. <code>mailto:</code> URIs return a prepared <code>{ to, subject, contentType, encoding, body }</code> object so operators hand it to <code>b.mail</code> with their configured relay (the framework doesn\'t bake an SMTP relay in — operators wire transport per their environment). Per-endpoint result records carry <code>{ uri, kind, ok, status, error }</code> so a failure on one rua doesn\'t cascade.</p>',
  '<pre><code class="language-javascript">var report = b.network.smtp.tlsRpt.recordShape({',
  '  organization: "example.com",',
  '  policies:     [{ type: "sts", domain: "example.com" }],',
  '});',
  '',
  '// Mock httpClient so the example doesn\'t hit the wire.',
  'var fakeHttp = { request: async function () { return { status: 202 }; } };',
  'var rv = await b.network.smtp.tlsRpt.submit(report, {',
  '  rua:        ["mailto:tls@example.com", "https://reports.example.com/submit"],',
  '  httpClient: fakeHttp,',
  '});',
  '// rv.submitted === 2; rv.results[0].kind === "mailto"; rv.results[1].kind === "https"',
  '</code></pre>',

].join("\n"),
};
