"use strict";

module.exports = {
  slug:  "middleware",
  title: "Middleware",
  body: [
  '<h1>Middleware</h1>',
  '<p>The default middleware stack <code>b.createApp</code> mounts, plus the standalone middleware primitives operators reach for individually. Every middleware composes via the standard <code>(req, res, next)</code> contract.</p>',

  '<h2 id="stack">The default stack <a class="anchor" href="#stack">#</a></h2>',
  '<p><code>b.createApp</code> mounts middleware in this order; operators can override any one or insert their own:</p>',
  '<ol>',
  '  <li><code>requestId</code> — assigns or threads <code>X-Request-Id</code>; downstream middleware reads <code>req.requestId</code>.</li>',
  '  <li><code>requestLog</code> — HTTP access log via <code>b.log</code> (status, duration, bytes, actor IP, user agent, request id).</li>',
  '  <li><code>securityHeaders</code> — HSTS, X-Content-Type-Options, X-Frame-Options, Referrer-Policy, Permissions-Policy, COOP / CORP, Origin-Agent-Cluster, X-DNS-Prefetch-Control.</li>',
  '  <li><code>botGuard</code> — fingerprints public GETs against <code>accept-language</code>, <code>sec-fetch-dest</code>, <code>sec-fetch-mode</code>; rejects on missing/inconsistent shapes.</li>',
  '  <li><code>cors</code> — allowlist-only; default is <em>same-origin</em> (empty <code>origins: []</code>). Pass <code>siteOrigin</code> behind a TLS-terminating proxy where the framework can\'t infer the request\'s scheme.</li>',
  '  <li><code>rateLimit</code> — token-bucket per IP + route, memory or cluster backend; <code>skipPaths: ["/healthz"]</code> for endpoints that should never be throttled.</li>',
  '  <li><code>cspNonce</code> — generates a nonce per response so apps can opt into single inline elements without softening the CSP.</li>',
  '  <li><code>bodyParser</code> — <code>{ json: true, urlencoded: true }</code>, raw, multipart; per-route limits.</li>',
  '  <li><code>compression</code> — Brotli first, gzip fallback; respects <code>Accept-Encoding: identity</code>.</li>',
  '  <li><code>attachUser</code> — reads the session cookie and threads <code>req.user</code> when present.</li>',
  '  <li><code>csrfProtect</code> — issues a CSRF token (double-submit cookie or session-stored) and validates on POST/PUT/PATCH/DELETE.</li>',
  '  <li><code>health</code> — <code>/healthz</code>, <code>/readyz</code>, <code>/startupz</code> respond before app-level routing.</li>',
  '</ol>',
  '<p>Each item is a small primitive. <code>b.middleware.rateLimit</code> for instance returns a function; calling it with custom options returns a different function. Apps pick a sensible global and override per-route where it matters:</p>',
  '<pre><code class="language-javascript">var rl = b.middleware.rateLimit({ burst: 120, refillPerSec: 2 });',
  '',
  'router.use(rl);                          // global default',
  'router.post("/login",',
  '  b.middleware.rateLimit({ burst: 5, refillPerSec: 0.05 }),  // tighter',
  '  loginHandler,',
  ');</code></pre>',

  '<h2 id="csrf">CSRF protection <a class="anchor" href="#csrf">#</a></h2>',
  '<p>JSON requests are protected by the encrypted session payload itself — an attacker who can\'t decrypt the session can\'t forge the request. Form POSTs (and any non-JSON content type) get a CSRF token via either the double-submit cookie pattern (default) or a session-stored token. The two are mutually exclusive — passing both at <code>create()</code> time throws.</p>',
  '<pre><code class="language-javascript">var csrf = b.middleware.csrfProtect({',
  '  cookie: { sameSite: "Lax" },     // name auto-resolves',
  '});',
  '// Default cookie name: "__Host-csrf" over HTTPS, "csrf" over plain HTTP.',
  '// The __Host- prefix forces browsers to refuse the cookie unless it carries',
  '// Secure + Path=/ + no Domain — closing the malicious-sibling-subdomain',
  '// override path. Operators with a custom name pass cookie: { name: "..." };',
  '// the framework validates that __Host-* names carry the required attrs.',
  '',
  '// Templates: render req.csrfToken into a hidden input',
  '//   &lt;input type="hidden" name="_csrf" value="{{csrfToken}}"&gt;</code></pre>',

  '<h2 id="csp">CSP and inline content <a class="anchor" href="#csp">#</a></h2>',
  '<p>Operators define a CSP at app boot. The framework default is intentionally strict — no <code>\'unsafe-inline\'</code>. Apps that need an inline script or style for a single element use <code>res.locals.cspNonce</code> on that element, and the response header carries <code>nonce-XYZ</code>.</p>',
  '<pre><code class="language-html">&lt;!-- in a template, with nonce threaded in --&gt;',
  '&lt;script nonce="{{cspNonce}}"&gt;',
  '  // one-off inline, allowed because of the nonce',
  '&lt;/script&gt;</code></pre>',
  '<p>Nonces are 16 random bytes per response, base64-url encoded. They expire with the response so an attacker can\'t cache one to inject later.</p>',

  '<h2 id="body-parser">Body parser <a class="anchor" href="#body-parser">#</a></h2>',
  '<p><code>b.middleware.bodyParser</code> ships four parsers: <code>json</code>, <code>urlencoded</code>, <code>raw</code>, <code>multipart</code>. Per-parser limits, per-field limits in multipart mode.</p>',
  '<pre><code class="language-javascript">router.post("/upload",',
  '  b.middleware.bodyParser.multipart({',
  '    limit:        C.BYTES.mib(50),',
  '    fileFilter:   function (part) {',
  '      // sync predicate — return false to reject before the tmp file opens',
  '      return /^image\\//.test(part.contentType);',
  '    },',
  '    fields: {',
  '      "thumb": { maxBytes: C.BYTES.mib(2), mimeTypes: ["image/png", "image/jpeg"] },',
  '    },',
  '  }),',
  '  async function (req, res) {',
  '    // req.files: [{ field, filename, contentType, sha3, path, size }, ...]',
  '    // req.filesRejected: [{ field, filename, reason }, ...]  (audit-emitted)',
  '  }',
  ');</code></pre>',
  '<p>File parts spool to a tmp dir; SHA3-512 is computed during the stream so operators can de-dup on the digest. Rejected parts land in <code>req.filesRejected</code>; an audit event fires when <code>audit:</code> is wired so post-incident review sees what was filtered.</p>',

  '<h2 id="sse">Server-Sent Events <a class="anchor" href="#sse">#</a></h2>',
  '<p><code>b.middleware.sse</code> opens an SSE channel for live updates without WebSocket overhead. Browser-native <code>EventSource</code> consumes the stream; the middleware handles <code>Content-Type: text/event-stream</code>, <code>Cache-Control: no-cache</code>, <code>X-Accel-Buffering: no</code> (defeats nginx buffering), and the <code>Vary: Accept</code> append.</p>',
  '<pre><code class="language-javascript">router.get("/live", b.middleware.sse(), async function (req, res) {',
  '  var ch = res.sseChannel;',
  '  ch.send({ event: "hello", data: { now: Date.now() } });',
  '',
  '  var t = setInterval(function () {',
  '    ch.ping();   // empty comment — keeps connection alive through proxies',
  '  }, b.constants.TIME.seconds(15));',
  '',
  '  ch.onAbort(function () { clearInterval(t); });',
  '});</code></pre>',
  '<p>Default heartbeat 15s. <code>ch.send({ id, event, data, retry })</code> writes one event; <code>ch.close()</code> ends the stream cleanly. The wrapper handles back-pressure-aware writes — a slow client that fills the kernel buffer doesn\'t pile up writes in process memory.</p>',

  '<h2 id="request-log">Request log <a class="anchor" href="#request-log">#</a></h2>',
  '<p><code>b.middleware.requestLog</code> emits one log line per HTTP request via <code>b.log</code>. Captures method, route pattern, status, duration in ms, response bytes, actor IP (gated by <code>trustProxy</code>), user agent, request id. <code>levelFn</code> dispatches by status: 5xx → <code>error</code>, 4xx → <code>warn</code>, otherwise <code>info</code>.</p>',
  '<pre><code class="language-javascript">app.use(b.middleware.requestLog({',
  '  log:         b.log.boot("http"),',
  '  trustProxy:  true,',
  '  // levelFn:  function (status) { return status &gt;= 500 ? "error" : "info"; },',
  '}));</code></pre>',
  '<p>Wraps <code>res.write</code>/<code>res.end</code>/<code>res.writeHead</code> inline so the byte counter increments before the log emit fires (the canonical bug class is logging from a status-capture hook before the byte counter has updated; this wraps in the right order).</p>',

  '<h2 id="cookies">Cookies <a class="anchor" href="#cookies">#</a></h2>',
  '<p><code>b.cookies</code> ships the cookie helpers — parse the <code>Cookie</code> request header into a key/value map, build a <code>Set-Cookie</code> response header with the right attributes, and a small middleware that wires both onto <code>req.cookies</code> + <code>res.cookie(name, value, opts)</code>. Validates Domain (rejects malformed values that would inject CRLF), Path (CRLF scrub), and SameSite (must be one of <code>Lax</code> / <code>Strict</code> / <code>None</code>) at the call site so a bad cookie definition throws rather than rendering as broken header bytes.</p>',
  '<pre><code class="language-javascript">app.use(b.cookies.middleware());',
  '',
  'router.get("/", function (req, res) {',
  '  res.cookie("theme", "dark", {',
  '    httpOnly: true,',
  '    secure:   true,',
  '    sameSite: "Lax",',
  '    maxAgeMs: C.TIME.days(30),',
  '  });',
  '  res.send(req.cookies.theme || "default");',
  '});</code></pre>',

  '<h2 id="api-encrypt">API encryption <a class="anchor" href="#api-encrypt">#</a></h2>',
  '<p><code>b.middleware.apiEncrypt</code> ECIES-encrypts entire request and response bodies for clients that establish a session over the wire. Full envelope details at <a href="/crypto-vault#ecies">Crypto &amp; Vault → ECIES</a>; the middleware wires it into the request lifecycle with replay-defense via <code>b.nonceStore</code>.</p>',

  '<h2 id="validate-opts">Boot-time config validation <a class="anchor" href="#validate-opts">#</a></h2>',
  '<p>Every primitive\'s <code>create()</code> validates its <code>opts</code> object against an explicit allow-list. A typo like <code>cors({ allowedOrigins: [] })</code> (the API expects <code>origins</code>) throws at boot with the offending key plus the full allowed-keys list, instead of silently weakening the operator\'s setup until a real request hits the wrong code path. The shared helper at <code>b.validateOpts(opts, allowedKeys, "primitive.name")</code> is what every framework primitive uses — operator-built primitives picking up the same pattern stay consistent with the framework\'s diagnostic style.</p>',
].join("\n"),
};
