"use strict";

module.exports = {
  slug:  "middleware",
  title: "Middleware",
  body: [
  '<h1>Middleware</h1>',
  '<p>The default middleware stack <code>b.createApp</code> mounts, plus the standalone middleware primitives operators reach for individually. Every middleware composes via the standard <code>(req, res, next)</code> contract.</p>',

  '<h2 id="stack">The default stack</h2>',
  '<p><code>b.createApp</code> mounts middleware in this order; operators can override any one or insert their own:</p>',
  '<ol>',
  '  <li><code>requestId</code> — assigns or threads <code>X-Request-Id</code>.</li>',
  '  <li><code>requestLog</code> — HTTP access log via <code>b.log</code>.</li>',
  '  <li><code>securityHeaders</code> — HSTS, X-Content-Type-Options, X-Frame-Options, Referrer-Policy, Permissions-Policy, COOP / CORP, Origin-Agent-Cluster, X-DNS-Prefetch-Control.</li>',
  '  <li><code>botGuard</code> — fingerprints public GETs against <code>accept-language</code>, <code>sec-fetch-dest</code>, <code>sec-fetch-mode</code>; rejects on missing/inconsistent shapes.</li>',
  '  <li><code>cors</code> — allowlist-only; default same-origin (empty <code>origins: []</code>).</li>',
  '  <li><code>rateLimit</code> — token-bucket per IP + route, memory or cluster backend.</li>',
  '  <li><code>cspNonce</code> — nonce per response so apps can opt into single inline elements without softening the CSP.</li>',
  '  <li><code>bodyParser</code> — JSON, urlencoded, raw, multipart; per-route limits.</li>',
  '  <li><code>compression</code> — Brotli first, gzip fallback; respects <code>Accept-Encoding: identity</code>.</li>',
  '  <li><code>attachUser</code> — reads the session cookie and threads <code>req.user</code>.</li>',
  '  <li><code>csrfProtect</code> — issues a CSRF token and validates on POST/PUT/PATCH/DELETE.</li>',
  '  <li><code>health</code> — <code>/healthz</code>, <code>/readyz</code>, <code>/startupz</code> respond before app-level routing.</li>',
  '</ol>',

  '<h3>b.middleware.rateLimit(opts) <a class="anchor" href="#rate-limit">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  // memory backend (default):',
  '  burst:           number,                  // max tokens in the bucket',
  '  refillPerSecond: number,                  // tokens added per second',
  '  // cluster backend:',
  '  limit:           number,                  // max requests per window',
  '  windowMs:        number,                  // window length in ms',
  '  pruneIntervalMs: number,                  // window-row sweep cadence',
  '  // common:',
  '  keyFn:           (req) => string,         // default: route + actorIp',
  '  backend:         "memory" | "cluster",    // default: "memory"',
  '  scope:           string,                  // default: req.routePattern',
  '  skipPaths:       [string],                // default: []',
  '  trustProxy:      boolean | number,        // default: false',
  '  statusOnLimit:   number,                  // default: 429',
  '  bodyOnLimit:     string,                  // default: "Too Many Requests"',
  '  header:          string,                  // default: "Retry-After"',
  '}</code></pre>',
  '<p>Token-bucket rate limiter. Apps pick a sensible global and override per-route where it matters (login routes, password-reset endpoints).</p>',
  '<pre><code class="language-javascript">var rl = b.middleware.rateLimit({ burst: 120, refillPerSecond: 2 });',
  'var tightRl = b.middleware.rateLimit({ burst: 5, refillPerSecond: 0.05 });',
  'router.use(rl);',
  'router.post("/login", tightRl, loginHandler);</code></pre>',

  '<h2 id="csrf">CSRF protection</h2>',

  '<h3>b.middleware.csrfProtect(opts?) <a class="anchor" href="#csrf-protect">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  cookie:          { name?, sameSite?, path?, domain? } | false,  // double-submit (default)',
  '  tokenLookup:     (req) => string,         // session-stored alt (mutually exclusive with cookie)',
  '  fieldName:       string,                  // default: "_csrf" — form field name',
  '  headerName:      string,                  // default: "x-csrf-token" — fetch header name',
  '  methods:         [string],                // default: ["POST", "PUT", "PATCH", "DELETE"]',
  '  trustProxy:      boolean | number,        // default: false — gates Secure-cookie inference',
  '  audit:           auditInstance,           // default: null — emits csrf.rejected',
  '  checkOrigin:     boolean,                 // default: true — Origin/Referer cross-check on state-changing requests',
  '  allowedOrigins:  [string],                // default: same-origin — extra origins to accept (e.g. "https://app.example.com")',
  '  requireOrigin:   boolean,                 // default: false — refuse browser state-changing requests that omit Origin AND Referer',
  '  requireJsonContentType: boolean,          // default: false — refuse non-JSON state-changing requests outright',
  '}</code></pre>',
  '<p>JSON requests are protected by the encrypted session payload itself. Form POSTs (and any non-JSON content type) get a CSRF token via the double-submit cookie pattern (default) or a session-stored token. The two are mutually exclusive — passing both throws at create-time. Default cookie name is <code>__Host-csrf</code> over HTTPS, <code>csrf</code> over plain HTTP. The <code>__Host-</code> prefix forces browsers to refuse the cookie unless it carries Secure + Path=/ + no Domain — closing the malicious-sibling-subdomain override path.</p>',
  '<pre><code class="language-javascript">var csrf = b.middleware.csrfProtect({',
  '  cookie: { sameSite: "Lax" },',
  '});',
  'router.use(csrf);</code></pre>',

  '<h2 id="csp">CSP and inline content</h2>',

  '<h3>b.middleware.cspNonce() <a class="anchor" href="#csp-nonce">#</a></h3>',
  '<p>Generates a fresh 16-byte random base64-url nonce per response and exposes it on <code>res.locals.cspNonce</code>. The framework default CSP is intentionally strict — no <code>\'unsafe-inline\'</code>. Apps that need an inline script or style for a single element use the nonce on that element; the response header carries <code>nonce-XYZ</code>. Nonces expire with the response so an attacker can\'t cache one to inject later.</p>',
  '<pre><code class="language-javascript">var cspMw = b.middleware.cspNonce();',
  'router.use(cspMw);',
  '// In a template, render res.locals.cspNonce into <script nonce="...">.</code></pre>',

  '<h2 id="body-parser">Body parser</h2>',

  '<h3>b.middleware.bodyParser(opts?) <a class="anchor" href="#body-parser">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  json:           { limit?, contentTypes?, strict? } | false,',
  '  urlencoded:     { limit?, contentTypes? } | false,',
  '  text:           { limit?, contentTypes? } | false,',
  '  raw:            { limit?, contentTypes? } | false,',
  '  multipart:      { limit?, fileFilter?, fields?, tmpDir?, audit? } | false,',
  '  keepRawBody:    boolean,                 // default: false — preserve req.rawBody',
  '}</code></pre>',
  '<p>Single combined parser. Each sub-key configures one parser; pass <code>false</code> to disable a parser entirely. Each parser tests <code>Content-Type</code> against its <code>contentTypes</code> list and skips silently for non-matching requests, so the same middleware handles JSON, urlencoded, multipart, and raw based on the inbound shape. Rejects with 413 when the payload exceeds the per-parser <code>limit</code> before the handler sees it.</p>',
  '<p><strong>Request-smuggling defense (RFC 9112 §6.1 + §7.1).</strong> The parser refuses ambiguous framing before reading the body — a request that carries both <code>Content-Length</code> and <code>Transfer-Encoding</code>, or duplicate <code>Content-Length</code> headers, returns 400 + <code>Connection: close</code> so an upstream proxy cannot reuse the socket. Mid-stream chunked-encoding parse failures (Node\'s <code>HPE_INVALID_CHUNK_SIZE</code> class) flow through the same path: 400 + <code>Connection: close</code> + <code>req.destroy()</code> + audit emit <code>http.chunked.malformed.refused</code> with the parser\'s diagnostic code. Operators do not need to do anything for this — the defenses are wired into the default body-parser stack.</p>',
  '<pre><code class="language-javascript">var parser = b.middleware.bodyParser({',
  '  json:       { limit: b.constants.BYTES.kib(64) },',
  '  urlencoded: { limit: b.constants.BYTES.kib(64) },',
  '  multipart:  { limit: b.constants.BYTES.mib(50),',
  '                fileFilter: function (part) { return /^image\\//.test(part.contentType); } },',
  '});',
  'router.use(parser);</code></pre>',

  '<h3>b.middleware.bodyParser.raw(opts?) <a class="anchor" href="#body-parser-raw">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  limit:           number,                  // default: C.BYTES.kib(100)',
  '  contentTypes:    [string],                // default: any',
  '}</code></pre>',
  '<p>Standalone raw-body middleware. Useful for webhook receivers (Stripe, GitHub, the framework\'s own <code>b.webhook.verifier</code>) that need the unmodified bytes for signature verification. Sets <code>req.body</code> to a <code>Buffer</code>.</p>',
  '<pre><code class="language-javascript">var rawMw = b.middleware.bodyParser.raw({ limit: b.constants.BYTES.mib(1) });',
  'router.post("/hooks/in", rawMw, function (req, res) { res.end(); });</code></pre>',

  '<h2 id="sse">Server-Sent Events</h2>',

  '<h3>b.middleware.sse(handler, opts?) <a class="anchor" href="#sse-mw">#</a></h3>',
  '<pre><code class="language-javascript">// handler signature:',
  '//   function (channel, req) { /* channel.send / .ping / .close / .onAbort */ }',
  '//',
  '// opts:',
  '{',
  '  heartbeatMs:     number,                  // default: C.TIME.seconds(15)',
  '  headers:         object,                  // additional response headers',
  '}</code></pre>',
  '<p>Opens an SSE channel for live updates without WebSocket overhead. Browser-native <code>EventSource</code> consumes the stream; the middleware handles <code>Content-Type: text/event-stream</code>, <code>Cache-Control: no-cache</code>, <code>X-Accel-Buffering: no</code> (defeats nginx buffering). The <code>channel</code> arg passed to <code>handler</code> exposes <code>send / ping / close / onAbort</code>. The wrapper is back-pressure-aware — a slow client filling the kernel buffer doesn\'t pile up writes in process memory.</p>',
  '<pre><code class="language-javascript">var sseMw = b.middleware.sse(function (channel, _req) {',
  '  channel.send({ event: "hello", data: { now: Date.now() } });',
  '  var t = setInterval(function () { channel.ping(); }, b.constants.TIME.seconds(15));',
  '  channel.onAbort(function () { clearInterval(t); });',
  '}, { heartbeatMs: b.constants.TIME.seconds(15) });',
  'router.get("/live", sseMw);</code></pre>',

  '<h2 id="request-log">Request log</h2>',

  '<h3>b.middleware.requestLog(opts) <a class="anchor" href="#request-log-mw">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  logger:          logger,                  // required — b.log.boot("http") instance',
  '  trustProxy:      boolean,                 // default: false',
  '  level:           string,                  // default: "info" — fixed level for non-error rows',
  '  levelFn:         (status) => string,      // default: 5xx→error, 4xx→warn, else level',
  '  fields:          (req, res) => object,    // default: null — operator-extra fields',
  '  skipPaths:       [string],                // default: [] — never log these prefixes',
  '}</code></pre>',
  '<p>Emits one log line per HTTP request via <code>b.log</code>. Captures method, route pattern, status, duration in ms, response bytes, actor IP (gated by <code>trustProxy</code>), user agent, request id. Wraps <code>res.write</code> / <code>res.end</code> / <code>res.writeHead</code> inline so the byte counter increments before the log emit fires.</p>',
  '<pre><code class="language-javascript">var rlog = b.middleware.requestLog({ logger: b.log.boot("http"), trustProxy: true });',
  'app.use(rlog);</code></pre>',

  '<h2 id="cookies">Cookies</h2>',

  '<h3>b.cookies.create(opts?) <a class="anchor" href="#cookies-create">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  defaults:        { secure?, httpOnly?, sameSite?, path?, domain? },',
  '  vault:           vaultInstance,           // optional — seal cookie values via b.vault',
  '}</code></pre>',
  '<p>Returns a cookie helper instance. Validates Domain (rejects malformed values that would inject CRLF), Path (CRLF scrub), and SameSite (must be one of <code>Lax</code> / <code>Strict</code> / <code>None</code>) at the call site so a bad cookie definition throws rather than rendering as broken header bytes. Operators with strict-policy apps pass defaults so every <code>.serialize</code> picks them up.</p>',
  '<pre><code class="language-javascript">var ck = b.cookies.create({',
  '  defaults: { httpOnly: true, secure: true, sameSite: "Lax" },',
  '});',
  'var setHeader = ck.serialize("theme", "dark", { maxAgeMs: b.constants.TIME.days(30) });',
  '// → Set-Cookie header value: "theme=dark; HttpOnly; Secure; SameSite=Lax; Max-Age=2592000"</code></pre>',

  '<h3>b.cookies.parse(headerValue) <a class="anchor" href="#cookies-parse">#</a></h3>',
  '<p>Parses a request <code>Cookie</code> header into a <code>{ name: value }</code> map. URL-decodes values; rejects malformed cookies silently (the framework\'s contract is "best effort, never throw on operator headers"). Reach for <code>parseSafe</code> when you want every anomaly surfaced.</p>',
  '<pre><code class="language-javascript">var jar = b.cookies.parse("theme=dark; sid=abc123");',
  '// → { theme: "dark", sid: "abc123" }</code></pre>',

  '<h3>b.cookies.parseSafe(headerValue, opts?) <a class="anchor" href="#cookies-parse-safe">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  maxHeaderBytes:  number,    // default 8 KiB',
  '  maxNameBytes:    number,    // default 256',
  '  maxValueBytes:   number,    // default 4 KiB',
  '}</code></pre>',
  '<p>Threat-detecting inbound parser. Returns <code>{ jar, issues }</code> where <code>issues</code> surfaces detected anomalies: <code>header-cap</code>, <code>header-control-byte</code> (CR / LF / NUL injected through proxy), <code>pair-malformed</code>, <code>pair-empty-name</code>, <code>name-cap</code>, <code>value-cap</code>, <code>duplicate-name</code> (cookie-tossing class). Issue shape: <code>{ kind, severity, snippet, name? }</code>.</p>',
  '<pre><code class="language-javascript">var rv = b.cookies.parseSafe("a=1; b=2; a=3");',
  '// → { jar: { a: "3", b: "2" },',
  '//     issues: [{ kind: "duplicate-name", severity: "high", name: "a", ... }] }</code></pre>',

  '<h3>b.middleware.headers(opts?) <a class="anchor" href="#middleware-headers">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  mode:           "enforce" | "audit-only" | "log-only",',
  '  audit:          b.audit,',
  '  refuseOnHigh:   true,            // 400 if any high-severity issue (enforce mode)',
  '  maxHeaderCount: 100,              // total inbound header count cap',
  '  maxValueBytes:  8 * 1024,         // single header value byte cap',
  '  trustProxy:     false,            // whether X-Forwarded-* are operator-trusted',
  '}</code></pre>',
  '<p>Inbound HTTP header threat detection. Sits at the top of the request lifecycle. Issue kinds: <code>header-name-shape</code> (header name not RFC 9110 §5.1 token), <code>header-value-control-byte</code> (CR / LF / NUL — header-injection defense in depth), <code>header-count-cap</code>, <code>header-value-cap</code>, <code>smuggling-cl-te</code> (RFC 9112 §6.1 — both Content-Length and Transfer-Encoding present), <code>smuggling-cl-multi</code> / <code>smuggling-te-multi</code> (proxy-desync class), <code>deprecated-trust-header</code> (X-Forwarded-* without trustProxy opt — adopt RFC 7239 <code>Forwarded</code>).</p>',
  '<pre><code class="language-javascript">app.use(b.middleware.headers({ mode: "enforce", audit: b.audit }));',
  '</code></pre>',

  '<h3>b.middleware.cookies(opts?) <a class="anchor" href="#middleware-cookies">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  mode:           "enforce" | "audit-only" | "log-only",',
  '  audit:          b.audit,',
  '  refuseOnHigh:   true,        // 400 if any high-severity issue (enforce mode)',
  '  maxHeaderBytes: number,',
  '  maxNameBytes:   number,',
  '  maxValueBytes:  number,',
  '}</code></pre>',
  '<p>Wires <code>parseSafe</code> into the request lifecycle. Populates <code>req.cookieJar</code>; emits one audit row per detected high-severity issue; on <code>mode: "enforce"</code> + <code>refuseOnHigh</code> (default), refuses the request with HTTP 400 + JSON body listing the detected issues.</p>',
  '<pre><code class="language-javascript">app.use(b.middleware.cookies({ mode: "enforce", audit: b.audit }));',
  '</code></pre>',

  '<h2 id="api-encrypt">API encryption</h2>',

  '<h3>b.middleware.apiEncrypt(opts) <a class="anchor" href="#api-encrypt-call">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  keypair:              { publicKey, privateKey, ecPublicKey, ecPrivateKey },',
  '  // OR for rotation overlap (active first; older keypairs follow):',
  '  keypairs:             [keypair, prevKeypair],',
  '  // ---- replay defense ----',
  '  replayWindowMs:       number,                  // default: 5 minutes',
  '  nonceStore:           b.nonceStore,            // default: in-memory; cluster-shared for multi-replica',
  '  pruneIntervalMs:      number,                  // default: max(30s, replayWindowMs/2)',
  '  // ---- routing ----',
  '  exemptPaths:          [string | RegExp],       // exact + prefix match for strings; RegExp test',
  '  contentTypes:         [string] | null,         // default: ["application/json"]; null = all non-exempt',
  '  // ---- keying mode (v0.7.3) ----',
  '  keying:               "per-request",           // default — fresh KEM material every request',
  '  // OR:',
  '  keying:               "per-session",           // opt-in — KEM amortized across sessionTtlMs',
  '  sessionTtlMs:         number,                  // default: 15 minutes (per-session only)',
  '  sessionMaxResponses:  number,                  // default: 1024 (per-session only)',
  '  sessionStore:         { get, set, delete },    // operator-supplied (b.cache-shaped) for cluster sharing',
  '  // ---- audit + observability ----',
  '  audit:                boolean,                 // default: true (false to suppress audit emits)',
  '  observability:        b.observability,         // optional — counters for sessions established / replay-rejected / expired / rotated',
  '  trustProxy:           boolean,                 // default: false — honour x-forwarded-for in audit ip field',
  '  maxDecryptedBytes:    number,                  // default: 4 MiB — parse-bomb defense',
  '}</code></pre>',
  '<p><code>b.middleware.apiEncrypt</code> end-to-end-encrypts request and response bodies between operator-controlled clients (mobile / desktop / service-to-service) and the framework. TLS protects the network hops; <code>apiEncrypt</code> protects the body through every internal cleartext segment (load balancer cleartext, sidecar proxy, log aggregator, APM tooling). Full envelope crypto detail at <a href="/crypto-vault#ecies">Crypto &amp; Vault → ECIES</a>: ML-KEM-1024 + P-384 ECDH hybrid → SHAKE256 KDF → XChaCha20-Poly1305. Replay defense is a 16-byte client nonce checked + inserted atomically against <code>nonceStore</code> within a configurable replay window.</p>',
  '<p><strong>Per-request keying (default):</strong> every request carries fresh KEM material (<code>_ek</code>) — strictly safer if the framework\'s session storage gets compromised. Each request stands alone; no session bookkeeping. The request body is <code>{ _ek, _ct, _ts, _nonce }</code>; the response body is <code>{ _ct }</code>.</p>',
  '<p><strong>Per-session keying (opt-in):</strong> the first request carries the full bootstrap envelope <code>{ _ek, _ct, _ts, _nonce, _sid, _ctr }</code> — server stores the session key keyed by sid. Subsequent requests omit <code>_ek</code> and <code>_nonce</code>, sending only <code>{ _ct, _ts, _sid, _ctr }</code> (the monotonic counter replaces the nonce for replay defense). The response carries <code>{ _ct, _sid, _ctr }</code> and the client validates the response counter is strictly increasing. Sessions expire on <code>sessionTtlMs</code> OR after <code>sessionMaxResponses</code> responses — server emits 401 with <code>session-expired</code> / <code>session-rotation-required</code> so the client re-bootstraps. <strong>The trade-off:</strong> per-session amortizes ~1.6 KB of KEM material across the session for high-throughput / mobile / metered-network apps, but a leaked session key exposes that session\'s traffic. Operators that can\'t afford a session-leak attack stay on per-request.</p>',
  '<p><strong>Operator-supplied <code>sessionStore</code>:</strong> defaults to an in-memory map for single-process apps. Multi-replica deploys pass a <code>{ get(sid), set(sid, row, opts?), delete(sid) }</code>-shaped handle — <code>b.cache.create({ backend: "cluster" })</code> is shape-compatible. The session row carries <code>{ sessionKey, lastReqCtr, responsesEmitted, createdAt, expiresAt, lastUsedAt }</code>; operators wiring an external store SHOULD seal the row via <code>b.vault.seal</code> at write time and unseal at read time so a leaked DB row doesn\'t leak the session key.</p>',
  '<pre><code class="language-javascript">// Per-request mode (default) — no behaviour change from v0.6.x.',
  '// var apiEncrypt = b.middleware.apiEncrypt({',
  '//   keypair:        keypair,',
  '//   replayWindowMs: b.constants.TIME.minutes(5),',
  '//   nonceStore:     b.nonceStore.create({ backend: "cluster" }),',
  '// });',
  '//',
  '// Per-session mode — opt in for high-throughput chat / streaming / mobile.',
  '// var apiEncrypt = b.middleware.apiEncrypt({',
  '//   keypair:             keypair,',
  '//   keying:              "per-session",',
  '//   sessionTtlMs:        b.constants.TIME.minutes(15),',
  '//   sessionMaxResponses: 1024,',
  '//   sessionStore:        b.cache.create({ backend: "cluster" }),',
  '//   observability:       b.observability,',
  '// });',
  '// router.use(apiEncrypt);',
  '//',
  '// Client side — same shape, opt into per-session via the keying field.',
  '// var enc = b.middleware.apiEncrypt.client({',
  '//   pubkey: callee.pubkey,',
  '//   keying: "per-session",',
  '// });',
  '// var first  = enc.encryptRequest({ user: "alice" });   // bootstrap envelope',
  '// var second = enc.encryptRequest({ msg:  "hello" });   // sid + counter only',
  '// // After the server returns 401 session-expired, call enc.resetSession()',
  '// // and re-issue.',
  '//',
  '// Server-to-server with the framework HTTP client:',
  '// var encClient = b.httpClient.encrypted({',
  '//   pubkey:  callee.pubkey,',
  '//   baseUrl: "https://callee.example",',
  '//   keying:  "per-session",',
  '// });',
  '// var resp = await encClient.request({ method: "POST", path: "/api/widget", body: { ... } });',
  'b.middleware.apiEncrypt.ApiEncryptError;   // referenced for symbol-resolve gate</code></pre>',

  '<h2 id="network-allowlist">Network allowlist</h2>',

  '<h3>b.middleware.networkAllowlist(opts) <a class="anchor" href="#network-allowlist-call">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  paths:        [string],                   // required: pathname prefixes to gate',
  '  allowedCidrs: [string],                   // required: IPv4 / IPv6 with prefix length',
  '  deniedCidrs:  [string],                   // default: [] — deny-then-allow precedence',
  '  trustProxy:   boolean | number,           // default: false (honour x-forwarded-for when true)',
  '  denyStatus:   number,                     // default: 404 — reveal nothing about the gate',
  '  denyBody:     string,                     // default: "Not Found"',
  '  audit:        auditInstance,              // default: null — emits network.gate.denied',
  '}</code></pre>',
  '<p>Restricts a named set of pathname prefixes to operator-approved CIDR ranges. The right place for this fence is the reverse proxy / NACL; this primitive is the in-process equivalent for deploys that don\'t have separate infrastructure for it. A path-only auth gate + a credential leak is full compromise — the network gate is the second layer. Path matching is boundary-aware: <code>/admin</code> matches <code>/admin</code> + <code>/admin/...</code> but not <code>/administer</code>. CIDRs are validated at <code>create()</code>; a malformed entry throws at boot.</p>',
  '<pre><code class="language-javascript">router.use(b.middleware.networkAllowlist({',
  '  paths:        ["/admin", "/healthz/internal"],',
  '  allowedCidrs: ["10.0.0.0/8", "192.168.0.0/16", "::1/128"],',
  '  trustProxy:   true,',
  '}));</code></pre>',

  '<h2 id="middleware-request-id">b.middleware.requestId(options) <a class="anchor" href="#middleware-request-id">#</a></h2>',
  '<p>Attaches a stable request id for logs, tracing, audit rows, and response headers. Operators put it near the top of the stack.</p>',
  '<pre><code class="language-javascript">var requestId = b.middleware.requestId({ headerName: "x-request-id" });',
  'typeof requestId; // "function"</code></pre>',

  '<h2 id="middleware-security-headers">b.middleware.securityHeaders(options) <a class="anchor" href="#middleware-security-headers">#</a></h2>',
  '<p>Sets the baseline browser security headers: content type sniffing off, frame policy, referrer policy, permissions policy, and related hardening headers.</p>',
  '<pre><code class="language-javascript">var headers = b.middleware.securityHeaders({});',
  'typeof headers; // "function"</code></pre>',

  '<h2 id="middleware-cors">b.middleware.cors(options) <a class="anchor" href="#middleware-cors">#</a></h2>',
  '<p>CORS gate for explicit origin allow-lists. Preflight handling and credential policy stay centralized instead of being rebuilt per route.</p>',
  '<pre><code class="language-javascript">var cors = b.middleware.cors({ origins: ["https://app.example.test"] });',
  'typeof cors; // "function"</code></pre>',

  '<h2 id="middleware-compression">b.middleware.compression(options) <a class="anchor" href="#middleware-compression">#</a></h2>',
  '<p>Response compression middleware with bounded buffering and content-type controls. Static assets and large HTML pages use this path in the wiki app.</p>',
  '<pre><code class="language-javascript">var compression = b.middleware.compression({});',
  'typeof compression; // "function"</code></pre>',

  '<h2 id="middleware-error-handler">b.middleware.errorHandler(options) <a class="anchor" href="#middleware-error-handler">#</a></h2>',
  '<p>Terminal error renderer that maps framework typed errors to HTTP status codes without leaking stack traces in production responses.</p>',
  '<pre><code class="language-javascript">var errors = b.middleware.errorHandler({});',
  'typeof errors; // "function"</code></pre>',

  '<h2 id="middleware-health">b.middleware.health(options) <a class="anchor" href="#middleware-health">#</a></h2>',
  '<p>Health and readiness endpoint helper for load balancers. Operators wire cheap process checks to health and dependency checks to readiness.</p>',
  '<pre><code class="language-javascript">var health = b.middleware.health({});',
  'typeof health; // "function"</code></pre>',

  '<h2 id="middleware-methods-content-type">b.middleware.requireMethods(options) / requireContentType(options) <a class="anchor" href="#middleware-methods-content-type">#</a></h2>',
  '<p>Request-shape gates that reject unsupported methods and unexpected content types before parsing or route dispatch.</p>',
  '<pre><code class="language-javascript">var methods = b.middleware.requireMethods(["GET", "POST"]);',
  'var jsonOnly = b.middleware.requireContentType(["application/json"]);',
  'typeof methods === "function" && typeof jsonOnly === "function";</code></pre>',

  '<h2 id="middleware-auth-gates">b.middleware.requireAuth(options) / attachUser(options) <a class="anchor" href="#middleware-auth-gates">#</a></h2>',
  '<p>Session authentication helpers. <code>attachUser</code> resolves the current session into request context; <code>requireAuth</code> rejects anonymous access.</p>',
  '<pre><code class="language-javascript">typeof b.middleware.attachUser; // "function"',
  'typeof b.middleware.requireAuth; // "function"</code></pre>',

  '<h2 id="middleware-aal-stepup">b.middleware.requireAal(options) / requireStepUp(options) <a class="anchor" href="#middleware-aal-stepup">#</a></h2>',
  '<p>Fresh-auth and assurance-level gates for sensitive routes. They compose with <code>b.auth.aal</code> and session auth-time metadata.</p>',
  '<pre><code class="language-javascript">typeof b.middleware.requireAal; // "function"',
  'typeof b.middleware.requireStepUp; // "function"</code></pre>',

  '<h2 id="middleware-dpop-mtls">b.middleware.dpop(options) / requireMtls(options) <a class="anchor" href="#middleware-dpop-mtls">#</a></h2>',
  '<p>Sender-constrained access-token gates. DPoP validates proof-of-possession headers; mTLS requires an authenticated client certificate context.</p>',
  '<pre><code class="language-javascript">typeof b.middleware.dpop; // "function"',
  'typeof b.middleware.requireMtls; // "function"</code></pre>',

  '<h2 id="middleware-quota">b.middleware.dailyByteQuota(options) <a class="anchor" href="#middleware-quota">#</a></h2>',
  '<p>Per-subject byte-budget gate for upload, export, and API abuse controls. The quota key is operator-defined so routes can budget by user, tenant, or token.</p>',
  '<pre><code class="language-javascript">typeof b.middleware.dailyByteQuota; // "function"</code></pre>',

  '<h2 id="middleware-host-allowlist">b.middleware.hostAllowlist(options) <a class="anchor" href="#middleware-host-allowlist">#</a></h2>',
  '<p>Host header allow-list defense for deployments behind proxies and CDNs. Refuses unknown authorities before route handlers see the request.</p>',
  '<pre><code class="language-javascript">var hostGate = b.middleware.hostAllowlist({ hosts: ["wiki.example.test"] });',
  'typeof hostGate; // "function"</code></pre>',

  '<h2 id="middleware-gpc">b.middleware.gpc(options) <a class="anchor" href="#middleware-gpc">#</a></h2>',
  '<p>Global Privacy Control reader that attaches the request privacy signal for downstream consent and processing gates.</p>',
  '<pre><code class="language-javascript">var gpc = b.middleware.gpc({});',
  'typeof gpc; // "function"</code></pre>',

  '<h2 id="middleware-age-bot">b.middleware.ageGate(options) / botDisclose(options) / botGuard(options) <a class="anchor" href="#middleware-age-bot">#</a></h2>',
  '<p>Policy middleware for age-restricted flows and automated-agent transparency. These gates attach or enforce operator policy without each route re-parsing headers.</p>',
  '<pre><code class="language-javascript">typeof b.middleware.ageGate; // "function"',
  'typeof b.middleware.botDisclose; // "function"',
  'typeof b.middleware.botGuard; // "function"</code></pre>',

  '<h2 id="middleware-ai-act">b.middleware.aiActDisclosure(options) <a class="anchor" href="#middleware-ai-act">#</a></h2>',
  '<p>EU AI Act disclosure middleware for routes that expose AI-generated or AI-mediated interactions.</p>',
  '<pre><code class="language-javascript">typeof b.middleware.aiActDisclosure; // "function"</code></pre>',

  '<h2 id="middleware-flags">b.middleware.flagContext(options) <a class="anchor" href="#middleware-flags">#</a></h2>',
  '<p>Attaches feature-flag evaluation context to the request so route handlers and templates read one consistent decision set.</p>',
  '<pre><code class="language-javascript">typeof b.middleware.flagContext; // "function"</code></pre>',

  '<h2 id="middleware-openapi-asyncapi">b.middleware.openapiServe(options) / asyncapiServe(options) <a class="anchor" href="#middleware-openapi-asyncapi">#</a></h2>',
  '<p>Serves generated OpenAPI and AsyncAPI documents from operator-provided specs with the same caching and security headers as the rest of the app.</p>',
  '<pre><code class="language-javascript">typeof b.middleware.openapiServe; // "function"',
  'typeof b.middleware.asyncapiServe; // "function"</code></pre>',

  '<h2 id="middleware-static-well-known">b.middleware.securityTxt(options) / assetlinks(options) / webAppManifest(options) <a class="anchor" href="#middleware-static-well-known">#</a></h2>',
  '<p>Well-known and browser-integration document middleware. Operators provide the contact, assetlinks, or manifest payload once and let the middleware serve the canonical route.</p>',
  '<pre><code class="language-javascript">typeof b.middleware.securityTxt; // "function"',
  'typeof b.middleware.assetlinks; // "function"',
  'typeof b.middleware.webAppManifest; // "function"</code></pre>',

  '<h2 id="middleware-assetlinks">b.middleware.assetlinks(options) <a class="anchor" href="#middleware-assetlinks">#</a></h2>',
  '<p>Serves Android Digital Asset Links JSON from an operator-owned route with stable content type and cache controls.</p>',
  '<pre><code class="language-javascript">typeof b.middleware.assetlinks; // "function"</code></pre>',

  '<h2 id="middleware-web-manifest">b.middleware.webAppManifest(options) <a class="anchor" href="#middleware-web-manifest">#</a></h2>',
  '<p>Serves a validated web app manifest document for installed-app surfaces and browser metadata endpoints.</p>',
  '<pre><code class="language-javascript">typeof b.middleware.webAppManifest; // "function"</code></pre>',

  '<h2 id="middleware-tracing">b.middleware.spanHttpServer(options) / tracePropagate(options) / traceLogCorrelation(options) <a class="anchor" href="#middleware-tracing">#</a></h2>',
  '<p>HTTP tracing middleware. It starts server spans, propagates trace context, and binds trace ids into logs without route-level boilerplate.</p>',
  '<pre><code class="language-javascript">typeof b.middleware.spanHttpServer; // "function"',
  'typeof b.middleware.tracePropagate; // "function"',
  'typeof b.middleware.traceLogCorrelation; // "function"</code></pre>',

  '<h2 id="middleware-trace-propagate">b.middleware.tracePropagate(options) <a class="anchor" href="#middleware-trace-propagate">#</a></h2>',
  '<p>Reads and writes trace context headers so downstream calls and logs stay correlated across service boundaries.</p>',
  '<pre><code class="language-javascript">typeof b.middleware.tracePropagate; // "function"</code></pre>',

  '<h2 id="middleware-trace-log-correlation">b.middleware.traceLogCorrelation(options) <a class="anchor" href="#middleware-trace-log-correlation">#</a></h2>',
  '<p>Attaches active trace identifiers to request-local logging context for incident reconstruction and distributed tracing.</p>',
  '<pre><code class="language-javascript">typeof b.middleware.traceLogCorrelation; // "function"</code></pre>',

  '<h2 id="middleware-asyncapi-serve">b.middleware.asyncapiServe(options) <a class="anchor" href="#middleware-asyncapi-serve">#</a></h2>',
  '<p>Serves an AsyncAPI document with the same static contract-serving posture as the OpenAPI middleware.</p>',
  '<pre><code class="language-javascript">typeof b.middleware.asyncapiServe; // "function"</code></pre>',

  '<h2 id="middleware-attach-user">b.middleware.attachUser(options) <a class="anchor" href="#middleware-attach-user">#</a></h2>',
  '<p>Attaches the authenticated user or actor record to the request before authorization middleware evaluates roles, scopes, or step-up requirements.</p>',
  '<pre><code class="language-javascript">typeof b.middleware.attachUser; // "function"</code></pre>',

  '<h2 id="middleware-require-content-type">b.middleware.requireContentType(options) <a class="anchor" href="#middleware-require-content-type">#</a></h2>',
  '<p>Rejects requests whose Content-Type does not match the route allowlist before body parsing or business logic runs.</p>',
  '<pre><code class="language-javascript">typeof b.middleware.requireContentType; // "function"</code></pre>',

  '<h2 id="middleware-require-mtls">b.middleware.requireMtls(options) <a class="anchor" href="#middleware-require-mtls">#</a></h2>',
  '<p>Requires a verified client certificate from the upstream TLS terminator or direct Node TLS request and exposes the peer identity to handlers.</p>',
  '<pre><code class="language-javascript">typeof b.middleware.requireMtls; // "function"</code></pre>',

  '<h2 id="middleware-require-step-up">b.middleware.requireStepUp(options) <a class="anchor" href="#middleware-require-step-up">#</a></h2>',
  '<p>Requires a fresh step-up authentication signal before privileged routes continue.</p>',
  '<pre><code class="language-javascript">typeof b.middleware.requireStepUp; // "function"</code></pre>',

  '<h2 id="middleware-bot-disclose">b.middleware.botDisclose(options) <a class="anchor" href="#middleware-bot-disclose">#</a></h2>',
  '<p>Adds bot-disclosure controls for routes where automated interaction must be visible to the user or downstream system.</p>',
  '<pre><code class="language-javascript">typeof b.middleware.botDisclose; // "function"</code></pre>',

  '<h2 id="middleware-bot-guard">b.middleware.botGuard(options) <a class="anchor" href="#middleware-bot-guard">#</a></h2>',
  '<p>Applies the bot policy gate for routes that distinguish human, automated, and unknown actors.</p>',
  '<pre><code class="language-javascript">typeof b.middleware.botGuard; // "function"</code></pre>',

  '<h2 id="middleware-tus">b.middleware.tusUpload(options) <a class="anchor" href="#middleware-tus">#</a></h2>',
  '<p>Resumable upload middleware for TUS-style clients. It centralizes upload offsets, body caps, and storage adapter wiring.</p>',
  '<pre><code class="language-javascript">typeof b.middleware.tusUpload; // "function"</code></pre>',

  '<h2 id="csp-report">b.middleware.cspReport(opts) <a class="anchor" href="#csp-report">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  audit:    object | boolean, // optional audit sink or false',
  '  onReport: function,         // optional operator hook',
  '  maxBytes: number,           // max accepted JSON body size',
  '}</code></pre>',
  '<p>Reporting-API endpoint for CSP, COEP, and network-error reports. The middleware bounds report size, parses JSON, emits an audit event, and hands the normalized report to an optional operator hook.</p>',
  '<pre><code class="language-javascript">var cspReport = b.middleware.cspReport({',
  '  maxBytes: b.constants.BYTES.kib(64),',
  '  onReport: function (report) { return report.type; },',
  '  audit: false,',
  '});',
  'typeof cspReport; // "function"</code></pre>',

  '<h2 id="validate-opts">Boot-time config validation</h2>',

  '<h3>b.validateOpts(config, allowedKeys, label) <a class="anchor" href="#validate-opts-call">#</a></h3>',
  '<p>Every framework primitive\'s <code>create()</code> validates its <code>opts</code> object against an explicit allow-list. A typo like <code>cors({ allowedOrigins: [] })</code> (the API expects <code>origins</code>) throws at boot with the offending key plus the full allowed-keys list, instead of silently weakening the operator\'s setup until a real request hits the wrong code path.</p>',
  '<pre><code class="language-javascript">// Operator-built primitive picks up the same diagnostic style:',
  'function myMiddleware(opts) {',
  '  b.validateOpts(opts, ["limit", "audit", "skipPaths"], "myMiddleware");',
  '  return function (_req, _res, next) { next(); };',
  '}',
  'var mw = myMiddleware({ limit: 100 });</code></pre>',

  '<h2 id="bearer-auth">b.middleware.bearerAuth(opts) <a class="anchor" href="#bearer-auth">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  verify:         async (token) => user | null,    // required',
  '  scheme:         string,                           // default: "Bearer"',
  '  realm:          string,                           // optional realm for WWW-Authenticate',
  '  errorMessage:   string,                           // default: "Bearer token required."',
  '  tokenAttachKey: string,                           // default: "bearerToken" — req[key] gets the raw token',
  '  userAttachKey:  string,                           // default: "user" — req[key] gets the verifier result',
  '  audit:          boolean,                          // default: true',
  '}</code></pre>',
  '<p>Extracts <code>Authorization: Bearer &lt;token&gt;</code>, runs the operator-supplied <code>verify(token)</code>, and attaches the result to <code>req.user</code>. Distinct from cookie-session <code>attachUser</code>. Missing-Authorization passes through (so the cookie path can take over); invalid / null / throw rejects with 401 + <code>WWW-Authenticate: Bearer error="invalid_token"</code> per RFC 6750 §3. Composes with <code>b.apiKey.verify</code> / <code>b.auth.jwt.verifyExternal</code> / operator-custom verifiers.</p>',
  '<pre><code class="language-javascript">// Operator-supplied verify() — example uses a literal allow-list for the harness.',
  'var bearer = b.middleware.bearerAuth({',
  '  verify: async function (token) {',
  '    return token === "good-token" ? { id: "u1", scopes: ["read"] } : null;',
  '  },',
  '});',
  '// bearer is a (req, res, next) function — wire via router.use("/api", bearer).',
  '// In production, verify() composes with b.auth.jwt.verifyExternal or operator-custom verifiers.',
  '</code></pre>',

  '<h2 id="fetch-metadata">b.middleware.fetchMetadata(opts) <a class="anchor" href="#fetch-metadata">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  allowSameSite:    boolean,                       // default: true',
  '  allowCrossSite:   boolean,                       // default: false',
  '  allowMissing:     boolean,                       // default: true (legacy browsers / curl pass through)',
  '  allowedDest:      [string],                      // ["empty","document"] — Sec-Fetch-Dest allowlist',
  '  allowedNavigate:  boolean,                       // default: true (typed URL / bookmark)',
  '  methods:          [string],                      // default: ["POST","PUT","DELETE","PATCH"]',
  '  audit:            boolean,                       // default: true',
  '}</code></pre>',
  '<p>Sec-Fetch-Site / Sec-Fetch-Mode / Sec-Fetch-Dest isolation primitive (web.dev fetch-metadata). On state-changing methods, refuses cross-site requests by default — second-line defense alongside CSRF tokens. Same-origin always passes; same-site configurable; navigations (typed URL / bookmark) pass through. Operators opt in cross-site for specific dest values (e.g. <code>allowedDest: ["empty"]</code> for AJAX-shaped requests). Missing fetch-metadata (legacy browsers, server-to-server) defers to other auth/CSRF layers per <code>allowMissing: true</code>.</p>',
  '<pre><code class="language-javascript">var fmGate = b.middleware.fetchMetadata({',
  '  allowedDest: ["empty"],',
  '});',
  '// fmGate is a (req, res, next) function — wire via router.use("/api", fmGate).',
  '</code></pre>',

].join("\n"),
};
