"use strict";

module.exports = {
  slug:  "network-crypto",
  title: "Network Crypto",
  body: [
  '<h1>Network Crypto</h1>',
  '<p>Cryptography that lives at the TLS layer or out on the wire. <code>b.mtlsCa</code> issues client certificates for service-to-service authentication; <code>b.pqcGate</code> inspects inbound TLS handshakes; <code>b.pqcAgent</code> pins the same posture on outbound HTTP.</p>',

  '<h2 id="mtls">mTLS CA</h2>',
  '<p><code>b.mtlsCa</code> is the operator\'s in-box certificate authority. It issues, rotates, and revokes mTLS leaf certificates for service-to-service authentication, signs them with a CA key that lives in the vault, and keeps the revocation list in <code>cert_revocations</code>. The CA primitive composes with a pluggable engine for the X.509 work; the framework ships a default pure-JS engine so nothing operator-side is required to start issuing certs.</p>',

  '<h3>b.mtlsCa.create(opts) <a class="anchor" href="#mtls-create">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  dataDir:          string,                   // required — where ca.crt + ca.key.enc land',
  '  vault:            vaultInstance,            // required — seals the CA private key',
  '  paths:            { ca?, leaf? },           // optional — file path overrides',
  '  caKeySealedMode:  "auto" | "required" | "disabled",  // default: "auto"',
  '  generation:       number,                   // default: 1 — bump to rotate to a new CA',
  '  engine:           engineInstance,           // optional — defaults to b.mtlsEngine',
  '}</code></pre>',
  '<p>Returns a CA instance with <code>initCA()</code> (idempotent — generates if missing), <code>signClientCert(opts)</code>, <code>revoke(certFingerprint)</code>, <code>status()</code>. <code>caKeySealedMode: "required"</code> refuses to write the plaintext PEM to disk — the CA private key only ever lives in <code>ca.key.enc</code> sealed under the vault. <code>"auto"</code> picks whichever form exists. <code>"disabled"</code> forces plaintext for environments without a vault passphrase. The pluggable engine lets operators swap to an HSM-backed signer or an externally-managed CA without rewriting consumers.</p>',
  '<pre><code class="language-javascript">// Factory shape — live boot needs a writable dataDir + initialized vault.',
  '// var ca = b.mtlsCa.create({',
  '//   dataDir:    "./data/mtls",',
  '//   vault:      b.vault,',
  '//   sealedMode: "required",',
  '// });',
  '// await ca.initCA();',
  '// var leaf = await ca.signClientCert({ subject: "client-1", days: 365 });',
  'b.mtlsCa.create;</code></pre>',

  '<h3 id="mtls-engine">Bundled engine <a class="anchor" href="#mtls-engine">#</a></h3>',
  '<p><code>b.mtlsEngine</code> is the default engine wired into <code>b.mtlsCa</code>. Uses the vendored <a href="https://github.com/PeculiarVentures/x509">@peculiar/x509</a> + <a href="https://github.com/PeculiarVentures/PKI.js">pkijs</a> stack — no openssl CLI, no shell-out, just <code>node:crypto.webcrypto</code>. Algorithm envelope:</p>',
  '<ul>',
  '  <li>CA + leaf signatures: ECDSA P-384, SHA-384</li>',
  '  <li>PKCS#12 key + cert bags: PBES2 + AES-256-CBC, PBKDF2-HMAC-SHA-512, 2,000,000 iterations</li>',
  '  <li>PKCS#12 outer integrity: HMAC-SHA-512, 2,000,000 iterations</li>',
  '  <li>CA validity: 10 years; leaf default: 365 days (overridable per call)</li>',
  '</ul>',
  '<p>Cert sigs stay classical ECDSA-P384 because no shipping browser or OS cert store will verify a post-quantum signature on a client cert today. Swap atomically when that lands; bump <code>generation</code> on the same release so <code>b.mtlsCa.status</code> flags legacy CAs as legacy. Operators with custom requirements (HSM-backed signing, hybrid PQ algorithms once supported, externally-managed CA) pass their own engine via <code>b.mtlsCa.create({ engine })</code>.</p>',

  '<h3 id="mtls-cli">CLI surface <a class="anchor" href="#mtls-cli">#</a></h3>',
  '<pre><code class="language-bash"># Inspect CA state on disk',
  'blamejs mtls status --data-dir ./data',
  '',
  '# Print the CA cert PEM (operators paste this into client truststores)',
  'blamejs mtls show-cert --data-dir ./data',
  '',
  '# Generate the CA (uses the bundled engine, seals the key under the vault)',
  'BLAMEJS_VAULT_PASSPHRASE="..." blamejs mtls init \\',
  '  --data-dir   ./data \\',
  '  --sealed-mode required',
  '',
  '# Issue a leaf client cert',
  'blamejs mtls issue --data-dir ./data --subject "client-1" --days 365',
  '',
  '# Issue + package as PKCS#12 for browser / OS-keychain import',
  'blamejs mtls issue-p12 \\',
  '  --data-dir ./data \\',
  '  --subject  "client-1" \\',
  '  --password "$P12_PASSPHRASE" \\',
  '  --out      ./client-1.p12</code></pre>',
  '<p><code>--sealed-mode required</code> seals the CA private key under the vault before writing it to disk — the plaintext PEM never touches the filesystem. <code>auto</code> (default) loads whichever form exists; <code>disabled</code> forces plaintext-on-disk for environments without a vault passphrase.</p>',

  '<h2 id="pqc-gate">PQC gate (inbound)</h2>',

  '<h3>b.pqcGate.create(opts) <a class="anchor" href="#pqc-gate-create">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  internalPort:         number,               // required — backend app listens here',
  '  internalHost:         string,               // default: "127.0.0.1"',
  '  bypass:               [CIDR string],        // default: DEFAULT_BYPASS',
  '  clientHelloTimeoutMs: number,               // default: ms — abort hung handshakes',
  '  maxClientHelloBytes:  number,               // default: bytes — DoS guard',
  '  log:                  logger,               // optional — b.log instance',
  '  // test-only injection points (not part of the supported public API):',
  '  _connect:             function,             // override net.connect',
  '  _server:              function,             // override net.createServer',
  '  _setTimeout:          function,             // override global setTimeout',
  '  _clearTimeout:        function,             // override global clearTimeout',
  '}</code></pre>',
  '<p>Inspects the TLS ClientHello at the TCP level and refuses connections that don\'t advertise an acceptable post-quantum or hybrid key-exchange. Operators rolling out PQ readiness behind a feature flag run the gate in <em>warn-only</em> first, watch the audit chain for clients that would have been rejected, then flip to <em>enforce</em> once their fleet has caught up. The framework ships <code>b.pqcGate.PQC_GROUP_IDS</code> as the canonical hybrid-group ID list.</p>',
  '<pre><code class="language-javascript">// Factory + listener shape — live mode binds two ports.',
  '// var gate = b.pqcGate.create({',
  '//   internalPort: 3001, externalPort: 3000,',
  '//   mode: "warn", audit: b.audit,',
  '// });',
  '// await gate.listen();',
  'b.pqcGate.create;',
  'b.pqcGate.PQC_GROUP_IDS;   // array of canonical PQC + hybrid group identifiers</code></pre>',

  '<h2 id="pqc-agent">PQC agent (outbound)</h2>',

  '<h3>b.pqcAgent.create(opts?) <a class="anchor" href="#pqc-agent-create">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  keepAlive:           boolean,               // default: true',
  '  minVersion:          string,                // default: "TLSv1.3"',
  '  ecdhCurve:           string,                // default: framework PQC-hybrid preference (SecP384r1MLKEM1024:X25519MLKEM768:SecP256r1MLKEM768)',
  '  allowOperatorGroups: boolean,               // default: false — when true, ecdhCurve may include any IANA TLS Supported Group (operator opt-in)',
  '  // ... other tls.Agent options pass through',
  '}</code></pre>',
  '<p>The gate covers <em>inbound</em> connections; this primitive covers <em>outbound</em>. Returns an <code>https.Agent</code> subclass that pins the TLS minimum version + curve list to PQ-acceptable values, so app code that does <code>b.httpClient.request({ url, agent })</code> against an upstream gets the same posture the inbound gate enforces. The framework also ships <code>b.pqcAgent.agent</code> as a singleton with default opts and <code>b.pqcAgent.enforced</code> as the strict-mode singleton. The default preference advertises three PQC hybrids — <code>SecP384r1MLKEM1024</code> (CNSA-2.0-aligned key strength), <code>X25519MLKEM768</code> (RFC 9794 codepoint 0x11EC, the IETF/Cloudflare/Chrome interop default), and <code>SecP256r1MLKEM768</code> (RFC 9794 codepoint 0x11EB, NIST-curve fallback for FIPS-mandated peers that refuse X25519). Operators wiring deliberate downgrades to a non-PQC peer pass <code>allowOperatorGroups: true</code> alongside an <code>ecdhCurve</code> drawn from the IANA registry (e.g. <code>"X25519"</code> or <code>"secp384r1"</code>); each accepted operator-supplied group emits a <code>pqcagent.operator_group.accepted</code> audit row so the deviation from the framework default is visible.</p>',
  '<pre><code class="language-javascript">var agent = b.pqcAgent.create({ keepAlive: true });',
  '// Pass via b.httpClient.request({ url, agent }) — PQ posture pinned per-call.',
  'agent;',
  '',
  'var defaults = b.pqcAgent.agent;       // shared default-mode agent',
  'var strict = b.pqcAgent.enforced;       // shared strict-mode agent',
  '',
  '// Operator opt-in to a non-default group (audited):',
  'var legacy = b.pqcAgent.create({',
  '  ecdhCurve:           "X25519",',
  '  allowOperatorGroups: true,',
  '});',
  'legacy;</code></pre>',

  '<h2 id="acme">b.acme.create(opts) <a class="anchor" href="#acme">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  directory:     string,                     // required — operator-supplied RFC 8555 directory URL (no framework default)',
  '  accountKey:    KeyObject | { privatePem }, // required — P-256 EC keypair (RFC 8555 §6.2 ES256)',
  '  audit:         auditInstance,              // optional — emits acme.* audit rows',
  '  contact:       ["mailto:..."],             // optional — operator contact URIs',
  '  timeoutMs:     number,                     // optional — per-request timeout',
  '  pollIntervalMs: number,                    // optional — order-status poll cadence',
  '  pollMaxMs:     number,                     // optional — max wait for order → valid',
  '  maxBytes:      number,                     // optional — per-response cap',
  '}</code></pre>',
  '<p>RFC 8555 ACME client + RFC 9773 ACME Renewal Information. The framework refuses to default the directory URL — every operator picks their CA explicitly (Let\'s Encrypt prod / Pebble in tests / any RFC 8555-compliant directory). JWS signing uses ES256 (P-256 + SHA-256) per §6.2; the framework\'s audit chain stays PQC-signed regardless of the wire algorithm. The returned object exposes <code>fetchDirectory()</code> / <code>newAccount()</code> / <code>newOrder({ identifiers })</code> / <code>finalize(order, csrDer)</code> / <code>retrieveCert(order)</code> for the issuance flow, plus <code>fetchAri({ certPem })</code> + <code>renewIfDue({ certPem })</code> for the RFC 9773 renewal-information endpoint. <code>renewIfDue</code> consults the directory\'s <code>renewalInfo</code> URL with the ACMECertID derived from the cert\'s AuthorityKeyIdentifier + serial, parses <code>{ suggestedWindow: { start, end }, explanationURL? }</code>, and returns <code>{ shouldRenew, reason, ari }</code> with <code>reason</code> ∈ <code>"before-window" | "in-window" | "past-window"</code>. Compose with <code>b.network.tls.expiryMonitor</code> for the trigger; the operator\'s scheduler invokes <code>renewIfDue</code> on each tick and only re-runs the issuance flow when <code>shouldRenew === true</code>. <code>keyAuthorization(token)</code> returns the HTTP-01 / DNS-01 challenge response (<code>token.thumbprint</code> per RFC 8555 §8.1) for the operator\'s challenge handler. CA/B SC-081 ratified the 47-day cert lifetime ceiling; ARI lets the CA dictate when the operator should renew rather than the operator guessing a fixed cadence.</p>',
  '<pre><code class="language-javascript">// var nodeCrypto = require("node:crypto");',
  '// var k = nodeCrypto.generateKeyPairSync("ec", { namedCurve: "P-256" });',
  '// var acme = b.acme.create({',
  '//   directory:  "https://acme-staging-v02.api.letsencrypt.org/directory",',
  '//   accountKey: k.privateKey,',
  '//   audit:      b.audit,',
  '//   contact:    ["mailto:ops@example.com"],',
  '// });',
  '//',
  '// Inspect the public JWK + a challenge keyAuthorization shape.',
  '// var jwk = acme.publicJwk();',
  '// jwk.kty === "EC" && jwk.crv === "P-256"',
  '// acme.keyAuthorization("token-from-challenge");',
  '// "token-from-challenge.<base64url-thumbprint>"',
  '//',
  '// At renewal time — RFC 9773 ARI verdict (no live network call shown).',
  '// var verdict = await acme.renewIfDue({ certPem });',
  '// verdict.shouldRenew === false && verdict.reason === "before-window"',
  'typeof b.acme.create; // "function"</code></pre>',

  '<h2 id="tls-pinset-drift">b.network.tls.pinsetDriftMonitor(opts) <a class="anchor" href="#tls-pinset-drift">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  intervalMs: number,   // required positive interval',
  '  audit:      boolean,  // default: true',
  '  onDrift:    function, // optional operator alert hook',
  '}</code></pre>',
  '<p>Periodically compares the active TLS trust-store fingerprint set against the boot-captured baseline and emits audit / observability evidence when a CA is added or removed.</p>',
  '<pre><code class="language-javascript">b.network.tls.captureBaselineFingerprints();',
  'var pinsetMonitor = b.network.tls.pinsetDriftMonitor({',
  '  intervalMs: b.constants.TIME.minutes(15),',
  '  audit: false,',
  '});',
  'pinsetMonitor.stop();</code></pre>',

  '<h2 id="tls-build-options">b.network.tls.buildOptions(opts) <a class="anchor" href="#tls-build-options">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  ecdhCurve:  string,                    // optional — `:`-joined named groups (Node alias)',
  '  groups:     string | string[],         // optional — RFC 9794 named groups; wins over ecdhCurve',
  '  cert:       string | Buffer | array,   // optional — client cert PEM(s)',
  '  key:        string | Buffer | array,   // optional — client key PEM(s)',
  '  ca:         string | Buffer | array,   // optional — trust-anchor PEM(s); arrays join with \\n',
  '  minVersion: "TLSv1.3",                 // default + only accepted value',
  '  sni:        string,                    // optional — servername override',
  '}</code></pre>',
  '<p>Assembles a plain options object suitable for <code>tls.connect</code>, <code>new https.Agent(...)</code>, or <code>https.request</code>, pre-populated with the framework\'s PQC group preference and TLS-1.3 floor. Operators that build their own outbound transport — a custom <code>https.Agent</code>, a raw <code>tls.connect</code> for non-HTTP protocol clients (LDAP, IMAP, AMQP) — route through this primitive so the same posture lands everywhere instead of hand-assembling the same opts at every call site. Caller may narrow the group list (drop a group, keep the rest) but cannot widen it; every requested group must appear in the active framework preferred list. <code>minVersion</code> is locked to <code>"TLSv1.3"</code> — anything else throws <code>NetworkTlsError("network-tls/bad-tls-options")</code>. The <code>ca</code> input accepts a PEM string, Buffer, or array of either; arrays are concatenated with <code>\\n</code> so Node\'s TLS layer parses every CERTIFICATE block.</p>',
  '<pre><code class="language-javascript">// var tlsOpts = b.network.tls.buildOptions({',
  '//   cert: clientCertPem,',
  '//   key:  clientKeyPem,',
  '//   ca:   [internalRootPem, partnerRootPem],',
  '//   sni:  "api.partner.example",',
  '// });',
  '// tlsOpts.minVersion === "TLSv1.3"',
  '// tlsOpts.groups       contains the framework PQC preference list',
  '// var sock = require("node:tls").connect(443, "api.partner.example", tlsOpts);',
  'typeof b.network.tls.buildOptions; // "function"</code></pre>',

  '<h2 id="hpke">RFC 9180 HPKE</h2>',
  '<p><code>b.crypto.hpke</code> implements RFC 9180 Hybrid Public-Key Encryption with the framework\'s PQC-first suite: ML-KEM-1024 + HKDF-SHA3-512 + ChaCha20-Poly1305. Operators wiring HPKE into application protocols (sealed message envelopes between named peers, encrypted-claim attribute statements, end-to-end encrypted notifications) get one-shot <code>seal</code> / <code>open</code> with suite-id binding (RFC 9180 §5.1) so a key derived under HPKE cannot be silently substituted under another suite.</p>',

  '<h3>b.crypto.hpke.seal(opts) / b.crypto.hpke.open(opts) <a class="anchor" href="#hpke-seal-open">#</a></h3>',
  '<pre><code class="language-javascript">// seal opts',
  '{',
  '  recipientPubKey: string,         // ML-KEM-1024 PEM',
  '  plaintext:       string|Buffer,',
  '  info:            string|Buffer,  // RFC 9180 §5.1 application context',
  '  aad:             string|Buffer,  // per-message AEAD AAD',
  '}',
  '',
  '// open opts',
  '{',
  '  privateKey:  string,             // ML-KEM-1024 private PEM',
  '  enc:         Buffer,             // KEM ciphertext from seal()',
  '  ciphertext:  Buffer,             // AEAD ciphertext from seal()',
  '  info:        string|Buffer,      // MUST match the seal() info',
  '  aad:         string|Buffer,      // MUST match the seal() aad',
  '}</code></pre>',
  '<p><code>seal</code> returns <code>{ enc, ciphertext }</code>. <code>enc</code> carries the KEM encapsulation; <code>ciphertext</code> carries the AEAD output. Both must travel together. <code>info</code> binds the derived key to an application context (so a key for "session-X" cannot decrypt "session-Y" even when the same recipient keypair is used); <code>aad</code> binds per-message authenticated data (transport metadata, sender identity, sequence numbers). Mismatched <code>info</code> or <code>aad</code> on <code>open</code> throws <code>HpkeError</code> with code <code>AEAD_DECRYPT_FAILED</code>. The classical HPKE suites in RFC 9180 §7 (DHKEM with X25519 / P-256 / P-384 / P-521 + AES-GCM) are NOT exposed — the framework\'s PQC-first defaults rule out classical-only key agreement and AES-GCM. Cross-system interop with peers that need the IETF / Cloudflare / Chrome TLS-1.3 hybrid uses <code>b.crypto.encryptMlkem768X25519</code> instead.</p>',
  '<pre><code class="language-javascript">var pair = b.crypto.hpke.generateKeyPair();',
  'var sealed = b.crypto.hpke.seal({',
  '  recipientPubKey: pair.publicKey,',
  '  plaintext:       "secret payload",',
  '  info:            "tenant=acme,channel=billing",',
  '  aad:             "msg-id=42",',
  '});',
  '// Send { enc: sealed.enc, ciphertext: sealed.ciphertext } to the recipient.',
  'var pt = b.crypto.hpke.open({',
  '  privateKey: pair.privateKey,',
  '  enc:        sealed.enc,',
  '  ciphertext: sealed.ciphertext,',
  '  info:       "tenant=acme,channel=billing",',
  '  aad:        "msg-id=42",',
  '});',
  '// pt is a Buffer — pt.toString("utf8") === "secret payload"',
  'b.crypto.hpke.seal;</code></pre>',

  '<h2 id="tls-exporter">RFC 9266 TLS-Exporter channel binding</h2>',
  '<p><code>b.tlsExporter</code> implements RFC 9266 channel-binding extraction over TLS 1.3 sockets (RFC 8446 §7.5 keying-material exporter). Bind authentication tokens (session cookies, bearer tokens, DPoP-style proofs, mTLS-derived headers) to the underlying TLS session so a captured token cannot be replayed across a different TLS connection.</p>',

  '<h3>b.tlsExporter.fromSocket(socket, opts) <a class="anchor" href="#tls-exporter-fromsocket">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  label:    string,    // default: "EXPORTER-Channel-Binding" (RFC 9266 §4)',
  '  length:   number,    // default: 32 bytes; range 16..255',
  '  context:  Buffer,    // default: null (RFC 8446 §7.5 "no context")',
  '}</code></pre>',
  '<p>Returns a <code>Buffer</code> of the requested length. Pass either a <code>TLSSocket</code> directly OR a Node http(s) request whose <code>.socket</code> property is the TLSSocket (the helper auto-resolves). Throws <code>TlsExporterError</code> with code <code>NOT_TLS</code> when the socket is plaintext and <code>NOT_TLS_1_3</code> when the active protocol is TLS 1.2 — RFC 9266 §4 only defines channel-binding semantics for TLS 1.3. <code>bindToken(socket, token)</code> + <code>verifyTokenBinding(socket, token, claimedBinding)</code> compose the exporter with a token to produce a session-bound hex string suitable for storage alongside the token; the verify side runs through <code>b.crypto.timingSafeEqual</code>.</p>',
  '<pre><code class="language-javascript">// In a request handler — bind the issued session cookie to the TLS session.',
  '// function issueSession(req, res) {',
  '//   var token = b.crypto.generateToken(32);',
  '//   var binding = b.tlsExporter.bindToken(req, token);',
  '//   // Persist (token, binding); set Cookie: session=<token>',
  '// }',
  '// On the next request — refuse if the binding does not match the active session.',
  '// function requireBoundSession(req, res, next) {',
  '//   var token = req.cookies && req.cookies.session;',
  '//   var stored = lookupBindingForToken(token);    // operator storage',
  '//   if (!b.tlsExporter.verifyTokenBinding(req, token, stored)) {',
  '//     res.statusCode = 401; res.end("session-replayed-across-tls"); return;',
  '//   }',
  '//   next();',
  '// }',
  'b.tlsExporter.fromSocket;</code></pre>',

  '<h3>b.tlsExporter.bindToken(socket, token) <a class="anchor" href="#tls-exporter-bindtoken">#</a></h3>',
  '<pre><code class="language-javascript">// signature',
  '{',
  '  socket:  TLSSocket | http(s) request,   // resolves the underlying TLS socket',
  '  token:   string | Buffer,                // any opaque application token',
  '}',
  '// returns: hex string (SHA3-512 of label || exporter || token)</code></pre>',
  '<p>Composes <code>fromSocket</code> with an opaque application token (session ID, bearer token, DPoP-style proof material) to produce a deterministic session-bound binding. The hash absorbs a framework-internal label (<code>"blamejs/tls-exporter/bind/v1"</code>) so the same exporter + token pair does not collide with hashes produced by any other framework primitive. Operators store the binding alongside the token in their session table; on the next request <code>verifyTokenBinding</code> compares the live exporter against the stored value.</p>',
  '<pre><code class="language-javascript">// var token = b.crypto.generateToken(32);',
  '// var binding = b.tlsExporter.bindToken(req, token);',
  '// // Persist (token, binding) in the session table.',
  'b.tlsExporter.bindToken;</code></pre>',

  '<h3>b.tlsExporter.verifyTokenBinding(socket, token, claimedBinding) <a class="anchor" href="#tls-exporter-verifytokenbinding">#</a></h3>',
  '<pre><code class="language-javascript">// signature',
  '{',
  '  socket:           TLSSocket | http(s) request,',
  '  token:            string | Buffer,',
  '  claimedBinding:   string,             // hex string from bindToken at issue time',
  '}',
  '// returns: boolean (constant-time compare via b.crypto.timingSafeEqual)</code></pre>',
  '<p>Recomputes the binding for the live TLS session and compares against <code>claimedBinding</code> in constant time. Returns <code>false</code> when the binding does not match (token replayed across a different TLS session, or token tampered) — does NOT throw, since binding-mismatch is a normal request-time outcome an operator inspects without try/catch. Throws <code>TlsExporterError</code> only on bad input or non-TLS sockets.</p>',
  '<pre><code class="language-javascript">// var stored = lookupBindingForToken(token);',
  '// if (!b.tlsExporter.verifyTokenBinding(req, token, stored)) {',
  '//   res.statusCode = 401; res.end("session-replayed-across-tls"); return;',
  '// }',
  'b.tlsExporter.verifyTokenBinding;</code></pre>',

  '<h2 id="ct-inclusion">RFC 9162 CT v2 inclusion-proof verification</h2>',
  '<p><code>b.network.tls.ct.verifyInclusion</code> + <code>b.network.tls.ct.verifyConsistency</code> close the CT loop the existing <code>inspect</code> / <code>parseScts</code> / <code>verifyScts</code> / <code>requireScts</code> primitives opened. SCT verification proves the log <em>promised</em> to publish a cert; inclusion-proof verification proves the log <em>kept</em> that promise (the leaf actually sits in the tree the log signed). Operators auditing a CT log\'s honesty fetch the inclusion proof via RFC 9162 §6.7 <code>get-proof-by-hash</code>, the signed tree head via §6.4 <code>get-sth</code>, and feed both into the verifier.</p>',

  '<h3>b.network.tls.ct.verifyInclusion(opts) <a class="anchor" href="#ct-verifyinclusion">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  sct:              { logIdHex, timestamp, signedEntryDer? },  // from parseScts',
  '  leafCertificate:  Buffer,        // leaf cert DER (when signedEntryDer absent the framework strips the SCT extension)',
  '  leafIndex:        number,        // 0-based position from get-proof-by-hash',
  '  auditPath:        [Buffer],      // 32-byte sibling hashes, bottom-up',
  '  sthFromLog: {',
  '    treeSize: number,              // signed-tree-head tree size',
  '    rootHash: Buffer | hexString,  // signed-tree-head root hash',
  '  },',
  '  consistency: {                   // optional — pin against an earlier STH',
  '    firstSize:  number,',
  '    firstRoot:  Buffer | hexString,',
  '    proof:      [Buffer],          // from get-sth-consistency',
  '  },',
  '}</code></pre>',
  '<p>Returns <code>{ valid: true, computedRoot, leafHash, consistency? }</code> on success or <code>{ valid: false, reason, ... }</code> on failure. The Merkle-tree algorithm is RFC 9162 §2.1 (SHA-256 with leaf prefix 0x00 / inner prefix 0x01); SHA-256 is wire-defined by every public CT log, so the framework keeps the algorithm here even though every other content-integrity primitive defaults to SHA3-512. Compose with <code>verifyScts</code> + <code>requireScts</code> for the full chain: SCT signature → inclusion proof → consistency proof.</p>',
  '<pre><code class="language-javascript">// Operator fetches the inclusion proof + STH from the CT log\'s HTTP API:',
  '//   GET /ct/v1/get-proof-by-hash?hash=<base64>&tree_size=<sth.tree_size>',
  '//   GET /ct/v1/get-sth',
  '// var verdict = b.network.tls.ct.verifyInclusion({',
  '//   sct:              parsedScts[0],',
  '//   leafCertificate:  peerCert.raw,',
  '//   leafIndex:        proofResp.leaf_index,',
  '//   auditPath:        proofResp.audit_path.map(b64 => Buffer.from(b64, "base64")),',
  '//   sthFromLog: { treeSize: sthResp.tree_size, rootHash: Buffer.from(sthResp.sha256_root_hash, "base64") },',
  '// });',
  'b.network.tls.ct.verifyInclusion;</code></pre>',

  '<h3>b.network.tls.ct.verifyConsistency(opts) <a class="anchor" href="#ct-verifyconsistency">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  firstSize:   number,             // earlier STH tree size',
  '  firstRoot:   Buffer | hexString, // earlier STH root',
  '  secondSize:  number,             // later STH tree size (>= firstSize)',
  '  secondRoot:  Buffer | hexString, // later STH root',
  '  proof:       [Buffer],           // from get-sth-consistency',
  '}</code></pre>',
  '<p>Returns <code>{ valid: true, computedRoot }</code> on success or <code>{ valid: false, reason }</code> on failure. Run on every fresh STH fetch — a passing consistency proof against the operator\'s last-pinned STH is the live signal that the log is append-only.</p>',
  '<pre><code class="language-javascript">// var verdict = b.network.tls.ct.verifyConsistency({',
  '//   firstSize:  pinned.treeSize,',
  '//   firstRoot:  pinned.rootHash,',
  '//   secondSize: latest.tree_size,',
  '//   secondRoot: Buffer.from(latest.sha256_root_hash, "base64"),',
  '//   proof:      consResp.consistency.map(b64 => Buffer.from(b64, "base64")),',
  '// });',
  'b.network.tls.ct.verifyConsistency;</code></pre>',
].join("\n"),
};
