"use strict";

module.exports = {
  slug:  "network-crypto",
  title: "Network Crypto",
  body: [
  '<h1>Network Crypto</h1>',
  '<p>Cryptography that lives at the TLS layer or out on the wire. <code>b.mtlsCa</code> issues client certificates for service-to-service authentication; <code>b.pqcGate</code> inspects inbound TLS handshakes; <code>b.pqcAgent</code> pins the same posture on outbound HTTP.</p>',

  '<h2 id="mtls">mTLS CA <a class="anchor" href="#mtls">#</a></h2>',
  '<p><code>b.mtlsCa</code> is the operator\'s in-box certificate authority. It issues, rotates, and revokes mTLS leaf certificates for service-to-service authentication, signs them with a CA key that lives in the vault, and keeps the revocation list in <code>cert_revocations</code>. The CA primitive composes with a pluggable engine for the X.509 work; the framework ships a default pure-JS engine so nothing operator-side is required to start issuing certs.</p>',

  '<h3 id="mtls-engine">Bundled engine <a class="anchor" href="#mtls-engine">#</a></h3>',
  '<p><code>b.mtlsEngine</code> is the default engine wired into <code>b.mtlsCa</code>. Uses the vendored <a href="https://github.com/PeculiarVentures/x509">@peculiar/x509</a> + <a href="https://github.com/PeculiarVentures/PKI.js">pkijs</a> stack — no openssl CLI, no shell-out, just <code>node:crypto.webcrypto</code>. Algorithm envelope:</p>',
  '<ul>',
  '  <li>CA + leaf signatures: ECDSA P-384, SHA-384</li>',
  '  <li>PKCS#12 key + cert bags: PBES2 + AES-256-CBC, PBKDF2-HMAC-SHA-512, 2,000,000 iterations</li>',
  '  <li>PKCS#12 outer integrity: HMAC-SHA-512, 2,000,000 iterations</li>',
  '  <li>CA validity: 10 years; leaf default: 365 days (overridable per call)</li>',
  '</ul>',
  '<p>Cert sigs stay classical ECDSA-P384 because no shipping browser or OS cert store will verify a post-quantum signature on a client cert today. Swap atomically when that lands; bump <code>generation</code> on the same release so <code>b.mtlsCa.status</code> flags legacy CAs as legacy. Operators with custom requirements (HSM-backed signing, hybrid PQ algorithms once supported, externally-managed CA) pass their own engine via <code>b.mtlsCa.create({ engine })</code>.</p>',

  '<h3 id="mtls-cli">CLI surface <a class="anchor" href="#mtls-cli">#</a></h3>',
  '<pre><code class="language-bash"># Inspect CA state on disk',
  'blamejs mtls status --data-dir ./data',
  '',
  '# Print the CA cert PEM (operators paste this into client truststores)',
  'blamejs mtls show-cert --data-dir ./data',
  '',
  '# Generate the CA (uses the bundled engine, seals the key under the vault)',
  'BLAMEJS_VAULT_PASSPHRASE="..." blamejs mtls init \\',
  '  --data-dir   ./data \\',
  '  --sealed-mode required',
  '',
  '# Issue a leaf client cert',
  'blamejs mtls issue --data-dir ./data --subject "client-1" --days 365',
  '',
  '# Issue + package as PKCS#12 for browser / OS-keychain import',
  'blamejs mtls issue-p12 \\',
  '  --data-dir ./data \\',
  '  --subject  "client-1" \\',
  '  --password "$P12_PASSPHRASE" \\',
  '  --out      ./client-1.p12</code></pre>',
  '<p><code>--sealed-mode required</code> seals the CA private key under the vault before writing it to disk — the plaintext PEM never touches the filesystem. <code>auto</code> (default) loads whichever form exists; <code>disabled</code> forces plaintext-on-disk for environments without a vault passphrase.</p>',

  '<h2 id="pqc-gate">PQC gate (inbound) <a class="anchor" href="#pqc-gate">#</a></h2>',
  '<p><code>b.pqcGate</code> inspects the TLS ClientHello at the TCP level and refuses connections that don\'t advertise an acceptable post-quantum or hybrid key-exchange. Operators rolling out PQ readiness behind a feature flag can run the gate in <em>warn-only</em> first, watch the audit chain for clients that would have been rejected, and flip to <em>enforce</em> once their fleet has caught up.</p>',
  '<pre><code class="language-javascript">var gate = b.pqcGate.create({',
  '  internalPort:  3001,             // app listens here; gate listens externally',
  '  externalPort:  3000,',
  '  mode:          "warn",           // or "enforce"',
  '  acceptable:    ["x25519+kyber768", "x25519+mlkem768"],',
  '  audit:         b.audit,',
  '});',
  'await gate.listen();</code></pre>',

  '<h2 id="pqc-agent">PQC agent (outbound) <a class="anchor" href="#pqc-agent">#</a></h2>',
  '<p>The gate covers <em>inbound</em> connections; <code>b.pqcAgent</code> covers <em>outbound</em>. It\'s an <code>https.Agent</code> subclass that pins the TLS minimum version + curve list to PQ-acceptable values, so app code that does <code>b.httpClient.request({ url })</code> against an upstream gets the same posture the inbound gate enforces. Operators with a fleet that\'s mostly modernized but still talks to a legacy straggler pass <code>{ allowFallback: true }</code> per call and audit the rare exception, instead of weakening the global default.</p>',
  '<pre><code class="language-javascript">var agent = b.pqcAgent.create({ keepAlive: true });',
  '',
  'await b.httpClient.request({',
  '  url:    "https://upstream.example.com/api",',
  '  agent:  agent,    // PQ posture pinned',
  '  // ...',
  '});</code></pre>',
].join("\n"),
};
