"use strict";

module.exports = {
  slug:  "notifications",
  title: "Notifications",
  body: [
  '<h1>Notifications</h1>',
  '<p><code>b.notify</code> is the generic dispatcher for any channel an app might send to: log, Slack, custom HTTP webhook, push, SMS. <code>b.events</code> is the framework-internal event bus that primitives use to surface lifecycle events for the operator to subscribe to.</p>',

  '<h2 id="notify">b.notify <a class="anchor" href="#notify">#</a></h2>',
  '<p>A channel entry is either a <em>Transport</em> directly (<code>{ name, send }</code>) or a config wrapper (<code>{ transport, retry?, breaker?, timeoutMs?, serialize? }</code>). The dispatcher owns retry, circuit breaking, timeout, redaction, and audit around the transport\'s <code>send</code>.</p>',
  '<h3>b.notify.create(opts)</h3>',
  '<pre><code class="language-javascript">{',
  '  channels:          { [name]: Transport | ChannelConfig },',
  '                                            // required: true',
  '  audit:             AuditTap,              // default: null',
  '  auditSuccess:      boolean,               // default: true',
  '  auditFailures:     boolean,               // default: true',
  '  redact:            (value) =&gt; value,      // default: b.redact.redact',
  '  defaultTimeoutMs:  number,                // default: C.TIME.seconds(30)',
  '  defaultRetry:      RetryOpts,             // default: b.retry.DEFAULT_RETRY',
  '  defaultBreaker:    BreakerOpts,           // default: null — opt-in per channel',
  '  queue:             QueueInstance,         // default: null — async dispatch backing',
  '  clock:             () =&gt; number,          // default: Date.now',
  '}',
  '',
  '// Transport contract:',
  '{',
  '  name:    string,',
  '  send:    async (message, sendOpts) =&gt; { id?, status, attempts?, durationMs? },',
  '}',
  '',
  '// ChannelConfig wrapping a transport with per-channel overrides:',
  '{',
  '  transport:  Transport,                    // required: true',
  '  retry:      RetryOpts,                    // default: defaultRetry',
  '  breaker:    BreakerOpts,                  // default: defaultBreaker',
  '  timeoutMs:  number,                       // default: defaultTimeoutMs',
  '  serialize:  boolean,                      // default: false — Mutex around send',
  '}</code></pre>',
  '<pre><code class="language-javascript">// var notify = b.notify.create({',
  '//   channels: {',
  '//     log:    b.notify.transports.log(),',
  '//     slack:  b.notify.transports.httpJson({',
  '//       url:   env("SLACK_WEBHOOK_URL"),',
  '//       shape: function (msg) { return { text: msg.text }; },',
  '//     }),',
  '//     sms:    {',
  '//       transport: operatorTwilioShim,             // operator-supplied { name, send }',
  '//       retry:     { maxAttempts: 3 },             // per-channel override',
  '//       breaker:   { failureThreshold: 5, cooldownMs: C.TIME.seconds(30) },',
  '//       timeoutMs: C.TIME.seconds(10),',
  '//     },',
  '//   },',
  '//   audit: b.audit,',
  '// });',
  '//',
  '// await notify.send({',
  '//   channel: "slack",',
  '//   message: { text: "Deploy started by " + actor.email, password: "leaked-here" },',
  '// });',
  '// Slack receives { text: "Deploy started by alice@..." }; the audit row',
  '// records the metadata with `password` redacted via b.redact.redact.',
  'typeof b.notify.create; // "function"</code></pre>',
  '<p>Three transports ship in the box under <code>b.notify.transports</code>: <code>log()</code> (writes via <code>b.log</code>), <code>httpJson({url, shape?})</code> (POSTs JSON to a URL), and <code>test()</code> (capture for tests). Slack, email, SMS, push — all are operator-supplied <code>{ name, send }</code>. Failures route through <code>b.retry</code> + <code>b.retry.CircuitBreaker</code>; broken channels emit <code>notify.send.failure</code> on the audit chain plus an observability counter so ops dashboards see the outage.</p>',

  '<h3 id="notify-transports">b.notify.transports.httpJson(opts) / log(opts?) / test() <a class="anchor" href="#notify-transports">#</a></h3>',
  '<pre><code class="language-javascript">// httpJson(opts):',
  '{',
  '  url:            string,                       // required: true',
  '  name:           string,                       // default: "httpJson"',
  '  method:         "POST" | "PUT" | "PATCH",     // default: "POST"',
  '  bodyFormat:     "json" | "form",              // default: "json"',
  '  headers:        { [name]: string },           // default: {}',
  '  signing:        { sign: (body) =&gt; headers|string },  // default: null — webhook-style request signer',
  '  successStatus:  (status) =&gt; boolean,          // default: 200..299',
  '  allowHttp:      boolean,                      // default: false — http:// requires explicit opt-in',
  '  allowInternal:  boolean,                      // default: null — defer to b.ssrfGuard',
  '  httpClient:     httpClientInstance,           // default: framework b.httpClient',
  '}',
  '',
  '// log(opts?):',
  '{',
  '  name:    string,                              // default: "log"',
  '  logger:  { info: (line) =&gt; void },            // default: b.log.boot("notify.log")',
  '}',
  '',
  '// test() takes no opts.</code></pre>',
  '<p>The three built-in transports the framework ships under <code>b.notify.create({ channels })</code>. <code>httpJson</code> POSTs JSON or form-encoded bodies through <code>b.httpClient</code> — proxy / DPI trust / SSRF guard inherit automatically; pass a <code>signing</code> shim shaped like <code>b.webhook.signer</code> for HMAC-signed webhooks. <code>log</code> is a fire-and-forget developer logger that never throws, useful for local dev and integration-test channels. <code>test</code> records every send into <code>.sent</code> and exposes <code>.clear()</code> for fixture reset — drop it into a channel during tests instead of mocking the dispatcher. Vendor SDKs (Slack-API / Twilio / FCM / APNs) stay operator-supplied: the contract is <code>{ name, send(message, sendOpts) }</code>, and the dispatcher wraps every call with retry + circuit breaker + timeout + audit.</p>',
  '<pre><code class="language-javascript">// var slack = b.notify.transports.httpJson({',
  '//   url:     env("SLACK_WEBHOOK_URL"),',
  '//   signing: b.webhook.signer({ secret: env("SLACK_SIGNING_SECRET"), algo: "hmac-sha3-512" }),',
  '// });',
  '',
  'var devLog = b.notify.transports.log();',
  '',
  'var capture = b.notify.transports.test();',
  'capture.send({ text: "fixture" }, null);',
  'capture.sent.length;          // 1',
  'capture.clear();</code></pre>',

  '<h2 id="events">b.events <a class="anchor" href="#events">#</a></h2>',
  '<p>The framework-internal event bus. Primitives publish lifecycle events here so operators can subscribe without having to wrap the primitive in their own EventEmitter. Events are typed; the published list of names lives at <code>b.events.EVENTS</code> so editor autocomplete catches typos.</p>',
  '<pre><code class="language-javascript">b.events.on(b.events.EVENTS.API_ENCRYPT_FAILURE, function (info) {',
  '  // { reason, ip, path, method, ts, requestId }',
  '  myDashboard.recordApiEncryptFailure(info);',
  '});',
  '',
  'b.events.on(b.events.EVENTS.CLUSTER_LEASE_RELEASED, function (info) {',
  '  // { fencingToken, releasedBy }',
  '  myAlerter.alert("cluster leadership changed");',
  '});</code></pre>',
  '<p>The bus is best-effort: a listener that throws is caught + logged but doesn\'t affect the publishing primitive. Use it for ops-dashboard wiring and incident-response automation; for state-mutating reactions, the <a href="/observability#audit">audit chain</a> is the right primitive.</p>',
].join("\n"),
};
