"use strict";

module.exports = {
  slug:  "object-store",
  title: "Object Store",
  body: [
  '<h1>Object Store</h1>',
  '<p><code>b.storage</code> is the file abstraction. Local disk, S3, GCS, Azure Blob — all behind the same <code>saveFile / getFileStream / saveRaw / getRawBuffer / deleteFile</code> surface. Files are encrypted at rest with a per-file XChaCha20-Poly1305 key wrapped under the operator\'s vault.</p>',

  '<h2 id="storage">Basics <a class="anchor" href="#storage">#</a></h2>',
  '<pre><code class="language-javascript">// Local disk in dev, S3 in prod — same code:',
  'await b.storage.saveFile(buf, "uploads/2026/04/avatar.png");</code></pre>',
  '<p>SigV4 (S3), signed URLs (GCS), and SAS (Azure) presigning are all native. POST-form policy presigning covers browsers that can\'t issue signed PUTs.</p>',
  '<h3>b.storage.presignedUploadPolicy(key, opts)</h3>',
  '<pre><code class="language-javascript">{',
  '  contentType:  string,                    // default: "application/octet-stream"',
  '  maxBytes:     number,                    // required: true (sigv4/gcs)',
  '  expiresIn:    number,                    // default: 900 — seconds',
  '  backend:      string,                    // default: first registered',
  '}</code></pre>',
  '<pre><code class="language-javascript">var policy = await b.storage.presignedUploadPolicy("uploads/2026/04/avatar.png", {',
  '  contentType: "image/png",',
  '  maxBytes:    C.BYTES.mib(5),',
  '  expiresIn:   600,    // seconds',
  '});',
  '// → { url, method, fields, expiresAt, maxBytes, enforcement }',
  '// Browser POSTs the file directly per the policy — never goes through Node.',
  '// content-length-range condition makes the object store reject oversize',
  '// bodies before they touch your origin.</code></pre>',

  '<h2 id="multipart">Multipart upload <a class="anchor" href="#multipart">#</a></h2>',
  '<p>The SigV4 adapter (S3 / R2 / B2 / MinIO / Wasabi / Tigris / DO Spaces) auto-dispatches large bodies through the 3-step multipart flow. Buffers above <code>multipartThresholdBytes</code> (default 64 MiB) trigger it; <code>Readable</code> streams always trigger it. A failure mid-upload runs <code>AbortMultipartUpload</code> automatically so partial parts don\'t accumulate server-side.</p>',
  '<pre><code class="language-javascript">b.storage.init({',
  '  backends: {',
  '    s3: {',
  '      protocol:                 "sigv4",',
  '      partSizeBytes:            16 * 1024 * 1024,  // default 16 MiB',
  '      multipartThresholdBytes:  64 * 1024 * 1024,  // default 64 MiB',
  '      partConcurrency:          4,                 // parallel UploadParts',
  '    },',
  '  },',
  '});',
  '',
  '// Streams always go multipart:',
  'await s3.put("backups/2026-04-30.tar.gz", fs.createReadStream(path));',
  '',
  '// Force single-PUT for small bodies / deterministic test fixtures:',
  'await s3.put("manifest.json", buf, { multipart: false });</code></pre>',

  '<h2 id="sse">Server-side encryption (SSE) <a class="anchor" href="#sse">#</a></h2>',
  '<p>SigV4 backends accept <code>opts.sse</code> on every <code>put()</code>. Pass <code>"AES256"</code> for S3-managed keys, <code>"aws:kms"</code> for the bucket\'s default KMS key, or <code>{ type: "aws:kms", keyId }</code> for a specific KMS CMK. The adapter <strong>verifies the response header</strong> echoed back by the server and fails the put if it\'s missing — so a misconfigured bucket policy that silently drops SSE shows up as a hard error rather than a quiet compliance hole.</p>',
  '<pre><code class="language-javascript">await s3.put("invoices/2026-04.pdf", pdfBuf, { sse: "AES256" });',
  '',
  'await s3.put("phi/record.json", buf, {',
  '  sse: { type: "aws:kms", keyId: "arn:aws:kms:us-east-1:123:key/abc" },',
  '});',
  '// → throws SSE_NOT_APPLIED if the server response drops the header.</code></pre>',

  '<h2 id="folder-upload">Multi-folder drag &amp; drop <a class="anchor" href="#folder-upload">#</a></h2>',
  '<p>The framework\'s body parser preserves multipart filenames verbatim (slashes included), so the operator just needs the right client wiring. Use <code>&lt;input type="file" webkitdirectory&gt;</code> for a folder picker, plus a drag/drop handler that walks <code>FileSystemEntry</code> trees recursively and supplies each file\'s relative path as the third argument to <code>FormData.append</code>.</p>',

  '<h2 id="bucket-ops">Bucket-level operations <a class="anchor" href="#bucket-ops">#</a></h2>',
  '<p><code>b.objectStore.bucketOps.create({ ... })</code> returns a service-scoped client for SigV4 buckets. Create the bucket your app expects at boot, attach a lifecycle rule that aborts incomplete multiparts after a week, set the CORS rules the upload UI needs.</p>',
  '<pre><code class="language-javascript">var ops = b.objectStore.bucketOps.create({',
  '  region:          "us-east-1",',
  '  accessKeyId:     env("AWS_ACCESS_KEY_ID"),',
  '  secretAccessKey: env("AWS_SECRET_ACCESS_KEY"),',
  '});',
  '',
  'await ops.create("my-app-uploads", { region: "eu-west-1" });',
  'var all = await ops.list();   // → [{ name, creationDate, region }]',
  '',
  'await ops.setLifecycle("my-app-uploads", [',
  '  { id: "abort-stale-multiparts", status: "Enabled", prefix: "",',
  '    abortIncompleteMultipartUpload: { daysAfterInitiation: 7 } },',
  '  { id: "expire-tmp", status: "Enabled", prefix: "tmp/",',
  '    expiration: { days: 30 } },',
  ']);',
  '',
  'await ops.setCorsRules("my-app-uploads", [{',
  '  allowedOrigins: ["https://app.example.com"],',
  '  allowedMethods: ["GET", "PUT", "POST"],',
  '  allowedHeaders: ["*"],',
  '  exposeHeaders:  ["ETag"],',
  '  maxAgeSeconds:  3600,',
  '}]);',
  '',
  'await ops.delete("my-app-uploads");   // idempotent: returns false if already gone</code></pre>',
  '<p>Conflict responses map to stable framework error codes: <code>BUCKET_ALREADY_OWNED</code>, <code>BUCKET_NAME_TAKEN</code>, <code>BUCKET_NOT_EMPTY</code>. Bad bucket names (S3 spec: 3..63 chars, lowercase, no consecutive dots) are rejected at the call site before the request leaves the process — no surprise 400s after a network round-trip.</p>',
].join("\n"),
};
