"use strict";

module.exports = {
  slug:  "object-store",
  title: "Object Store",
  body: [
  '<h1>Object Store</h1>',
  '<p><code>b.storage</code> is the file abstraction. Local disk, S3, GCS, Azure Blob — all behind the same <code>saveFile / getFileStream / saveRaw / getRawBuffer / deleteFile</code> surface. Files are encrypted at rest with a per-file XChaCha20-Poly1305 key wrapped under the operator\'s vault.</p>',

  '<h2 id="storage">Basics <a class="anchor" href="#storage">#</a></h2>',
  '<pre><code class="language-javascript">// Local disk in dev, S3 in prod — same code:',
  'await b.storage.saveFile(buf, "uploads/2026/04/avatar.png");</code></pre>',
  '<p>SigV4 (S3), signed URLs (GCS), and SAS (Azure) presigning are all native. POST-form policy presigning covers browsers that can\'t issue signed PUTs.</p>',

  '<h2 id="storage-init">b.storage.init(options) / listBackends() / getBackend(name) <a class="anchor" href="#storage-init">#</a></h2>',
  '<p>Registers local, SigV4, GCS, Azure, or custom storage backends and exposes read-only backend diagnostics.</p>',
  '<pre><code class="language-javascript">typeof b.storage.init; // "function"',
  'typeof b.storage.listBackends; // "function"',
  'typeof b.storage.getBackend; // "function"</code></pre>',

  '<h2 id="storage-list-backends">b.storage.listBackends() <a class="anchor" href="#storage-list-backends">#</a></h2>',
  '<p>Returns registered storage backend descriptors for admin and diagnostics views.</p>',
  '<pre><code class="language-javascript">typeof b.storage.listBackends; // "function"</code></pre>',

  '<h2 id="storage-get-backend">b.storage.getBackend(name) <a class="anchor" href="#storage-get-backend">#</a></h2>',
  '<p>Returns the backend adapter selected by name so operator tooling can inspect protocol capabilities before issuing storage calls.</p>',
  '<pre><code class="language-javascript">typeof b.storage.getBackend; // "function"</code></pre>',

  '<h2 id="storage-save-file">b.storage.saveFile(buffer, key, options) / getFileBuffer(key, sealedKey, options) <a class="anchor" href="#storage-save-file">#</a></h2>',
  '<p>Encrypted object save/read pair. <code>saveFile</code> returns the sealed key metadata needed to retrieve and decrypt the object later.</p>',
  '<pre><code class="language-javascript">typeof b.storage.saveFile; // "function"',
  'typeof b.storage.getFileBuffer; // "function"</code></pre>',

  '<h2 id="storage-get-file-buffer">b.storage.getFileBuffer(key, sealedKey, options) <a class="anchor" href="#storage-get-file-buffer">#</a></h2>',
  '<p>Reads and decrypts a saved object into a Buffer using the sealed per-file key metadata returned at write time.</p>',
  '<pre><code class="language-javascript">typeof b.storage.getFileBuffer; // "function"</code></pre>',

  '<h2 id="storage-stream">b.storage.getFileStream(key, sealedKey, options) <a class="anchor" href="#storage-stream">#</a></h2>',
  '<p>Streaming read path for large objects where buffering the full decrypted payload is undesirable.</p>',
  '<pre><code class="language-javascript">typeof b.storage.getFileStream; // "function"</code></pre>',

  '<h2 id="storage-raw">b.storage.saveRaw(buffer, key, options) / getRawBuffer(key, options) <a class="anchor" href="#storage-raw">#</a></h2>',
  '<p>Raw object operations for artifacts that are already encrypted or intentionally public.</p>',
  '<pre><code class="language-javascript">typeof b.storage.saveRaw; // "function"',
  'typeof b.storage.getRawBuffer; // "function"</code></pre>',

  '<h2 id="storage-get-raw-buffer">b.storage.getRawBuffer(key, options) <a class="anchor" href="#storage-get-raw-buffer">#</a></h2>',
  '<p>Reads an object without framework decryption for public or pre-encrypted artifacts.</p>',
  '<pre><code class="language-javascript">typeof b.storage.getRawBuffer; // "function"</code></pre>',

  '<h2 id="storage-delete-exists">b.storage.deleteFile(key, options) / exists(key, options) <a class="anchor" href="#storage-delete-exists">#</a></h2>',
  '<p>Object deletion and existence checks across the configured backend set.</p>',
  '<pre><code class="language-javascript">typeof b.storage.deleteFile; // "function"',
  'typeof b.storage.exists; // "function"</code></pre>',

  '<h2 id="storage-exists">b.storage.exists(key, options) <a class="anchor" href="#storage-exists">#</a></h2>',
  '<p>Checks whether an object key exists in the selected backend.</p>',
  '<pre><code class="language-javascript">typeof b.storage.exists; // "function"</code></pre>',

  '<h2 id="storage-presigned-urls">b.storage.presignedUploadUrl(key, options) / presignedDownloadUrl(key, options) <a class="anchor" href="#storage-presigned-urls">#</a></h2>',
  '<p>Backend-native signed URLs for direct browser/client transfer without proxying bytes through the Node process.</p>',
  '<pre><code class="language-javascript">typeof b.storage.presignedUploadUrl; // "function"',
  'typeof b.storage.presignedDownloadUrl; // "function"</code></pre>',

  '<h2 id="storage-presigned-download">b.storage.presignedDownloadUrl(key, options) <a class="anchor" href="#storage-presigned-download">#</a></h2>',
  '<p>Creates a short-lived signed download URL for clients that should read directly from object storage.</p>',
  '<pre><code class="language-javascript">typeof b.storage.presignedDownloadUrl; // "function"</code></pre>',

  '<h2 id="storage-presigned-upload-policy">b.storage.presignedUploadPolicy(key, opts) <a class="anchor" href="#storage-presigned-upload-policy">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  contentType:  string,                    // default: "application/octet-stream"',
  '  maxBytes:     number,                    // required: true (sigv4/gcs)',
  '  expiresIn:    number,                    // default: 900 — seconds',
  '  backend:      string,                    // default: first registered',
  '}</code></pre>',
  '<p>POST-form policy presigning for browsers that need to upload directly to an object store without signed PUT support. The backend enforces content-length and content-type before bytes reach the app.</p>',
  '<pre><code class="language-javascript">var policyPlan = { key: "uploads/2026/04/avatar.png", options: {',
  '  contentType: "image/png",',
  '  maxBytes:    C.BYTES.mib(5),',
  '  expiresIn:   600,    // seconds',
  '} };',
  '// var policy = await b.storage.presignedUploadPolicy(policyPlan.key, policyPlan.options);',
  'typeof b.storage.presignedUploadPolicy; // "function"',
  '// → { url, method, fields, expiresAt, maxBytes, enforcement }',
  '// Browser POSTs the file directly per the policy — never goes through Node.',
  '// content-length-range condition makes the object store reject oversize',
  '// bodies before they touch your origin.</code></pre>',

  '<h2 id="multipart">Multipart upload <a class="anchor" href="#multipart">#</a></h2>',
  '<p>The SigV4 adapter (S3 / R2 / B2 / MinIO / Wasabi / Tigris / DO Spaces) auto-dispatches large bodies through the 3-step multipart flow. Buffers above <code>multipartThresholdBytes</code> (default 64 MiB) trigger it; <code>Readable</code> streams always trigger it. A failure mid-upload runs <code>AbortMultipartUpload</code> automatically so partial parts don\'t accumulate server-side.</p>',
  '<pre><code class="language-javascript">b.storage.init({',
  '  backends: {',
  '    s3: {',
  '      protocol:                 "sigv4",',
  '      partSizeBytes:            16 * 1024 * 1024,  // default 16 MiB',
  '      multipartThresholdBytes:  64 * 1024 * 1024,  // default 64 MiB',
  '      partConcurrency:          4,                 // parallel UploadParts',
  '    },',
  '  },',
  '});',
  '',
  '// Streams always go multipart:',
  'await s3.put("backups/2026-04-30.tar.gz", fs.createReadStream(path));',
  '',
  '// Force single-PUT for small bodies / deterministic test fixtures:',
  'await s3.put("manifest.json", buf, { multipart: false });</code></pre>',

  '<h2 id="sse">Server-side encryption (SSE) <a class="anchor" href="#sse">#</a></h2>',
  '<p>SigV4 backends accept <code>opts.sse</code> on every <code>put()</code>. Pass <code>"AES256"</code> for S3-managed keys, <code>"aws:kms"</code> for the bucket\'s default KMS key, or <code>{ type: "aws:kms", keyId }</code> for a specific KMS CMK. The adapter <strong>verifies the response header</strong> echoed back by the server and fails the put if it\'s missing — so a misconfigured bucket policy that silently drops SSE shows up as a hard error rather than a quiet compliance hole.</p>',
  '<pre><code class="language-javascript">await s3.put("invoices/2026-04.pdf", pdfBuf, { sse: "AES256" });',
  '',
  'await s3.put("phi/record.json", buf, {',
  '  sse: { type: "aws:kms", keyId: "arn:aws:kms:us-east-1:123:key/abc" },',
  '});',
  '// → throws SSE_NOT_APPLIED if the server response drops the header.</code></pre>',

  '<h2 id="folder-upload">Multi-folder drag &amp; drop <a class="anchor" href="#folder-upload">#</a></h2>',
  '<p>The framework\'s body parser preserves multipart filenames verbatim (slashes included), so the operator just needs the right client wiring. Use <code>&lt;input type="file" webkitdirectory&gt;</code> for a folder picker, plus a drag/drop handler that walks <code>FileSystemEntry</code> trees recursively and supplies each file\'s relative path as the third argument to <code>FormData.append</code>.</p>',

  '<h2 id="bucket-ops">b.objectStore.bucketOps.create(opts) <a class="anchor" href="#bucket-ops">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  protocol:           "sigv4" | "azure-blob" | "gcs",   // required: true',
  '  // sigv4 (S3 / R2 / B2 / MinIO / Wasabi / Tigris / Storj / DO Spaces / etc.):',
  '  region:             string,',
  '  accessKeyId:        string,',
  '  secretAccessKey:    string,',
  '  endpoint:           string,                            // optional — non-AWS S3-compatible',
  '  // azure-blob:',
  '  accountName:        string,',
  '  accountKey:         string,',
  '  // gcs:',
  '  serviceAccountFile: string,                            // path to service-account JSON',
  '}</code></pre>',
  '<p>Service-scoped client for bucket lifecycle (create / delete / list) plus per-bucket lifecycle and CORS rules. Each protocol module owns its own validation, signing, and REST translation; <code>bucketOps.create</code> just dispatches by <code>protocol</code>. The returned <code>ops</code> object exposes <code>create(name, opts?)</code>, <code>delete(name)</code>, <code>list(opts?)</code>, <code>setLifecycle(name, rules)</code>, and <code>setCorsRules(name, rules)</code> — Azure CORS is account-level so its <code>setCorsRules(rules)</code> drops the bucket name; Azure lifecycle is intentionally not implemented (configure via Terraform / Bicep / az CLI). Conflict responses map to stable framework error codes: <code>BUCKET_ALREADY_OWNED</code>, <code>BUCKET_NAME_TAKEN</code>, <code>BUCKET_NOT_EMPTY</code>, <code>BUCKET_INVALID_NAME</code>. Bad bucket / container names are rejected at the call site before the request leaves the process. <code>b.objectStore.bucketOps.PROTOCOLS</code> lists supported protocols; the per-protocol modules are also surfaced (<code>b.objectStore.bucketOps.sigv4</code> / <code>gcs</code> / <code>"azure-blob"</code>) for advanced operators wiring their own dispatch.</p>',
  '<pre><code class="language-javascript">// SigV4 (S3 / R2 / B2 / MinIO / Wasabi / Tigris / Storj / DO Spaces / etc.)',
  '// var s3ops = b.objectStore.bucketOps.create({',
  '//   protocol:        "sigv4",',
  '//   region:          "us-east-1",',
  '//   accessKeyId:     env("AWS_ACCESS_KEY_ID"),',
  '//   secretAccessKey: env("AWS_SECRET_ACCESS_KEY"),',
  '// });',
  '//',
  '// await s3ops.create("my-app-uploads", { region: "eu-west-1" });',
  '// var buckets = await s3ops.list();',
  '//',
  '// await s3ops.setLifecycle("my-app-uploads", [',
  '//   { id: "abort-stale-multiparts", status: "Enabled", prefix: "",',
  '//     abortIncompleteMultipartUpload: { daysAfterInitiation: 7 } },',
  '//   { id: "expire-tmp", status: "Enabled", prefix: "tmp/",',
  '//     expiration: { days: 30 } },',
  '// ]);',
  '//',
  '// await s3ops.setCorsRules("my-app-uploads", [{',
  '//   allowedOrigins: ["https://app.example.com"],',
  '//   allowedMethods: ["GET", "PUT", "POST"],',
  '//   allowedHeaders: ["*"],',
  '//   exposeHeaders:  ["ETag"],',
  '//   maxAgeSeconds:  3600,',
  '// }]);',
  '//',
  '// await s3ops.delete("my-app-uploads");   // idempotent: returns false if already gone',
  '//',
  '// Azure Blob Storage — Shared Key auth; CORS is account-level',
  '// (Azure has no per-container CORS). setLifecycle is intentionally',
  '// not implemented because Azure Storage lifecycle policies live on',
  '// Azure Resource Manager (separate auth scheme); configure them via',
  '// Terraform / Bicep / az CLI.',
  '// var azops = b.objectStore.bucketOps.create({',
  '//   protocol:    "azure-blob",',
  '//   accountName: env("AZURE_STORAGE_ACCOUNT"),',
  '//   accountKey:  env("AZURE_STORAGE_KEY"),',
  '// });',
  '//',
  '// await azops.create("uploads", { publicAccess: "blob" });',
  '// var containers = await azops.list();',
  '// await azops.setCorsRules([{',
  '//   allowedOrigins: ["https://app.example.com"],',
  '//   allowedMethods: ["GET", "PUT"],',
  '//   allowedHeaders: ["*"],',
  '//   exposedHeaders: ["ETag"],',
  '//   maxAgeInSeconds: 3600,',
  '// }]);',
  '// await azops.delete("uploads");',
  '//',
  '// Google Cloud Storage — service-account JWT exchanged for OAuth2',
  '// access token; per-bucket lifecycle + CORS via the Storage JSON API.',
  '// var gcsops = b.objectStore.bucketOps.create({',
  '//   protocol:           "gcs",',
  '//   serviceAccountFile: env("GOOGLE_APPLICATION_CREDENTIALS"),',
  '// });',
  '//',
  '// await gcsops.create("my-app-uploads", { location: "US", storageClass: "STANDARD" });',
  '// var gbuckets = await gcsops.list();',
  '// await gcsops.setLifecycle("my-app-uploads", [',
  '//   { action: { type: "Delete" }, condition: { age: 365 } },',
  '//   { action: { type: "SetStorageClass", storageClass: "ARCHIVE" }, condition: { age: 90 } },',
  '// ]);',
  '// await gcsops.setCorsRules("my-app-uploads", [{',
  '//   origin:         ["https://app.example.com"],',
  '//   method:         ["GET", "PUT"],',
  '//   responseHeader: ["Content-Type"],',
  '//   maxAgeSeconds:  3600,',
  '// }]);',
  '// await gcsops.delete("my-app-uploads");',
  'typeof b.objectStore.bucketOps.create; // "function"</code></pre>',
  '<p>Conflict responses map to stable framework error codes: <code>BUCKET_ALREADY_OWNED</code>, <code>BUCKET_NAME_TAKEN</code>, <code>BUCKET_NOT_EMPTY</code>, <code>BUCKET_INVALID_NAME</code>. Bad bucket / container names are rejected at the call site before the request leaves the process — no surprise 400s after a network round-trip.</p>',

  '<h3 id="object-lock">Object Lock, retention, and legal hold (SigV4 only) <a class="anchor" href="#object-lock">#</a></h3>',
  '<p>S3-compatible backends offer write-once-read-many semantics for compliance workloads (SEC 17a-4, FINRA, HIPAA retention). The framework exposes the full surface — bucket-level default retention, per-object retention dates, and per-object legal holds — with up-front validation so a typo in <code>mode</code> or a past <code>retainUntil</code> never reaches the wire.</p>',
  '<pre><code class="language-javascript">// Object Lock can ONLY be enabled at create time on S3.',
  '// await s3ops.create("compliance-archive", { objectLockEnabled: true });',
  '//',
  '// Bucket-level default retention (applied to every newly-uploaded object).',
  '// await s3ops.setObjectLockConfiguration("compliance-archive", {',
  '//   mode: "COMPLIANCE",   // or "GOVERNANCE"',
  '//   years: 7,             // OR days; mutually exclusive',
  '// });',
  '// var lock = await s3ops.getObjectLockConfiguration("compliance-archive");',
  '// { enabled: true, mode: "COMPLIANCE", years: 7, days: null }',
  '//',
  '// Per-object retention (overrides the bucket default for one key).',
  '// await s3ops.setObjectRetention("compliance-archive", "filings/2026-Q1.pdf", {',
  '//   mode:        "GOVERNANCE",',
  '//   retainUntil: new Date("2033-04-15T00:00:00Z"),',
  '// });',
  '// To shorten or remove a GOVERNANCE retention, the operator role must',
  '// include s3:BypassGovernanceRetention and bypassGovernance: true:',
  '// await s3ops.setObjectRetention("compliance-archive", "filings/2026-Q1.pdf", {',
  '//   mode:               "GOVERNANCE",',
  '//   retainUntil:        new Date(Date.now() + 60_000),',
  '//   bypassGovernance:   true,',
  '// });',
  '//',
  '// Legal hold — independent of retention, holds the object until OFF.',
  '// await s3ops.setObjectLegalHold("compliance-archive", "filings/2026-Q1.pdf", "ON");',
  '// var hold = await s3ops.getObjectLegalHold("compliance-archive", "filings/2026-Q1.pdf");',
  '// { status: "ON" }',
  '// await s3ops.setObjectLegalHold("compliance-archive", "filings/2026-Q1.pdf", "OFF");',
  'typeof b.objectStore.bucketOps.create; // "function"</code></pre>',
  '<p>Validation rejects bad inputs at the call site: unknown <code>mode</code>, <code>days</code>+<code>years</code> together, fractional or negative durations, non-Date or past-dated <code>retainUntil</code>, and statuses outside <code>ON</code>/<code>OFF</code> all throw <code>INVALID_OBJECT_LOCK</code> / <code>INVALID_RETENTION</code> / <code>INVALID_LEGAL_HOLD</code> before any request is signed. <code>COMPLIANCE</code> mode cannot be shortened or bypassed by anyone (including root) — pick it deliberately.</p>',
].join("\n"),
};
