"use strict";

module.exports = {
  slug:  "observability",
  title: "Observability",
  body: [
  '<h1>Observability</h1>',
  '<p>blamejs ships five observability primitives that compose: <code>b.audit</code> (tamper-evident chain), <code>b.metrics</code> (counter taps), <code>b.tracing</code> (span taps), <code>b.redact</code> (PII scrubbing), and <code>b.otelExport</code> (ship counters + observations to any OTel-compatible backend). The wrapper <code>b.observability.tap</code> unifies span + counter into one call so primitives don\'t have to interleave them.</p>',
  '<p>Every framework primitive emits audit events on operator-action paths by default. High-throughput verifiers can disable success-event audit with <code>auditSuccess: false</code>; failures emit regardless.</p>',

  '<h2 id="audit">Audit chain <a class="anchor" href="#audit">#</a></h2>',
  '<p>The audit chain is hash-chained, signed, tamper-evident, and append-only. Every framework primitive that mutates operator-visible state emits an audit event when wired with <code>audit: b.audit</code>:</p>',
  '<pre><code class="language-javascript">var b = require("@blamejs/core");',
  '',
  'var keys = b.apiKey.create({',
  '  namespace: "wiki",',
  '  audit:     b.audit,         // wires the chain',
  '});',
  '',
  '// Every issue / verify / revoke / rotate emits with the 5 W\'s',
  'await keys.issue({ ownerId: "u-42", req: req });',
  '// → audit row: { action: "apikey.issue", actor: { ip, userAgent,',
  '//                  sessionId, requestId, method, route, userId },',
  '//                resource: { kind: "apikey", id: "wiki:abc..." },',
  '//                outcome: "success", ... }</code></pre>',

  '<h3 id="five-ws">The 5 W\'s <a class="anchor" href="#five-ws">#</a></h3>',
  '<p>Audit rows carry WHO, WHAT, WHEN, WHERE, and HOW for every operator action. <code>b.requestHelpers.extractActorContext(req, override?)</code> derives the actor from the inbound request:</p>',
  '<table>',
  '  <thead><tr><th>5 W</th><th>Field</th><th>Source</th></tr></thead>',
  '  <tbody>',
  '    <tr><td>WHO</td><td><code>actor.userId</code></td><td><code>req.user.id</code> / <code>req.apiKey.ownerId</code> / explicit override</td></tr>',
  '    <tr><td>WHEN</td><td><code>recordedAt</code></td><td>framework-set unix ms (NTP-validated)</td></tr>',
  '    <tr><td>WHERE</td><td><code>actor.ip</code></td><td><code>requestHelpers.clientIp(req, { trustProxy })</code> — gates X-Forwarded-For</td></tr>',
  '    <tr><td>HOW</td><td><code>actor.userAgent</code></td><td><code>req.headers["user-agent"]</code></td></tr>',
  '    <tr><td>HOW</td><td><code>actor.sessionId</code></td><td><code>req.session.id</code></td></tr>',
  '    <tr><td>HOW</td><td><code>actor.requestId</code></td><td><code>req.requestId</code> / <code>req.headers["x-request-id"]</code></td></tr>',
  '    <tr><td>HOW</td><td><code>actor.method</code></td><td><code>req.method</code></td></tr>',
  '    <tr><td>HOW</td><td><code>actor.route</code></td><td><code>req.routePattern</code> (the template, not the materialized URL — keeps cardinality bounded)</td></tr>',
  '    <tr><td>WHAT</td><td><code>resource.kind / .id</code></td><td>per-primitive (e.g. <code>"wiki.page"</code>, <code>"apikey"</code>)</td></tr>',
  '  </tbody>',
  '</table>',

  '<aside class="callout">',
  '  <p class="callout-title">Note</p>',
  '  <p>Audit chain treats null fields as "unknown" — partial context is safe. Pass <code>{ req }</code> to any primitive method and the framework threads <code>extractActorContext</code> through every emission. Add per-call overrides via <code>{ context: { ip: "10.0.0.1" } }</code> for proxy scenarios.</p>',
  '</aside>',

  '<h3 id="audit-emit">b.audit.safeEmit(event) <a class="anchor" href="#audit-emit">#</a></h3>',
  '<p>For operator-authored events. <strong>Tier B — drop-silent.</strong> Bad input drops, emit failures (DB unreachable, etc.) drop. The audit primitive must never crash the request that triggered it. Only <code>action</code> is enforced as a non-empty string; every other field is convention-by-passing-it.</p>',
  '<pre><code class="language-javascript">{',
  '  action:     string,                      // required: true — namespace.verb',
  '                                            //   (only field the call enforces)',
  '  outcome:    "success" | "failure",       // default: "success"',
  '  actor:      ActorContext,                // default: {} — pass extractActorContext(req)',
  '  resource:   { kind: string, id: string },// default: null',
  '  metadata:   object,                      // default: null',
  '  reason:     string,                      // default: null — describe the cause on failure',
  '  requestId:  string,                      // default: actor.requestId',
  '}</code></pre>',
  '<pre><code class="language-javascript">b.audit.safeEmit({',
  '  action:   "wiki.page.published",',
  '  outcome:  "success",                 // "success" | "failure"',
  '  actor:    b.requestHelpers.extractActorContext(req),',
  '  resource: { kind: "wiki.page", id: groupName + "/" + slug },',
  '  metadata: { title: title, byteLength: body.length },',
  '  reason:   null,                       // string when outcome === "failure"',
  '});</code></pre>',
  '<p>Audit emit failures (DB unreachable, etc.) drop silently — the framework\'s audit primitive must never crash the request that triggered it. Operators monitor audit health via the metrics emitted by <code>audit-chain</code> itself.</p>',

  '<h3 id="audit-chain-verify">Tamper detection <a class="anchor" href="#audit-chain-verify">#</a></h3>',
  '<p>Each row carries <code>prevHash</code>, <code>rowHash</code>, <code>nonce</code>, and <code>fencingToken</code>. Boot-time verification (<code>auditChain.verifyChain</code>) replays the chain and rejects any mismatch. The signing keypair (SLH-DSA-SHAKE-256f by default) seals checkpoint signatures to the audit signing key — corrupting a row breaks the chain at that point and refuses subsequent appends until the operator restores from backup.</p>',
  '<aside class="callout callout-warning">',
  '  <p class="callout-title">Operator note</p>',
  '  <p>Production deployments should set <code>auditSigning: { mode: "wrapped" }</code> (default) and supply <code>BLAMEJS_AUDIT_SIGNING_PASSPHRASE</code>. The plaintext-signing-key files generated in dev mode print a boot warning — never ship a deployment with <code>WARNING: PLAINTEXT mode — audit-sign.key is unprotected on disk</code> in the logs.</p>',
  '</aside>',

  '<h3 id="audit-tools">Audit tools <a class="anchor" href="#audit-tools">#</a></h3>',
  '<p><code>b.auditTools</code> packs the offline maintenance surface: chain export to a sealed bundle, signed-checkpoint emission, scoped purge (e.g. GDPR right-to-erasure on a subject), and chain rebuild from a verified bundle. Every operation runs through the same chain-writer primitive that record() uses, so an export carries the same signatures it emitted at write time.</p>',

  '<h2 id="metrics">Metrics <a class="anchor" href="#metrics">#</a></h2>',
  '<p>Every framework primitive emits structured counters via <code>b.observability.event(name, value, labels)</code>:</p>',
  '<pre><code class="language-javascript">var notify = b.notify.create({',
  '  channels: { ... },',
  '  observability: b.observability,',
  '});',
  'await notify.send({ channel: "slack", message: { text: "Deploy started" } });',
  '// Emits these events (counter taps):',
  '//   notify.send.attempt   { channel: "slack", attempt: 1 }',
  '//   notify.send.success   { channel: "slack", durationMs: 124 }',
  '// Plus a span via observability.tap (next section).</code></pre>',
  '<p>Operators wire a real backend (Prometheus exporter, OTel collector, etc.) by replacing the framework default with <code>b.metrics.tap = function (name, value, labels) { ... }</code>. Bad input drops silently so a malformed metric can\'t crash the request that emitted it.</p>',

  '<h2 id="tracing">Tracing <a class="anchor" href="#tracing">#</a></h2>',
  '<p><code>b.observability.tap(name, attrs, fn)</code> wraps an async operation in BOTH a span AND a counter. This is the canonical pattern primitives use:</p>',
  '<pre><code class="language-javascript">// Inside b.cache, b.api-key, b.notify, b.permissions, etc:',
  'return b.observability.tap("apikey.verify", { namespace: ns }, async function (span) {',
  '  // span is null when no real OTel tracer wired (pass-through);',
  '  // span is a real OTel Span when operators install @opentelemetry/api',
  '  // and call b.tracing.useTracer(otelTrace).',
  '  if (span) span.setAttribute("apikey.id", id);',
  '  var result = await _verifyImpl(secret);',
  '  return result;',
  '});</code></pre>',
  '<p>Without OTel installed, tracing is pass-through: <code>fn(null)</code> runs, return value propagates, throws escape, no spans produced. With OTel: <code>otel.trace.getTracer().startSpan(name, opts)</code> + <code>otel.context.with(ctx, fn)</code> so child spans nest correctly across <code>async</code> suspension points.</p>',
  '<p>W3C <code>traceparent</code> parsing/emission works in both modes so trace IDs propagate through logs and HTTP for correlation regardless of OTel.</p>',

  '<h2 id="otel-export">OTel export <a class="anchor" href="#otel-export">#</a></h2>',
  '<p><code>b.otelExport</code> ships <code>b.observability</code> events to any OTLP/HTTP-JSON backend — Honeycomb, Datadog, Grafana, Jaeger collector, AWS Distro, NewRelic. The JSON variant of the OTLP protobuf spec (every modern collector accepts it). The framework refuses to ship the binary protobuf encoding because it would require either a vendored proto runtime or hand-rolled wire format with no benefit at this scope.</p>',
  '<h3>b.otelExport.create(opts)</h3>',
  '<pre><code class="language-javascript">{',
  '  endpoint:            string,             // required: true — OTLP/HTTP-JSON URL',
  '  serviceName:         string,             // required: true',
  '  headers:             object,             // default: {} — auth headers etc.',
  '  intervalMs:          number,             // default: C.TIME.seconds(15) — auto-flush',
  '  resourceAttributes:  object,             // default: {} — extra attrs',
  '  scope:               { name, version },  // default: { name: "blamejs", version }',
  '  httpClient:          HttpClient,         // default: b.httpClient — for testing',
  '}</code></pre>',
  '<pre><code class="language-javascript">var otel = b.otelExport.create({',
  '  endpoint:    "https://otel.honeycomb.io/v1/metrics",',
  '  headers:     { "X-Honeycomb-Team": env("HONEYCOMB_API_KEY") },',
  '  serviceName: "wiki",',
  '  intervalMs:  b.constants.TIME.seconds(15),',
  '});',
  '',
  '// Wire it as the b.observability tap and any event() call ships:',
  'b.observability.setTap(otel.tapHandler);',
  '',
  'otel.recordCounter("http.requests", 1, { method: "GET", status: 200 });',
  'otel.recordObservation("http.duration_ms", 142, { route: "/api/x" });',
  '',
  'await otel.flush();   // manual flush',
  'otel.close();         // cancels the auto-flush interval, drains once</code></pre>',
  '<p>Auto-aggregation: <code>recordCounter</code> buckets by <code>(name, sorted-attrs)</code> and accumulates until flush, then ships a single OTLP <code>Sum</code> per bucket with DELTA temporality. <code>recordObservation</code> tracks <code>sum + count + min + max</code> per bucket as an OTLP <code>Summary</code> with <code>q=0</code> / <code>q=1</code> for min/max. Auto-flush via <code>setTimeout</code> chain (<code>.unref()</code>\'d so it never blocks shutdown).</p>',
  '<p>Validates <code>endpoint</code> / <code>serviceName</code> / <code>intervalMs</code> at create-time — throws <code>OtelExportError</code> on bad config so the app refuses to boot rather than failing on the first event. Bad event inputs (empty name, NaN value) drop silently — observability sinks must never crash the request that emitted to them.</p>',

  '<h2 id="redact">Redaction <a class="anchor" href="#redact">#</a></h2>',
  '<p><code>b.redact.redact(value)</code> walks an arbitrary value and strips PII-shaped fields. The default detectors catch:</p>',
  '<ul>',
  '  <li>Field names matching <code>password</code>, <code>secret</code>, <code>token</code>, <code>ssn</code>, <code>api_key</code>, <code>credit_card</code>, …</li>',
  '  <li>Values matching email-like, phone-number-like, JWT-like, credit-card-like patterns</li>',
  '</ul>',
  '<pre><code class="language-javascript">b.redact.redact({',
  '  user: { email: "alice@example.com" },',
  '  password: "hunter2",',
  '  body: "Reset link: https://app/reset?token=eyJhbGc..."',
  '});',
  '// → {',
  '//     user: { email: "[REDACTED-EMAIL]" },',
  '//     password: "[REDACTED]",',
  '//     body: "Reset link: https://app/reset?token=[REDACTED-JWT]",',
  '//   }</code></pre>',
  '<p>Operators register custom rules via <code>b.redact.registerFieldRule(name, replacement)</code> and <code>b.redact.registerValueDetector(name, testFn, replacement)</code>. <code>b.notify</code> uses <code>b.redact.redact</code> as its default audit-metadata redactor; operators can override per primitive.</p>',

  '<h2 id="consent">Consent + subject identity <a class="anchor" href="#consent">#</a></h2>',
  '<p>The audit chain is a tamper-evident <em>operator</em> action log. <code>b.consent</code> is the parallel chain for <em>subject</em> consent state — capturing who agreed to what, when, and under which lawful basis. Same chain primitive underneath, so consent records get the same hash-linked durability as the audit log. The verbs are explicit — <code>grant</code> and <code>withdraw</code>, not a single record-with-boolean.</p>',
  '<h3>b.consent.grant(opts) / .withdraw(opts) / .isGranted(opts) / .history(subjectId)</h3>',
  '<pre><code class="language-javascript">// grant opts:',
  '{',
  '  subjectId:    string,                      // required: true — opaque subject id',
  '  purpose:      string,                      // required: true — what they consented to',
  '  lawfulBasis:  "consent" | "contract" | "legal_obligation"',
  '              | "vital_interests" | "public_task" | "legitimate_interests",',
  '                                              // required: true (GDPR Article 6)',
  '  channel:      string,                      // required: true — e.g. "web-signup"',
  '  scope:        object,                      // default: null — extra scoping (sealed)',
  '  evidenceRef:  string,                      // default: null — pointer to proof artifact',
  '}',
  '',
  '// withdraw opts:',
  '{',
  '  subjectId:  string,                         // required: true',
  '  purpose:    string,                         // required: true',
  '  channel:    string,                         // default: "api"',
  '  reason:     string,                         // default: null',
  '}</code></pre>',
  '<pre><code class="language-javascript">// Capture an explicit grant',
  'await b.consent.grant({',
  '  subjectId:    user.id,',
  '  purpose:      "marketing-email",',
  '  lawfulBasis:  "consent",',
  '  channel:      "web-signup",',
  '  evidenceRef:  "form-submission:" + req.requestId,',
  '});',
  '',
  '// Withdraw — produces a paired row in the chain',
  'await b.consent.withdraw({ subjectId: user.id, purpose: "marketing-email", reason: "user clicked unsubscribe" });',
  '',
  '// Most-recent state for (subjectId, purpose)',
  'var ok = b.consent.isGranted({ subjectId: user.id, purpose: "marketing-email" });',
  '// → boolean',
  '',
  '// Full history — for the privacy dashboard / DSAR export',
  'var rows = b.consent.history(user.id);</code></pre>',
  '<p><code>b.subject</code> is the identity-resolution helper that produces a stable opaque subject ID from whichever attributes the operator considers identifying (email, phone, account ID, anonymous fingerprint). Consent records key off that ID, so a subject who later changes their email still has their consent state attached.</p>',

  '<h2 id="log-stream">Log stream sinks <a class="anchor" href="#log-stream">#</a></h2>',
  '<p><code>b.logStream</code> is the operator-facing log-shipper primitive: the framework\'s structured log records can be tee\'d to an external SIEM, ELK, or any HTTPS POST endpoint without giving up the local stdout / file destination. Multi-sink dispatcher with named protocol backends; metadata is run through <code>b.redact.redact</code> before any sink sees it.</p>',
  '<h3>b.logStream.init(opts)</h3>',
  '<pre><code class="language-javascript">{',
  '  sinks:           { [name]: SinkConfig },   // required: true',
  '  minLevel:        "debug" | "info" | "warn" | "error" | "fatal",',
  '                                              // default: "info"',
  '  classification:  string,                    // default: null — per-deploy data class tag',
  '}',
  '',
  '// SinkConfig:',
  '{',
  '  protocol:  string,                          // required: true — "webhook" | custom',
  '  minLevel:  string,                          // default: top-level minLevel',
  '  // ...protocol-specific config (e.g. { url, secret, retry } for "webhook")',
  '}</code></pre>',
  '<pre><code class="language-javascript">b.logStream.init({',
  '  sinks: {',
  '    siem: {',
  '      protocol: "webhook",',
  '      url:      "https://siem.example.com/ingest",',
  '      secret:   env("SIEM_HMAC_SECRET"),',
  '      retry:    { maxAttempts: 5, baseDelayMs: 250 },',
  '    },',
  '  },',
  '  minLevel: "info",',
  '});',
  '// Local stdout / file destinations are unchanged — sinks are tee\'d on top.</code></pre>',
  '<p>Sink errors do NOT bubble — they\'re captured on the audit chain as <code>system.log.sink-failure</code>, so an external SIEM outage doesn\'t take down the app\'s request handlers.</p>',

  '<h2 id="primitive-internals">How primitives wire it <a class="anchor" href="#primitive-internals">#</a></h2>',
  '<p>The wiring inside framework primitives threads through <code>b.observability.tap</code>, <code>b.audit.safeEmit</code>, and <code>b.redact.redact</code>. Excerpt from <code>lib/notify.js</code>:</p>',
  '<pre><code class="language-javascript">// notify.send — the hot path:',
  'return b.observability.tap("notify.send", { channel: ch }, async function () {',
  '  try {',
  '    var result = await b.retry.withRetry(_oneAttempt, retryOpts);',
  '    if (auditSuccess) {',
  '      b.audit.safeEmit({',
  '        action:   "notify.send.success",',
  '        actor:    b.requestHelpers.extractActorContext(req),',
  '        resource: { kind: "notify.channel", id: ch },',
  '        outcome:  "success",',
  '        metadata: _redactedMetadata(ch, message),  // b.redact.redact',
  '      });',
  '    }',
  '    return result;',
  '  } catch (e) {',
  '    if (auditFailures) b.audit.safeEmit({ ... });',
  '    throw e;',
  '  }',
  '});</code></pre>',
  '<p>This pattern repeats across every primitive: <code>b.cache</code>, <code>b.apiKey</code>, <code>b.permissions</code>, <code>b.seeders</code>, <code>b.webhook</code>, <code>b.i18n</code>. Operators inherit it by default; turning audit off requires explicit opt-out.</p>',
].join("\n"),
};
