"use strict";

module.exports = {
  slug:  "observability",
  title: "Observability",
  body: [
  '<h1>Observability</h1>',
  '<p>blamejs ships five observability primitives that compose: <code>b.audit</code> (tamper-evident chain), <code>b.metrics</code> (counter taps), <code>b.tracing</code> (span taps), <code>b.redact</code> (PII scrubbing), and <code>b.otelExport</code> (ship counters + observations to any OTel-compatible backend). The wrapper <code>b.observability.tap</code> unifies span + counter into one call so primitives don\'t have to interleave them.</p>',
  '<p>Every framework primitive emits audit events on operator-action paths by default. High-throughput verifiers can disable success-event audit with <code>auditSuccess: false</code>; failures emit regardless.</p>',

  '<h2 id="audit">Audit chain <a class="anchor" href="#audit">#</a></h2>',
  '<p>The audit chain is hash-chained, signed, tamper-evident, and append-only. Every framework primitive that mutates operator-visible state emits an audit event when wired with <code>audit: b.audit</code>:</p>',
  '<pre><code class="language-javascript">var b = require("@blamejs/core");',
  '',
  'var keys = b.apiKey.create({',
  '  namespace: "wiki",',
  '  audit:     b.audit,         // wires the chain',
  '});',
  '',
  '// Every issue / verify / revoke / rotate emits with the 5 W\'s',
  'await keys.issue({ ownerId: "u-42", req: req });',
  '// → audit row: { action: "apikey.issue", actor: { ip, userAgent,',
  '//                  sessionId, requestId, method, route, userId },',
  '//                resource: { kind: "apikey", id: "wiki:abc..." },',
  '//                outcome: "success", ... }</code></pre>',

  '<h3 id="five-ws">The 5 W\'s <a class="anchor" href="#five-ws">#</a></h3>',
  '<p>Audit rows carry WHO, WHAT, WHEN, WHERE, and HOW for every operator action. <code>b.requestHelpers.extractActorContext(req, override?)</code> derives the actor from the inbound request:</p>',
  '<table>',
  '  <thead><tr><th>5 W</th><th>Field</th><th>Source</th></tr></thead>',
  '  <tbody>',
  '    <tr><td>WHO</td><td><code>actor.userId</code></td><td><code>req.user.id</code> / <code>req.apiKey.ownerId</code> / explicit override</td></tr>',
  '    <tr><td>WHEN</td><td><code>recordedAt</code></td><td>framework-set unix ms (NTP-validated)</td></tr>',
  '    <tr><td>WHERE</td><td><code>actor.ip</code></td><td><code>requestHelpers.clientIp(req, { trustProxy })</code> — gates X-Forwarded-For</td></tr>',
  '    <tr><td>HOW</td><td><code>actor.userAgent</code></td><td><code>req.headers["user-agent"]</code></td></tr>',
  '    <tr><td>HOW</td><td><code>actor.sessionId</code></td><td><code>req.session.id</code></td></tr>',
  '    <tr><td>HOW</td><td><code>actor.requestId</code></td><td><code>req.requestId</code> / <code>req.headers["x-request-id"]</code></td></tr>',
  '    <tr><td>HOW</td><td><code>actor.method</code></td><td><code>req.method</code></td></tr>',
  '    <tr><td>HOW</td><td><code>actor.route</code></td><td><code>req.routePattern</code> (the template, not the materialized URL — keeps cardinality bounded)</td></tr>',
  '    <tr><td>WHAT</td><td><code>resource.kind / .id</code></td><td>per-primitive (e.g. <code>"wiki.page"</code>, <code>"apikey"</code>)</td></tr>',
  '  </tbody>',
  '</table>',

  '<aside class="callout">',
  '  <p class="callout-title">Note</p>',
  '  <p>Audit chain treats null fields as "unknown" — partial context is safe. Pass <code>{ req }</code> to any primitive method and the framework threads <code>extractActorContext</code> through every emission. Add per-call overrides via <code>{ context: { ip: "10.0.0.1" } }</code> for proxy scenarios.</p>',
  '</aside>',

  '<h3 id="audit-emit">b.audit.safeEmit(event) <a class="anchor" href="#audit-emit">#</a></h3>',
  '<p>For operator-authored events. <strong>Drop-silent</strong> by design: bad input drops, emit failures (DB unreachable, etc.) drop. The audit primitive must never crash the request that triggered it. Only <code>action</code> is enforced as a non-empty string; every other field is convention-by-passing-it.</p>',
  '<pre><code class="language-javascript">{',
  '  action:     string,                      // required: true — namespace.verb',
  '                                            //   (only field the call enforces)',
  '  outcome:    "success" | "failure",       // default: "success"',
  '  actor:      ActorContext,                // default: {} — pass extractActorContext(req)',
  '  resource:   { kind: string, id: string },// default: null',
  '  metadata:   object,                      // default: null',
  '  reason:     string,                      // default: null — describe the cause on failure',
  '  requestId:  string,                      // default: actor.requestId',
  '}</code></pre>',
  '<pre><code class="language-javascript">b.audit.safeEmit({',
  '  action:   "wiki.page.published",',
  '  outcome:  "success",                 // "success" | "failure"',
  '  actor:    b.requestHelpers.extractActorContext(req),',
  '  resource: { kind: "wiki.page", id: groupName + "/" + slug },',
  '  metadata: { title: title, byteLength: body.length },',
  '  reason:   null,                       // string when outcome === "failure"',
  '});</code></pre>',
  '<p>Audit emit failures (DB unreachable, etc.) drop silently — the framework\'s audit primitive must never crash the request that triggered it. Operators monitor audit health via the metrics emitted by <code>audit-chain</code> itself.</p>',

  '<h2 id="audit-record">b.audit.record(event) / emit(event) <a class="anchor" href="#audit-record">#</a></h2>',
  '<p>Strict audit write paths for operator code that wants failures to surface instead of the drop-silent <code>safeEmit</code> behavior.</p>',
  '<pre><code class="language-javascript">typeof b.audit.record; // "function"',
  'typeof b.audit.emit; // "function"</code></pre>',

  '<h2 id="audit-register-namespace">b.audit.registerNamespace(name, options) <a class="anchor" href="#audit-register-namespace">#</a></h2>',
  '<p>Registers action namespaces so audit rows can be checked against an operator-approved vocabulary.</p>',
  '<pre><code class="language-javascript">typeof b.audit.registerNamespace; // "function"</code></pre>',

  '<h2 id="audit-query">b.audit.query(options) <a class="anchor" href="#audit-query">#</a></h2>',
  '<p>Read-side query helper for admin dashboards, investigations, and compliance exports.</p>',
  '<pre><code class="language-javascript">typeof b.audit.query; // "function"</code></pre>',

  '<h2 id="audit-flush">b.audit.flush() <a class="anchor" href="#audit-flush">#</a></h2>',
  '<p>Drains buffered audit work before shutdown or before handing evidence to an external process.</p>',
  '<pre><code class="language-javascript">typeof b.audit.flush; // "function"</code></pre>',

  '<h2 id="audit-export">b.audit.export(opts) / b.auditTools.exportCadf(opts) <a class="anchor" href="#audit-export">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  format:  "cadf",          // currently only "cadf" — Cloud Auditing Data Federation (ISO/IEC 19395:2017)',
  '  from:    Date | number,   // optional — Unix-ms or Date lower bound',
  '  to:      Date | number,   // optional — Unix-ms or Date upper bound',
  '  action:  string,          // optional — filter to a single action verb',
  '}</code></pre>',
  '<p>Federated SIEM-shape export for the audit chain. Maps every blamejs audit field onto CADF cadf:* attributes (initiator, target, observer, action, outcome, eventTime) and carries the chain anchor (prevHash, rowHash, monotonicCounter) under the framework&#39;s <code>blamejs:chain</code> CADF extension. Operators forward the result to OpenStack/FedRAMP/cloud-audit pipelines without writing per-attribute mappers.</p>',
  '<pre><code class="language-javascript">// var bundle = await b.audit.export({ format: "cadf", from: Date.UTC(2026, 4, 1) });',
  '// bundle.events.length;     // number of events',
  'typeof b.audit.export; // "function"</code></pre>',

  '<h2 id="audit-verify">b.audit.verify(options) <a class="anchor" href="#audit-verify">#</a></h2>',
  '<p>Verifies audit-chain continuity for a requested range and returns structured evidence for operator review.</p>',
  '<pre><code class="language-javascript">typeof b.audit.verify; // "function"</code></pre>',

  '<h2 id="audit-trace">b.audit.beginTrace(options) <a class="anchor" href="#audit-trace">#</a></h2>',
  '<p>Starts an audit trace scope so related operator actions can be correlated without overloading request ids.</p>',
  '<pre><code class="language-javascript">typeof b.audit.beginTrace; // "function"</code></pre>',

  '<h2 id="audit-checkpoint">b.audit.checkpoint(options) / verifyCheckpoints(options) <a class="anchor" href="#audit-checkpoint">#</a></h2>',
  '<p>Signed checkpoint creation and verification. Checkpoints give auditors a compact proof of chain state at a point in time.</p>',
  '<pre><code class="language-javascript">typeof b.audit.checkpoint; // "function"',
  'typeof b.audit.verifyCheckpoints; // "function"</code></pre>',

  '<h3 id="audit-chain-verify">Tamper detection <a class="anchor" href="#audit-chain-verify">#</a></h3>',
  '<p>Each row carries <code>prevHash</code>, <code>rowHash</code>, <code>nonce</code>, and <code>fencingToken</code>. Boot-time verification (<code>auditChain.verifyChain</code>) replays the chain and rejects any mismatch. The signing keypair (SLH-DSA-SHAKE-256f by default) seals checkpoint signatures to the audit signing key — corrupting a row breaks the chain at that point and refuses subsequent appends until the operator restores from backup.</p>',
  '<aside class="callout callout-warning">',
  '  <p class="callout-title">Operator note</p>',
  '  <p>Production deployments should set <code>auditSigning: { mode: "wrapped" }</code> (default) and supply <code>BLAMEJS_AUDIT_SIGNING_PASSPHRASE</code>. The plaintext-signing-key files generated in dev mode print a boot warning — never ship a deployment with <code>WARNING: PLAINTEXT mode — audit-sign.key is unprotected on disk</code> in the logs.</p>',
  '</aside>',

  '<h3 id="audit-tools">Audit tools <a class="anchor" href="#audit-tools">#</a></h3>',
  '<p><code>b.auditTools</code> packs the offline maintenance surface: chain export to a sealed bundle, signed-checkpoint emission, scoped purge (e.g. GDPR right-to-erasure on a subject), and chain rebuild from a verified bundle. Every operation runs through the same chain-writer primitive that record() uses, so an export carries the same signatures it emitted at write time.</p>',

  '<h2 id="metrics">Metrics <a class="anchor" href="#metrics">#</a></h2>',
  '<p>Every framework primitive emits structured counters via <code>b.observability.event(name, value, labels)</code>:</p>',
  '<pre><code class="language-javascript">var notify = b.notify.create({',
  '  channels: { ... },',
  '  observability: b.observability,',
  '});',
  'await notify.send({ channel: "slack", message: { text: "Deploy started" } });',
  '// Emits these events (counter taps):',
  '//   notify.send.attempt   { channel: "slack", attempt: 1 }',
  '//   notify.send.success   { channel: "slack", durationMs: 124 }',
  '// Plus a span via observability.tap (next section).</code></pre>',
  '<p>Operators wire a real backend (Prometheus exporter, OTel collector, etc.) by replacing the framework default with <code>b.metrics.tap = function (name, value, labels) { ... }</code>. Bad input drops silently so a malformed metric can\'t crash the request that emitted it.</p>',

  '<h2 id="observability-event">b.observability.event(name, value, labels) / safeEvent(name, value, labels) <a class="anchor" href="#observability-event">#</a></h2>',
  '<p>Counter emission surface. <code>event</code> is strict; <code>safeEvent</code> drops malformed input and sink errors so observability cannot crash request handling.</p>',
  '<pre><code class="language-javascript">b.observability.safeEvent("wiki.page.view", 1, { route: "/welcome" });',
  'typeof b.observability.event; // "function"</code></pre>',

  '<h2 id="observability-tap">b.observability.tap(name, attrs, fn) / setTap(fn) <a class="anchor" href="#observability-tap">#</a></h2>',
  '<p>Unified span/counter hook used by primitives to wrap operator-visible work. <code>setTap</code> installs the process-wide sink.</p>',
  '<pre><code class="language-javascript">var value = await b.observability.tap("wiki.example", {}, async function () { return 42; });',
  'value; // 42',
  'typeof b.observability.setTap; // "function"</code></pre>',

  '<h2 id="observability-timed">b.observability.timed(name, attrs, fn) <a class="anchor" href="#observability-timed">#</a></h2>',
  '<p>Duration wrapper for async work. It emits timing metadata while preserving the wrapped function return value or thrown error.</p>',
  '<pre><code class="language-javascript">typeof b.observability.timed; // "function"</code></pre>',

  '<h2 id="observability-context">b.observability.traceContext(headers) / baggage(headers) <a class="anchor" href="#observability-context">#</a></h2>',
  '<p>W3C trace context and baggage parsing helpers for HTTP boundaries and queue messages.</p>',
  '<pre><code class="language-javascript">typeof b.observability.traceContext; // "function"',
  'typeof b.observability.baggage; // "function"</code></pre>',

  '<h2 id="observability-tracer">b.observability.tracer(options) / otlpExporter(options) <a class="anchor" href="#observability-tracer">#</a></h2>',
  '<p>Tracing/exporter construction helpers for operators wiring OpenTelemetry-compatible backends.</p>',
  '<pre><code class="language-javascript">typeof b.observability.tracer; // "function"',
  'typeof b.observability.otlpExporter; // "function"</code></pre>',

  '<h2 id="tracing">Tracing <a class="anchor" href="#tracing">#</a></h2>',
  '<p><code>b.observability.tap(name, attrs, fn)</code> wraps an async operation in BOTH a span AND a counter. This is the canonical pattern primitives use:</p>',
  '<pre><code class="language-javascript">// Inside b.cache, b.api-key, b.notify, b.permissions, etc:',
  'return b.observability.tap("apikey.verify", { namespace: ns }, async function (span) {',
  '  // span is null when no real OTel tracer wired (pass-through);',
  '  // span is a real OTel Span when operators install @opentelemetry/api',
  '  // and call b.tracing.useTracer(otelTrace).',
  '  if (span) span.setAttribute("apikey.id", id);',
  '  var result = await _verifyImpl(secret);',
  '  return result;',
  '});</code></pre>',
  '<p>Without OTel installed, tracing is pass-through: <code>fn(null)</code> runs, return value propagates, throws escape, no spans produced. With OTel: <code>otel.trace.getTracer().startSpan(name, opts)</code> + <code>otel.context.with(ctx, fn)</code> so child spans nest correctly across <code>async</code> suspension points.</p>',
  '<p>W3C <code>traceparent</code> parsing/emission works in both modes so trace IDs propagate through logs and HTTP for correlation regardless of OTel.</p>',

  '<h2 id="otel-export">OTel export <a class="anchor" href="#otel-export">#</a></h2>',
  '<p><code>b.otelExport</code> ships <code>b.observability</code> events to any OTLP/HTTP-JSON backend — Honeycomb, Datadog, Grafana, Jaeger collector, AWS Distro, NewRelic. The JSON variant of the OTLP protobuf spec (every modern collector accepts it). The framework refuses to ship the binary protobuf encoding because it would require either a vendored proto runtime or hand-rolled wire format with no benefit at this scope.</p>',
  '<h3>b.otelExport.create(opts)</h3>',
  '<pre><code class="language-javascript">{',
  '  endpoint:            string,             // required: true — OTLP/HTTP-JSON URL',
  '  serviceName:         string,             // required: true',
  '  headers:             object,             // default: {} — auth headers etc.',
  '  intervalMs:          number,             // default: C.TIME.seconds(15) — auto-flush',
  '  resourceAttributes:  object,             // default: {} — extra attrs',
  '  scope:               { name, version },  // default: { name: "blamejs", version }',
  '  httpClient:          HttpClient,         // default: b.httpClient — for testing',
  '}</code></pre>',
  '<pre><code class="language-javascript">var otel = b.otelExport.create({',
  '  endpoint:    "https://otel.honeycomb.io/v1/metrics",',
  '  headers:     { "X-Honeycomb-Team": env("HONEYCOMB_API_KEY") },',
  '  serviceName: "wiki",',
  '  intervalMs:  b.constants.TIME.seconds(15),',
  '});',
  '',
  '// Wire it as the b.observability tap and any event() call ships:',
  'b.observability.setTap(otel.tapHandler);',
  '',
  'otel.recordCounter("http.requests", 1, { method: "GET", status: 200 });',
  'otel.recordObservation("http.duration_ms", 142, { route: "/api/x" });',
  '',
  'await otel.flush();   // manual flush',
  'otel.close();         // cancels the auto-flush interval, drains once</code></pre>',
  '<p>Auto-aggregation: <code>recordCounter</code> buckets by <code>(name, sorted-attrs)</code> and accumulates until flush, then ships a single OTLP <code>Sum</code> per bucket with DELTA temporality. <code>recordObservation</code> tracks <code>sum + count + min + max</code> per bucket as an OTLP <code>Summary</code> with <code>q=0</code> / <code>q=1</code> for min/max. Auto-flush via <code>setTimeout</code> chain (<code>.unref()</code>\'d so it never blocks shutdown).</p>',
  '<p>Validates <code>endpoint</code> / <code>serviceName</code> / <code>intervalMs</code> at create-time — throws <code>OtelExportError</code> on bad config so the app refuses to boot rather than failing on the first event. Bad event inputs (empty name, NaN value) drop silently — observability sinks must never crash the request that emitted to them.</p>',

  '<h2 id="redact">Redaction <a class="anchor" href="#redact">#</a></h2>',
  '<p><code>b.redact.redact(value)</code> walks an arbitrary value and strips PII-shaped fields. The default detectors catch:</p>',
  '<ul>',
  '  <li>Field names matching <code>password</code>, <code>secret</code>, <code>token</code>, <code>ssn</code>, <code>api_key</code>, <code>credit_card</code>, …</li>',
  '  <li>Values matching email-like, phone-number-like, JWT-like, credit-card-like patterns</li>',
  '</ul>',
  '<pre><code class="language-javascript">b.redact.redact({',
  '  user: { email: "alice@example.com" },',
  '  password: "hunter2",',
  '  body: "Reset link: https://app/reset?token=eyJhbGc..."',
  '});',
  '// → {',
  '//     user: { email: "[REDACTED-EMAIL]" },',
  '//     password: "[REDACTED]",',
  '//     body: "Reset link: https://app/reset?token=[REDACTED-JWT]",',
  '//   }</code></pre>',
  '<p>Operators register custom rules via <code>b.redact.registerFieldRule(name, replacement)</code> and <code>b.redact.registerValueDetector(name, testFn, replacement)</code>. <code>b.notify</code> uses <code>b.redact.redact</code> as its default audit-metadata redactor; operators can override per primitive.</p>',

  '<h2 id="consent">Consent + subject identity <a class="anchor" href="#consent">#</a></h2>',
  '<p>The audit chain is a tamper-evident <em>operator</em> action log. <code>b.consent</code> is the parallel chain for <em>subject</em> consent state — capturing who agreed to what, when, and under which lawful basis. Same chain primitive underneath, so consent records get the same hash-linked durability as the audit log. The verbs are explicit — <code>grant</code> and <code>withdraw</code>, not a single record-with-boolean.</p>',
  '<h3>b.consent.grant(opts) / .withdraw(opts) / .isGranted(opts) / .history(subjectId)</h3>',
  '<pre><code class="language-javascript">// grant opts:',
  '{',
  '  subjectId:    string,                      // required: true — opaque subject id',
  '  purpose:      string,                      // required: true — what they consented to',
  '  lawfulBasis:  "consent" | "contract" | "legal_obligation"',
  '              | "vital_interests" | "public_task" | "legitimate_interests",',
  '                                              // required: true (GDPR Article 6)',
  '  channel:      string,                      // required: true — e.g. "web-signup"',
  '  scope:        object,                      // default: null — extra scoping (sealed)',
  '  evidenceRef:  string,                      // default: null — pointer to proof artifact',
  '}',
  '',
  '// withdraw opts:',
  '{',
  '  subjectId:  string,                         // required: true',
  '  purpose:    string,                         // required: true',
  '  channel:    string,                         // default: "api"',
  '  reason:     string,                         // default: null',
  '}</code></pre>',
  '<pre><code class="language-javascript">// Capture an explicit grant',
  'await b.consent.grant({',
  '  subjectId:    user.id,',
  '  purpose:      "marketing-email",',
  '  lawfulBasis:  "consent",',
  '  channel:      "web-signup",',
  '  evidenceRef:  "form-submission:" + req.requestId,',
  '});',
  '',
  '// Withdraw — produces a paired row in the chain',
  'await b.consent.withdraw({ subjectId: user.id, purpose: "marketing-email", reason: "user clicked unsubscribe" });',
  '',
  '// Most-recent state for (subjectId, purpose)',
  'var ok = b.consent.isGranted({ subjectId: user.id, purpose: "marketing-email" });',
  '// → boolean',
  '',
  '// Full history — for the privacy dashboard / DSAR export',
  'var rows = b.consent.history(user.id);</code></pre>',
  '<p><code>b.subject</code> is the identity-resolution helper that produces a stable opaque subject ID from whichever attributes the operator considers identifying (email, phone, account ID, anonymous fingerprint). Consent records key off that ID, so a subject who later changes their email still has their consent state attached.</p>',

  '<h2 id="log-stream">Log stream sinks <a class="anchor" href="#log-stream">#</a></h2>',
  '<p><code>b.logStream</code> is the operator-facing log-shipper primitive: the framework\'s structured log records can be tee\'d to an external SIEM, ELK, or any HTTPS POST endpoint without giving up the local stdout / file destination. Multi-sink dispatcher with named protocol backends; metadata is run through <code>b.redact.redact</code> before any sink sees it.</p>',
  '<h3>b.logStream.init(opts)</h3>',
  '<pre><code class="language-javascript">{',
  '  sinks:           { [name]: SinkConfig },   // required: true',
  '  minLevel:        "debug" | "info" | "warn" | "error" | "fatal",',
  '                                              // default: "info"',
  '  classification:  string,                    // default: null — per-deploy data class tag',
  '}',
  '',
  '// SinkConfig:',
  '{',
  '  protocol:  string,                          // required: "local" | "webhook" | "otlp" | "cloudwatch" | "syslog" | custom',
  '  minLevel:  string,                          // default: top-level minLevel',
  '  // ...protocol-specific config:',
  '  //   webhook:    { url, auth, headers, batchSize, retry, onDrop }',
  '  //   otlp:       { url, serviceName, serviceVersion, resourceAttributes,',
  '  //                 auth, headers, batchSize, retry, onDrop }',
  '  //   cloudwatch: { region, accessKeyId, secretAccessKey, sessionToken?,',
  '  //                 logGroupName, logStreamName, autoCreate?, batchSize, retry, onDrop }',
  '  //   syslog:     { url, facility?, appName?, procId?, hostname?,',
  '  //                 structuredData?, ca?, servername?, bufferLimit?, onDrop }',
  '  //   local:      { path, rotateBytes, rotateKeep }',
  '}</code></pre>',
  '<pre><code class="language-javascript">b.logStream.init({',
  '  sinks: {',
  '    siem: {',
  '      protocol: "webhook",',
  '      url:      "https://siem.example.com/ingest",',
  '      secret:   env("SIEM_HMAC_SECRET"),',
  '      retry:    { maxAttempts: 5, baseDelayMs: 250 },',
  '    },',
  '    otel: {',
  '      protocol:           "otlp",',
  '      url:                "https://otel-collector.internal:4318",  // /v1/logs auto-appended',
  '      serviceName:        "my-service",',
  '      serviceVersion:     env("APP_VERSION"),',
  '      resourceAttributes: { env: "production", region: env("AWS_REGION") },',
  '      auth:               "bearer",',
  '      token:              env("OTEL_TOKEN"),',
  '    },',
  '    aws: {',
  '      protocol:        "cloudwatch",',
  '      region:          env("AWS_REGION"),',
  '      accessKeyId:     env("AWS_ACCESS_KEY_ID"),',
  '      secretAccessKey: env("AWS_SECRET_ACCESS_KEY"),',
  '      sessionToken:    env("AWS_SESSION_TOKEN"),         // optional, STS creds',
  '      logGroupName:    "/blamejs/my-app",                 // operator pre-creates by default',
  '      logStreamName:   "instance-" + process.env.HOSTNAME,',
  '      autoCreate:      false,                             // true → framework issues',
  '                                                          // CreateLogGroup + CreateLogStream',
  '    },',
  '    syslog: {',
  '      protocol:  "syslog",',
  '      url:       "tls://syslog.internal:6514",            // udp:// / tcp:// / tls://',
  '      appName:   "my-service",',
  '      facility:  16,                                       // local0',
  '      ca:        env("SYSLOG_CA_PEM"),                     // private CA pinning',
  '    },',
  '  },',
  '  minLevel: "info",',
  '});',
  '// Local stdout / file destinations are unchanged — sinks are tee\'d on top.</code></pre>',
  '<p>The <code>otlp</code> sink emits OpenTelemetry Protocol logs over HTTP/JSON (per the OTel Logs Data Model: <code>resourceLogs</code> → <code>scopeLogs</code> → <code>logRecords</code> with <code>severityNumber</code>, <code>severityText</code>, <code>timeUnixNano</code>, <code>body</code>, <code>attributes</code>). Severity maps debug→5, info→9, warn→13, error→17 per spec. Operators with an OTel collector (k8s sidecar, AWS ADOT, GCP Ops Agent) point the URL at it; the collector forwards upstream via gRPC / Tempo / Jaeger / etc. The framework hands the collector JSON, so no protobuf parser ships in the bundle.</p>',
  '<p>The <code>cloudwatch</code> sink emits AWS CloudWatch Logs <code>PutLogEvents</code> over HTTPS with SigV4 signing (service: <code>logs</code>). By default the operator pre-creates the log group + log stream (<code>aws logs create-log-group</code> / <code>create-log-stream</code> via CDK or Terraform); pass <code>autoCreate: true</code> to have the framework issue <code>CreateLogGroup</code> + <code>CreateLogStream</code> on first emit (idempotent — <code>ResourceAlreadyExistsException</code> is treated as success). Honors IAM role + STS session-token credentials. Respects all three CloudWatch caps automatically: 10,000 events / 1 MiB / 256 KiB-per-event. Per-event oversize is dropped at <code>emit()</code>-time with <code>onDrop</code>; per-batch oversize is split mid-flush. Permanent AWS errors (ResourceNotFoundException / AccessDeniedException / etc.) skip the retry budget.</p>',
  '<p>The <code>syslog</code> sink emits RFC 5424 records over UDP, TCP, or TLS. URL drives the transport: <code>udp://host:514</code> for best-effort datagrams, <code>tcp://host:514</code> for octet-counting framed delivery (RFC 6587), <code>tls://host:6514</code> for the TLS variant (TLS 1.3 minimum, with optional <code>ca</code> for private-CA pinning). PRI is computed from <code>(facility &lt;&lt; 3) | severity</code>; severity is mapped from the framework\'s level (debug=7 / info=6 / warn=4 / error=3). Default facility is <code>local0</code> (16); <code>appName</code> defaults to <code>blamejs</code>, <code>hostname</code> to <code>os.hostname()</code>, <code>structuredData</code> to <code>-</code>. TCP and TLS reconnect with exponential backoff and buffer outgoing records during the down window with <code>bufferLimit</code>-bounded oldest-drop semantics; <code>close()</code> waits for any in-flight (re)connect to drain the buffer before tearing down.</p>',
  '<p>Sink errors do NOT bubble — they\'re captured on the audit chain as <code>system.log.sink-failure</code>, so an external SIEM outage doesn\'t take down the app\'s request handlers.</p>',

  '<h2 id="primitive-internals">How primitives wire it <a class="anchor" href="#primitive-internals">#</a></h2>',
  '<p>The wiring inside framework primitives threads through <code>b.observability.tap</code>, <code>b.audit.safeEmit</code>, and <code>b.redact.redact</code>. Excerpt from <code>lib/notify.js</code>:</p>',
  '<pre><code class="language-javascript">// notify.send — the hot path:',
  'return b.observability.tap("notify.send", { channel: ch }, async function () {',
  '  try {',
  '    var result = await b.retry.withRetry(_oneAttempt, retryOpts);',
  '    if (auditSuccess) {',
  '      b.audit.safeEmit({',
  '        action:   "notify.send.success",',
  '        actor:    b.requestHelpers.extractActorContext(req),',
  '        resource: { kind: "notify.channel", id: ch },',
  '        outcome:  "success",',
  '        metadata: _redactedMetadata(ch, message),  // b.redact.redact',
  '      });',
  '    }',
  '    return result;',
  '  } catch (e) {',
  '    if (auditFailures) b.audit.safeEmit({ ... });',
  '    throw e;',
  '  }',
  '});</code></pre>',
  '<p>This pattern repeats across every primitive: <code>b.cache</code>, <code>b.apiKey</code>, <code>b.permissions</code>, <code>b.seeders</code>, <code>b.webhook</code>, <code>b.i18n</code>. Operators inherit it by default; turning audit off requires explicit opt-out.</p>',

  '<h2 id="audit-chain-get-tip">b.auditChain.getChainTip(queryOneAsync, tableName) <a class="anchor" href="#audit-chain-get-tip">#</a></h2>',
  '<p>Reads the current chain tip (last row\'s <code>rowHash</code> + <code>monotonicCounter</code>) for a chain-backed audit table. The async signature accepts an operator-supplied <code>queryOneAsync(sql, params?) → row | null</code> reader so the helper works against single-node SQLite, cluster-mode external-db, or a unit-test stub. Returns <code>{ prevHash, counter }</code>; an empty table yields <code>{ prevHash: ZERO_HASH, counter: 0 }</code> so the first append seeds correctly.</p>',
  '<pre><code class="language-javascript">// Operator supplies the queryOneAsync reader bound to their DB pool.',
  '// var tip = await b.auditChain.getChainTip(',
  '//   async function (sql, params) { return /* db.queryOne(sql, params) */; },',
  '//   "audit_log"',
  '// );',
  '// → { prevHash: "0000...", counter: 0 } on a fresh chain',
  '// → { prevHash: "<64-char hex>", counter: 12345 } on a populated chain',
  'typeof b.auditChain.getChainTip; // "function"</code></pre>',

  '<h2 id="audit-chain-verify-chain">b.auditChain.verifyChain(queryAllAsync, tableName, opts?) <a class="anchor" href="#audit-chain-verify-chain">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  maxRows:  number,                 // default: null — bound the walk for sampling verifications',
  '}</code></pre>',
  '<p>Walks the entire chain forward, recomputing each row\'s <code>rowHash</code> and verifying the linked <code>prevHash</code>. Returns <code>{ ok, table, rowsVerified, lastHash }</code> on success, or <code>{ ok: false, breakAt, breakRowId, reason, expected, actual }</code> on the first mismatch. The walk transparently honors a <code>_blamejs_audit_purge_anchor</code> row when present, so chains that have been purged via <code>b.auditTools.purge</code> still verify against the post-purge anchor without the bundle as the source of truth. Boot-time verification calls this at <code>O(n)</code>; production deployments size their audit retention with that walk in mind.</p>',
  '<pre><code class="language-javascript">// Operator supplies a queryAllAsync reader bound to their DB pool.',
  '// var result = await b.auditChain.verifyChain(',
  '//   async function (sql, params) { return /* db.queryAll(sql, params) */; },',
  '//   "audit_log"',
  '// );',
  '// if (!result.ok) {',
  '//   // Operator runbook: the chain broke at result.breakRowId — restore from a verified bundle',
  '//   throw new Error("audit chain tampered at counter " + result.breakAt + ": " + result.reason);',
  '// }',
  'typeof b.auditChain.verifyChain; // "function"</code></pre>',

  '<h2 id="audit-sign-verify">b.auditSign.verify(payload, signature, publicKeyPem?) <a class="anchor" href="#audit-sign-verify">#</a></h2>',
  '<p>Verifies a SLH-DSA-SHAKE-256f (or ML-DSA-87) signature produced by <code>b.auditSign.sign</code>. The third argument is optional — when omitted, the in-memory current public key is used; pass a PEM string to verify under a historical key (e.g. an archive bundle signed before a key rotation). Returns boolean. Pairs with <code>b.auditSign.getPublicKey()</code> and <code>getPublicKeyFingerprint()</code> for auditor lookups.</p>',
  '<pre><code class="language-javascript">// Operator reads a checkpoint row from audit_checkpoints, then:',
  '// var payload = Buffer.from(',
  '//   "blamejs-audit-checkpoint-v1\\n" +',
  '//   String(checkpoint.atMonotonicCounter) + "\\n" +',
  '//   checkpoint.atRowHash + "\\n" +',
  '//   String(checkpoint.createdAt),',
  '//   "utf8"',
  '// );',
  '// var ok = b.auditSign.verify(payload, checkpoint.signature);',
  '// → true when the in-memory key still anchors this checkpoint',
  '//',
  '// Auditor-side verification under an explicit historical public key',
  '// var ok2 = b.auditSign.verify(payload, checkpoint.signature, archivedPublicKeyPem);',
  'typeof b.auditSign.verify; // "function"</code></pre>',

  '<h2 id="audit-sign-rotate">b.auditSign.rotateSigningKey(opts) <a class="anchor" href="#audit-sign-rotate">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  algorithm:     "slh-dsa-shake-256f" | "ml-dsa-87",  // default: current keypair\'s algorithm',
  '  privateKeyPem: string,                              // default: null — BYO keypair (pair with publicKeyPem)',
  '  publicKeyPem:  string,                              // default: null — BYO keypair (pair with privateKeyPem)',
  '}</code></pre>',
  '<p>Rotates the audit-signing keypair in memory and on disk. Either generates a fresh keypair or accepts an operator-supplied PEM pair (e.g. for HSM-backed signers). The previous sealed/plaintext key file is moved to a timestamped history path so checkpoints signed under the old key still verify; the framework keeps history forever because audit checkpoints can be decades old. Throws <code>ROTATE_NOOP</code> if the new fingerprint matches the old one. Rotation does NOT walk and re-sign existing checkpoints — pair with <code>reSignAll</code> for that.</p>',
  '<pre><code class="language-javascript">// Operator runbook for a planned rotation:',
  '//   1. rotate to a fresh keypair',
  '//   2. read every audit_checkpoints row',
  '//   3. re-sign each through reSignAll',
  '//   4. write the new signatures back atomically',
  '// var rot = await b.auditSign.rotateSigningKey({ algorithm: "slh-dsa-shake-256f" });',
  '// → { previousFingerprint, newFingerprint, algorithm, rotatedAt, historyPath }',
  '//',
  '// log.info("audit-signing key rotated", {',
  '//   from: rot.previousFingerprint.slice(0, 16),',
  '//   to:   rot.newFingerprint.slice(0, 16),',
  '//   alg:  rot.algorithm,',
  '// });',
  'typeof b.auditSign.rotateSigningKey; // "function"</code></pre>',

  '<h2 id="audit-sign-resign">b.auditSign.reSignAll(iterable, opts?) <a class="anchor" href="#audit-sign-resign">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  onProgress:  function ({ id, newSignature }) { ... },  // default: null — per-row hook for atomic write-back',
  '}</code></pre>',
  '<p>Walks an operator-supplied async iterable of <code>{ id, payload, signature, oldPublicKeyPem }</code> entries and re-signs each payload with the CURRENT in-memory key. Skips entries that don\'t verify under the supplied old public key (already tampered or never signed under that key) so a single bad row doesn\'t abort the whole walk. Returns <code>{ reSigned, skipped, errors }</code> for the operator\'s log line. The primitive returns the new signatures via <code>onProgress</code> so the caller\'s storage layer owns the transaction shape.</p>',
  '<pre><code class="language-javascript">// async function* checkpointIterator() {',
  '//   var rows = await db.queryAll("SELECT _id, atMonotonicCounter, atRowHash, createdAt, signature FROM audit_checkpoints ORDER BY atMonotonicCounter ASC");',
  '//   for (var row of rows) {',
  '//     var payload = Buffer.from(',
  '//       "blamejs-audit-checkpoint-v1\\n" + row.atMonotonicCounter + "\\n" + row.atRowHash + "\\n" + row.createdAt,',
  '//       "utf8"',
  '//     );',
  '//     yield { id: row._id, payload: payload, signature: row.signature, oldPublicKeyPem: oldPubPem };',
  '//   }',
  '// }',
  '//',
  '// var summary = await b.auditSign.reSignAll(checkpointIterator(), {',
  '//   onProgress: function (entry) {',
  '//     db.execute("UPDATE audit_checkpoints SET signature = ? WHERE _id = ?", [entry.newSignature, entry.id]);',
  '//   },',
  '// });',
  '// → { reSigned: 14302, skipped: 0, errors: 0 }',
  'typeof b.auditSign.reSignAll; // "function"</code></pre>',

  '<h2 id="audit-tools-archive">b.auditTools.archive(opts) <a class="anchor" href="#audit-tools-archive">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  out:                     string,        // required: true — fresh directory path; refuses to overwrite',
  '  before:                  string | number | Date,  // required: true — archive rows older than this',
  '  passphrase:              string | Buffer,         // required: true — PQC bundle passphrase',
  '  readRows:                function,                // default: cluster-storage reader — async (criteria) → rows',
  '  readCoveringCheckpoint:  function,                // default: cluster-storage reader',
  '  readPredecessorRowHash:  function,                // default: cluster-storage reader',
  '}</code></pre>',
  '<p>Bundles audit rows older than <code>before</code> into a PQC-encrypted archive directory. The bundle layout is <code>manifest.json</code> + <code>rows.enc</code> + <code>checkpoint.enc</code>; the manifest carries the chain-range proof (<code>firstCounter</code> / <code>lastCounter</code> / <code>predecessorRowHash</code>) and a copy of a covering signed checkpoint so the archive is tamper-evident on its own. Throws if no signed checkpoint covers the slice — operators run <code>b.audit.checkpoint()</code> before archiving so the bundle has an off-chain anchor. Live rows stay untouched until <code>b.auditTools.purge</code> consumes the archive.</p>',
  '<pre><code class="language-javascript">// var oneYearAgo = Date.now() - b.constants.TIME.days(365);',
  '// var bundle = await b.auditTools.archive({',
  '//   out:        "/var/blamejs/archives/audit-2026-Q1",',
  '//   before:     oneYearAgo,',
  '//   passphrase: process.env.AUDIT_BUNDLE_PASSPHRASE,',
  '// });',
  '// → { manifest, manifestPath, outDir, rowCount, range }',
  'typeof b.auditTools.archive; // "function"</code></pre>',

  '<h2 id="audit-tools-export-slice">b.auditTools.exportSlice(opts) <a class="anchor" href="#audit-tools-export-slice">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  out:                     string,                  // required: true — fresh directory path',
  '  passphrase:              string | Buffer,         // required: true',
  '  from:                    string | number | Date,  // default: null — start of date range (inclusive)',
  '  to:                      string | number | Date,  // default: null — end of date range (inclusive)',
  '  action:                  string,                  // default: null — narrow to a single namespaced action',
  '  readRows:                function,                // default: cluster-storage reader',
  '  readPredecessorRowHash:  function,                // default: cluster-storage reader',
  '}</code></pre>',
  '<p>Produces an auditor-shaped slice with a self-contained chain proof. Unlike <code>archive</code>, the slice does not embed a covering checkpoint signature — auditors typically follow up with an <code>audit.verify</code> call against the live system to confirm the slice still chains. Refuses non-contiguous slices (e.g. an <code>action</code> filter that breaks <code>monotonicCounter</code> contiguity) because chain verification can\'t ground a non-contiguous sequence — use date-range filters that cover every row in the range.</p>',
  '<pre><code class="language-javascript">// var slice = await b.auditTools.exportSlice({',
  '//   out:        "/tmp/auditor-evidence-incident-42",',
  '//   from:       "2026-01-01T00:00:00Z",',
  '//   to:         "2026-01-31T23:59:59Z",',
  '//   passphrase: process.env.AUDITOR_BUNDLE_PASSPHRASE,',
  '// });',
  '// → { manifest, manifestPath, outDir, rowCount, range }',
  'typeof b.auditTools.exportSlice; // "function"</code></pre>',

  '<h2 id="audit-tools-verify-bundle">b.auditTools.verifyBundle(opts) <a class="anchor" href="#audit-tools-verify-bundle">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  in:                        string,            // required: true — path to a bundle directory',
  '  passphrase:                string | Buffer,   // required: true',
  '  verifyCheckpointSignature: boolean,           // default: true — set false to skip ML-DSA verify',
  '  verifySignature:           function,          // default: framework — auditor-supplied verifier with a different pubkey',
  '  includeRows:               boolean,           // default: false — return decrypted rows alongside the result',
  '}</code></pre>',
  '<p>Round-trip integrity check: decrypts the bundle, walks the chain math across the contained rows, confirms the manifest\'s <code>firstRowHash</code> / <code>lastRowHash</code>, and (archive bundles only) verifies the covering checkpoint signature. Returns <code>{ ok: true, kind, rowsVerified, range, manifest }</code> on success or a structured <code>{ ok: false, reason, expected, actual }</code> on the first mismatch. Auditors verifying on a different machine pass <code>verifySignature</code> with their own loaded public key — the bundle deliberately doesn\'t embed the public key (the checkpoint\'s <code>publicKeyFingerprint</code> is the verifier\'s lookup index).</p>',
  '<pre><code class="language-javascript">// var v = await b.auditTools.verifyBundle({',
  '//   in:         "/var/blamejs/archives/audit-2026-Q1",',
  '//   passphrase: process.env.AUDIT_BUNDLE_PASSPHRASE,',
  '// });',
  '// if (!v.ok) throw new Error("bundle failed verify: " + v.reason);',
  '// log.info("bundle verified", { kind: v.kind, rowsVerified: v.rowsVerified, range: v.range });',
  'typeof b.auditTools.verifyBundle; // "function"</code></pre>',

  '<h2 id="audit-tools-purge">b.auditTools.purge(opts) <a class="anchor" href="#audit-tools-purge">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  archive:          string,            // required: true — path to a verified archive bundle',
  '  passphrase:       string | Buffer,   // required: true — bundle passphrase',
  '  confirm:          true,              // required: must be exactly === true — destructive op gate',
  '  verifySignature:  function,          // default: framework — auditor pubkey override',
  '  readAnchor:       function,          // default: cluster-storage reader',
  '  apply:            function,          // default: framework — operator hook for testability',
  '}</code></pre>',
  '<p>Confirmation-gated deletion of live audit rows already captured in a verified archive bundle. Refuses with a clear reason when (a) the archive fails verification, (b) the archive isn\'t kind <code>archive</code>, (c) the archive\'s <code>firstCounter</code> doesn\'t match the next-purge counter, or (d) the archive\'s <code>predecessorRowHash</code> doesn\'t match the prior purge anchor — the chain anchor stays monotonic and operators can\'t jump-purge a middle range. Writes a <code>_blamejs_audit_purge_anchor</code> row so live <code>audit.verify()</code> keeps working post-purge with the anchor as the new chain origin.</p>',
  '<pre><code class="language-javascript">// var purged = await b.auditTools.purge({',
  '//   archive:    "/var/blamejs/archives/audit-2026-Q1",',
  '//   passphrase: process.env.AUDIT_BUNDLE_PASSPHRASE,',
  '//   confirm:    true,',
  '// });',
  '// → { purged: true, rowsDeleted, checkpointsDeleted, lastPurgedCounter, lastPurgedRowHash, archiveBundleId }',
  'typeof b.auditTools.purge; // "function"</code></pre>',

  '<h2 id="chain-writer-create">b.chainWriter.create(opts) <a class="anchor" href="#chain-writer-create">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  table:             string,    // required: true — must be in ALLOWED_CHAIN_TABLES ("audit_log", "consent_log")',
  '  columnsForInsert:  [string],  // required: true — INSERT column order; every name validated as a SQL identifier',
  '  hashableColumns:   [string],  // required: true — columns canonicalize null-fills before computing rowHash',
  '  validateInput:     function,  // default: null — throws on bad logical row at append time',
  '}</code></pre>',
  '<p>Race-safe append primitive for hash-chained log tables. Both <code>audit_log</code> and <code>consent_log</code> share the same shape — read prev tip, compute <code>prevHash</code>, seal sealed-fields via field-crypto, materialize null entries for every hashable column, compute <code>rowHash</code>, INSERT with <code>prevHash</code> / <code>rowHash</code> / <code>nonce</code> / <code>fencingToken</code>. A per-instance Mutex serializes the read-prev-tip → compute-hash → insert sequence; without serialization concurrent appends would hash against the same tip and fork the chain. Operators usually don\'t construct chain-writers directly — <code>b.audit</code> and <code>b.consent</code> each construct one at module load.</p>',
  '<pre><code class="language-javascript">// var writer = b.chainWriter.create({',
  '//   table:            "consent_log",',
  '//   columnsForInsert: [',
  '//     "_id", "monotonicCounter", "recordedAt", "subjectId", "purpose",',
  '//     "verb", "lawfulBasis", "channel", "scopeSealed", "evidenceRef",',
  '//     "prevHash", "rowHash", "nonce", "fencingToken",',
  '//   ],',
  '//   hashableColumns: ["subjectId", "purpose", "verb", "lawfulBasis", "channel", "scopeSealed", "evidenceRef"],',
  '//   validateInput:   function (logical) {',
  '//     if (!logical.subjectId) throw new Error("subjectId is required");',
  '//   },',
  '// });',
  '//',
  '// var row = await writer.append({',
  '//   subjectId:   "subj-123",',
  '//   purpose:     "marketing-email",',
  '//   verb:        "grant",',
  '//   lawfulBasis: "consent",',
  '//   channel:     "web-signup",',
  '// });',
  '// → { rowHash, prevHash, _id, recordedAt, monotonicCounter, ... }',
  'typeof b.chainWriter.create; // "function"</code></pre>',

  '<h2 id="log-create">b.log.create(opts) <a class="anchor" href="#log-create">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  level:             "debug" | "info" | "warn" | "error" | "fatal" | number,',
  '                                                // default: env LOG_LEVEL > "info"',
  '  destination:       "stdout" | "stderr" | Stream | function,',
  '                                                // default: process.stdout — legacy two-sink form',
  '  errorDestination:  "stdout" | "stderr" | Stream | function,',
  '                                                // default: process.stderr — legacy two-sink form',
  '  sinks:             [{ stream, level? }],      // default: null — multi-sink config (mutually exclusive with destination/errorDestination)',
  '  format:            "json",                    // default: "json" — only json supported',
  '  redact:            boolean,                   // default: true — run extras through b.redact',
  '  base:              object,                    // default: {} — fields stamped on every line (service, version, ...)',
  '  clock:             function,                  // default: () => new Date() — test seam for deterministic timestamps',
  '}</code></pre>',
  '<p>Structured JSON application logger with request-id correlation. Each line is one JSON object on a single line, terminated with <code>\\n</code>. Default routing splits info-and-below to stdout and warn-and-up to stderr; the multi-sink form takes full control of routing (each sink gets every line at-or-above its own level). The instance exposes <code>debug</code> / <code>info</code> / <code>warn</code> / <code>error</code> / <code>fatal</code>, plus <code>bind(extra)</code> for child loggers with stacked context, <code>middleware()</code> for a request-id-allocating router middleware, and <code>runWithRequestId</code> / <code>getRequestId</code> for AsyncLocalStorage propagation. Defends against Trojan-Source CVE-2021-42574 by escaping Unicode bidi / format controls in the JSON wire output.</p>',
  '<pre><code class="language-javascript">// var log = b.log.create({',
  '//   level: "info",',
  '//   base:  { service: "wiki", version: process.env.APP_VERSION },',
  '//   sinks: [',
  '//     { stream: process.stdout, level: "info"  },',
  '//     { stream: fs.createWriteStream("./logs/errors.log"), level: "error" },',
  '//   ],',
  '// });',
  '//',
  '// log.info("user logged in", { userId: "u-1" });',
  '// log.error("payment failed", { orderId: "o-42", err: e.message });',
  '//',
  '// Bound child logger with extra context',
  '// var authLog = log.bind({ component: "auth" });',
  '// authLog.warn("password reuse detected", { userId: "u-1" });',
  '//',
  '// Router middleware allocates a requestId and propagates it via ALS',
  '// r.use(log.middleware());',
  'typeof b.log.create; // "function"</code></pre>',

  '<h2 id="log-get-request-id">b.log.getRequestId() <a class="anchor" href="#log-get-request-id">#</a></h2>',
  '<p>Reads the current request id from AsyncLocalStorage. Returns the id when called inside a <code>runWithRequestId</code> / <code>middleware()</code> async chain, or <code>null</code> outside one. The module-level helper exists alongside the instance method so code paths that don\'t have a logger handle (e.g. a vendored utility deep in the call graph) can still tag emissions with the active request id.</p>',
  '<pre><code class="language-javascript">var requestId = b.log.getRequestId();',
  '// → "a3f1c9b8d4e2..." inside a request handler',
  '// → null outside one',
  '',
  '// Manual correlation when calling into a third-party library',
  '// thirdParty.observe({ requestId: b.log.getRequestId() });',
  'typeof b.log.getRequestId; // "function"</code></pre>',

  '<h2 id="log-run-with-request-id">b.log.runWithRequestId(requestId, fn) <a class="anchor" href="#log-run-with-request-id">#</a></h2>',
  '<p>Runs <code>fn</code> inside an AsyncLocalStorage scope with <code>requestId</code> bound. Every <code>log.info</code> / <code>log.error</code> / etc. emission inside the fn (including async continuations) carries the id. Pair with <code>b.log.middleware()</code> for the router-level path, or call directly from worker / scheduler code that processes off-request work.</p>',
  '<pre><code class="language-javascript">// Background worker tagging every emission with the originating job id',
  '// await b.log.runWithRequestId("job-" + jobId, async function () {',
  '//   log.info("job started", { jobId: jobId });',
  '//   await processJob(jobId);',
  '//   log.info("job completed", { jobId: jobId });',
  '// });',
  'typeof b.log.runWithRequestId; // "function"</code></pre>',

  '<h2 id="metrics-create">b.metrics.create(opts) <a class="anchor" href="#metrics-create">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  namespace:            string,    // default: "" — prepended to every metric name (e.g. "myapp_http_requests_total")',
  '  defaultLabels:        object,    // default: {} — stamped on every counter / gauge / histogram',
  '  labelCardinalityCap:  number,    // default: 10000 — per-metric ceiling on distinct label combinations',
  '}</code></pre>',
  '<p>Prometheus-format registry with counters, gauges, and histograms. Exposes <code>counter(name, opts)</code> / <code>gauge(name, opts)</code> / <code>histogram(name, opts)</code> factories, plus <code>requestMiddleware()</code> for auto-timed HTTP handlers and <code>expositionHandler()</code> for the <code>/metrics</code> endpoint. Framework hot paths (audit, vault, queue, error construction) call <code>b.metrics.tap</code> at runtime; <code>create()</code> wires the active registry into the tap so the framework\'s vital signs (audit events, queue depth, vault seal/unseal counts, error class counts) appear in the exposition for free. Cardinality cap prevents runaway label sets (one label per request id, full URL with query string) from OOMing the process — operators size up via <code>labelCardinalityCap</code> when they have a legitimate need.</p>',
  '<pre><code class="language-javascript">var m = b.metrics.create({',
  '  namespace:     "wiki",',
  '  defaultLabels: { service: "wiki", version: process.env.APP_VERSION },',
  '});',
  '',
  'var requests = m.counter("page_views_total", {',
  '  help:       "Total page views",',
  '  labelNames: ["route", "status"],',
  '});',
  'requests.inc({ route: "/welcome", status: "200" });',
  '',
  'var latency = m.histogram("page_render_seconds", {',
  '  help:       "Page render latency",',
  '  labelNames: ["route"],',
  '  buckets:    [0.005, 0.025, 0.1, 0.5, 1, 5],',
  '});',
  'latency.observe({ route: "/welcome" }, 0.142);',
  '',
  '// Auto-time every request + expose /metrics',
  'router.use(m.requestMiddleware());',
  'router.get("/metrics", m.expositionHandler());</code></pre>',

  '<h2 id="tracing-create">b.tracing.create(opts) <a class="anchor" href="#tracing-create">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  instrumentationName:    string,   // default: "blamejs" — OTel tracer name',
  '  instrumentationVersion: string,   // default: "0.0.0" — OTel tracer version',
  '}</code></pre>',
  '<p>OpenTelemetry seam without an OTel runtime dependency. When <code>@opentelemetry/api</code> is installed in the operator\'s app, every span call routes into OTel\'s real tracer and shows up in the wired exporter (Jaeger, Zipkin, OTLP, console). Without OTel, every call is a pass-through — fn still executes, return values still propagate, errors still escape, and the W3C <code>traceparent</code> parser still works so trace IDs propagate through logs and HTTP for correlation regardless. Exposes <code>span(name, fn, opts)</code> / <code>spanSync</code> / <code>currentSpan</code> / <code>setAttributes</code> / <code>recordException</code> / <code>contextHeaders</code> / <code>extractContext</code> / <code>requestMiddleware</code> / <code>tap</code>.</p>',
  '<pre><code class="language-javascript">var t = b.tracing.create({',
  '  instrumentationName:    "wiki",',
  '  instrumentationVersion: process.env.APP_VERSION,',
  '});',
  '',
  '// var result = await t.span("render-page", async function (span) {',
  '//   span.setAttribute("page.slug", slug);',
  '//   span.addEvent("cache-miss");',
  '//   return await renderPage(slug);',
  '// }, { kind: "internal", attributes: { route: "/page/:slug" } });',
  '//',
  '// Auto-span every request named "HTTP <method> <route>"',
  '// router.use(t.requestMiddleware());',
  '//',
  '// Outbound HTTP carries the W3C traceparent header for correlation',
  'var headers = t.contextHeaders();',
  'typeof headers === "object";</code></pre>',

  '<h2 id="alerting">Alerting on framework events <a class="anchor" href="#alerting">#</a></h2>',
  '<p>The framework emits structured events (audit chain rows + observability counters) but does not run alerting itself — alerting lives in the operator\'s SIEM / Prometheus / PagerDuty stack. The signals below are the ones most commonly worth a page; thresholds are starting points, not policy.</p>',
  '<table>',
  '  <thead><tr><th>Signal</th><th>Why it matters</th><th>Suggested rule</th></tr></thead>',
  '  <tbody>',
  '    <tr><td><code>auth.lockout.triggered</code></td><td>Sustained credential brute force against an account.</td><td>&gt; 5 events in 1h for the same key → page on-call.</td></tr>',
  '    <tr><td><code>apikey.verify.failure</code> spike</td><td>Token leaked or revoked-but-still-being-used.</td><td>Failure rate &gt; 10% sustained for 5 min → ticket; spike &gt; 100/min → page.</td></tr>',
  '    <tr><td><code>permissions.check.deny</code></td><td>Path-level access attempts with wrong scope; could be reconnaissance OR a permissions misconfig.</td><td>Distinct-actor count &gt; 20 in 1h → ticket. Per-actor &gt; 50/h → page.</td></tr>',
  '    <tr><td><code>permissions.mfa.required</code></td><td>Privileged route hit without MFA — operator workflow breakdown OR active probing.</td><td>Any → ticket. Burst &gt; 5/min → page.</td></tr>',
  '    <tr><td><code>auth.session.fingerprint_drift</code></td><td>Session token used from a different IP / UA than the create.</td><td>Per-session count &gt; 1 → log. Per-user &gt; 3 in 1h → ticket. Geographically impossible → page.</td></tr>',
  '    <tr><td><code>breakglass.grant.created</code> + <code>breakglass.row.unsealed</code></td><td>Every PHI / PCI cleartext access. Compliance requires after-the-fact review.</td><td>Daily digest to compliance inbox. Spike &gt; 3× weekday baseline → ticket.</td></tr>',
  '    <tr><td><code>db.role.switched</code> spike</td><td>Per-role binding usage out of normal pattern.</td><td>Per-role rate change &gt; 5× baseline → ticket.</td></tr>',
  '    <tr><td><code>config.drift.detected</code></td><td>Runtime config changed between boots — silent ops change.</td><td>Any → ticket. <code>config.baseline.tamper</code> → page (sidecar tampered, not just changed).</td></tr>',
  '    <tr><td><code>system.security.assert.failure</code></td><td>Production posture assertion failed at boot — the deploy went out with a weak posture.</td><td>Any → page. The boot already failed; this is the post-mortem trail.</td></tr>',
  '    <tr><td><code>dual.grant.consumed</code></td><td>Destructive op ran with two-person approval. Compliance trail.</td><td>Daily digest. <code>dual.grant.expired</code> spike → ticket (workflow stalling).</td></tr>',
  '    <tr><td><code>retention.sweep.failed</code></td><td>Retention rule errored mid-run — data is older than the declared TTL.</td><td>Any → ticket. Repeated failure on the same rule → page.</td></tr>',
  '    <tr><td><code>network.gate.denied</code></td><td>Admin / internal route reached from outside the allowed CIDR — probable scan or misrouted traffic.</td><td>Burst &gt; 10/min → page. Sustained &gt; 100/h → ticket.</td></tr>',
  '    <tr><td><code>system.scheduler.tick.skew</code></td><td>Scheduler tick fired late by &gt; 30 s — clock skew, leader churn, or process pause.</td><td>Any &gt; 60s → ticket.</td></tr>',
  '  </tbody>',
  '</table>',
  '<p>Wire <code>b.logStream</code> to your SIEM and these events flow into your existing alerting; wire <code>b.otelExport</code> and the framework counters land alongside them. Both primitives let the alerting rules live where the operator already owns the on-call rotation.</p>',
].join("\n"),
};
