"use strict";

module.exports = {
  slug:  "outbound-http",
  title: "Outbound HTTP",
  body: [
  '<h1>Outbound HTTP</h1>',
  '<p><code>b.httpClient</code> is the framework\'s outbound HTTP. It exists so app code can call upstream services without dragging in <code>axios</code> / <code>got</code> / <code>node-fetch</code> as transitive deps. Every outbound request passes through <code>b.safeUrl</code> (scheme allowlist) and <code>b.ssrfGuard</code> (IP-range gate) before the socket opens.</p>',

  '<h2 id="http-client">HTTP client <a class="anchor" href="#http-client">#</a></h2>',
  '<pre><code class="language-javascript">var res = await b.httpClient.request({',
  '  method:    "POST",',
  '  url:       "https://upstream.example.com/api/v1/things",',
  '  body:      JSON.stringify(payload),',
  '  headers:   { "content-type": "application/json" },',
  '  timeoutMs: C.TIME.seconds(10),',
  '  retry:     { maxAttempts: 3, isPermanent: function (e) { return e.statusCode === 401; } },',
  '});',
  '// res.statusCode, res.headers, res.body (Buffer); audit + observability emitted.</code></pre>',
  '<p>HTTP/1.1 + HTTP/2 via ALPN per origin (h2 preferred), connection-pooled, AbortSignal-aware. Webhook delivery, OAuth token exchange, mail HTTP transports, object-store adapters, and notify all inherit the same SSRF protection without per-call setup.</p>',

  '<h3 id="http-client-redirect">Redirect following <a class="anchor" href="#http-client-redirect">#</a></h3>',
  '<p>Pass <code>maxRedirects: N</code> to follow up to N hops. Without the opt, 3xx responses still throw as <code>HTTP_ERROR</code> (existing contract).</p>',
  '<pre><code class="language-javascript">var res = await b.httpClient.request({',
  '  url:          "https://short.ly/abc",',
  '  maxRedirects: 5,',
  '});',
  '// → final 2xx after up to 5 hops; SSRF gate runs at every hop;',
  '//   Authorization / Cookie / Proxy-Authorization headers strip on',
  '//   cross-origin hops; 303 always coerces follow-up to GET; 307/308',
  '//   preserve method + body.</code></pre>',

  '<h3 id="http-client-multipart">Outbound multipart <a class="anchor" href="#http-client-multipart">#</a></h3>',
  '<p>Round-trip parity with <code>b.middleware.bodyParser</code>. The framework builds the body with a random boundary; method defaults to POST.</p>',
  '<pre><code class="language-javascript">await b.httpClient.request({',
  '  url: "https://upstream/upload",',
  '  multipart: {',
  '    fields: { title: "Doc", tags: ["a", "b"] },     // arrays repeat the field',
  '    files:  [{ field: "file", filename: "x.txt",',
  '               contentType: "text/plain", content: buf }],',
  '  },',
  '});</code></pre>',

  '<h3 id="http-client-interceptors">Interceptors <a class="anchor" href="#http-client-interceptors">#</a></h3>',
  '<p><code>before</code> hooks mutate or replace the request opts; <code>after</code> hooks observe the final opts + response. Operators inject auth headers, observability, audit emits without wrapping <code>request</code>.</p>',
  '<pre><code class="language-javascript">await b.httpClient.request({',
  '  url:    "https://upstream/data",',
  '  before: [function (req) {',
  '    req.headers = Object.assign({}, req.headers || {},',
  '      { Authorization: "Bearer " + currentToken() });',
  '    return req;',
  '  }],',
  '  after:  [function (reqOpts, res) {',
  '    metrics.counter("upstream.calls").inc({ status: res.statusCode });',
  '  }],',
  '});</code></pre>',
  '<p><code>before</code> throws surface as <code>BEFORE_THREW</code> errors. <code>after</code> throws are caught — a broken hook never blocks the response.</p>',

  '<h3 id="http-client-progress">Upload + download progress <a class="anchor" href="#http-client-progress">#</a></h3>',
  '<pre><code class="language-javascript">await b.httpClient.request({',
  '  url:                "https://upstream/upload",',
  '  method:             "POST",',
  '  body:               largeBuffer,',
  '  onUploadProgress:   function (e) { /* { loaded, total } */ },',
  '  onDownloadProgress: function (e) { /* { loaded, total } */ },',
  '});</code></pre>',
  '<p>Buffer / string bodies are sliced into 64 KiB chunks for incremental upload progress; <code>Readable</code> bodies emit on each <code>data</code> event from the source. Download progress fires on each response chunk; <code>total</code> is <code>Content-Length</code> when present, <code>null</code> otherwise.</p>',

  '<h3 id="http-client-cookie-jar">Cookie jar <a class="anchor" href="#http-client-cookie-jar">#</a></h3>',
  '<p>For multi-call flows where outbound cookies need to persist across requests — login → mutate → logout, OAuth code-exchange → userinfo, etc. Default in-memory; <code>persist: "vault"</code> seals every cookie value via <code>b.vault.seal</code> so a memory dump or core file never exposes plaintext cookie state.</p>',
  '<pre><code class="language-javascript">var jar = b.httpClient.cookieJar.create({',
  '  persist: "vault",',
  '  vault:   b.vault,',
  '});',
  '',
  'await b.httpClient.request({ url: loginUrl, method: "POST", body, jar: jar });',
  'await b.httpClient.request({ url: meUrl, jar: jar });   // session cookie attaches</code></pre>',
  '<p>RFC 6265 attribute coverage: Domain (with subdomain match), Path (prefix match), Expires / Max-Age (Max-Age wins on conflict), HttpOnly, Secure, SameSite. Outbound sort follows §5.4 — longer path first, earlier creation time second.</p>',

  '<h2 id="ssrf-guard">SSRF guard <a class="anchor" href="#ssrf-guard">#</a></h2>',
  '<p><code>b.ssrfGuard</code> is the framework\'s outbound-URL gate. Every <code>b.httpClient.request({ url })</code> call resolves the hostname through DNS, classifies the resolved IP, and refuses the request with an <code>SsrfError</code> if the IP lands in any of the unsafe ranges:</p>',
  '<ul>',
  '  <li>IPv4 private (RFC 1918): 10/8, 172.16/12, 192.168/16</li>',
  '  <li>IPv4 loopback: 127/8 — and IPv6 ::1</li>',
  '  <li>IPv4 link-local: 169.254/16 — and IPv6 fe80::/10</li>',
  '  <li>IPv6 ULA (private): fc00::/7</li>',
  '  <li>Cloud metadata: 169.254.169.254 (AWS / GCP / Azure / DO / OpenStack), 169.254.170.2 (AWS ECS), fd00:ec2::254</li>',
  '  <li>Reserved / documentation / multicast / broadcast ranges</li>',
  '</ul>',
  '<p>DNS rebinding TOCTOU is closed by the IP-pinning resolver: the IPs the gate validates are passed to <code>connect()</code> directly, so a hostile DNS that re-resolves to a private IP between the check and the connect can\'t bypass the gate.</p>',
  '<pre><code class="language-javascript">// Unrestricted internal mesh — bypass the gate entirely',
  'b.httpClient.request({ url: "http://internal.svc/health", allowInternal: true });',
  '',
  '// Narrower override — allow only specific CIDRs through',
  'b.httpClient.request({',
  '  url:           "http://10.0.5.1:8080",',
  '  allowInternal: ["10.0.0.0/8", "192.168.0.0/16"],',
  '});</code></pre>',
  '<p>Standalone use — for example, validating a user-supplied webhook URL before storing it:</p>',
  '<pre><code class="language-javascript">try {',
  '  await b.ssrfGuard.checkUrl(req.body.webhookUrl);',
  '  // safe to store',
  '} catch (e) {',
  '  return res.status(400).json({ error: "URL refused: " + e.code });',
  '}</code></pre>',
  '<p>Classification helpers (<code>classify(ip)</code>, <code>isPrivate(ip)</code>, <code>isLoopback(ip)</code>, <code>isCloudMetadata(ip)</code>, <code>cidrContains(cidr, ip)</code>) cover the offline cases — operators building a custom validator (e.g. to refuse a Slack webhook hostname) compose these without DNS round-trips.</p>',

  '<h2 id="safe-url">Safe URL parsing <a class="anchor" href="#safe-url">#</a></h2>',
  '<p><code>b.safeUrl.parse(input, { allowedProtocols })</code> validates a URL\'s shape and protocol before any network I/O sees it. Defaults accept <code>https:</code> only — <code>file:</code>, <code>data:</code>, <code>javascript:</code>, plain <code>http:</code>, and other schemes are rejected. Operators with internal cleartext endpoints opt in via <code>safeUrl.ALLOW_HTTP_ALL</code> or <code>safeUrl.ALLOW_HTTP_TLS</code>. The IP-range guard is a separate concern handled by <code>b.ssrfGuard</code>.</p>',

  '<h2 id="webhook">Webhook signer + verifier <a class="anchor" href="#webhook">#</a></h2>',
  '<p><code>b.webhook</code> covers two halves: <code>signer</code> for outbound deliveries you author, <code>verifier</code> for inbound deliveries from third parties. The framework owns the wire shape so operators don\'t hand-roll HMAC code per integration.</p>',
  '<pre><code class="language-javascript">// Outbound — sign + deliver',
  'var signer = b.webhook.signer.create({',
  '  algo:        "hmac-sha3-512",          // default; or "pqc-pem" for SLH-DSA keys',
  '  keys:        { active: { kid: "k1", secret: env("WEBHOOK_SECRET") } },',
  '  toleranceMs: C.TIME.minutes(5),',
  '});',
  '',
  'var delivery = b.webhook.delivery.create({',
  '  httpClient: b.httpClient,',
  '  signer:     signer,',
  '  retry:      { maxAttempts: 5 },',
  '});',
  'await delivery.send({ url: "https://customer.example.com/hooks", payload: { ... } });',
  '',
  '// Inbound — verify',
  'var verifier = b.webhook.verifier.create({',
  '  keys:        { k1: env("WEBHOOK_SECRET") },',
  '  toleranceMs: C.TIME.minutes(5),',
  '  nonceStore:  b.nonceStore.create({ backend: "cluster" }),  // replay defense',
  '});',
  '',
  'router.post("/hooks/in", b.middleware.bodyParser.raw(), async function (req, res) {',
  '  try { await verifier.verify(req.headers["x-blamejs-signature"], req.body); }',
  '  catch (e) { return res.status(401).end(); }',
  '  // proceed with the body — verified + replay-checked',
  '});</code></pre>',
  '<p>Header shape is Stripe-compatible: <code>t=&lt;sec&gt;,id=&lt;uuid&gt;,&lt;kid&gt;=&lt;sig&gt;</code>. <code>id</code> + <code>nonceStore</code> give one-time-use semantics; replays fail. Multi-key rotation works the same way as JWT — keep old <code>kid</code>s in the verifier map until you\'re sure no in-flight delivery is signed by them.</p>',
].join("\n"),
};
