"use strict";

module.exports = {
  slug:  "outbound-http",
  title: "Outbound HTTP",
  body: [
  '<h1>Outbound HTTP</h1>',
  '<p><code>b.httpClient</code> is the framework\'s outbound HTTP. It exists so app code can call upstream services without dragging in <code>axios</code> / <code>got</code> / <code>node-fetch</code> as transitive deps. Every outbound request passes through <code>b.safeUrl</code> (scheme allowlist) and <code>b.ssrfGuard</code> (IP-range gate) before the socket opens.</p>',

  '<h2 id="http-client">HTTP client</h2>',

  '<h3>b.httpClient.request(opts) <a class="anchor" href="#http-client-request">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  method:           string,                  // default: "GET"',
  '  url:              string | URL,            // required',
  '  body:             string | Buffer | Readable | object,  // object → JSON-encoded',
  '  headers:          object,                  // request headers',
  '  timeoutMs:        number,                  // default: C.TIME.seconds(30)',
  '  idleTimeoutMs:    number,                  // default: C.TIME.seconds(15)',
  '  retry:            { maxAttempts, baseDelayMs, isPermanent, ... },',
  '  maxRedirects:     number,                  // default: 0 — 3xx surfaces as HTTP_ERROR',
  '  multipart:        { fields, files },       // mutually exclusive with body',
  '  allowedProtocols: [string],                // default: HTTPS only',
  '  allowedHosts:     [string],                // exact / .suffix / per-method entries',
  '  allowInternal:    boolean | [CIDR],        // default: false — bypasses SSRF gate',
  '  jar:              cookieJar,               // optional — RFC 6265 jar instance',
  '  responseMode:     "buffer" | "stream",     // default: "buffer"',
  '  maxResponseBytes: number,                  // default: C.BYTES.mib(8)',
  '  onUploadProgress: (e) => void,             // { loaded, total }',
  '  onDownloadProgress: (e) => void,           // { loaded, total }',
  '  before:           [(req) => req | null],   // mutate / replace request opts',
  '  after:            [(reqOpts, res) => void], // observe final opts + response',
  '  errorClass:       errorClass,              // default: HttpClientError',
  '}</code></pre>',
  '<p>HTTP/1.1 + HTTP/2 via ALPN per origin (h2 preferred), connection-pooled, AbortSignal-aware. Returns <code>{ statusCode, headers, body }</code>. Webhook delivery, OAuth token exchange, mail HTTP transports, object-store adapters, and notify all inherit the same SSRF protection without per-call setup.</p>',
  '<pre><code class="language-javascript">// Async signature — call shape only here; live network call would need',
  '// a real upstream. The signature + opts model are what operators write.',
  'var reqShape = {',
  '  method:    "POST",',
  '  url:       "https://upstream.example.com/api/v1/things",',
  '  body:      JSON.stringify({ k: "v" }),',
  '  headers:   { "content-type": "application/json" },',
  '  timeoutMs: b.constants.TIME.seconds(10),',
  '  retry:     { maxAttempts: 3, isPermanent: function (e) { return e.statusCode === 401; } },',
  '};',
  '// var res = await b.httpClient.request(reqShape);',
  '// res.statusCode, res.headers, res.body (Buffer); audit + observability emitted.',
  'b.httpClient.request;   // function — exists on the live framework</code></pre>',

  '<h3 id="http-client-redirect">b.httpClient.request({ maxRedirects }) <a class="anchor" href="#http-client-redirect">#</a></h3>',
  '<p>Pass <code>maxRedirects: N</code> to follow up to N hops. Without the opt, 3xx responses still throw as <code>HTTP_ERROR</code>. The SSRF gate runs at every hop; <code>Authorization</code> / <code>Cookie</code> / <code>Proxy-Authorization</code> headers strip on cross-origin hops; 303 always coerces follow-up to GET; 307/308 preserve method + body.</p>',
  '<pre><code class="language-javascript">var reqShape = { url: "https://short.ly/abc", maxRedirects: 5 };',
  '// var res = await b.httpClient.request(reqShape);',
  'b.httpClient.request;</code></pre>',

  '<h3 id="http-client-multipart">b.httpClient.request({ multipart }) <a class="anchor" href="#http-client-multipart">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  fields:         { <name>: string | [string] },',
  '  files:          [{ field, filename, contentType, content }],',
  '}</code></pre>',
  '<p>Round-trip parity with <code>b.middleware.bodyParser({ multipart: ... })</code>. The framework builds the body with a random boundary; method defaults to POST. Buffers, strings, or <code>Readable</code> streams accepted as <code>content</code>.</p>',
  '<pre><code class="language-javascript">var reqShape = {',
  '  url: "https://upstream/upload",',
  '  multipart: {',
  '    fields: { title: "Doc", tags: ["a", "b"] },',
  '    files:  [{ field: "file", filename: "x.txt",',
  '               contentType: "text/plain", content: largeBuffer }],',
  '  },',
  '};',
  'b.httpClient.request;</code></pre>',

  '<h3 id="http-client-interceptors">b.httpClient.request({ before, after }) <a class="anchor" href="#http-client-interceptors">#</a></h3>',
  '<p><code>before</code> hooks mutate or replace the request opts; <code>after</code> hooks observe the final opts + response. Operators inject auth headers, observability, audit emits without wrapping <code>request</code>. <code>before</code> throws surface as <code>BEFORE_THREW</code>. <code>after</code> throws are caught — a broken hook never blocks the response.</p>',
  '<pre><code class="language-javascript">var reqShape = {',
  '  url:    "https://upstream/data",',
  '  before: [function (req) {',
  '    req.headers = Object.assign({}, req.headers || {},',
  '      { Authorization: "Bearer " + currentToken() });',
  '    return req;',
  '  }],',
  '  after:  [function (_reqOpts, res) {',
  '    metrics.counter("upstream.calls").inc({ status: res.statusCode });',
  '  }],',
  '};',
  'b.httpClient.request;</code></pre>',

  '<h3 id="http-client-cookie-jar">b.httpClient.cookieJar.create(opts?) <a class="anchor" href="#http-client-cookie-jar">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  persist:        "memory" | "vault" | "file",  // default: "memory"',
  '  vault:          vaultInstance,            // required when persist === "vault"',
  '  file:           string,                   // absolute path; required when persist === "file"',
  '  flushDebounceMs: number,                  // default: C.TIME.seconds(2)',
  '}</code></pre>',
  '<p>RFC 6265 jar for multi-call flows where outbound cookies need to persist across requests — login → mutate → logout, OAuth code-exchange → userinfo, etc. <code>persist: "vault"</code> seals every cookie value via <code>b.vault.seal</code> so a memory dump or core file never exposes plaintext cookie state. Attribute coverage: Domain (with subdomain match), Path (prefix match), Expires / Max-Age (Max-Age wins on conflict), HttpOnly, Secure, SameSite.</p>',
  '<pre><code class="language-javascript">var jar = b.httpClient.cookieJar.create({ persist: "memory" });',
  '// jar passes to subsequent requests via { jar }; the harness exec proves',
  '// the factory shape and that .persist defaults work.',
  'jar.set || jar;   // jar is the operator-side cookie store</code></pre>',

  '<h2 id="http-client-pool">Connection pool tuning</h2>',

  '<h3 id="http-client-configure-pool">b.httpClient.configurePool(opts) <a class="anchor" href="#http-client-configure-pool">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  keepAlive:       boolean,                  // default: true',
  '  keepAliveMsecs:  number,                   // default: C.TIME.seconds(1) — positive integer',
  '  maxSockets:      number,                   // default: 16 — positive integer, per origin',
  '  maxFreeSockets:  number,                   // default: 8 — positive integer',
  '  scheduling:      "lifo" | "fifo",          // default: "lifo"',
  '}</code></pre>',
  '<p>Boot-time tuning for the per-origin transport cache. Existing transports keep the values they were built with (Node\'s <code>http.Agent</code> copies opts at construction); <code>configurePool</code> drops the cache and tears down idle agents + h2 sessions so subsequent requests build fresh transports with the new opts. The framework\'s PQC-only TLS posture (<code>ecdhCurve</code>, <code>minVersion</code>) lives in <code>lib/pqc-agent.js</code> and is NOT operator-tunable here — one place owns the TLS posture. Bad input throws at <code>configurePool</code> time so operators catch typos at boot, not first request.</p>',
  '<pre><code class="language-javascript">b.httpClient.configurePool({',
  '  maxSockets:     32,                        // raise per-origin parallelism for a heavy upstream',
  '  maxFreeSockets: 16,',
  '  keepAliveMsecs: b.constants.TIME.seconds(2),',
  '  scheduling:     "lifo",                    // reuse hottest socket first',
  '});',
  '// Subsequent b.httpClient.request(...) calls build new agents with the updated opts.</code></pre>',

  '<h2 id="http-client-streaming">Streaming primitives</h2>',

  '<h3 id="http-client-download-stream">b.httpClient.downloadStream(opts) <a class="anchor" href="#http-client-download-stream">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  url:              string,                  // required — runs through safeUrl + ssrfGuard',
  '  dest:             string,                  // required — final on-disk path; framework writes <dest>.tmp-<rand> first',
  '  hash:             "sha3-512" | "sha-256" | "sha-512" | "shake256",  // default: "sha3-512"',
  '  expected:         string,                  // optional — hex digest; mismatch deletes tmp + throws httpclient/hash-mismatch',
  '  agent:            httpAgent,               // optional — override per-origin pool (h1 only)',
  '  timeoutMs:        number,                  // wall-clock cap, positive finite ms',
  '  idleTimeoutMs:    number,                  // zero-progress idle cap',
  '  maxBytes:         number,                  // optional — refuses + cleans tmp on overrun',
  '  signal:           AbortSignal,             // propagated to req + pipeline',
  '  allowedProtocols: tokenSet,                // default: HTTPS only',
  '  allowedHosts:     [string],                // optional egress allowlist',
  '  allowInternal:    boolean | [CIDR],        // default: false — bypasses SSRF gate',
  '  audit:            auditEmitter,            // optional — receives .completed / .refused emits',
  '}</code></pre>',
  '<p>Streams a GET response body to <code>&lt;dest&gt;.tmp-&lt;rand&gt;</code> with mode 0o600, hashes-while-piping with a single Transform pass (no Buffer.concat), <code>fsync</code>s the tmp file, and atomically renames to <code>dest</code> only after the hash compares clean. On hash mismatch the tmp is deleted and an <code>HttpClientError</code> with code <code>httpclient/hash-mismatch</code> throws; non-2xx upstream surfaces as <code>httpclient/http-error</code>; pipeline / rename / response-too-large failures throw with matching codes and clean up the tmp. Returns <code>{ statusCode, bytesWritten, hash }</code> — the hex digest is always returned even when no <code>expected</code> was supplied, so callers can record / compare downstream. Audit emits <code>system.httpclient.download_stream.completed</code> on success, <code>.refused</code> on every failure path with a <code>reason</code> tag.</p>',
  '<pre><code class="language-javascript">// Pin a vendored binary by sha3-512; a wrong digest or a tampered',
  '// upstream leaves the destination untouched.',
  '// var result = await b.httpClient.downloadStream({',
  '//   url:      "https://releases.example.com/bin/v1.2.3/blamejs-cli.tar.gz",',
  '//   dest:     "/var/lib/blamejs/cli/v1.2.3.tar.gz",',
  '//   hash:     "sha3-512",',
  '//   expected: "abc123...def",  // pinned digest from the publisher',
  '//   timeoutMs:        b.constants.TIME.minutes(5),',
  '//   maxBytes:         b.constants.BYTES.mib(64),',
  '//   audit:            b.audit,',
  '// });',
  '// result.statusCode    // 200',
  '// result.bytesWritten  // exact byte count piped to disk',
  '// result.hash          // hex digest the operator can log / compare',
  'typeof b.httpClient.downloadStream; // "function"</code></pre>',

  '<h3 id="http-client-upload-multipart-stream">b.httpClient.uploadMultipartStream(opts) <a class="anchor" href="#http-client-upload-multipart-stream">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  url:              string,                  // required — runs through safeUrl + ssrfGuard',
  '  fields:           object,                  // optional text fields (string values), serialized first',
  '  file: {',
  '    path:        string,                     // required — on-disk path piped via fs.createReadStream',
  '    fieldName:   string,                     // required — multipart field name',
  '    filename:    string,                     // optional — defaults to basename(path)',
  '    contentType: string,                     // optional — defaults to "application/octet-stream"',
  '  },',
  '  agent:            httpAgent,               // optional — override per-origin pool',
  '  timeoutMs:        number,                  // wall-clock cap',
  '  idleTimeoutMs:    number,                  // zero-progress idle cap',
  '  maxBytes:         number,                  // optional — request body cap',
  '  signal:           AbortSignal,             // propagated',
  '  allowedProtocols: tokenSet,                // default: HTTPS only',
  '  allowedHosts:     [string],                // optional egress allowlist',
  '  allowInternal:    boolean | [CIDR],        // default: false',
  '  audit:            auditEmitter,            // optional',
  '}</code></pre>',
  '<p>POSTs a file as <code>multipart/form-data</code> without buffering: text <code>fields</code> serialize first, then the file part with the operator-supplied <code>contentType</code> (default <code>application/octet-stream</code>) is piped from disk via <code>fs.createReadStream</code>. The same <code>safeUrl</code> + <code>ssrfGuard</code> + <code>allowedHosts</code> + per-origin transport cache as <code>request()</code> apply unchanged. Refuses at config-time when <code>file.path</code> is missing or non-regular — code <code>httpclient/missing-file</code>. Returns <code>{ statusCode, response }</code>. Audit emits <code>system.httpclient.upload_stream.completed</code> on success, <code>.refused</code> on every failure with a <code>reason</code> tag.</p>',
  '<pre><code class="language-javascript">// Stream a multi-GiB capture upstream without holding the body in memory.',
  '// var result = await b.httpClient.uploadMultipartStream({',
  '//   url:    "https://intake.example.com/uploads",',
  '//   fields: { caseId: "abc-123", uploader: "svc-account" },',
  '//   file: {',
  '//     path:        "/var/lib/blamejs/captures/case-abc-123.pcap",',
  '//     fieldName:   "capture",',
  '//     filename:    "case-abc-123.pcap",',
  '//     contentType: "application/vnd.tcpdump.pcap",',
  '//   },',
  '//   timeoutMs: b.constants.TIME.minutes(15),',
  '//   audit:     b.audit,',
  '// });',
  '// result.statusCode  // upstream response code',
  '// result.response    // raw response object from b.httpClient.request',
  'typeof b.httpClient.uploadMultipartStream; // "function"</code></pre>',

  '<h2 id="http-client-encrypted-section">PQC-encrypted client</h2>',

  '<h3 id="http-client-encrypted">b.httpClient.encrypted(opts) <a class="anchor" href="#http-client-encrypted">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  pubkey:            object,                 // required — callee\'s publishPublicKey() bootstrap doc',
  '  baseUrl:           string,                 // optional — required when calling .request({ path })',
  '  headers:           object,                 // default-applied headers (e.g. Authorization)',
  '  method:            string,                 // default: "POST"',
  '  maxDecryptedBytes: number,                 // default: C.BYTES.mib(4) — response plaintext cap',
  '  keying:            "per-request" | "per-session",  // default: "per-request"',
  '}</code></pre>',
  '<p>PQC-encrypted variant of <code>b.httpClient.request</code>. Wraps every body in an ML-KEM-1024 envelope to the callee\'s published public key, sends through <code>b.httpClient.request</code> (so SSRF + safeUrl + allowedHosts gates still apply), then decrypts + JSON-parses the response. Built for blamejs ↔ blamejs service calls where both peers run <code>b.middleware.apiEncrypt</code>. Returns an instance with a single <code>.request(reqOpts)</code> method; <code>reqOpts.url</code> or <code>reqOpts.path</code> (with <code>baseUrl</code> at create time) selects the destination. Response body lands as decrypted plaintext object — the helper handles JSON-shaped payloads only, matching the middleware\'s default content types.</p>',
  '<pre><code class="language-javascript">// var enc = b.httpClient.encrypted({',
  '//   pubkey:  callee.pubkey,                    // { publicKey, ecPublicKey } from callee.publishPublicKey()',
  '//   baseUrl: "https://callee.example",',
  '//   headers: { Authorization: "Bearer " + currentToken() },',
  '// });',
  '// var resp = await enc.request({ method: "POST", path: "/api/widget",',
  '//                                body: { user: "alice" } });',
  '// resp.body  // → decrypted plaintext object',
  'typeof b.httpClient.encrypted; // "function"</code></pre>',

  '<h2 id="auth-header">Authorization headers</h2>',

  '<h3>b.authHeader.basic(username, password) <a class="anchor" href="#auth-header-basic">#</a></h3>',
  '<p>Builds the RFC 7617 Basic <code>Authorization</code> header for an outbound request. <code>username</code> is required (passing <code>null</code>/<code>undefined</code> throws — silent <code>"undefined:..."</code> credentials are a recurring source of confused-deputy outages); empty-string username is allowed for endpoints that genuinely want <code>Basic &lt;b64("::")&gt;</code>. Returns <code>{ Authorization: "Basic &lt;b64(user:pass)&gt;" }</code>.</p>',
  '<pre><code class="language-javascript">var headers = b.authHeader.basic("alice", "s3cret");',
  '// → { Authorization: "Basic YWxpY2U6czNjcmV0" }</code></pre>',

  '<h3>b.authHeader.bearer(token) <a class="anchor" href="#auth-header-bearer">#</a></h3>',
  '<p>Builds the RFC 6750 Bearer <code>Authorization</code> header. Empty / non-string tokens throw at call time so a missing token surfaces at the call site rather than as a blank header sent on the wire. Returns <code>{ Authorization: "Bearer &lt;token&gt;" }</code>.</p>',
  '<pre><code class="language-javascript">var headers = b.authHeader.bearer("eyJhbGciOiJIUzI1Ni...");',
  '// → { Authorization: "Bearer eyJhbGciOiJIUzI1Ni..." }</code></pre>',

  '<h3>b.authHeader.fromConfig(opts) <a class="anchor" href="#auth-header-from-config">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  auth:      "none" | "bearer" | "basic",   // required — branch selector',
  '  token:     string,                         // auth === "bearer"',
  '  username:  string,                         // auth === "basic"',
  '  password:  string,                         // auth === "basic" (optional, defaults to "")',
  '}</code></pre>',
  '<p>Config-driven dispatch — operators wire one block of YAML / env config and the framework picks the right header builder. <code>auth: "none"</code> returns <code>{}</code> (so callers can <code>Object.assign</code> unconditionally). Unknown <code>auth</code> values throw <code>AuthHeaderError</code> with code <code>auth-header/unknown-method</code>. Header pass-through ("just merge these headers") is intentionally NOT a mode here — that\'s plain header merging at the call site, not authorization construction.</p>',
  '<pre><code class="language-javascript">// Same call site for every webhook destination, regardless of auth flavor.',
  'var hdrs = b.authHeader.fromConfig({ auth: "bearer", token: "demo-token-value" });',
  '// or fromConfig({ auth: "basic", username: "svc", password: process.env.UPSTREAM_PASS })',
  '// or fromConfig({ auth: "none" })',
  '',
  '// var res = await b.httpClient.request({',
  '//   url:     "https://upstream/api/v1/things",',
  '//   headers: Object.assign({ "content-type": "application/json" }, hdrs),',
  '// });',
  'typeof hdrs.Authorization === "string";</code></pre>',

  '<h2 id="ssrf-guard">SSRF guard</h2>',

  '<h3>b.ssrfGuard.checkUrl(url, opts?) <a class="anchor" href="#ssrf-guard-checkurl">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  allowedProtocols: [string],               // default: ["https:"]',
  '  allowInternal:   boolean | [CIDR string], // default: false',
  '  resolver:        dnsResolver,             // default: b.network.dns',
  '  errorClass:      errorClass,              // default: SsrfError',
  '}</code></pre>',
  '<p>Resolves the hostname through DNS, classifies every resolved IP, and refuses the request with an <code>SsrfError</code> if the IP lands in any of the unsafe ranges: IPv4 private (RFC 1918), loopback, link-local, IPv6 ULA, cloud metadata (hard-denied even with <code>allowInternal: true</code>), reserved ranges. DNS rebinding TOCTOU is closed by the IP-pinning resolver: the IPs the gate validates are passed to <code>connect()</code> directly.</p>',
  '<pre><code class="language-javascript">// Standalone — validating a user-supplied webhook URL before storing it.',
  '// Exec proves the function shape; live DNS resolution would happen on real',
  '// hosts.',
  'b.ssrfGuard.checkUrl;</code></pre>',

  '<h3>b.ssrfGuard.classify(ip) <a class="anchor" href="#ssrf-classify">#</a></h3>',
  '<p>Offline IP classifier. Returns one of <code>"private"</code>, <code>"loopback"</code>, <code>"link-local"</code>, <code>"cloud-metadata"</code>, <code>"ula"</code>, <code>"reserved"</code>, <code>"public"</code>. Pure synchronous function — operators building a custom validator (e.g. to refuse a Slack webhook hostname before storing it) call <code>classify</code> after their own DNS resolution without a second round-trip through <code>checkUrl</code>.</p>',
  '<pre><code class="language-javascript">b.ssrfGuard.classify("169.254.169.254");      // → "cloud-metadata"',
  'b.ssrfGuard.classify("10.0.0.5");              // → "private"',
  'b.ssrfGuard.classify("127.0.0.1");             // → "loopback"',
  'b.ssrfGuard.classify("8.8.8.8");               // → "public"</code></pre>',

  '<h2 id="ssrf-private">b.ssrfGuard.isPrivate(ip) <a class="anchor" href="#ssrf-private">#</a></h2>',
  '<p>Returns true for RFC1918 private address ranges.</p>',
  '<pre><code class="language-javascript">typeof b.ssrfGuard.isPrivate; // "function"</code></pre>',

  '<h2 id="ssrf-loopback">b.ssrfGuard.isLoopback(ip) <a class="anchor" href="#ssrf-loopback">#</a></h2>',
  '<p>Returns true for IPv4 and IPv6 loopback ranges.</p>',
  '<pre><code class="language-javascript">typeof b.ssrfGuard.isLoopback; // "function"</code></pre>',

  '<h2 id="ssrf-link-local">b.ssrfGuard.isLinkLocal(ip) <a class="anchor" href="#ssrf-link-local">#</a></h2>',
  '<p>Returns true for link-local ranges that should not be reachable from server-side fetches.</p>',
  '<pre><code class="language-javascript">typeof b.ssrfGuard.isLinkLocal; // "function"</code></pre>',

  '<h2 id="ssrf-cloud-metadata">b.ssrfGuard.isCloudMetadata(ip) <a class="anchor" href="#ssrf-cloud-metadata">#</a></h2>',
  '<p>Detects cloud metadata service addresses such as <code>169.254.169.254</code>.</p>',
  '<pre><code class="language-javascript">typeof b.ssrfGuard.isCloudMetadata; // "function"</code></pre>',

  '<h2 id="ssrf-reserved">b.ssrfGuard.isReserved(ip) <a class="anchor" href="#ssrf-reserved">#</a></h2>',
  '<p>Detects reserved and special-purpose IP ranges that should not be used as public egress targets.</p>',
  '<pre><code class="language-javascript">typeof b.ssrfGuard.isReserved; // "function"</code></pre>',

  '<h2 id="ssrf-cidr">b.ssrfGuard.cidrContains(cidr, ip) <a class="anchor" href="#ssrf-cidr">#</a></h2>',
  '<p>Checks whether an IP address falls inside a CIDR block for allowlist and denylist decisions.</p>',
  '<pre><code class="language-javascript">typeof b.ssrfGuard.cidrContains; // "function"</code></pre>',

  '<h3>b.ssrfGuard.createAllowlist(opts) <a class="anchor" href="#ssrf-allowlist">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  allow: [string],  // exact host, suffix host, or CIDR',
  '  deny:  [string],  // deny entries win before allow entries',
  '}</code></pre>',
  '<p>Builds a reusable egress allowlist object for operators that want named outbound policies instead of repeating <code>allowedHosts</code> arrays on every HTTP request.</p>',
  '<pre><code class="language-javascript">var egress = b.ssrfGuard.createAllowlist({',
  '  allow: ["api.partner.example", ".corp.example"],',
  '  deny: ["169.254.169.254"],',
  '});',
  'typeof egress.assert; // "function"</code></pre>',

  '<h3>b.network.allowlist.create(opts) <a class="anchor" href="#network-allowlist-create">#</a></h3>',
  '<p>Namespace alias for <code>b.ssrfGuard.createAllowlist(opts)</code>, colocated under <code>b.network</code> for teams documenting egress controls with the rest of the network configuration.</p>',
  '<pre><code class="language-javascript">var allowlist = b.network.allowlist.create({',
  '  allow: ["api.partner.example"],',
  '  deny: [],',
  '});',
  'typeof allowlist.assert; // "function"</code></pre>',

  '<h2 id="safe-url">Safe URL parsing</h2>',

  '<h3>b.safeUrl.parse(input, opts?) <a class="anchor" href="#safe-url-parse">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  allowedProtocols:  [string],              // default: ["https:"]',
  '  allowUserinfo:     boolean,               // default: false — reject user:pass@ form',
  '  allowMixedScript:  boolean,               // default: false — reject IDN homograph hosts (UTS #39 §5)',
  '  allowedScripts:    [string],              // optional script allowlist, e.g. ["latin","cyrillic"]',
  '  errorClass:        errorClass,            // default: SafeUrlError',
  '  maxUrlLength:      number,                // default: C.BYTES.kib(8) (RFC 7230 §3.1.1)',
  '}</code></pre>',
  '<p>Validates a URL\'s shape and protocol before any network I/O sees it. Defaults accept <code>https:</code> only — <code>file:</code>, <code>data:</code>, <code>javascript:</code>, plain <code>http:</code>, and other schemes are rejected. Operators with internal cleartext endpoints opt in via <code>safeUrl.ALLOW_HTTP_ALL</code> or <code>safeUrl.ALLOW_HTTP_TLS</code>. URLs that carry <code>user:pass@</code> credentials in the authority are rejected by default (those leak into request logs / metric labels / trace spans). Returns the parsed <code>URL</code> instance on success.</p>',
  '<p><strong>IDN homograph defense:</strong> Each host label MUST be single-script per UTS #39 §5. A label that mixes Cyrillic + Latin (the <code>xn--ggle-55da.com</code>-shape attack where Cyrillic <code>о</code> sits inside an otherwise-Latin label) refuses with <code>safe-url/idn-homograph</code> and audits <code>safeurl.idn_homograph.refused</code>. Operators with a legitimate non-Latin host pass either <code>allowMixedScript: true</code> (with an audited reason) or <code>allowedScripts: ["latin","cyrillic"]</code> to allowlist specific writing systems. Per-label detection — <code>eu.shop.example.org</code> mixing scripts across labels still refuses on the offending label.</p>',
  '<pre><code class="language-javascript">var u = b.safeUrl.parse("https://api.example.com/v1/things?id=42");',
  '// u.hostname === "api.example.com", u.pathname === "/v1/things"',
  '',
  'try { b.safeUrl.parse("file:///etc/passwd"); }',
  'catch (e) { /* SafeUrlError code: safe-url/protocol-disallowed */ }',
  '',
  '// IDN homograph — Cyrillic-inside-Latin label refused by default',
  'try { b.safeUrl.parse("https://xn--ggle-55da.com/"); }',
  'catch (e) { /* SafeUrlError code: safe-url/idn-homograph */ }',
  '',
  '// Legitimate mixed-script hosts opt in explicitly',
  'var partner = b.safeUrl.parse("https://xn--ggle-55da.com/", {',
  '  allowMixedScript: true,                   // audited; vendor-specific',
  '});</code></pre>',

  '<h2 id="allowed-hosts">Outbound destination allowlist</h2>',

  '<h3>b.httpClient.request({ allowedHosts }) <a class="anchor" href="#allowed-hosts-call">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  allowedHosts: [',
  '    string,                                  // exact match: "api.partner.com"',
  '    string,                                  // suffix match: ".internal.example.com"',
  '    "<METHOD>:<host-or-suffix>",             // per-method: "POST:api.x.com"',
  '  ],',
  '}</code></pre>',
  '<p>SafeUrl gates protocol + userinfo, ssrfGuard gates IP class — the third layer is the destination hostname. Operators with strict egress policies pin the upstreams the app is allowed to talk to so a compromised process can\'t reach arbitrary destinations. A request to a host outside the allowlist throws with code <code>HOST_DISALLOWED</code> before the socket opens.</p>',
  '<pre><code class="language-javascript">var reqShape = {',
  '  url: "https://api.partner.com/orders",',
  '  allowedHosts: [',
  '    "api.partner.com",                       // exact',
  '    ".internal.example.com",                 // suffix',
  '  ],',
  '};',
  'b.httpClient.request;</code></pre>',

  '<h2 id="webhook">Webhook signer + verifier</h2>',

  '<h3>b.webhook.signer(opts) <a class="anchor" href="#webhook-signer">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  algo:            "hmac-sha3-512" | "pqc-pem", // required',
  '  keys:            { <kid>: secret | { algo, secret/private } },',
  '  defaultKid:      string,                  // required when keys has > 1 entry',
  '  signatureHeader: string,                  // default: "x-blamejs-signature"',
  '  idGenerator:     () => string,            // default: random 16-byte token',
  '  now:             () => number,            // default: Date.now',
  '  retry:           { maxAttempts, baseDelayMs, ... },',
  '  audit:           auditInstance,           // optional',
  '}</code></pre>',
  '<p>Outbound signer — produces the Stripe-shape header <code>t=&lt;sec&gt;,id=&lt;uuid&gt;,&lt;kid&gt;=&lt;sig&gt;</code> for a payload. Multi-key rotation works the same way as JWT — keep old <code>kid</code>s in the signer map until you\'re sure no in-flight delivery is signed by them. Returns an instance with <code>sign(payload)</code>, <code>headers(payload)</code>, and <code>send(opts)</code> (which composes <code>b.httpClient</code> + <code>b.retry</code> internally).</p>',
  '<pre><code class="language-javascript">var s = b.webhook.signer({',
  '  algo:        "hmac-sha3-512",',
  '  keys:        { k1: "wiki-validator-hmac-secret-32-chars-pad" },',
  '  defaultKid:  "k1",',
  '});',
  's.sign;   // function — sign(payload) returns the header string</code></pre>',

  '<h3>b.webhook.verifier(opts) <a class="anchor" href="#webhook-verifier">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  algo:            "hmac-sha3-512" | "pqc-pem", // required',
  '  keys:            { <kid>: secret | { algo, secret/public } },',
  '  toleranceMs:     number,                  // default: C.TIME.minutes(5)',
  '  signatureHeader: string,                  // default: "x-blamejs-signature"',
  '  nonceStore:      nonceStoreInstance,      // optional — replay defense via id',
  '  audit:           auditInstance,           // optional',
  '}</code></pre>',
  '<p>Inbound verification half. <code>verify(headerValue, body)</code> rejects on signature mismatch, expired timestamp (outside <code>toleranceMs</code>), unknown <code>kid</code>, or — when <code>nonceStore</code> is wired — replay of a seen <code>id</code>.</p>',
  '<pre><code class="language-javascript">var v = b.webhook.verifier({',
  '  algo:        "hmac-sha3-512",',
  '  keys:        { k1: "wiki-validator-hmac-secret-32-chars-pad" },',
  '  toleranceMs: b.constants.TIME.minutes(5),',
  '});',
  'v.verify;   // function — verify(headerValue, body) → throws on bad signature</code></pre>',

  '<h2 id="http-message-signatures">RFC 9421 HTTP Message Signatures</h2>',
  '<p><code>b.crypto.httpSig</code> implements RFC 9421 (April 2024) HTTP Message Signatures — message-level integrity for HTTP requests and responses where TLS-only protection isn\'t enough (signed-API contracts that survive intermediary terminations, audit-bound machine-to-machine calls, request-bound non-repudiation). The framework exposes Ed25519 (classical backward-compat for non-PQC peers) and ML-DSA-65 (FIPS 204 lattice signatures, the PQC default once both peers are PQC-aware). RSA / ECDSA-P256 / ECDSA-P384 / HMAC variants from RFC 9421 §3.3 are NOT exposed — same crypto-policy stance as the rest of the framework.</p>',

  '<h3>b.crypto.httpSig.sign(msg, opts) <a class="anchor" href="#httpsig-sign">#</a></h3>',
  '<pre><code class="language-javascript">// msg',
  '{',
  '  method:  string,                  // "POST" / "GET" / ...',
  '  url:     string,                  // full target URI',
  '  headers: { [name]: string },      // existing headers',
  '  body:    Buffer | string,         // optional — required when "content-digest" is covered',
  '}',
  '',
  '// opts',
  '{',
  '  keyid:      string,               // identifier the verifier resolves to a public key',
  '  alg:        "ed25519" | "ml-dsa-65",',
  '  privateKey: string,               // PEM',
  '  covered:    [string],             // RFC 9421 §2.5 covered components',
  '  created:    number,               // unix-seconds; defaults to Date.now()/1000',
  '  expires:    number,               // optional unix-seconds',
  '  nonce:      string,               // optional replay nonce',
  '  label:      string,               // default: "sig1"',
  '  tag:        string,               // optional application tag',
  '}</code></pre>',
  '<p>Returns <code>{ headers, label, signature, base }</code>. <code>headers</code> contains <code>Signature-Input</code>, <code>Signature</code>, and (when <code>"content-digest"</code> is covered) an auto-emitted RFC 9530 <code>Content-Digest: sha3-512=:&lt;base64&gt;:</code>. Derived components implemented per RFC 9421 §2.2: <code>@method</code> / <code>@target-uri</code> / <code>@authority</code> / <code>@scheme</code> / <code>@request-target</code> / <code>@path</code> / <code>@query</code> / <code>@query-param;name="X"</code>. Operators wiring this with <code>b.httpClient.request</code> spread the returned headers into the outbound request; the verifier on the other side runs <code>b.crypto.httpSig.verify</code> with a <code>keyResolver</code> that maps <code>(keyid, alg)</code> to the registered public key PEM.</p>',
  '<pre><code class="language-javascript">// var keys = require("crypto").generateKeyPairSync("ed25519", {',
  '//   publicKeyEncoding:  { type: "spki",  format: "pem" },',
  '//   privateKeyEncoding: { type: "pkcs8", format: "pem" },',
  '// });',
  '// var signed = b.crypto.httpSig.sign({',
  '//   method:  "POST",',
  '//   url:     "https://api.example.com/orders",',
  '//   headers: { host: "api.example.com", "content-type": "application/json" },',
  '//   body:    JSON.stringify({ amount: 100 }),',
  '// }, {',
  '//   keyid:      "service-a-2026-05",',
  '//   alg:        "ed25519",',
  '//   privateKey: keys.privateKey,',
  '//   covered:    ["@method", "@target-uri", "@authority", "content-digest"],',
  '// });',
  '// signed.headers["Signature-Input"], signed.headers["Signature"], signed.headers["Content-Digest"]',
  'typeof b.crypto.httpSig.sign; // "function"</code></pre>',

  '<h3>b.crypto.httpSig.verify(msg, opts) <a class="anchor" href="#httpsig-verify">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  keyResolver:  function (keyid, alg) → publicKeyPem | null,  // required',
  '  toleranceMs:  number,             // default: 5 minutes',
  '  clockSkewMs:  number,             // default: 1 minute',
  '  now:          function,           // optional — for deterministic tests',
  '}</code></pre>',
  '<p>Returns <code>{ valid, label, keyid, alg, covered, created, expires, nonce }</code> on success or <code>{ valid: false, reason, ... }</code> on failure. <code>reason</code> ∈ <code>"missing-signature-input" | "missing-signature" | "bad-signature-input" | "unsupported-alg" | "missing-keyid" | "expired" | "future" | "expires-passed" | "unknown-keyid" | "content-digest-no-body" | "content-digest-header-missing" | "content-digest-mismatch" | "bad-signature" | "build-base-failed" | "verify-threw"</code>. The verifier re-runs the SHA3-512 content-digest over the body when <code>"content-digest"</code> is in the covered set so a stale header from a proxy doesn\'t verify trivially. Compose with <code>b.crypto.timingSafeEqual</code> at the application layer when comparing returned <code>keyid</code> to expected partner identities.</p>',
  '<pre><code class="language-javascript">// var verdict = b.crypto.httpSig.verify({',
  '//   method:  "POST",',
  '//   url:     "https://api.example.com/orders",',
  '//   headers: incomingReqHeaders,',
  '//   body:    incomingReqBody,',
  '// }, {',
  '//   keyResolver: function (keyid, alg) {',
  '//     return registeredPartnerKeys[keyid] || null;',
  '//   },',
  '//   toleranceMs: b.constants.TIME.minutes(5),',
  '// });',
  '// verdict.valid === true → request authentic; verdict.keyid → partner identity',
  'typeof b.crypto.httpSig.verify; // "function"</code></pre>',
].join("\n"),
};
