"use strict";

module.exports = {
  slug:  "queue-cache",
  title: "Queue & Cache",
  body: [
  '<h1>Queue &amp; Cache</h1>',
  '<p>Two state primitives that don\'t need a DB schema: <code>b.queue</code> for durable work-in-flight, and <code>b.cache</code> for ephemeral values that benefit from a TTL. Both compose with cluster mode (shared SQLite table over the external DB) without a Redis dependency.</p>',

  '<h2 id="queue">Queue <a class="anchor" href="#queue">#</a></h2>',
  '<p>Durable work-in-flight: enqueue an item, a consumer leases it for a window, work runs, the consumer extends the lease for long jobs, then either acks or fails. Failed items move to a DLQ after a configurable attempt count. <code>b.jobs</code> is the higher-level wrapper most apps use — it owns the name → handler registry on top of the queue.</p>',

  '<h3>b.jobs.create(opts)</h3>',
  '<pre><code class="language-javascript">{',
  '  queueBackend:               string,       // default: "primary" — backend name from queue.init',
  '  consumerDefaults:           {             // default: {}',
  '    concurrency, leaseDurationMs,           //   forwarded to queue.consume per definition',
  '    pollIntervalMs, fastPollMs,',
  '  },',
  '  allowUnregisteredEnqueue:   boolean,      // default: false',
  '}</code></pre>',
  '<h3>jobs.define(name, handler, defineOpts?) / jobs.enqueue(name, payload, enqueueOpts?) / jobs.start() / jobs.shutdown(opts?)</h3>',
  '<pre><code class="language-javascript">// queue.init must run before jobs.create — wire a backend first.',
  'b.queue.init({ backends: { primary: { protocol: "local" } } });',
  '',
  'var jobs = b.jobs.create();',
  'var mail = b.mail.create({',
  '  transport: b.mail.transports.console(),',
  '  defaults:  { from: "ops@example.test" },',
  '});',
  '',
  '// Define handlers BEFORE start() — defining after start() throws.',
  'jobs.define("send-welcome", async function (job) {',
  '  // job: { jobId, queueName, payload, attempts, maxAttempts, traceId, classification, ... }',
  '  await mail.send({ to: job.payload.email, subject: "Welcome", text: "Welcome aboard!" });',
  '}, {',
  '  concurrency:       4,                    // forwarded to queue.consume',
  '  leaseDurationMs:   C.TIME.minutes(2),',
  '});',
  '',
  'await jobs.start();                        // begins consuming; idempotent',
  '',
  'await jobs.enqueue("send-welcome", { email: "alice@example.com" });',
  '// Cluster-safe by default — only one replica leases each item.</code></pre>',
  '<p><code>jobs.enqueue</code> rejects unknown names by default — typos and forgotten <code>define</code> calls fail loud at call time rather than silently piling up jobs no consumer will ever pick up. Operators with lazy registration patterns opt in via <code>allowUnregisteredEnqueue: true</code>.</p>',

  '<h3 id="queue-priority">b.queue.enqueue(queueName, payload, opts) <a class="anchor" href="#queue-priority">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  priority:        number,                  // default: 0 — integer, higher wins',
  '  delaySeconds:    number,                  // default: 0',
  '  maxAttempts:     number,                  // default: 5',
  '  flowId:          string,                  // default: null',
  '  flowChildName:   string,                  // default: null',
  '  repeat:          { cron, timezone? },     // default: null',
  '  traceId:         string,                  // default: null',
  '  classification:  string,                  // default: null',
  '  backend:         string,                  // default: defaultBackend from init',
  '}</code></pre>',
  '<pre><code class="language-javascript">await b.queue.enqueue("emails", { kind: "password-reset" }, { priority: 10 });',
  'await b.queue.enqueue("emails", { kind: "weekly-digest" }, { priority: 1 });',
  '// Lease order: password-reset first regardless of arrival order.',
  '',
  '// Delayed enqueue — job becomes available 30 minutes from now',
  'await b.queue.enqueue("reminders", payload, { delaySeconds: 1800 });</code></pre>',
  '<p>Backed by a dedicated index on <code>(priority DESC, availableAt ASC, enqueuedAt ASC)</code>, so high-priority arrivals jump the line without scanning the whole table.</p>',

  '<h3>b.queue.consume(queueName, handler, opts)</h3>',
  '<pre><code class="language-javascript">{',
  '  concurrency:       number,                // default: 1',
  '  leaseDurationMs:   number,                // default: 30000',
  '  pollIntervalMs:    number,                // default: 1000',
  '  fastPollMs:        number,                // default: 50',
  '  rateLimit:         { max, perSeconds },   // default: null',
  '  backend:           string,                // default: defaultBackend',
  '}</code></pre>',
  '<pre><code class="language-javascript">b.queue.consume("emails", async function (job) {',
  '  await sendEmail(job.payload);',
  '  // Throw to trigger retry; return cleanly to ack.',
  '}, {',
  '  concurrency:      10,',
  '  rateLimit:        { max: 100, perSeconds: 1 },',
  '  leaseDurationMs:  C.TIME.minutes(2),',
  '});</code></pre>',
  '<p><code>maxAttempts</code> lives on <strong>enqueue</strong>, not on consume — each job carries its own retry budget so different items in the same queue can have different patience. Permanent failure (exhausted attempts) routes the job to the DLQ; the framework emits <code>system.queue.dlq</code> on the audit chain when it lands.</p>',

  '<h3 id="queue-repeat">Repeat-in-queue (cron) <a class="anchor" href="#queue-repeat">#</a></h3>',
  '<p>Pass <code>repeat: { cron, timezone? }</code> on enqueue and the framework re-enqueues the same payload after each successful completion, anchored to the next firing time computed via <code>scheduler.nextCronFire</code>. Useful for low-coordination periodic work without instantiating a full scheduler.</p>',
  '<pre><code class="language-javascript">await b.queue.enqueue("nightly-digest",',
  '  { recipientList: "all" },',
  '  { repeat: { cron: "0 9 * * *", timezone: "America/New_York" } },',
  ');</code></pre>',
  '<p>Final-failure jobs (DLQ landing) do NOT re-enqueue — operators investigate before the cron resumes, so a permanently broken handler can\'t loop a doomed job forever.</p>',

  '<h3 id="queue-flows">b.queue.enqueueFlow(opts) <a class="anchor" href="#queue-flows">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  queueName:      string,                  // required: true',
  '  children:       Array&lt;{                  // required: true',
  '    name:         string,                  // required: true — unique within the flow',
  '    payload:      any,                     // default: null',
  '    dependsOn:    string[],                // default: [] — sibling names',
  '    priority:     number,                  // default: 0',
  '  }&gt;,',
  '}</code></pre>',
  '<pre><code class="language-javascript">var flow = await b.queue.enqueueFlow({',
  '  queueName: "ingest",',
  '  children: [',
  '    { name: "fetch",     payload: { url: "https://upstream/data.json" } },',
  '    { name: "transform", payload: { rule: "schema-v2" }, dependsOn: ["fetch"] },',
  '    { name: "publish",   payload: { topic: "ingest.done" }, dependsOn: ["transform"] },',
  '  ],',
  '});',
  '// → { flowId: "flow-...", jobs: [{ name, jobId }, ...] }',
  '',
  '// Diamond shape works the same way — end waits for both branches:',
  'await b.queue.enqueueFlow({',
  '  queueName: "diamond",',
  '  children: [',
  '    { name: "root", payload: {} },',
  '    { name: "a",    payload: {}, dependsOn: ["root"] },',
  '    { name: "b",    payload: {}, dependsOn: ["root"] },',
  '    { name: "end",  payload: {}, dependsOn: ["a", "b"] },',
  '  ],',
  '});</code></pre>',
  '<p>Cycle detection runs at registration time — a graph with a cycle throws at <code>enqueueFlow()</code> rather than deadlocking at runtime. Unknown dependency names fail loudly with the offending name. Each flow gets a generated <code>flowId</code>; child rows in <code>_blamejs_jobs</code> carry <code>flowId</code> + <code>flowChildName</code> + <code>dependsOn</code> for inspection.</p>',

  '<h3 id="queue-dlq">DLQ inspection &amp; retry <a class="anchor" href="#queue-dlq">#</a></h3>',
  '<p>Failed-after-retries jobs land in the per-queue DLQ with the original payload, the failure reason, and the attempt history. The DLQ surface is flat on <code>b.queue</code> (not a nested namespace):</p>',
  '<pre><code class="language-javascript">var dead = await b.queue.dlqList("emails");',
  '// → [{ jobId, payload, attempts, lastError, ... }, ...]',
  '',
  'var size = await b.queue.dlqSize("emails");',
  '// → number',
  '',
  'await b.queue.dlqRetry(jobId);',
  '// Resets the job back to "pending" so the next consumer poll picks it up.</code></pre>',

  '<h2 id="cache">Cache <a class="anchor" href="#cache">#</a></h2>',
  '<p>Memory or cluster-shared key/value cache with TTL, LRU + bytes-cap eviction, optional sliding TTL, and tag-based bulk invalidation. Single-process apps use the memory backend; cluster apps share state via the external DB. Operators can plug in their own <code>{ get, set, del, clear, size, close }</code> for Redis / Memcached.</p>',

  '<h3>b.cache.create(opts)</h3>',
  '<pre><code class="language-javascript">{',
  '  namespace:             string,            // required: true — keys prefixed with this',
  '  backend:               "memory" | "cluster"',
  '                         | { get, set, del, clear, size, close },',
  '                                            // default: "memory"',
  '  ttlMs:                 number,            // default: C.TIME.minutes(5)',
  '  maxEntries:            number,            // default: 10_000 — memory backend',
  '  maxBytes:              number,            // default: Infinity — memory backend',
  '  sizeOf:                (value) =&gt; number, // default: best-effort byte estimate',
  '  sweepIntervalMs:       number,            // default: C.TIME.minutes(1)',
  '  staleWhileRevalidate:  boolean,           // default: false',
  '  slidingTtl:            boolean,           // default: false — refresh TTL on read',
  '  auditFailures:         boolean,           // default: true',
  '  auditClear:            boolean,           // default: true',
  '  audit:                 AuditTap,          // default: null',
  '  observability:         ObservabilityTap,  // default: null',
  '  clock:                 () =&gt; number,      // default: Date.now',
  '}</code></pre>',
  '<pre><code class="language-javascript">var apiCache = b.cache.create({',
  '  namespace:   "wiki.api",',
  '  backend:     "memory",',
  '  ttlMs:       C.TIME.minutes(5),',
  '  slidingTtl:  true,',
  '  audit:       b.audit,',
  '});</code></pre>',

  '<h3>cache.set(key, value, opts?) / cache.wrap(key, computeFn, opts?) / cache.invalidateTag(tag)</h3>',
  '<pre><code class="language-javascript">// set opts:',
  '{',
  '  ttlMs:  number,                          // default: create-time ttlMs',
  '  tags:   string[],                        // default: [] — tag the entry',
  '}',
  '',
  '// wrap opts:',
  '{',
  '  ttlMs:        number,                    // default: create-time ttlMs',
  '  singleFlight: boolean,                   // default: true — collapse concurrent computes',
  '}</code></pre>',
  '<pre><code class="language-javascript">// Tags via set() — wrap() does not accept tags directly',
  'await apiCache.set("page:" + slug, html, { tags: ["page", "page:" + slug] });',
  '',
  '// wrap = "compute and cache, return cached on subsequent calls"',
  'var page = await apiCache.wrap("page:" + slug, async function () {',
  '  return await renderPage(slug);',
  '});',
  '',
  '// Tag-based invalidation — singular tag at a time (one call per tag)',
  'await apiCache.invalidateTag("page:intro");',
  'await apiCache.invalidateTag("page");        // invalidates every page-tagged entry</code></pre>',
  '<p>Memory backend evicts on TTL + LRU + bytes-cap (default <code>Infinity</code> — operators wanting a memory cap pass <code>maxBytes</code> explicitly). Cluster backend stores in <code>_blamejs_cache</code>, sweeps expired rows on a background interval, and shares state across replicas without operator wiring. <code>invalidateTag</code> against a cluster-backend cache throws — tag indexing is memory-backend only; operators wanting cluster-wide tagged invalidation maintain their own indexed-key scheme.</p>',
].join("\n"),
};
