"use strict";

module.exports = {
  slug:  "queue-cache",
  title: "Queue & Cache",
  body: [
  '<h1>Queue &amp; Cache</h1>',
  '<p>Two state primitives that don\'t need a DB schema: <code>b.queue</code> for durable work-in-flight, and <code>b.cache</code> for ephemeral values that benefit from a TTL. Both compose with cluster mode (shared SQLite table over the external DB) without a Redis dependency.</p>',

  '<h2 id="queue">Queue <a class="anchor" href="#queue">#</a></h2>',
  '<p>Durable work-in-flight: enqueue an item, a consumer leases it for a window, work runs, the consumer extends the lease for long jobs, then either acks or fails. Failed items move to a DLQ after a configurable attempt count. <code>b.jobs</code> is the higher-level wrapper most apps use — it owns the name → handler registry on top of the queue.</p>',

  '<h3>b.jobs.create(opts)</h3>',
  '<pre><code class="language-javascript">{',
  '  queueBackend:               string,       // default: "primary" — backend name from queue.init',
  '  consumerDefaults:           {             // default: {}',
  '    concurrency, leaseDurationMs,           //   forwarded to queue.consume per definition',
  '    pollIntervalMs, fastPollMs,',
  '  },',
  '  allowUnregisteredEnqueue:   boolean,      // default: false',
  '}</code></pre>',
  '<h3>jobs.define(name, handler, defineOpts?) / jobs.enqueue(name, payload, enqueueOpts?) / jobs.start() / jobs.shutdown(opts?)</h3>',
  '<pre><code class="language-javascript">// queue.init must run before jobs.create — wire a backend first.',
  'b.queue.init({ backends: { primary: { protocol: "local" } } });',
  '',
  'var jobs = b.jobs.create();',
  'var mail = b.mail.create({',
  '  transport: b.mail.transports.console(),',
  '  defaults:  { from: "ops@example.test" },',
  '});',
  '',
  '// Define handlers BEFORE start() — defining after start() throws.',
  'jobs.define("send-welcome", async function (job) {',
  '  // job: { jobId, queueName, payload, attempts, maxAttempts, traceId, classification, ... }',
  '  await mail.send({ to: job.payload.email, subject: "Welcome", text: "Welcome aboard!" });',
  '}, {',
  '  concurrency:       4,                    // forwarded to queue.consume',
  '  leaseDurationMs:   C.TIME.minutes(2),',
  '});',
  '',
  'await jobs.start();                        // begins consuming; idempotent',
  '',
  'await jobs.enqueue("send-welcome", { email: "alice@example.com" });',
  '// Cluster-safe by default — only one replica leases each item.</code></pre>',
  '<p><code>jobs.enqueue</code> rejects unknown names by default — typos and forgotten <code>define</code> calls fail loud at call time rather than silently piling up jobs no consumer will ever pick up. Operators with lazy registration patterns opt in via <code>allowUnregisteredEnqueue: true</code>.</p>',

  '<h3 id="queue-priority">b.queue.enqueue(queueName, payload, opts) <a class="anchor" href="#queue-priority">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  priority:        number,                  // default: 0 — integer, higher wins',
  '  delaySeconds:    number,                  // default: 0',
  '  maxAttempts:     number,                  // default: 5',
  '  flowId:          string,                  // default: null',
  '  flowChildName:   string,                  // default: null',
  '  repeat:          { cron, timezone? },     // default: null',
  '  traceId:         string,                  // default: null',
  '  classification:  string,                  // default: null',
  '  backend:         string,                  // default: defaultBackend from init',
  '}</code></pre>',
  '<pre><code class="language-javascript">await b.queue.enqueue("emails", { kind: "password-reset" }, { priority: 10 });',
  'await b.queue.enqueue("emails", { kind: "weekly-digest" }, { priority: 1 });',
  '// Lease order: password-reset first regardless of arrival order.',
  '',
  '// Delayed enqueue — job becomes available 30 minutes from now',
  'await b.queue.enqueue("reminders", payload, { delaySeconds: 1800 });</code></pre>',
  '<p>Backed by a dedicated index on <code>(priority DESC, availableAt ASC, enqueuedAt ASC)</code>, so high-priority arrivals jump the line without scanning the whole table.</p>',

  '<h3>b.queue.consume(queueName, handler, opts)</h3>',
  '<pre><code class="language-javascript">{',
  '  concurrency:       number,                // default: 1',
  '  leaseDurationMs:   number,                // default: 30000',
  '  pollIntervalMs:    number,                // default: 1000',
  '  fastPollMs:        number,                // default: 50',
  '  rateLimit:         { max:        positive int,',
  '                       perSeconds: positive finite number },',
  '                                            // default: null — bad input throws at consume() time',
  '  backend:           string,                // default: defaultBackend',
  '}</code></pre>',
  '<pre><code class="language-javascript">b.queue.consume("emails", async function (job) {',
  '  await sendEmail(job.payload);',
  '  // Throw to trigger retry; return cleanly to ack.',
  '}, {',
  '  concurrency:      10,',
  '  rateLimit:        { max: 100, perSeconds: 1 },',
  '  leaseDurationMs:  C.TIME.minutes(2),',
  '});</code></pre>',
  '<p><code>maxAttempts</code> lives on <strong>enqueue</strong>, not on consume — each job carries its own retry budget so different items in the same queue can have different patience. Permanent failure (exhausted attempts) routes the job to the DLQ; the framework emits <code>system.queue.dlq</code> on the audit chain when it lands.</p>',

  '<h2 id="queue-init">b.queue.init(options) / listBackends() <a class="anchor" href="#queue-init">#</a></h2>',
  '<p>Queue backend registration and introspection. Operators call <code>init</code> once at boot and inspect configured backends in admin diagnostics.</p>',
  '<pre><code class="language-javascript">typeof b.queue.init; // "function"',
  'typeof b.queue.listBackends; // "function"</code></pre>',

  '<h2 id="queue-list-backends">b.queue.listBackends() <a class="anchor" href="#queue-list-backends">#</a></h2>',
  '<p>Returns configured queue backend descriptors for diagnostics and admin views.</p>',
  '<pre><code class="language-javascript">typeof b.queue.listBackends; // "function"</code></pre>',

  '<h2 id="queue-size-purge">b.queue.size(queueName, options) / purge(queueName, options) <a class="anchor" href="#queue-size-purge">#</a></h2>',
  '<p>Queue inspection and administrative purge helpers. Use purge for controlled cleanup, not as a retry mechanism.</p>',
  '<pre><code class="language-javascript">typeof b.queue.size; // "function"',
  'typeof b.queue.purge; // "function"</code></pre>',

  '<h2 id="queue-purge">b.queue.purge(queueName, options) <a class="anchor" href="#queue-purge">#</a></h2>',
  '<p>Deletes queued jobs for a named queue as an explicit admin maintenance operation.</p>',
  '<pre><code class="language-javascript">typeof b.queue.purge; // "function"</code></pre>',

  '<h2 id="queue-shutdown">b.queue.shutdown(options) <a class="anchor" href="#queue-shutdown">#</a></h2>',
  '<p>Stops consumers and drains queue background work during app shutdown.</p>',
  '<pre><code class="language-javascript">typeof b.queue.shutdown; // "function"</code></pre>',

  '<h3 id="queue-repeat">Repeat-in-queue (cron) <a class="anchor" href="#queue-repeat">#</a></h3>',
  '<p>Pass <code>repeat: { cron, timezone? }</code> on enqueue and the framework re-enqueues the same payload after each successful completion, anchored to the next firing time computed via <code>scheduler.nextCronFire</code>. Useful for low-coordination periodic work without instantiating a full scheduler.</p>',
  '<pre><code class="language-javascript">await b.queue.enqueue("nightly-digest",',
  '  { recipientList: "all" },',
  '  { repeat: { cron: "0 9 * * *", timezone: "America/New_York" } },',
  ');</code></pre>',
  '<p>Final-failure jobs (DLQ landing) do NOT re-enqueue — operators investigate before the cron resumes, so a permanently broken handler can\'t loop a doomed job forever.</p>',

  '<h3 id="queue-flows">b.queue.enqueueFlow(opts) <a class="anchor" href="#queue-flows">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  queueName:      string,                  // required: true',
  '  children:       Array&lt;{                  // required: true',
  '    name:         string,                  // required: true — unique within the flow',
  '    payload:      any,                     // default: null',
  '    dependsOn:    string[],                // default: [] — sibling names',
  '    priority:     number,                  // default: 0',
  '  }&gt;,',
  '}</code></pre>',
  '<pre><code class="language-javascript">var flow = await b.queue.enqueueFlow({',
  '  queueName: "ingest",',
  '  children: [',
  '    { name: "fetch",     payload: { url: "https://upstream/data.json" } },',
  '    { name: "transform", payload: { rule: "schema-v2" }, dependsOn: ["fetch"] },',
  '    { name: "publish",   payload: { topic: "ingest.done" }, dependsOn: ["transform"] },',
  '  ],',
  '});',
  '// → { flowId: "flow-...", jobs: [{ name, jobId }, ...] }',
  '',
  '// Diamond shape works the same way — end waits for both branches:',
  'await b.queue.enqueueFlow({',
  '  queueName: "diamond",',
  '  children: [',
  '    { name: "root", payload: {} },',
  '    { name: "a",    payload: {}, dependsOn: ["root"] },',
  '    { name: "b",    payload: {}, dependsOn: ["root"] },',
  '    { name: "end",  payload: {}, dependsOn: ["a", "b"] },',
  '  ],',
  '});</code></pre>',
  '<p>Cycle detection runs at registration time — a graph with a cycle throws at <code>enqueueFlow()</code> rather than deadlocking at runtime. Unknown dependency names fail loudly with the offending name. Each flow gets a generated <code>flowId</code>; child rows in <code>_blamejs_jobs</code> carry <code>flowId</code> + <code>flowChildName</code> + <code>dependsOn</code> for inspection.</p>',

  '<h3 id="queue-dlq">DLQ inspection &amp; retry <a class="anchor" href="#queue-dlq">#</a></h3>',
  '<p>Failed-after-retries jobs land in the per-queue DLQ with the original payload, the failure reason, and the attempt history. The DLQ surface is flat on <code>b.queue</code> (not a nested namespace):</p>',
  '<pre><code class="language-javascript">var dead = await b.queue.dlqList("emails");',
  '// → [{ jobId, payload, attempts, lastError, ... }, ...]',
  '',
  'var size = await b.queue.dlqSize("emails");',
  '// → number',
  '',
  'await b.queue.dlqRetry(jobId);',
  '// Resets the job back to "pending" so the next consumer poll picks it up.</code></pre>',

  '<h2 id="queue-dlq-list">b.queue.dlqList(queueName, options) <a class="anchor" href="#queue-dlq-list">#</a></h2>',
  '<p>Lists dead-lettered jobs for inspection and remediation.</p>',
  '<pre><code class="language-javascript">typeof b.queue.dlqList; // "function"</code></pre>',

  '<h2 id="queue-dlq-size">b.queue.dlqSize(queueName, options) <a class="anchor" href="#queue-dlq-size">#</a></h2>',
  '<p>Returns the dead-letter queue depth for alerting and dashboards.</p>',
  '<pre><code class="language-javascript">typeof b.queue.dlqSize; // "function"</code></pre>',

  '<h2 id="queue-dlq-retry">b.queue.dlqRetry(jobId, options) <a class="anchor" href="#queue-dlq-retry">#</a></h2>',
  '<p>Moves a dead-lettered job back to the live queue after the operator has remediated the failure cause.</p>',
  '<pre><code class="language-javascript">typeof b.queue.dlqRetry; // "function"</code></pre>',

  '<h3 id="queue-redis-backend">Redis backend (queue.init protocol "redis") <a class="anchor" href="#queue-redis-backend">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  protocol:    "redis",                   // required',
  '  url:         string,                    // required: redis://host:port/db OR rediss://...',
  '  username:    string,                    // default: null — Redis ACL username',
  '  password:    string,                    // default: null — AUTH password',
  '  tls:         boolean,                   // default: inferred from rediss:// — explicit override',
  '  keyPrefix:   string,                    // default: "blamejs:queue" — namespace key in shared Redis',
  '  connectTimeoutMs: number,               // default: 5000',
  '  commandTimeoutMs: number,               // default: 10000',
  '}</code></pre>',
  '<p>Single-node Redis backend for <code>b.queue</code>. Multi-replica apps share a single queue without each needing to be the framework cluster leader, since Redis itself is the coordination point. Atomicity comes from server-side Lua scripts (lease / sweep / fail / dlqRetry) so concurrent consumers never double-lease and a sweep can\'t race a complete. The same <code>cryptoField</code> sealedFields config the local backend uses applies to Redis — payload + lastError seal/unseal automatically. Out of scope for v1: Redis Cluster (slot routing), Sentinel (managed primary), priority ordering, flow children with <code>dependsOn</code>.</p>',
  '<pre><code class="language-javascript">b.queue.init({',
  '  backends: {',
  '    primary: {',
  '      protocol: "redis",',
  '      url:      "redis://cache.internal:6379/0",',
  '      password: process.env.REDIS_PASSWORD,',
  '    },',
  '  },',
  '  defaultBackend: "primary",',
  '});',
  '// b.queue.enqueue / consume / dlqList work identically to the local backend.</code></pre>',

  '<h3 id="queue-boot-from-env">b.queue.bootFromEnv(opts?) <a class="anchor" href="#queue-boot-from-env">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  env:  process.env,                      // default',
  '}</code></pre>',
  '<p>Env-driven init mirroring <code>b.network.bootFromEnv</code> and <code>b.logStream.bootFromEnv</code>. Reads <code>BLAMEJS_QUEUE_PROTOCOL</code> (<code>local</code> or <code>redis</code>; default <code>local</code>), <code>BLAMEJS_QUEUE_REDIS_URL</code>, <code>BLAMEJS_QUEUE_REDIS_PASSWORD</code>, <code>BLAMEJS_QUEUE_REDIS_USERNAME</code>, <code>BLAMEJS_QUEUE_REDIS_TLS</code>, <code>BLAMEJS_QUEUE_REDIS_KEY_PREFIX</code>. Operators flip from local to Redis without a code change; the wiki app reads these from docker-compose.</p>',
  '<pre><code class="language-javascript">// At app boot, before b.createApp:',
  'b.queue.bootFromEnv({ env: process.env });',
  '// BLAMEJS_QUEUE_PROTOCOL=redis BLAMEJS_QUEUE_REDIS_URL=redis://cache:6379/0 → wires the Redis backend',
  '// BLAMEJS_QUEUE_PROTOCOL unset OR =local → wires the SQLite-backed local backend</code></pre>',

  '<h2 id="cache">Cache <a class="anchor" href="#cache">#</a></h2>',
  '<p>Memory or cluster-shared key/value cache with TTL, LRU + bytes-cap eviction, optional sliding TTL, and tag-based bulk invalidation. Single-process apps use the memory backend; cluster apps share state via the external DB. Operators can plug in their own <code>{ get, set, del, clear, size, close }</code> for Redis / Memcached.</p>',

  '<h3>b.cache.create(opts)</h3>',
  '<pre><code class="language-javascript">{',
  '  namespace:             string,            // required: true — keys prefixed with this',
  '  backend:               "memory" | "cluster"',
  '                         | { get, set, del, clear, size, close },',
  '                                            // default: "memory"',
  '  ttlMs:                 number,            // default: C.TIME.minutes(5)',
  '  maxEntries:            number,            // default: 10_000 — memory backend',
  '  maxBytes:              number,            // default: Infinity — memory backend',
  '  sizeOf:                (value) =&gt; number, // default: best-effort byte estimate',
  '  sweepIntervalMs:       number,            // default: C.TIME.minutes(1)',
  '  staleWhileRevalidate:  boolean,           // default: false',
  '  slidingTtl:            boolean,           // default: false — refresh TTL on read',
  '  auditFailures:         boolean,           // default: true',
  '  auditClear:            boolean,           // default: true',
  '  audit:                 AuditTap,          // default: null',
  '  observability:         ObservabilityTap,  // default: null',
  '  clock:                 () =&gt; number,      // default: Date.now',
  '  redisUrl:              string,            // backend === "redis"',
  '  redisPassword:         string,            // backend === "redis"',
  '  redisUsername:         string,            // backend === "redis"',
  '  redisTls:              boolean,           // backend === "redis"',
  '  redisCa:               string | Buffer,   // backend === "redis"',
  '  redisServername:       string,            // backend === "redis"',
  '  redisConnectTimeoutMs: number,            // backend === "redis"',
  '  redisCommandTimeoutMs: number,            // backend === "redis"',
  '  redisMaxReconnectAttempts: number,        // backend === "redis"',
  '  invalidationPubsub:    PubsubInstance,    // optional cross-node invalidation bus',
  '}</code></pre>',
  '<p>Returns a cache instance with <code>get</code>, <code>set</code>, <code>del</code>, <code>has</code>, <code>clear</code>, <code>size</code>, <code>bytes</code>, <code>wrap</code>, <code>invalidateTag</code>, <code>getTags</code>, and <code>close</code>. Memory mode is process-local; cluster/custom backends share state through the operator-provided backend.</p>',
  '<pre><code class="language-javascript">var apiCache = b.cache.create({',
  '  namespace:   "wiki.api",',
  '  backend:     "memory",',
  '  ttlMs:       b.constants.TIME.minutes(5),',
  '  slidingTtl:  true,',
  '});',
  'await apiCache.set("page:welcome", { title: "Welcome" }, { tags: ["page"] });',
  'var page = await apiCache.get("page:welcome");',
  'page.title; // "Welcome"</code></pre>',

  '<h3>cache.set(key, value, opts?) / cache.wrap(key, computeFn, opts?) / cache.invalidateTag(tag)</h3>',
  '<pre><code class="language-javascript">// set opts:',
  '{',
  '  ttlMs:  number,                          // default: create-time ttlMs',
  '  tags:   string[],                        // default: [] — tag the entry',
  '}',
  '',
  '// wrap opts:',
  '{',
  '  ttlMs:        number,                    // default: create-time ttlMs',
  '  singleFlight: boolean,                   // default: true — collapse concurrent computes',
  '}</code></pre>',
  '<pre><code class="language-javascript">var apiCache = b.cache.create({',
  '  namespace: "wiki.html",',
  '  backend: "memory",',
  '});',
  'var slug = "welcome";',
  'var html = "&lt;h1&gt;Welcome&lt;/h1&gt;";',
  '',
  '// Tags via set() — wrap() does not accept tags directly',
  'await apiCache.set("page:" + slug, html, { tags: ["page", "page:" + slug] });',
  '',
  '// wrap = "compute and cache, return cached on subsequent calls"',
  'var page = await apiCache.wrap("page:" + slug, async function () {',
  '  return await renderPage(slug);',
  '});',
  '',
  '// Tag-based invalidation — singular tag at a time (one call per tag)',
  'await apiCache.invalidateTag("page:intro");',
  'await apiCache.invalidateTag("page");        // invalidates every page-tagged entry</code></pre>',
  '<p>Memory backend evicts on TTL + LRU + bytes-cap (default <code>Infinity</code> — operators wanting a memory cap pass <code>maxBytes</code> explicitly). Cluster backend stores in <code>_blamejs_cache</code>, sweeps expired rows on a background interval, and shares state across replicas without operator wiring. <code>invalidateTag</code> against a cluster-backend cache throws — tag indexing is memory-backend only; operators wanting cluster-wide tagged invalidation maintain their own indexed-key scheme.</p>',

  '<h3 id="cache-seal">cache.set(key, value, { seal: true }) — vault-sealed cluster cache values <a class="anchor" href="#cache-seal">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  ttlMs: number,        // default: create-time ttlMs',
  '  tags:  string[],      // default: [] — tag the entry',
  '  seal:  boolean,       // default: false — XChaCha20-Poly1305 seal via b.vault.seal',
  '}</code></pre>',
  '<p>Opt-in vault seal for cluster-backend cache values. When <code>seal: true</code>, the cache wraps the JSON-serialized value through <code>b.vault.seal</code> (XChaCha20-Poly1305) before writing to <code>_blamejs_cache.valueJson</code>. Reads detect the marker prefix and unseal transparently. Sealed entries store the same shape on disk as non-sealed entries — the cache table layout is unchanged — but a snapshot of <code>_blamejs_cache</code> taken with framework keys absent surfaces only the marker prefix instead of cleartext. Throws when used against the memory or custom backends; memory caches never reach disk and custom backends wrap their own at-rest encryption.</p>',
  '<pre><code class="language-javascript">var sessionCache = b.cache.create({',
  '  namespace: "session.user",',
  '  backend:   "cluster",',
  '  ttlMs:     b.constants.TIME.minutes(30),',
  '});',
  '// Sealed write — valueJson on disk is "blamejs:cache.sealed:<base64>"',
  'await sessionCache.set("u-42", { roles: ["admin"], lastSeenAt: Date.now() }, { seal: true });',
  '// Read transparent — caller sees the original object',
  'var profile = await sessionCache.get("u-42");',
  'profile.roles[0]; // "admin"</code></pre>',

  '<h2 id="inbox">Inbox <a class="anchor" href="#inbox">#</a></h2>',
  '<p>Exactly-once receive companion to <code>b.outbox</code>. Records every <code>(source, messageId)</code> pair in the same transaction as the business state change so a duplicate delivery (network retry, replay, broker re-dispatch) short-circuits cleanly on the second attempt.</p>',

  '<h3>b.inbox.create(opts)</h3>',
  '<pre><code class="language-javascript">{',
  '  externalDb:        b.externalDb,           // required — Postgres or SQLite handle',
  '  table:             string,                 // required — SQL identifier; PRIMARY KEY (source, message_id)',
  '  retentionDays:     number,                 // default: 30 — sweep older rows',
  '  audit:             boolean,                // default: true',
  '  maxPayloadBytes:   number,                 // default: C.BYTES.kib(64) — metadata serialized cap',
  '  messageIdMaxLen:   number,                 // default: 256',
  '  sourceMaxLen:      number,                 // default: 256',
  '}</code></pre>',
  '<p>Returns an instance with <code>declareSchema</code>, <code>recordReceive</code>, <code>markProcessed</code>, <code>handle</code>, <code>sweep</code>, <code>isFresh</code>, and <code>getStats</code>. <code>handle({ messageId, source }, fn)</code> is the high-level form — runs the inner handler in a transaction and only commits when the <code>(source, messageId)</code> pair was fresh; duplicates short-circuit with <code>{ fresh: false, result: null }</code>. Postgres uses <code>ON CONFLICT (source, message_id) DO NOTHING RETURNING</code>; SQLite uses <code>INSERT OR IGNORE ... RETURNING 1</code>. NUL + C0 control characters in <code>messageId</code> / <code>source</code> are rejected at the gate so <code>"abc\\0attacker"</code> can\'t collide with <code>"abc"</code> through silent driver truncation.</p>',
  '<pre><code class="language-javascript">var inbox = b.inbox.create({',
  '  externalDb:    b.externalDb,',
  '  table:         "inbox_events",',
  '  retentionDays: 30,',
  '});',
  'await inbox.declareSchema(b.externalDb);',
  '',
  '// Exactly-once handler — runs the body iff (source, messageId) is fresh.',
  'await inbox.handle({',
  '  messageId: "kafka-evt-7c3a",',
  '  source:    "kafka:orders.created.v1",',
  '  metadata:  { partition: 4 },',
  '}, async function (xdb) {',
  '  await xdb.query("INSERT INTO orders (id, total) VALUES ($1, $2)",',
  '                  ["o-1234", 4250]);',
  '});',
  '',
  '// Periodic retention sweep (operator wires their scheduler).',
  'await inbox.sweep();</code></pre>',

  '<h2 id="outbox">Outbox <a class="anchor" href="#outbox">#</a></h2>',
  '<p>Transactional outbox — write the business state change AND an event row in the SAME database transaction; a separate publisher worker drains the table to the message bus. Crashes between commit and publish leave the row pending so the worker retries after restart, giving at-least-once delivery without distributed transactions.</p>',

  '<h3>b.outbox.create(opts)</h3>',
  '<pre><code class="language-javascript">{',
  '  externalDb:       b.externalDb,            // required',
  '  table:            string,                  // required — SQL identifier',
  '  publisher:        async (event) => void,   // required — bus dispatch',
  '  pollIntervalMs:   number,                  // default: C.TIME.seconds(1)',
  '  batchSize:        number,                  // default: 100',
  '  maxAttempts:      number,                  // default: 10 — exceeded → row marked dead',
  '  retryBackoff:     { initialMs, maxMs, factor }, // default: 1s → 5min, factor 2',
  '  audit:            boolean,                 // default: true',
  '  name:             string,                  // optional — appears in audit metadata + logs',
  '  envelope:         "raw" | "debezium",      // default: "raw" — wrap each event in a Debezium ChangeEvent envelope',
  '  connectorName:    string,                  // optional — Debezium source.connector field (default "blamejs")',
  '  connectorVersion: string,                  // optional — Debezium source.version field',
  '  dbName:           string,                  // optional — Debezium source.db field',
  '}</code></pre>',
  '<p>Returns an instance with <code>enqueue(event, txn)</code>, <code>declareSchema</code>, <code>start</code>, <code>stop</code>, <code>pendingCount</code>, and <code>deadCount</code>. <code>enqueue</code> writes the row in the operator\'s transaction so the event lands iff the business state change commits — no distributed-transaction coordinator. The publisher worker polls with <code>SELECT ... FOR UPDATE SKIP LOCKED</code> on Postgres (safe for multiple competing publishers) and a plain transactional select on SQLite. Publisher exceptions advance <code>attempts</code> and the next-attempt-at curve; <code>maxAttempts</code> exhaustion routes the row to a <code>dead</code> state with audit emission <code>outbox.dead-letter</code>.</p>',
  '<pre><code class="language-javascript">var outbox = b.outbox.create({',
  '  externalDb:    b.externalDb,',
  '  table:         "outbox_events",',
  '  publisher:     async function (event) { await myBus.publish(event); },',
  '  pollIntervalMs: b.constants.TIME.seconds(1),',
  '  batchSize:     100,',
  '  maxAttempts:   10,',
  '});',
  'await outbox.declareSchema(b.externalDb);',
  '',
  '// Inside the operator\'s transaction — state change + event row commit together.',
  'await b.externalDb.transaction(async function (xdb) {',
  '  await xdb.query("UPDATE accounts SET balance = balance - $1 WHERE id = $2",',
  '                  [50, "a-7"]);',
  '  await outbox.enqueue({',
  '    topic:   "account.debited",',
  '    payload: { accountId: "a-7", amount: 50 },',
  '    key:     "a-7",',
  '    headers: { "trace-id": "t-abc" },',
  '  }, xdb);',
  '});',
  '',
  'await outbox.start();         // publisher worker begins draining',
  '// await outbox.stop();       // graceful shutdown</code></pre>',

  '<h2 id="pubsub">b.pubsub.create(opts) <a class="anchor" href="#pubsub">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  backend:         "local" | "cluster" | "redis"',
  '                   | { publishRemote, start, stop },',
  '                                            // default: "local"',
  '  cluster:         clusterInstance,         // backend === "cluster"',
  '  pollIntervalMs:  number,                  // default: C.TIME.ms(100) — cluster',
  '  retentionMs:     number,                  // default: C.TIME.seconds(60) — cluster',
  '  pruneEveryMs:    number,                  // default: C.TIME.minutes(5) — cluster',
  '  redisUrl:        string,                  // backend === "redis"',
  '  redisPassword:   string,                  // backend === "redis"',
  '  redisUsername:   string,                  // backend === "redis"',
  '  redisTls:        boolean,                 // backend === "redis"',
  '  redisCa:         string | Buffer,         // backend === "redis"',
  '  redisServername: string,                  // backend === "redis"',
  '  topicPrefix:     string,                  // default: "" — scopes channels',
  '  audit:           boolean,                 // default: false',
  '}</code></pre>',
  '<p>Returns an instance with <code>publish(channel, payload)</code>, <code>subscribe(channel, handler)</code> → token, <code>subscribePattern(pattern, handler)</code> (glob: <code>*</code> within a segment, <code>**</code> across segments), <code>unsubscribe(token)</code>, and <code>close()</code>. Local dispatch always runs synchronously before <code>publish()</code> resolves; the remote write is awaited so the caller knows the cross-node fan-out completed. Subscription handler errors are caught and logged — they never abort dispatch to other handlers. The pattern matcher is hand-rolled (no <code>new RegExp</code> on operator input) so a hostile pattern can\'t compile a backtracking regex; channel length is bounded to <code>C.BYTES.kib(1)</code>.</p>',
  '<pre><code class="language-javascript">// Cluster-shared bus over the framework\'s external DB — no Redis required.',
  '// var ps = b.pubsub.create({',
  '//   backend:     "cluster",',
  '//   cluster:     clusterInstance,',
  '//   topicPrefix: "wiki",',
  '// });',
  '//',
  '// var token = ps.subscribe("cache.invalidate", function (payload, ev) {',
  '//   // ev = { channel: "cache.invalidate", source: "local" | "remote", publishedBy?, publishedAt? }',
  '//   apiCache.del(payload.key);',
  '// });',
  '//',
  '// await ps.publish("cache.invalidate", { key: "page:welcome" });',
  '// → { local: 1, remote: 1 }   // dispatched count + persisted to cluster table',
  '//',
  '// Pattern subscribe — "orders.*" matches "orders.created" but not "orders.line.created".',
  '// ps.subscribePattern("orders.*", function (payload, ev) { /* ... */ });',
  '//',
  '// ps.unsubscribe(token);',
  '// await ps.close();',
  'typeof b.pubsub.create; // "function"</code></pre>',

  '<h2 id="cloud-events">CloudEvents 1.0 envelope <a class="anchor" href="#cloud-events">#</a></h2>',
  '<p><code>b.cloudEvents</code> wraps outbound events from webhook / pubsub / queue boundaries in the <strong>CloudEvents 1.0</strong> spec envelope (<a href="https://cloudevents.io/spec/v1.0">cloudevents.io/spec/v1.0</a>) — a vendor-neutral event format adopted by AWS EventBridge, Knative, Azure Event Grid, Google Eventarc, Datadog, and the broader CNCF event ecosystem. Operators wrap outbound rows so downstream consumers don\'t have to learn a bespoke shape.</p>',
  '<h3>b.cloudEvents.wrap(opts) / b.cloudEvents.parse(envelope)</h3>',
  '<pre><code class="language-javascript">// wrap opts:',
  '{',
  '  source:          string,                  // required — RFC 3986 URI-reference identifying the producer',
  '  type:            string,                  // required — reverse-DNS event type (e.g. "com.example.order.created")',
  '  id:              string,                  // default: auto-minted RFC 4122 v4 UUID',
  '  time:            string,                  // default: new Date().toISOString()',
  '  subject:         string,                  // default: null — fine-grained event subject',
  '  datacontenttype: string,                  // default: auto from data type',
  '  dataschema:      string,                  // default: null — URI to JSON Schema',
  '  data:            any,                     // default: undefined — JSON or Buffer',
  '  extensions:      object,                  // default: {} — operator-defined attrs (lowercase ASCII alnum, 1-20 chars)',
  '}</code></pre>',
  '<pre><code class="language-javascript">var ce = b.cloudEvents.wrap({',
  '  source:  "/services/orders",',
  '  type:    "com.example.order.created",',
  '  subject: "order/o-1234",',
  '  data:    { id: "o-1234", total: 4250 },',
  '});',
  '// → {',
  '//     specversion: "1.0",',
  '//     id:          "<auto-uuid-v4>",',
  '//     source:      "/services/orders",',
  '//     type:        "com.example.order.created",',
  '//     time:        "2026-05-06T...",',
  '//     subject:     "order/o-1234",',
  '//     datacontenttype: "application/json",',
  '//     data:        { id: "o-1234", total: 4250 },',
  '//   }',
  '',
  '// .parse() on the receiver — validates the envelope shape and surfaces',
  '// extension attributes separately so consumers can route on operator-',
  '// defined fields without grepping the envelope.',
  'var rv = b.cloudEvents.parse(ce);',
  '// → { specversion, id, source, type, time, subject, datacontenttype,',
  '//     dataschema, data, extensions: { /* operator-defined */ } }</code></pre>',
  '<p>Buffer-typed <code>data</code> auto-encodes to <code>data_base64</code> with <code>datacontenttype: "application/octet-stream"</code> per CloudEvents §3.1.1. Refuses <code>data</code> + <code>data_base64</code> together (spec violation), unsupported <code>specversion</code>, missing required attributes, malformed extension names. Errors carry <code>cloud-events/&lt;reason&gt;</code> codes — <code>missing-required</code> / <code>unsupported-specversion</code> / <code>data-conflict</code> / <code>bad-extension-name</code> / <code>extension-conflicts-with-spec</code>.</p>',
].join("\n"),
};
