"use strict";

module.exports = {
  slug:  "reliability",
  title: "Reliability",
  body: [
  '<h1>Reliability</h1>',
  '<p>The primitives that handle <em>what happens when things go wrong</em>: retry with backoff, circuit breaking, graceful shutdown, deprecation policy, and the durable-job patterns layered over <code>b.queue</code>.</p>',

  '<h2 id="retry">Retry <a class="anchor" href="#retry">#</a></h2>',
  '<p><code>b.retry.withRetry(fn, opts)</code> is the single retry surface the framework and operator code share. Exponential backoff with proportional jitter, configurable max attempts and per-attempt cap, an <code>isRetryable(err)</code> predicate, and a built-in error classifier covering common HTTP statuses + network errors.</p>',
  '<h3>b.retry.withRetry(fn, opts)</h3>',
  '<pre><code class="language-javascript">{',
  '  maxAttempts:     number,                 // default: 5 — total attempts including the first',
  '  baseDelayMs:     number,                 // default: 100 — initial backoff',
  '  maxDelayMs:      number,                 // default: C.TIME.seconds(10) — per-attempt cap',
  '  jitterFactor:    number,                 // default: 0.5 — finite in [0, 1]',
  '  isRetryable:     (err) =&gt; boolean,       // default: built-in HTTP/network classifier',
  '  onRetry:         (err, attemptNumber) =&gt; void,',
  '                                           // default: null',
  '  signal:          AbortSignal,            // default: null — abort retry loop',
  '}</code></pre>',
  '<pre><code class="language-javascript">var upstream  = { fetch: function (u) { return Promise.resolve({ url: u }); } };',
  'var fetchUrl = "https://example.test/api";',
  '',
  'var result = await b.retry.withRetry(',
  '  function () { return upstream.fetch(fetchUrl); },',
  '  {',
  '    maxAttempts:  5,',
  '    baseDelayMs:  100,',
  '    maxDelayMs:   5000,',
  '    isRetryable:  function (e) { return e.statusCode &gt;= 500 || /ECONN/.test(e.code || ""); },',
  '    onRetry:      function (err, n) { log.warn("retry " + n + ": " + err.message); },',
  '  },',
  ');</code></pre>',
  '<p>Built-in classifier: HTTP 408/425/429/500/502/503/504 retry; 4xx (other than the listed transients) and 501/505 are permanent. Network errors <code>ECONNRESET</code> / <code>ECONNREFUSED</code> / <code>ETIMEDOUT</code> / <code>EPIPE</code> / <code>EAGAIN</code> / <code>ENOTFOUND</code> / <code>ENETUNREACH</code> retry; everything else is permanent. Override via <code>isRetryable</code>.</p>',

  '<h2 id="safe-async-timeouts">b.safeAsync.withTimeout(promise, ms, opts?) / withSignal(promise, signal) <a class="anchor" href="#safe-async-timeouts">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  signal:       AbortSignal,',
  '  timeoutCode:  string,',
  '  timeoutError: Error,',
  '}</code></pre>',
  '<p>Promise-boundary helpers for request, queue, and background work. They turn hung async operations into explicit timeout or abort errors instead of leaving unresolved promises behind.</p>',
  '<pre><code class="language-javascript">var value = await b.safeAsync.withTimeout(Promise.resolve("ok"), b.constants.TIME.seconds(1));',
  'value; // "ok"',
  'typeof b.safeAsync.withSignal; // "function"</code></pre>',

  '<h2 id="safe-async-with-signal">b.safeAsync.withSignal(promise, signal) <a class="anchor" href="#safe-async-with-signal">#</a></h2>',
  '<p>Rejects work when the supplied abort signal fires, giving operator code one consistent cancellation shape.</p>',
  '<pre><code class="language-javascript">typeof b.safeAsync.withSignal; // "function"</code></pre>',

  '<h2 id="safe-async-sleep">b.safeAsync.sleep(ms, opts?) / withTimeoutSignal(signal, ms) <a class="anchor" href="#safe-async-sleep">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  signal: AbortSignal,',
  '}</code></pre>',
  '<p>Abort-aware sleep and timeout-signal helpers. Retry, polling, and scheduled jobs use these instead of raw <code>setTimeout</code> promises.</p>',
  '<pre><code class="language-javascript">await b.safeAsync.sleep(1);',
  'var signal = b.safeAsync.withTimeoutSignal(null, b.constants.TIME.seconds(1));',
  'signal.aborted; // false</code></pre>',

  '<h2 id="safe-async-timeout-signal">b.safeAsync.withTimeoutSignal(signal, ms) <a class="anchor" href="#safe-async-timeout-signal">#</a></h2>',
  '<p>Combines an optional caller signal with a timeout-generated abort signal for bounded operations.</p>',
  '<pre><code class="language-javascript">typeof b.safeAsync.withTimeoutSignal; // "function"</code></pre>',

  '<h2 id="safe-async-capture">b.safeAsync.safeAwait(promise) / safeInvoke(fn, payload, onError) <a class="anchor" href="#safe-async-capture">#</a></h2>',
  '<p>Error-capturing helpers for optional hooks and firebreak boundaries. They keep operator callbacks from breaking the framework path that invoked them.</p>',
  '<pre><code class="language-javascript">var pair = await b.safeAsync.safeAwait(Promise.resolve(42));',
  'pair[0] === null && pair[1] === 42; // true',
  'b.safeAsync.safeInvoke(function (x) { return x.ok; }, { ok: true });</code></pre>',

  '<h2 id="safe-async-safe-invoke">b.safeAsync.safeInvoke(fn, payload, onError) <a class="anchor" href="#safe-async-safe-invoke">#</a></h2>',
  '<p>Runs an optional hook and captures thrown errors so observers cannot break the caller path.</p>',
  '<pre><code class="language-javascript">b.safeAsync.safeInvoke(function (x) { return x.ok; }, { ok: true });</code></pre>',

  '<h2 id="safe-async-drop">b.safeAsync.makeDropCallback(onDrop, onError) <a class="anchor" href="#safe-async-drop">#</a></h2>',
  '<p>Wraps queue/cache drop hooks so a broken observer cannot crash the producer that noticed the drop.</p>',
  '<pre><code class="language-javascript">var dropped = false;',
  'var onDrop = b.safeAsync.makeDropCallback(function () { dropped = true; });',
  'onDrop("overflow", [], null);',
  'dropped; // true</code></pre>',

  '<h2 id="safe-async-scheduled-flush">b.safeAsync.makeScheduledFlush(delayMs, flushFn) <a class="anchor" href="#safe-async-scheduled-flush">#</a></h2>',
  '<p>Debounced flush scheduler for writers that should coalesce bursts but still expose explicit cancel and pending state.</p>',
  '<pre><code class="language-javascript">var scheduled = b.safeAsync.makeScheduledFlush(b.constants.TIME.seconds(1), function () {});',
  'scheduled.schedule();',
  'scheduled.isPending(); // true',
  'scheduled.cancel();</code></pre>',

  '<h2 id="safe-async-parallel">b.safeAsync.parallel(items, fn, opts?) <a class="anchor" href="#safe-async-parallel">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  concurrency: number,       // default 8, max 256',
  '  signal:      AbortSignal,  // refuses to dispatch further items on abort',
  '}</code></pre>',
  '<p>Bounded-concurrency mapAsync. Runs <code>fn(item, index)</code> over the input list with a continuous worker queue (no Promise.all-batched chunks, so a slow item does not block unrelated items from entering the pool) and resolves with results in input order. The first rejection propagates; in-flight promises run to settle.</p>',
  '<pre><code class="language-javascript">var doubled = await b.safeAsync.parallel([1, 2, 3, 4], async function (n) {',
  '  return n * 2;',
  '}, { concurrency: 2 });',
  'doubled.join(","); // "2,4,6,8"</code></pre>',

  '<h2 id="safe-async-concurrency">b.safeAsync.Semaphore / Mutex / Once <a class="anchor" href="#safe-async-concurrency">#</a></h2>',
  '<p>Small concurrency primitives used by the framework and available to operator extensions: bounded parallelism, exclusive sections, and exactly-once async initialization.</p>',
  '<pre><code class="language-javascript">var sem = new b.safeAsync.Semaphore(2);',
  'typeof sem.acquire; // "function"',
  'var once = new b.safeAsync.Once(async function () { return "ready"; });',
  'await once.run();</code></pre>',

  '<h2 id="safe-async-semaphore">b.safeAsync.Semaphore(limit) <a class="anchor" href="#safe-async-semaphore">#</a></h2>',
  '<p>Bounds concurrent async work with acquire and release semantics.</p>',
  '<pre><code class="language-javascript">var sem = new b.safeAsync.Semaphore(2);',
  'typeof sem.acquire; // "function"</code></pre>',

  '<h2 id="safe-async-mutex">b.safeAsync.Mutex() <a class="anchor" href="#safe-async-mutex">#</a></h2>',
  '<p>Serializes an async critical section when only one caller may mutate shared state at a time.</p>',
  '<pre><code class="language-javascript">var mutex = new b.safeAsync.Mutex();',
  'typeof mutex.runExclusive; // "function"</code></pre>',

  '<h2 id="safe-async-once">b.safeAsync.Once(fn) <a class="anchor" href="#safe-async-once">#</a></h2>',
  '<p>Runs an async initializer once and shares the result with every caller.</p>',
  '<pre><code class="language-javascript">var once = new b.safeAsync.Once(async function () { return "ready"; });',
  'typeof once.run; // "function"</code></pre>',

  '<h2 id="safe-async-repeating">b.safeAsync.repeating(fn, intervalMs, opts?) / flushLoop(fn, intervalMs, opts?) <a class="anchor" href="#safe-async-repeating">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  name:    string,',
  '  onError: function,',
  '  signal:  AbortSignal,',
  '}</code></pre>',
  '<p>Unref-aware background loops for monitors and flushers. The returned handle has <code>stop()</code> so app shutdown can quiesce periodic work.</p>',
  '<pre><code class="language-javascript">var loop = b.safeAsync.repeating(function () {}, b.constants.TIME.seconds(60));',
  'loop.stop();',
  'typeof b.safeAsync.flushLoop; // "function"</code></pre>',

  '<h2 id="safe-async-flush-loop">b.safeAsync.flushLoop(fn, intervalMs, options) <a class="anchor" href="#safe-async-flush-loop">#</a></h2>',
  '<p>Runs a periodic flush loop with the same stop handle and unref behavior as other safe-async background work.</p>',
  '<pre><code class="language-javascript">typeof b.safeAsync.flushLoop; // "function"</code></pre>',

  '<h2 id="safe-async-circuit-breaker">b.safeAsync.CircuitBreaker(name, options) <a class="anchor" href="#safe-async-circuit-breaker">#</a></h2>',
  '<p>Compatibility circuit-breaker constructor exposed on the safe-async namespace for modules that do not import retry directly.</p>',
  '<pre><code class="language-javascript">typeof b.safeAsync.CircuitBreaker; // "function"</code></pre>',

  '<h2 id="safe-async-retry">b.safeAsync.asyncRetry(fn, opts?) <a class="anchor" href="#safe-async-retry">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  attempts: number,',
  '  delayMs:  number,',
  '  onRetry:  function,',
  '}</code></pre>',
  '<p>Compatibility alias for async retry workflows that need the safe-async namespace. New operator code usually calls <code>b.retry.withRetry</code> directly.</p>',
  '<pre><code class="language-javascript">typeof b.safeAsync.asyncRetry; // "function"</code></pre>',

  '<h2 id="retry-circuit">b.retry.CircuitBreaker(name, opts) <a class="anchor" href="#retry-circuit">#</a></h2>',
  '<p>Wraps a callable in a half-open / open / closed state machine: when an upstream is consistently failing, the breaker trips open and short-circuits new calls without burning attempts. After a cooldown the breaker enters half-open and probes; <code>successThreshold</code> consecutive probes re-close it.</p>',
  '<pre><code class="language-javascript">// CircuitBreaker constructor opts:',
  '{',
  '  failureThreshold:   number,              // default: 10 — open after N consecutive failures',
  '  cooldownMs:         number,              // default: C.TIME.seconds(30)',
  '  successThreshold:   number,              // default: 2 — half-open probes before re-close',
  '}</code></pre>',
  '<pre><code class="language-javascript">var breaker = new b.retry.CircuitBreaker("upstream-x", {',
  '  failureThreshold: 10,',
  '  cooldownMs:       C.TIME.seconds(30),',
  '});',
  '',
  '// .wrap(fn) runs the function through the breaker',
  'var upstream = { fetch: function (u) { return Promise.resolve({ url: u }); } };',
  'await breaker.wrap(function () { return upstream.fetch("https://example.test/api"); });',
  '// → throws CIRCUIT_OPEN immediately when the breaker is tripped</code></pre>',

  '<h2 id="shutdown">Graceful shutdown <a class="anchor" href="#shutdown">#</a></h2>',
  '<p><code>b.appShutdown.create()</code> coordinates an orderly stop: drain the HTTP listener, wait for in-flight requests, close websockets, finish queue leases, flush audit, sync vault, close the DB. <strong>Phases are an array passed at create time</strong> — each one runs sequentially with its own <code>timeoutMs</code>; a phase that misses its budget is logged and the next phase starts anyway, so a stuck connection can\'t hold the whole shutdown hostage.</p>',
  '<h3>b.appShutdown.create(opts)</h3>',
  '<pre><code class="language-javascript">{',
  '  graceMs:                 number,         // default: 30000 — overall budget',
  '  installSignalHandlers:   boolean,        // default: false — when true, SIGTERM/SIGINT trigger',
  '  phases:                  Array&lt;{         // default: []',
  '    name:       string,                    //   required: true',
  '    run:        () =&gt; Promise,             //   required: true',
  '    timeoutMs:  number,                    //   default: framework default',
  '  }&gt;,',
  '}</code></pre>',
  '<pre><code class="language-javascript">var shutdown = b.appShutdown.create({',
  '  graceMs: C.TIME.seconds(30),',
  '  installSignalHandlers: true,',
  '  phases: [',
  '    { name: "drain-http",      run: async () =&gt; { await server.close(); }, timeoutMs: 10000 },',
  '    { name: "flush-app-state", run: async () =&gt; { await myWriter.flush(); }, timeoutMs: 5000 },',
  '    { name: "close-db",        run: async () =&gt; { await b.db.close(); },    timeoutMs: 5000 },',
  '  ],',
  '});',
  '',
  '// Wire shutdown.middleware() into the request pipeline so new requests',
  '// get 503 once draining begins. Operators that want manual control:',
  'process.on("SIGTERM", function () { shutdown.shutdown(); });</code></pre>',

  '<h2 id="jobs-advanced">Advanced jobs <a class="anchor" href="#jobs-advanced">#</a></h2>',
  '<p><code>b.jobs</code> sits over <code>b.queue</code> for durable work-in-flight. Register a handler by name; enqueue a payload; the framework leases it to one consumer at a time, extends the lease for long-running work, and moves the item to the dead-letter queue after the per-job <code>maxAttempts</code> budget is exhausted.</p>',
  '<p>Long-job patterns:</p>',
  '<ul>',
  '  <li><strong>Retry tuning</strong>: pass <code>maxAttempts</code> on enqueue per-job; the framework decrements on each lease and routes to DLQ at zero.</li>',
  '  <li><strong>Idempotency</strong>: handlers should be safe to re-run. The framework re-leases on consumer crash; a handler that booked a payment must dedupe by the payload\'s idempotency key.</li>',
  '  <li><strong>DLQ inspection &amp; retry</strong>: <code>b.queue.dlqList(queueName)</code> / <code>b.queue.dlqSize(queueName)</code> / <code>b.queue.dlqRetry(jobId)</code> — the DLQ surface is flat on <code>b.queue</code>, not a nested namespace.</li>',
  '</ul>',

  '<h2 id="deprecate">Deprecation policy <a class="anchor" href="#deprecate">#</a></h2>',
  '<p><code>b.deprecate</code> is the framework\'s own deprecation-warning channel — primitives that move surface forward emit a one-line warning per process per <code>(name, since)</code> tuple. Operators control the behavior:</p>',
  '<ul>',
  '  <li><code>BLAMEJS_DEPRECATIONS=warn</code> — print to stderr (default for non-production).</li>',
  '  <li><code>BLAMEJS_DEPRECATIONS=silent</code> — drop (default for <code>NODE_ENV=production</code>).</li>',
  '  <li><code>BLAMEJS_DEPRECATIONS=error</code> — throw on first deprecated call. Useful as a CI gate so a deprecated surface never lands silently.</li>',
  '</ul>',
  '<p><code>b.deprecate.list()</code> returns every deprecation seen this process — <code>{ name, since, removeIn, callCount, firstSeen }</code> — for ops dashboards / pre-upgrade reports.</p>',

  '<h2 id="deprecate-warn">b.deprecate.warn(name, options) <a class="anchor" href="#deprecate-warn">#</a></h2>',
  '<p>Emits the framework deprecation warning for one surface, respecting warn, silent, and error modes.</p>',
  '<pre><code class="language-javascript">typeof b.deprecate.warn; // "function"</code></pre>',

  '<h2 id="deprecate-wrap">b.deprecate.wrap(fn, options) <a class="anchor" href="#deprecate-wrap">#</a></h2>',
  '<p>Wraps a deprecated function so the warning channel fires when callers use the old surface.</p>',
  '<pre><code class="language-javascript">typeof b.deprecate.wrap; // "function"</code></pre>',

  '<h2 id="deprecate-alias">b.deprecate.alias(target, options) <a class="anchor" href="#deprecate-alias">#</a></h2>',
  '<p>Builds a deprecated alias around a replacement function while preserving the warning metadata.</p>',
  '<pre><code class="language-javascript">typeof b.deprecate.alias; // "function"</code></pre>',

  '<h2 id="deprecate-list">b.deprecate.list() <a class="anchor" href="#deprecate-list">#</a></h2>',
  '<p>Returns deprecation warnings seen in this process for pre-upgrade reports and ops dashboards.</p>',
  '<pre><code class="language-javascript">Array.isArray(b.deprecate.list()); // true</code></pre>',

  '<h2 id="deprecate-reset">b.deprecate.reset() <a class="anchor" href="#deprecate-reset">#</a></h2>',
  '<p>Clears process-local deprecation warning state for tests and controlled reloads.</p>',
  '<pre><code class="language-javascript">typeof b.deprecate.reset; // "function"</code></pre>',

  '<h2 id="deprecate-mode">b.deprecate.getMode() <a class="anchor" href="#deprecate-mode">#</a></h2>',
  '<p>Returns the active deprecation mode after environment defaults and overrides are applied.</p>',
  '<pre><code class="language-javascript">typeof b.deprecate.getMode; // "function"</code></pre>',
].join("\n"),
};
