"use strict";

module.exports = {
  slug:  "routing",
  title: "Routing",
  body: [
  '<h1>Routing</h1>',
  '<p>The HTTP entry surface: a path-based router with parameters, schema-validated routes, OpenAPI publication, content rendering with sane Cache-Control defaults, request-context helpers, static file serving, and operator-friendly error pages.</p>',

  '<h2 id="router">Router</h2>',

  '<h3>new b.router.Router(opts?) <a class="anchor" href="#router-ctor">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  caseSensitive:   boolean,                 // default: false — "/Users" === "/users"',
  '  strict:          boolean,                 // default: false — "/users" === "/users/"',
  '  trustProxy:      boolean | number,        // default: false — gates X-Forwarded-* in helpers',
  '}</code></pre>',
  '<p>Returns a router with parameter-aware paths (<code>:id</code>), wildcards (<code>*</code>), and a stable <code>req.routePattern</code> field that propagates to metrics + tracing so cardinality stays bounded. Middleware that takes <code>(req, res, next)</code> can stop the chain by not calling <code>next()</code>; terminal handlers take <code>(req, res)</code> and the framework treats them as the end of the chain regardless. The router dispatches on <code>handler.length</code>, so the convention is structural — not return-value inspection.</p>',
  '<pre><code class="language-javascript">var r = new b.router.Router();',
  'r.get("/users/:id", function (req, res) { res.json({ id: req.params.id }); });',
  'r.post("/users", function (req, res) { res.json({ created: true }); });',
  '</code></pre>',

  '<h3>b.router.create(opts?) <a class="anchor" href="#router-create">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  tls0Rtt:  "refuse" | "replay-cache",   // default: "refuse"',
  '                                         //   RFC 8446 §8 + RFC 8470 anti-replay posture',
  '}</code></pre>',
  '<p>Factory equivalent to <code>new b.router.Router(opts)</code>. The <code>tls0Rtt</code> opt selects the TLS 1.3 0-RTT (early-data) anti-replay posture. <code>"refuse"</code> (default, matches Node) sets <code>allowEarlyData: false</code> on the underlying h2 secure server AND refuses any inbound request bearing the RFC 8470 <code>Early-Data: 1</code> header with HTTP 425 + <code>Connection: close</code>. <code>"replay-cache"</code> opts in: 0-RTT is admitted at the TLS layer and every <code>Early-Data: 1</code> request is dedupe-checked against an in-process replay cache (SHA3-512 over method + URL + Host + Authorization + Date + Idempotency-Key, rolling 10 s window). Cache hit refuses with HTTP 425 + audit <code>tls.0rtt.replayed</code>; cache miss admits with audit <code>tls.0rtt.accepted</code>. Posture-asserted regulatory regimes (<code>pci-dss</code>, <code>fapi2</code>) override <code>"replay-cache"</code> → <code>"refuse"</code> at listen time and emit <code>tls.0rtt.refused</code> with reason <code>posture-failclosed</code>.</p>',
  '<pre><code class="language-javascript">var r = b.router.create({ tls0Rtt: "refuse" });',
  'r.get("/healthz", function (req, res) { res.json({ ok: true }); });',
  '// Under "replay-cache" + Early-Data: 1, second identical request → 425 early-data-replay',
  '</code></pre>',

  '<h3>router.METHOD(path, spec?, ...handlers) <a class="anchor" href="#router-schema">#</a></h3>',
  '<pre><code class="language-javascript">// spec (optional — pass before any handler):',
  '{',
  '  body:          schema,                    // optional — b.safeSchema validator',
  '  query:         schema,                    // optional — query param validator',
  '  params:        schema,                    // optional — :param validator',
  '  response:      schema,                    // optional — outgoing JSON validator',
  '  validateResponse: "throw" | "warn",       // optional — per-route override',
  '  description:   string,                    // OpenAPI description',
  '  summary:       string,                    // OpenAPI summary',
  '  tags:          [string],                  // OpenAPI tags',
  '  auditAction:   string,                    // optional — auto-emitted on success',
  '}</code></pre>',
  '<p>Pass a spec object as the second arg (before any handler) to validate body / query / params via <code>b.safeSchema</code>. Mismatches return 400 with per-field paths before the handler runs. <code>response: schema</code> validates outgoing JSON in dev and as an opt-in prod gate via <code>BLAMEJS_VALIDATE_RESPONSES</code>.</p>',
  '<pre><code class="language-javascript">var s = b.safeSchema;',
  'var r = new b.router.Router();',
  'r.post("/users",',
  '  {',
  '    body:        s.object({ name: s.string(), age: s.number().int().min(0) }),',
  '    query:       s.object({ ref: s.string().optional() }),',
  '    description: "Create a new user",',
  '    summary:     "Create user",',
  '    tags:        ["users"],',
  '  },',
  '  function (req, res) { res.json({ id: "u-1" }); }',
  ');</code></pre>',

  '<h3>router.openapi(opts) <a class="anchor" href="#router-openapi">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  info:          { title: string, version: string, description?: string },',
  '  servers:       [{ url: string, description?: string }],  // optional',
  '  components:    object,                    // optional — schemas / securitySchemes',
  '}</code></pre>',
  '<p>Walks the route table and returns a Swagger 3.0 doc — paths, methods, summaries, descriptions, tags, path-params auto-derived from the pattern. Operators serve it from a route to ship live API docs without an extra build step.</p>',
  '<pre><code class="language-javascript">var r = new b.router.Router();',
  'r.get("/users/:id", { summary: "Get user", tags: ["users"] }, function (req, res) { res.end(); });',
  'var doc = r.openapi({ info: { title: "My API", version: "1.0.0" } });',
  '</code></pre>',

  '<h2 id="protocol-dispatcher">b.protocolDispatcher.create(opts) <a class="anchor" href="#protocol-dispatcher">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  name:             string,                  // required — appears in error messages',
  '  protocols:        { <name>: { create, ... } },  // required — implemented backends',
  '  deferred:         { <name>: { description?, since? } },  // optional — known-but-not-implemented',
  '  fallbackProtocol: string,                  // optional — hinted in deferred-error message',
  '  errorClass:       errorClass,              // optional — defineClass-built; default ProtocolDispatcherError',
  '}</code></pre>',
  '<p>Pluggable backend resolver shared by <code>b.queue</code>, <code>b.logStream</code>, and <code>b.objectStore</code>. Each previously copied a ~30-line dispatch block that validated <code>{ protocol }</code>, distinguished implemented from deferred backends, and threw a typed error for unknown values. The dispatcher owns that lookup so callers focus on post-resolve concerns (retry+breaker wrapping, classification, batched dispatch). Returns an instance with <code>resolve(protocol)</code> → backend module, plus <code>protocols</code> + <code>deferred</code> string lists for boot-time diagnostics. <code>resolve</code> throws with codes <code>MISSING_PROTOCOL</code> / <code>PROTOCOL_NOT_IMPLEMENTED</code> / <code>UNKNOWN_PROTOCOL</code> — every error carries the dispatcher\'s <code>name</code> so an operator with multiple dispatchers reading the message knows which one rejected.</p>',
  '<pre><code class="language-javascript">// var queueDispatcher = b.protocolDispatcher.create({',
  '//   name:             "queue",',
  '//   protocols:        { local: localQueue, redis: redisQueue },',
  '//   deferred:         { sqs: { description: "Amazon SQS", since: "v0.9" } },',
  '//   fallbackProtocol: "local",',
  '// });',
  '//',
  '// var backend = queueDispatcher.resolve("redis");   // → redisQueue module',
  '// queueDispatcher.resolve("kafka") throws UNKNOWN_PROTOCOL with "known: local, redis".',
  '// queueDispatcher.resolve("sqs")   throws PROTOCOL_NOT_IMPLEMENTED hinting fallback "local".',
  '//',
  '// queueDispatcher.protocols;   // → ["local", "redis"]',
  '// queueDispatcher.deferred;    // → ["sqs"]',
  'typeof b.protocolDispatcher.create; // "function"</code></pre>',

  '<h2 id="render">Render + Cache-Control</h2>',

  '<h3>b.render.htmlString(res, html, opts?) / b.render.json(res, body, opts?) / b.render.text(res, body, opts?) / b.render.redirect(res, url, opts?) <a class="anchor" href="#render-helpers">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  status:        number,                    // default: 200 (302 for redirect)',
  '  headers:       object,                    // additional / overriding headers',
  '}</code></pre>',
  '<p>Each helper sets a sensible default <code>Cache-Control: private, no-cache, must-revalidate</code> on every dynamic surface. Browsers may still cache the response, but they\'re forced to revalidate on every navigation. Operators who want a CDN-cacheable response override per-call.</p>',
  '<pre><code class="language-javascript">b.render.htmlString(res, "<h1>hi</h1>", {',
  '  headers: { "Cache-Control": "public, max-age=300, stale-while-revalidate=60" },',
  '});</code></pre>',

  '<h3>b.render.json(res, body, opts?) <a class="anchor" href="#render-json">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  status:    number,                        // default: 200',
  '  headers:   object,                        // additional / overriding headers',
  '}</code></pre>',
  '<p>JSON-encodes <code>body</code>, sets <code>Content-Type: application/json; charset=utf-8</code>, computes <code>Content-Length</code>, and ends the response. The default <code>Cache-Control: private, no-cache, must-revalidate</code> still applies — operators wanting CDN-cacheable JSON override per call. Falls through silently when the response is already finished (<code>res.writableEnded === true</code>) so a stray late write from a rejected Promise can\'t corrupt the wire.</p>',
  '<pre><code class="language-javascript">b.render.json(res, { id: "u-1", name: "Alice" });',
  '',
  '// Custom status + extra header',
  'b.render.json(res, { error: "not_found" }, {',
  '  status:  404,',
  '  headers: { "X-Request-Id": req.requestId },',
  '});</code></pre>',

  '<h3>b.render.redirect(res, location, opts?) <a class="anchor" href="#render-redirect">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  status:    number,                        // default: 302; 301 / 303 / 307 / 308 also valid',
  '  headers:   object,                        // additional / overriding headers',
  '}</code></pre>',
  '<p>Sets <code>Location</code>, picks a 3xx status, and ends with an empty body. Empty / non-string <code>location</code> throws at call time. Status outside the 3xx range throws — the helper is for redirects only, not arbitrary status codes with a <code>Location</code> header. Operators forwarding to user-supplied URLs should run <code>b.safeRedirect</code> first to gate against open-redirect abuse before passing the value here.</p>',
  '<pre><code class="language-javascript">// Default 302',
  'b.render.redirect(res, "/login");',
  '',
  '// 303 See Other after a successful POST → GET handoff (RFC 9110 §15.4.4)',
  'b.render.redirect(res, "/orders/o-1234", { status: 303 });</code></pre>',

  '<h3>b.render.text(res, body, opts?) <a class="anchor" href="#render-text">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  status:    number,                        // default: 200',
  '  headers:   object,                        // additional / overriding headers',
  '  charset:   string,                        // default: "utf-8"',
  '}</code></pre>',
  '<p>Plain-text response. Sets <code>Content-Type: text/plain; charset=&lt;charset&gt;</code>, computes <code>Content-Length</code> against the chosen charset, and ends the response. <code>null</code> / <code>undefined</code> bodies coerce to the empty string so a 200-with-empty-body shape (typical for liveness probes) doesn\'t require a special branch in the route handler.</p>',
  '<pre><code class="language-javascript">b.render.text(res, "OK");',
  '',
  '// Health-check endpoint that needs an explicit no-store directive.',
  'b.render.text(res, "ok", {',
  '  headers: { "Cache-Control": "no-store" },',
  '});</code></pre>',

  '<h3>b.htmlBalance.check(html) <a class="anchor" href="#html-balance">#</a></h3>',
  '<p>Structural sanity check for operator-submitted HTML — unclosed tags, orphan closes, mismatched closers, unterminated comments, void-element close tags. Returns <code>null</code> when balanced; an object <code>{ code, message, line, column }</code> when not. Useful as a CI gate on user-authored content (CMS bodies, email templates) before the framework caches it.</p>',
  '<pre><code class="language-javascript">var problem = b.htmlBalance.check("<p>hi <strong>world</p>");',
  '// → { code: "MISMATCHED_CLOSE", message: "...", line: 1, column: ... }',
  '',
  'var ok = b.htmlBalance.check("<p>hi <strong>world</strong></p>");',
  '// → null   (balanced)</code></pre>',

  '<h2 id="static">Static file serving</h2>',

  '<h3>b.staticServe.create(opts) <a class="anchor" href="#static-serve">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  root:               string,               // required — directory to serve from',
  '  mountPath:          string,               // optional — strip this prefix off req.url',
  '  hashedPathPattern:  RegExp,               // default: framework-bundler hash pattern',
  '  indexFile:          string | null,        // default: "index.html"; null to disable',
  '  defaultMaxAge:      number,               // default: 3600 (seconds) for non-hashed files',
  '  contentTypes:       object,               // optional — extension → mime overrides',
  '  // ---- conditional / range posture ----',
  '  acceptRanges:       boolean,              // default: true — RFC 7233 single-range support (multi-range refused with 416)',
  '  // ---- security gates (all optional, security-on by default when wired) ----',
  '  permissions:        b.permissions,        // optional — framework calls .check(req, "static.serve") before serving',
  '  retention:          { isServable },       // optional — compliance gate, returns 451 when !isServable',
  '  revokeStore:        { isRevoked, revoke }, // optional — force-revoke registry; serves 404 when revoked',
  '  fileType:           b.fileType,           // required when allowedFileTypes set',
  '  allowedFileTypes:   ["image/png", ...],   // optional — magic-byte MIME allowlist; refuses 415',
  '  contentSafety:      { ".csv": gate },     // default: b.guardAll.byExtension({ profile: "strict" }); null to opt out (audited via contentSafetyDisabledReason)',
  '  contentSafetyDisabledReason: string,      // optional — operator reason recorded in audit when contentSafety: null',
  '  // ---- bandwidth + concurrency caps (require opts.cache) ----',
  '  cache:              b.cache,              // required when any quota is set',
  '  maxBytesPerActorPerWindowMs:  number,     // default: 0 (no cap)',
  '  maxBytesAllActorsPerWindowMs: number,     // default: 0 (no cap)',
  '  bandwidthWindowMs:  number,               // default: 60_000ms',
  '  maxConcurrentDownloadsPerActor: number,   // default: 0 (no cap)',
  '  // ---- streaming + cancellation ----',
  '  maxIdleMs:          number,               // default: 120_000ms — close stalled streams',
  '  // ---- audit + observability (security-on defaults) ----',
  '  audit:              b.audit,              // optional — emits staticServe.serve.success/failure with 5-W actor context',
  '  observability:      b.observability,      // optional — counters: bytes_served, requests_served, etag_hits, range_requests, etc.',
  '  auditSuccess:       boolean,              // default: true (the serve event IS the audit-worthy act)',
  '  auditFailures:      boolean,              // default: true',
  '  // ---- per-request operator hook ----',
  '  onServe:            async function (info), // optional — called pre-stream with { req, res, urlPath, headers, range, actor, ... }',
  '}</code></pre>',
  '<p>Returns a callable handle that doubles as a middleware <code>(req, res, next)</code> and exposes instance methods (<code>.revoke(key)</code>, <code>.unrevoke(key)</code>, <code>.stats()</code>, <code>.invalidateMeta(key)</code>). The path-resolution layer enforces a containment check so a request for <code>/../../etc/passwd</code> resolves outside <code>root</code> and falls through to <code>next()</code> (operators surface a 404 there). The <code>immutable</code> directive is set automatically when the URL matches <code>hashedPathPattern</code> (default matches Vite / esbuild / framework-bundler content-hashed filenames) — operators serving raw <code>style.css</code> get <code>max-age=3600</code> with no immutable; the hashed <code>style.83631e970cc34c0d.css</code> next to it gets the longer cache + immutable hint.</p>',
  '<p><strong>Conditional + range responses:</strong> the framework handles every conditional header (<code>If-None-Match</code>, <code>If-Match</code>, <code>If-Modified-Since</code>, <code>If-Unmodified-Since</code>) plus single-range <code>Range</code> requests (RFC 7233). Multi-range requests are explicitly refused with 416 — operators with a multi-range need use <code>b.objectStore.presignedDownloadUrl</code> directly. Cancellation is propagated: when the client disconnects mid-stream the file read is destroyed and the concurrency slot is released.</p>',
  '<p><strong>Security gates wired in order:</strong> permissions → retention → revoke → MIME allowlist → conditional headers → range parsing → concurrency cap → bandwidth quota → onServe hook → stream. Each fails with the operator-meaningful HTTP status (403 / 451 / 404 / 415 / 412 / 416 / 429 / 500). Audit emission carries the 5 W&apos;s via <code>b.requestHelpers.extractActorContext</code> on every success and every failure (operators with extreme-volume read paths can opt out of success emissions via <code>auditSuccess: false</code>).</p>',
  '<pre><code class="language-javascript">// Production wiring with permissions + bandwidth caps + audit.',
  '// `permissions`, `cache`, `audit`, `observability` are instances the',
  '// operator built earlier in their bootstrap (b.permissions.create / etc).',
  '//',
  '// var assets = b.staticServe.create({',
  '//   root:               "./public/dist",',
  '//   mountPath:          "/assets",',
  '//   defaultMaxAge:      b.constants.TIME.days(30) / b.constants.TIME.seconds(1),',
  '//   permissions:        permissions,         // framework calls .check(req, "static.serve")',
  '//   cache:              cache,                // cluster-shared bandwidth tracking',
  '//   maxBytesPerActorPerWindowMs: b.constants.BYTES.gib(1),',
  '//   maxConcurrentDownloadsPerActor: 8,',
  '//   audit:              audit,',
  '//   observability:      observability,',
  '// });',
  '// router.use("/assets", assets);',
  '//',
  '// Force-revoke a key (e.g. operator pulls a leaked file).',
  '// await assets.revoke("/assets/leaked.pdf");',
  '//',
  '// Operator dashboard snapshot.',
  '// var s = assets.stats();',
  '// → { requestsServed, bytesServed, etagHits, rangeRequests, permissionDenied, quotaRejected, failures }',
  'b.staticServe.DEFAULT_MAX_AGE_SEC;   // 3600 — referenced for symbol-resolve gate</code></pre>',

  '<h2 id="error-page">Error pages</h2>',

  '<h3>b.errorPage.create(opts) <a class="anchor" href="#error-page-create">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  audit:         auditInstance,             // required — b.audit instance for actor emission',
  '  mode:          "dev" | "prod",            // default: derived from NODE_ENV',
  '  trustProxy:    boolean,                   // default: false — honor X-Forwarded-For for actor.ip',
  '  template:      function,                  // optional — custom HTML renderer (req, err) → string',
  '}</code></pre>',
  '<p>Operator-friendly error renderer. Different responses for HTML clients (templated page with the request-id) vs JSON clients (RFC 7807 Problem+JSON). Audit emission with the actor 5 W\'s.</p>',
  '<pre><code class="language-javascript">var errorHandler = b.errorPage.create({',
  '  audit:      b.audit,',
  '  trustProxy: true,',
  '});',
  '// errorHandler is a (err, req, res, next) middleware — mount last in the stack.</code></pre>',

  '<h2 id="request-helpers">Request helpers</h2>',

  '<h3>b.requestHelpers.extractActorContext(req, override?) <a class="anchor" href="#extract-actor">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  // override (optional) — fields here win over header-derived values',
  '  ip:            string,',
  '  userAgent:     string,',
  '  userId:        string,',
  '  sessionId:     string,',
  '}</code></pre>',
  '<p>Returns the 5 W\'s actor object every audit emission expects: <code>{ userId, sessionId, ip, userAgent, requestId, method, route }</code>. Pulls from the request\'s session, headers, socket; <code>override</code> lets operators inject CDN-supplied client IP headers without weakening the framework default of socket-only IP.</p>',
  '<pre><code class="language-javascript">var actor = b.requestHelpers.extractActorContext(req, {',
  '  ip: req.headers["cf-connecting-ip"],',
  '});',
  '</code></pre>',

  '<h3>b.requestHelpers.parseQualityList(value, opts?) <a class="anchor" href="#parse-quality-list">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  lowercase:   boolean,                    // default: true — normalize tokens to lowercase',
  '  defaultQ:    number,                     // default: 1 — q for entries without ;q=',
  '}</code></pre>',
  '<p>RFC 9110 §12.5 Accept-* parser. Walks a quality-weighted header value (Accept, Accept-Language, Accept-Encoding, Accept-Charset) and returns <code>[{ value, q }, ...]</code> sorted by q descending. Pure function — no request / response references.</p>',
  '<pre><code class="language-javascript">var langs = b.requestHelpers.parseQualityList("en-US,en;q=0.9,fr;q=0.7");',
  '// → [{ value: "en-us", q: 1 }, { value: "en", q: 0.9 }, { value: "fr", q: 0.7 }]</code></pre>',

  '<h3>b.requestHelpers.parseListHeader(value, opts?) <a class="anchor" href="#parse-list-header">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  lowercase:   boolean,                    // default: false',
  '  trim:        boolean,                    // default: true',
  '  unique:      boolean,                    // default: false — dedupe',
  '}</code></pre>',
  '<p>Comma-separated header parser. Splits, trims (default), optionally lowercases + dedupes, and drops empty tokens. Used for parsing <code>Vary</code>, <code>Connection</code>, <code>Forwarded</code>, custom comma-separated headers — anything where RFC 9110 list rules apply.</p>',
  '<pre><code class="language-javascript">var tokens = b.requestHelpers.parseListHeader("X-Foo, X-Bar , ,X-Foo", { unique: true });',
  '// → ["X-Foo", "X-Bar"]</code></pre>',

  '<h2 id="request-helper-route">b.requestHelpers.resolveRoute(req) <a class="anchor" href="#request-helper-route">#</a></h2>',
  '<p>Returns the best route identifier for audit and observability metadata, preferring framework route state over raw URL strings.</p>',
  '<pre><code class="language-javascript">typeof b.requestHelpers.resolveRoute; // "function"</code></pre>',

  '<h2 id="request-helper-status">b.requestHelpers.captureResponseStatus(res) <a class="anchor" href="#request-helper-status">#</a></h2>',
  '<p>Captures response status for audit emitters that need the final status code after middleware and handlers run.</p>',
  '<pre><code class="language-javascript">typeof b.requestHelpers.captureResponseStatus; // "function"</code></pre>',

  '<h2 id="request-helper-actor-override">b.requestHelpers.resolveActorWithOverride(options) <a class="anchor" href="#request-helper-actor-override">#</a></h2>',
  '<p>Builds actor metadata from either a request or explicit caller options, used by background jobs and admin tools that still need the audit 5 W\'s.</p>',
  '<pre><code class="language-javascript">typeof b.requestHelpers.resolveActorWithOverride; // "function"</code></pre>',

  '<h2 id="request-helper-client-ip">b.requestHelpers.clientIp(req, options) <a class="anchor" href="#request-helper-client-ip">#</a></h2>',
  '<p>Resolves client IP through the configured trust-proxy boundary instead of reading forwarded headers directly.</p>',
  '<pre><code class="language-javascript">typeof b.requestHelpers.clientIp; // "function"</code></pre>',

  '<h2 id="request-helper-protocol">b.requestHelpers.requestProtocol(req, options) <a class="anchor" href="#request-helper-protocol">#</a></h2>',
  '<p>Resolves HTTP protocol under the same proxy trust model as client IP.</p>',
  '<pre><code class="language-javascript">typeof b.requestHelpers.requestProtocol; // "function"</code></pre>',

  '<h2 id="request-helper-vary">b.requestHelpers.appendVary(res, value) <a class="anchor" href="#request-helper-vary">#</a></h2>',
  '<p>Appends a <code>Vary</code> response token without duplicating existing values.</p>',
  '<pre><code class="language-javascript">typeof b.requestHelpers.appendVary; // "function"</code></pre>',

  '<h2 id="request-helper-safe-headers">b.requestHelpers.safeHeadersDistinct(req) <a class="anchor" href="#request-helper-safe-headers">#</a></h2>',
  '<p>Returns a safe distinct-header view for Node versions and proxies with different raw header behavior.</p>',
  '<pre><code class="language-javascript">typeof b.requestHelpers.safeHeadersDistinct; // "function"</code></pre>',
].join("\n"),
};
