"use strict";

module.exports = {
  slug:  "routing",
  title: "Routing",
  body: [
  '<h1>Routing</h1>',
  '<p>The HTTP entry surface: a path-based router with parameters, schema-validated routes, OpenAPI publication, content rendering with sane Cache-Control defaults, request-context helpers, static file serving, and operator-friendly error pages.</p>',

  '<h2 id="router">Router <a class="anchor" href="#router">#</a></h2>',
  '<p><code>b.router</code> is a path-based router with parameters, wildcards, a route-pattern field that propagates to metrics and tracing so cardinality stays bounded, and an optional schema-spec for body / query / params validation + OpenAPI publication.</p>',
  '<pre><code class="language-javascript">var router = b.router.create();',
  '',
  'router.get("/users/:id", async function (req, res) {',
  '  // req.params.id, req.routePattern === "/users/:id"',
  '  res.json(await users.findOne({ _id: req.params.id }));',
  '});',
  '',
  'router.post("/users",',
  '  b.middleware.bodyParser.json({ limit: C.BYTES.kib(64) }),',
  '  async function (req, res) {',
  '    // req.body parsed; rejected with 413 if larger than the limit.',
  '  });</code></pre>',
  '<p>Middleware that takes <code>(req, res, next)</code> can stop the chain by not calling <code>next()</code>; terminal handlers take <code>(req, res)</code> and the framework treats them as the end of the chain regardless. The router dispatches on <code>handler.length</code>, so the convention is structural, not by inspection of return values.</p>',

  '<h3 id="router-schema">Schema-validated routes <a class="anchor" href="#router-schema">#</a></h3>',
  '<p>Pass a spec object as the second arg (before any handler) to validate body / query / params via <code>b.safeSchema</code>. Mismatches return 400 with per-field paths before the handler runs.</p>',
  '<pre><code class="language-javascript">router.post("/users",',
  '  {',
  '    body:    s.object({ name: s.string(), age: s.number().int().min(0) }),',
  '    query:   s.object({ ref: s.string().optional() }),',
  '    description: "Create a new user",',
  '    summary:     "Create user",',
  '    tags:        ["users"],',
  '  },',
  '  authMiddleware,                         // any number of middlewares',
  '  async function (req, res) {',
  '    res.json(await users.create(req.body));',
  '  });</code></pre>',
  '<p><code>response: schema</code> validates outgoing JSON in dev and as an opt-in prod gate via the <code>BLAMEJS_VALIDATE_RESPONSES</code> env var: <code>throw</code> raises on drift (dev), <code>warn</code> logs and ships (prod-safe). Per-route override via <code>validateResponse: "throw" | "warn"</code>.</p>',

  '<h3 id="router-openapi">OpenAPI publication <a class="anchor" href="#router-openapi">#</a></h3>',
  '<p><code>router.openapi(opts)</code> walks the route table and returns a Swagger 3.0 doc — paths, methods, summaries, descriptions, tags, path-params auto-derived from the pattern.</p>',
  '<pre><code class="language-javascript">router.get("/openapi.json", function (_req, res) {',
  '  res.json(router.openapi({',
  '    info: { title: "My API", version: "1.0.0" },',
  '  }));',
  '});</code></pre>',

  '<h2 id="render">Render + Cache-Control <a class="anchor" href="#render">#</a></h2>',
  '<p><code>b.render</code> writes responses with a sensible default <code>Cache-Control: private, no-cache, must-revalidate</code> on every dynamic surface (<code>json</code>, <code>text</code>, <code>htmlString</code>, <code>redirect</code>). Browsers may still cache the response, but they\'re forced to revalidate on every navigation. Operators who want a CDN-cacheable response override per-call:</p>',
  '<pre><code class="language-javascript">b.render.htmlString(res, html, {',
  '  headers: { "Cache-Control": "public, max-age=300, stale-while-revalidate=60" },',
  '});</code></pre>',
  '<p><code>b.render.create({ engine: template })</code> binds a template engine for view rendering; the bound <code>html(res, viewName, data)</code> auto-merges <code>res.locals</code> (cspNonce, requestId, current user) into the template scope.</p>',
  '<p><code>b.htmlBalance.check(html)</code> is a structural sanity check for operator-submitted HTML — unclosed tags, orphan closes, mismatched closers, unterminated comments, void-element close tags. Returns <code>null</code> when balanced; an object <code>{ code, message, line, column }</code> when not.</p>',
  '<p><code>template.create({ viewsDir }).precompileAll()</code> compiles every <code>.html</code> file under <code>viewsDir</code> at boot. Syntax errors fail the deploy with <code>view \'admin/edit\' — trailing tokens in expression: IDENT</code> instead of surfacing as a 500 the first time an operator hits the route.</p>',

  '<h2 id="static">Static file serving <a class="anchor" href="#static">#</a></h2>',
  '<p><code>b.staticServe(rootDir, opts)</code> returns a middleware that serves files from <code>rootDir</code>. The path-resolution layer enforces a containment check so a request for <code>/../../etc/passwd</code> resolves outside <code>rootDir</code> and returns 403. Default <code>Cache-Control: public, max-age=3600</code>; override per-mount with <code>{ maxAgeMs }</code>.</p>',
  '<pre><code class="language-javascript">router.use("/assets", b.staticServe("./public/dist", {',
  '  maxAgeMs:    C.TIME.days(30),         // immutable hashed filenames',
  '  immutable:   true,                    // adds "immutable" directive',
  '  index:       false,                   // no auto-index.html',
  '}));</code></pre>',
  '<p><code>immutable: true</code> only sets the directive when the URL contains a content-addressable hash (Vite / esbuild / framework-bundler output) — operators serving raw <code>style.css</code> get <code>max-age=3600</code> with no immutable; the hashed <code>style.83631e970cc34c0d.css</code> next to it gets the longer cache + immutable hint.</p>',

  '<h2 id="error-page">Error pages <a class="anchor" href="#error-page">#</a></h2>',
  '<p><code>b.errorPage</code> is the operator-friendly error renderer. Different responses for HTML clients (templated error page with the request-id) vs JSON clients (RFC 7807 Problem+JSON), audit emission with the actor 5 W\'s, and the route\'s <code>auditAction</code> name is validated at create-time so a typo fails at boot.</p>',
  '<pre><code class="language-javascript">var errorHandler = b.errorPage.create({',
  '  audit:       b.audit,',
  '  // mode: "dev"  → full stack in the response',
  '  // mode: "prod" → request id only (errors logged at full detail)',
  '  // omit       → reads NODE_ENV via b.parsers.env.readVar',
  '  trustProxy:  true,                    // honor X-Forwarded-For for actor.ip',
  '});',
  '',
  'app.use(errorHandler);   // mounted last in the stack</code></pre>',

  '<h2 id="request-helpers">Request helpers <a class="anchor" href="#request-helpers">#</a></h2>',
  '<p>Small but recurring shapes live under <code>b.requestHelpers</code>. The most-used is <code>extractActorContext(req, override)</code>, which produces the 5 W\'s actor object every audit emission expects. Companion helpers cover the rest of the request-shape surface:</p>',
  '<ul>',
  '  <li><code>resolveRoute(req)</code> — returns <code>req.routePattern</code> when set, otherwise the URL with query string stripped.</li>',
  '  <li><code>captureResponseStatus(res, onEnd)</code> — wraps <code>res.writeHead</code> / <code>res.end</code>; calls <code>onEnd(status)</code> exactly once.</li>',
  '  <li><code>clientIp(req, { trustProxy })</code> — gates X-Forwarded-For consumption behind an explicit operator opt; default is socket-only.</li>',
  '  <li><code>requestProtocol(req, { trustProxy })</code> — gates X-Forwarded-Proto consumption.</li>',
  '  <li><code>parseQualityList(headerValue, opts)</code> — RFC 9110 §12.5 Accept-* parser, sorted by q desc.</li>',
  '  <li><code>parseListHeader(value, opts)</code> — comma-separated header → trimmed non-empty token array, optional lowercase.</li>',
  '  <li><code>appendVary(res, token)</code> — idempotent <code>Vary</code> header builder.</li>',
  '</ul>',
  '<pre><code class="language-javascript">var actor = b.requestHelpers.extractActorContext(req, {',
  '  // operator override — useful behind a CDN that strips X-Forwarded-For',
  '  ip: req.headers["cf-connecting-ip"],',
  '});',
  '',
  'b.audit.safeEmit({',
  '  action:   "page.published",',
  '  actor:    actor,',
  '  resource: { kind: "page", id: req.params.slug },',
  '  outcome:  "success",',
  '});</code></pre>',
].join("\n"),
};
