"use strict";

module.exports = {
  slug:  "safe-parsers",
  title: "Safe Parsers",
  body: [
  '<h1>Safe Parsers</h1>',
  '<p>Defensive parsing primitives — every operator-bordering input goes through one of these before any framework code touches the value. JSON, buffers, SQL identifiers, schemas, URLs, XML / TOML / YAML / .env files, environment variables.</p>',

  '<h2 id="safe-json">safeJson</h2>',

  '<h3>b.safeJson.parse(text, opts?) <a class="anchor" href="#safe-json-parse">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  maxBytes:    number,                       // default: C.BYTES.mib(1) — input size cap',
  '  maxDepth:    number,                       // default: 100 — nested-object depth cap',
  '  maxKeys:     number,                       // default: 10_000 — per-object key-count cap (CVE-2026-21717 V8 HashDoS guard)',
  '  errorClass:  errorClass,                   // default: SafeJsonError',
  '}</code></pre>',
  '<p>Parses JSON with explicit caps the standard <code>JSON.parse</code> doesn\'t enforce — <code>maxBytes</code> for parse-bombs, <code>maxDepth</code> for stack-blowing pathologic shapes, <code>maxKeys</code> for V8 HashDoS via integer-shaped keys (CVE-2026-21717), prototype-pollution rejection on <code>__proto__</code> / <code>constructor</code> / <code>prototype</code> keys. Throws <code>SafeJsonError</code> on any cap breach or parse error.</p>',
  '<pre><code class="language-javascript">var data = b.safeJson.parse(\'{"k":"v"}\', {',
  '  maxBytes: b.constants.BYTES.mib(2),',
  '  maxDepth: 16,',
  '  maxKeys:  1000,',
  '});',
  '// → { k: "v" }',
  '',
  'try { b.safeJson.parse(\'{"__proto__":{"polluted":true}}\'); }',
  'catch (e) { /* SafeJsonError code: json/syntax / json/too-many-keys / etc. */ }</code></pre>',

  '<h2 id="safe-json-stringify">b.safeJson.stringify(value, options) <a class="anchor" href="#safe-json-stringify">#</a></h2>',
  '<p>Serializes JSON with framework caps and deterministic behavior for operator-facing artifacts.</p>',
  '<pre><code class="language-javascript">typeof b.safeJson.stringify; // "function"</code></pre>',

  '<h2 id="safe-json-parse-default">b.safeJson.parseOrDefault(text, fallback, options) <a class="anchor" href="#safe-json-parse-default">#</a></h2>',
  '<p>Parses JSON and returns a fallback value instead of throwing, useful for optional config files and best-effort metadata.</p>',
  '<pre><code class="language-javascript">typeof b.safeJson.parseOrDefault; // "function"</code></pre>',

  '<h2 id="safe-json-validate">b.safeJson.validate(value, schema) <a class="anchor" href="#safe-json-validate">#</a></h2>',
  '<p>Validates parsed JSON against a framework schema before handlers consume it.</p>',
  '<pre><code class="language-javascript">typeof b.safeJson.validate; // "function"</code></pre>',

  '<h2 id="safe-json-canonical">b.safeJson.canonical(value) <a class="anchor" href="#safe-json-canonical">#</a></h2>',
  '<p>Returns a canonical JSON representation for signing, hashing, and snapshot comparisons.</p>',
  '<pre><code class="language-javascript">typeof b.safeJson.canonical; // "function"</code></pre>',

  '<h2 id="safe-json-format">b.safeJson.registerFormat(name, validator) <a class="anchor" href="#safe-json-format">#</a></h2>',
  '<p>Registers a named schema format validator for safe JSON validation flows.</p>',
  '<pre><code class="language-javascript">typeof b.safeJson.registerFormat; // "function"</code></pre>',

  '<h2 id="safe-json-formats">b.safeJson.formats() <a class="anchor" href="#safe-json-formats">#</a></h2>',
  '<p>Returns the registered safe JSON format validators for diagnostics and schema tooling.</p>',
  '<pre><code class="language-javascript">typeof b.safeJson.formats; // "function"</code></pre>',

  '<h2 id="safe-buffer">safeBuffer</h2>',

  '<h3>b.safeBuffer.normalizeText(input, opts?) <a class="anchor" href="#safe-buffer-normalize">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  maxBytes:    number,                       // default: C.BYTES.mib(8) — UTF-8 byte cap',
  '  errorClass:  errorClass,                   // default: SafeBufferError',
  '  typeCode:    string,                       // error code on bad input type',
  '  sizeCode:    string,                       // error code on cap breach',
  '}</code></pre>',
  '<p>Accept <code>string</code> | <code>Buffer</code> | <code>Uint8Array</code>, return a string. Throws on any other type and on cap breach. Centralizes the input-normalize pattern operators previously hand-rolled across parsers, atomic-file, object-store, and log-stream call sites.</p>',
  '<pre><code class="language-javascript">var text = b.safeBuffer.normalizeText(Buffer.from("hello"), {',
  '  maxBytes: b.constants.BYTES.kib(64),',
  '});',
  '// → "hello"</code></pre>',

  '<h3>b.safeBuffer.boundedChunkCollector(opts) <a class="anchor" href="#safe-buffer-collector">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  maxBytes:    number,                       // required — cumulative bytes cap',
  '  errorClass:  errorClass,                   // default: SafeBufferError',
  '  sizeCode:    string,                       // default: "BUFFER_TOO_LARGE"',
  '}</code></pre>',
  '<p>OOM defense for unbounded HTTP bodies. Returns <code>{ push(chunk), result(), bytesCollected() }</code>. <code>push</code> throws when the cumulative size would exceed <code>maxBytes</code> — operators wire it as the <code>data</code> handler on a <code>Readable</code> and resolve <code>result()</code> on <code>end</code>.</p>',
  '<pre><code class="language-javascript">var collector = b.safeBuffer.boundedChunkCollector({',
  '  maxBytes: b.constants.BYTES.mib(16),',
  '});',
  'collector.push(Buffer.from("hello "));',
  'collector.push(Buffer.from("world"));',
  'collector.bytesCollected();   // 11',
  'collector.result();   // Buffer "hello world"</code></pre>',

  '<h3>b.safeBuffer.secureZero(buf) <a class="anchor" href="#safe-buffer-zero">#</a></h3>',
  '<p>Best-effort zero on a sensitive Buffer. Use after consuming a private key, passphrase-derived bytes, or any other in-memory secret to reduce the window an attacker has to recover it from a memory dump or core file.</p>',
  '<pre><code class="language-javascript">var pk = Buffer.from("secret-bytes-go-here-padded-pad-32");',
  'b.safeBuffer.secureZero(pk);',
  '// pk[0] === 0 — best effort; JS doesn\'t guarantee no copies were made.</code></pre>',

  '<h2 id="safe-sql">safeSql</h2>',

  '<h3>b.safeSql.validateIdentifier(value, opts?) <a class="anchor" href="#safe-sql-identifier">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  allowReserved: boolean,                    // default: false — reject SQL keywords',
  '  errorClass:    errorClass,                 // default: SafeSqlError',
  '}</code></pre>',
  '<p>Validates a SQL identifier (table name, column name, ORDER BY column) against the strict regex <code>^[A-Za-z_][A-Za-z0-9_]*$</code> before it\'s interpolated into a query. Use any time the operator routes user-supplied or computed identifiers into SQL — typed parameters cover values, this primitive covers names. Throws <code>SafeSqlError</code> on a malformed identifier.</p>',
  '<pre><code class="language-javascript">b.safeSql.validateIdentifier("createdAt");   // → "createdAt"',
  '',
  'try { b.safeSql.validateIdentifier("DROP TABLE users; --"); }',
  'catch (e) { /* SafeSqlError */ }</code></pre>',

  '<h2 id="safe-schema">safeSchema</h2>',

  '<h3>b.safeSchema.object(shape) / .string() / .number() / .boolean() / .array(of) / .literal(v) / .union(of) <a class="anchor" href="#safe-schema-types">#</a></h3>',
  '<p>Schema validator the router uses for body / query / params validation. Surface mirrors zod. Each leaf supports refinements (<code>.min</code> / <code>.max</code> / <code>.length</code> / <code>.regex</code> / <code>.email</code> / <code>.uuid</code> / <code>.ipv4</code> / <code>.ipv6</code> / <code>.url</code> / <code>.int</code>) and modifiers (<code>.optional()</code>, <code>.nullable()</code>, <code>.default(v)</code>). Calling <code>schema.safeParse(input)</code> returns <code>{ ok: true, value }</code> on success or <code>{ ok: false, error: { issues } }</code> on failure with per-field paths.</p>',
  '<pre><code class="language-javascript">var s = b.safeSchema;',
  'var userSpec = s.object({',
  '  email:    s.string().email(),',
  '  age:      s.number().int().min(0).max(150),',
  '  roles:    s.array(s.string()).max(20),',
  '  optional: s.string().optional(),',
  '});',
  '',
  'var result = userSpec.safeParse({ email: "alice@example.com", age: 30, roles: ["admin"] });',
  '// → { ok: true, value: { email: "alice@example.com", age: 30, roles: ["admin"] } }</code></pre>',
  '<p>The framework also exposes <code>b.safeSchema.EMAIL_RE</code>, <code>UUID_RE</code>, <code>IPV4_RE</code>, <code>IPV6_RE</code>, etc. for use outside schema bodies.</p>',

  '<h2 id="safe-schema-string">b.safeSchema.string() <a class="anchor" href="#safe-schema-string">#</a></h2>',
  '<p>String schema with length, format, regex, and substring refinements. Operators use it for request fields, env values, and config strings before reading the value.</p>',
  '<pre><code class="language-javascript">var schema = b.safeSchema.string().email().max(254);',
  'schema.safeParse("alice@example.com").ok; // true</code></pre>',

  '<h2 id="safe-schema-number">b.safeSchema.number() <a class="anchor" href="#safe-schema-number">#</a></h2>',
  '<p>Number schema with integer, finite, min/max, sign, and multiple-of checks. It rejects non-numeric strings unless the operator explicitly preprocesses or uses config coercion.</p>',
  '<pre><code class="language-javascript">var schema = b.safeSchema.number().int().min(1);',
  'schema.safeParse(42).ok; // true</code></pre>',

  '<h2 id="safe-schema-boolean">b.safeSchema.boolean() <a class="anchor" href="#safe-schema-boolean">#</a></h2>',
  '<p>Strict boolean schema. Use <code>b.config.coerce.boolean()</code> at env boundaries when strings like <code>"true"</code> need explicit conversion.</p>',
  '<pre><code class="language-javascript">var schema = b.safeSchema.boolean();',
  'schema.safeParse(false).ok; // true</code></pre>',

  '<h2 id="safe-schema-literal">b.safeSchema.literal(value) <a class="anchor" href="#safe-schema-literal">#</a></h2>',
  '<p>Exact-value schema for protocol discriminators, fixed version strings, and narrow command names.</p>',
  '<pre><code class="language-javascript">var schema = b.safeSchema.literal("v1");',
  'schema.safeParse("v1").ok; // true</code></pre>',

  '<h2 id="safe-schema-null">b.safeSchema.null_() / undefined_() <a class="anchor" href="#safe-schema-null">#</a></h2>',
  '<p>Explicit null and undefined schemas for JSON-boundary contracts where absence and null carry different meanings.</p>',
  '<pre><code class="language-javascript">b.safeSchema.null_().safeParse(null).ok; // true',
  'b.safeSchema.undefined_().safeParse(undefined).ok; // true</code></pre>',

  '<h2 id="safe-schema-any">b.safeSchema.any() / unknown() <a class="anchor" href="#safe-schema-any">#</a></h2>',
  '<p>Escape-hatch schemas for payload areas intentionally owned by another validator. Prefer narrower schemas for operator-controlled inputs.</p>',
  '<pre><code class="language-javascript">var passthrough = b.safeSchema.unknown();',
  'passthrough.safeParse({ vendor: "payload" }).ok; // true</code></pre>',

  '<h2 id="safe-schema-object">b.safeSchema.object(shape) <a class="anchor" href="#safe-schema-object">#</a></h2>',
  '<p>Strict object schema by default. Unknown keys and prototype-pollution keys are rejected unless the operator intentionally opts into passthrough.</p>',
  '<pre><code class="language-javascript">var schema = b.safeSchema.object({ id: b.safeSchema.string().uuid() });',
  'schema.safeParse({ id: "550e8400-e29b-41d4-a716-446655440000" }).ok; // true</code></pre>',

  '<h2 id="safe-schema-array">b.safeSchema.array(item) <a class="anchor" href="#safe-schema-array">#</a></h2>',
  '<p>Array schema with item validation and min/max/length/nonempty refinements for bounded list inputs.</p>',
  '<pre><code class="language-javascript">var schema = b.safeSchema.array(b.safeSchema.string()).max(3);',
  'schema.safeParse(["read", "write"]).ok; // true</code></pre>',

  '<h2 id="safe-schema-tuple">b.safeSchema.tuple(items) <a class="anchor" href="#safe-schema-tuple">#</a></h2>',
  '<p>Positional tuple schema for fixed protocol arrays where each position has a different type.</p>',
  '<pre><code class="language-javascript">var schema = b.safeSchema.tuple([b.safeSchema.string(), b.safeSchema.number()]);',
  'schema.safeParse(["page", 2]).ok; // true</code></pre>',

  '<h2 id="safe-schema-union">b.safeSchema.union(options) <a class="anchor" href="#safe-schema-union">#</a></h2>',
  '<p>First-match union for inputs that legitimately accept one of several shapes.</p>',
  '<pre><code class="language-javascript">var schema = b.safeSchema.union([b.safeSchema.string(), b.safeSchema.number()]);',
  'schema.safeParse("42").ok; // true</code></pre>',

  '<h2 id="safe-schema-discriminated-union">b.safeSchema.discriminatedUnion(key, options) <a class="anchor" href="#safe-schema-discriminated-union">#</a></h2>',
  '<p>Tagged-union validator for command envelopes. The discriminator chooses the object schema before field validation, which produces clearer errors for API clients.</p>',
  '<pre><code class="language-javascript">var schema = b.safeSchema.discriminatedUnion("type", [',
  '  b.safeSchema.object({ type: b.safeSchema.literal("email"), to: b.safeSchema.string().email() }),',
  '  b.safeSchema.object({ type: b.safeSchema.literal("sms"), to: b.safeSchema.string() }),',
  ']);',
  'schema.safeParse({ type: "email", to: "alice@example.com" }).ok; // true</code></pre>',

  '<h2 id="safe-schema-record">b.safeSchema.record(value) <a class="anchor" href="#safe-schema-record">#</a></h2>',
  '<p>String-keyed object map with validated values. Prototype-pollution keys remain rejected even when the value schema is permissive.</p>',
  '<pre><code class="language-javascript">var schema = b.safeSchema.record(b.safeSchema.number());',
  'schema.safeParse({ retries: 3 }).ok; // true</code></pre>',

  '<h2 id="safe-schema-lazy">b.safeSchema.lazy(factory) <a class="anchor" href="#safe-schema-lazy">#</a></h2>',
  '<p>Deferred schema construction for recursive or mutually-recursive object shapes.</p>',
  '<pre><code class="language-javascript">var node;',
  'node = b.safeSchema.lazy(function () {',
  '  return b.safeSchema.object({ name: b.safeSchema.string(), children: b.safeSchema.array(node).default([]) });',
  '});',
  'node.safeParse({ name: "root" }).ok; // true</code></pre>',

  '<h2 id="safe-schema-preprocess">b.safeSchema.preprocess(fn, schema) <a class="anchor" href="#safe-schema-preprocess">#</a></h2>',
  '<p>Runs a small normalization function before validation. Keep preprocessors deterministic and local; expensive async checks belong outside the schema.</p>',
  '<pre><code class="language-javascript">var schema = b.safeSchema.preprocess(function (v) { return String(v).trim(); }, b.safeSchema.string().nonempty());',
  'schema.safeParse(" ok ").value; // "ok"</code></pre>',

  '<h2 id="safe-schema-enum">b.safeSchema.enum_(values) / oneOf(values) <a class="anchor" href="#safe-schema-enum">#</a></h2>',
  '<p>Allow-list schema for finite string or number sets. <code>oneOf</code> is the alias for codebases that prefer the non-reserved name.</p>',
  '<pre><code class="language-javascript">var schema = b.safeSchema.enum_(["draft", "published"]);',
  'schema.safeParse("draft").ok; // true',
  'b.safeSchema.oneOf(["read", "write"]).safeParse("read").ok; // true</code></pre>',

  '<h2 id="safe-schema-modifiers">b.safeSchema.optional(schema) / nullable(schema) <a class="anchor" href="#safe-schema-modifiers">#</a></h2>',
  '<p>Composition helpers matching the chained <code>.optional()</code> and <code>.nullable()</code> methods on every schema.</p>',
  '<pre><code class="language-javascript">var maybeName = b.safeSchema.optional(b.safeSchema.string());',
  'maybeName.safeParse(undefined).ok; // true',
  'var nullableName = b.safeSchema.nullable(b.safeSchema.string());',
  'nullableName.safeParse(null).ok; // true</code></pre>',

  '<h2 id="parsers">Format parsers <a class="anchor" href="#parsers">#</a></h2>',
  '<p><code>b.parsers</code> covers the data interchange formats other than JSON. Each parser ships the same security defaults: size + depth limits, prototype-pollution rejection, no implicit type coercion that depends on the locale.</p>',
  '<ul>',
  '  <li><code>b.parsers.xml.parse(input, opts)</code> — RFC-compliant subset; XXE / DOCTYPE / billion-laughs blocked by default; depth + element + attribute count limits; numeric character refs bounds-checked.</li>',
  '  <li><code>b.parsers.toml.parse(input, opts)</code> — TOML 1.0 with depth + size limits; prototype-pollution rejection on dotted-key path segments; strict same-key redefinition; offset date-times decoded as JS Date, local date-time / date / time preserved as ISO strings.</li>',
  '  <li><code>b.parsers.yaml.parse(input, opts)</code> — YAML 1.2 safe subset (JSON-shaped). Rejects anchors (billion-laughs), aliases (cycles), tags (deserialization gadgets), directives, multi-document streams, complex keys, merge keys (<code>&lt;&lt;</code>), tabs in indentation. Avoids the YAML 1.1 "Norway problem" (<code>country: NO</code> parsing as <code>false</code>).</li>',
  '  <li><code>b.parsers.env</code> — .env file loader; size cap + schema validation; refuses <code>$VAR</code> expansion (consumers reading <code>process.env</code> later don\'t know whether the value was literal or expanded — consistency over convenience); refuses keys outside <code>^[A-Z_][A-Z0-9_]*$</code>; diff against the previous snapshot writes a <code>system.config.changed</code> audit row.</li>',
  '</ul>',
  '<p>CSV parsing is its own primitive at <code>b.csv</code> — see <a href="/format-helpers#csv">Format Helpers → CSV</a>.</p>',

  '<h3 id="safe-env-readvar">readVar <a class="anchor" href="#safe-env-readvar">#</a></h3>',
  '<p><code>b.parsers.env.readVar(name, schema)</code> is the framework\'s central <code>process.env</code> reader: size cap, type coercion (<code>string</code> / <code>number</code> / <code>boolean</code> / <code>json</code> / <code>buffer</code>), optional default, optional <code>required: true</code>, optional <code>strip: true</code> for secrets that should be deleted from <code>process.env</code> after read.</p>',
  '<pre><code class="language-javascript">var port = b.parsers.env.readVar("PORT", {',
  '  type: "number", default: 3000,',
  '});',
  '',
  'var passphrase = b.parsers.env.readVar("BLAMEJS_VAULT_PASSPHRASE", {',
  '  required: true, maxBytes: 4096, strip: true,',
  '});</code></pre>',

  '<h2 id="config">Config <a class="anchor" href="#config">#</a></h2>',
  '<p><code>b.config</code> is the schema-validated environment-config primitive. Operators declare what their app expects from the environment; config refuses to boot the app on anything missing or invalid.</p>',
  '<pre><code class="language-javascript">var config = b.config.create({',
  '  env: process.env,',
  '  schema: {',
  '    PORT:                       b.config.coerce.number({ default: 3000 }),',
  '    NODE_ENV:                   { type: "string", enum: ["development", "production", "test"] },',
  '    BLAMEJS_VAULT_PASSPHRASE:   { type: "string", required: true, maxBytes: 4096 },',
  '    FEATURE_NEW_UPLOADS:        b.config.coerce.boolean({ default: false }),',
  '    DATABASE_URL:               { type: "string", required: true, regex: /^postgres:\\/\\// },',
  '  },',
  '  redactKeys: ["BLAMEJS_VAULT_PASSPHRASE"],   // for safe diagnostic dumps',
  '});',
  '',
  'config.value.PORT;        // 3000 (number)',
  'config.has("DATABASE_URL");',
  'console.log(config.redacted);   // every redactKey replaced with [REDACTED]</code></pre>',
  '<p>Throws <code>ConfigError</code> at <code>create()</code> time on missing required / type mismatch / regex fail / enum violation. <code>coerce.boolean</code> accepts <code>"1"</code> / <code>"true"</code> / <code>"yes"</code> as true; <code>coerce.number</code> rejects non-finite values. Operators wrap a <code>try / catch</code> at boot and exit with a clear message — the app refuses to start on broken config.</p>',

  '<h2 id="config-load-db-backed">b.config.loadDbBacked(opts) <a class="anchor" href="#config-load-db-backed">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  schema:      SafeSchema, // required; same shape as b.config.create',
  '  env:         object,     // optional baseline env',
  '  redactKeys:  array,',
  '  fetchRows:   function,   // required async () => [{ key, value }]',
  '  intervalMs:  number,     // required positive polling interval',
  '  audit:       boolean,',
  '}</code></pre>',
  '<p>Composes <code>b.config.create</code> with a periodic database override poller. Reload failures emit audit evidence and keep the last-good value instead of clobbering live config.</p>',
  '<pre><code class="language-javascript">var cfg = b.config.loadDbBacked({',
  '  schema: b.safeSchema.object({',
  '    FEATURE_X: b.config.coerce.boolean().default(false),',
  '  }),',
  '  env: { FEATURE_X: "false" },',
  '  fetchRows: async function () { return [{ key: "FEATURE_X", value: "true" }]; },',
  '  intervalMs: b.constants.TIME.minutes(1),',
  '  audit: false,',
  '});',
  'cfg.stop();',
  'cfg.value.FEATURE_X; // false until the first poll applies the override</code></pre>',

  '<h2 id="file-type">File-type magic-byte detection <a class="anchor" href="#file-type">#</a></h2>',
  '<p><code>b.fileType</code> classifies an upload by its leading bytes — independent of the client-supplied <code>Content-Type</code>. A polyglot HTML payload labeled <code>image/png</code> by an attacker still gets classified as PNG by <code>detect()</code> because the PNG magic bytes match. Operators rejecting executables on upload pin allowlists by MIME / category and let the magic-byte check enforce.</p>',
  '<h3>b.fileType.detect(buffer, opts?) <a class="anchor" href="#file-type-detect">#</a></h3>',
  '<p>Returns <code>{ mime, extension, category, name }</code> when a signature matches, <code>null</code> when nothing matches or the buffer is empty. Categories: <code>image</code>, <code>document</code>, <code>archive</code>, <code>audio</code>, <code>video</code>, <code>executable</code>.</p>',
  '<pre><code class="language-javascript">var det = b.fileType.detect(uploadedBuffer);',
  '// → { mime: "image/png", extension: "png", category: "image", name: "png" }',
  '</code></pre>',
  '<h3>b.fileType.assertOneOf(buffer, allowlist, opts?) <a class="anchor" href="#file-type-assert">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  allowEmpty: boolean,                          // default: false — reject zero-byte buffers',
  '  extra:      Array<SignatureEntry>,            // default: [] — operator-extended registry',
  '}</code></pre>',
  '<p>Throws <code>FileTypeError</code> when no signature matches (<code>UNKNOWN_TYPE</code>) or the detected type is not in the allowlist (<code>DISALLOWED_TYPE</code>). Allowlist entries match against <code>mime</code> OR <code>name</code> OR <code>category</code>, so operators pin <code>"image/png"</code> for one format or <code>"image"</code> for the whole bucket.</p>',
  '<pre><code class="language-javascript">try {',
  '  var det = b.fileType.assertOneOf(uploadedBuffer, ["image", "application/pdf"]);',
  '  // safe to store det.extension as the canonical filename suffix',
  '} catch (e) {',
  '  return res.status(415).json({ error: e.code });',
  '}</code></pre>',

  '<h2 id="safe-redirect">b.safeRedirect.resolve(rawTarget, opts) <a class="anchor" href="#safe-redirect">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  base:           string,                       // optional reference origin',
  '  allowedOrigins: [string],                     // ["https://app.example.com"]',
  '  allowedHosts:   [string],                     // alt to allowedOrigins (host-only match)',
  '  fallback:       string,                       // default: "/" — returned on any refusal',
  '}</code></pre>',
  '<p>Open-redirect (CWE-601) defense for operator-supplied <code>?next=</code> / <code>?return_to=</code> parameters. Refuses protocol-relative URLs (<code>//attacker.com</code>), backslash variants (<code>\\\\attacker.com</code>), CRLF / control chars (header-injection vector), and <code>data:</code> / <code>javascript:</code> / <code>vbscript:</code> schemes. Same-origin paths (<code>/dashboard</code>) and fragments (<code>#x</code>) pass through; full URLs require the operator to provide <code>allowedOrigins</code> or <code>allowedHosts</code> — without an allowlist, every full URL falls back. Drop the result straight into <code>res.writeHead(302, { Location: ... })</code>.</p>',
  '<pre><code class="language-javascript">// Same-origin path — passes through.',
  'var ok = b.safeRedirect.resolve("/dashboard", { fallback: "/" });',
  '// ok → "/dashboard"',
  '',
  '// Protocol-relative attacker URL — refused, returns fallback.',
  'var bad = b.safeRedirect.resolve("//attacker.com/x", { fallback: "/" });',
  '// bad → "/"',
  '',
  '// Full URL within allowlist — passes through.',
  'var allowed = b.safeRedirect.resolve("https://app.example.com/x", {',
  '  allowedOrigins: ["https://app.example.com"], fallback: "/",',
  '});',
  '// allowed → "https://app.example.com/x"',
  '</code></pre>',

  '<h2 id="pick">b.pick(input, allowList, opts?) <a class="anchor" href="#pick">#</a></h2>',
  '<pre><code class="language-javascript">{',
  '  onUnknown:  "drop" | "throw",                  // default: "drop"',
  '}</code></pre>',
  '<p>Mass-assignment (CWE-915 / OWASP API3:2023) defense. Returns a NEW object with only allowlisted keys; prototype-pollution keys (<code>__proto__</code> / <code>constructor</code> / <code>prototype</code>) are ALWAYS stripped even if listed. Nested allowlist syntax for object-shaped fields. Operators wire this between request body and DB write so unknown fields silently drop (or explicitly throw with <code>onUnknown: "throw"</code>).</p>',
  '<pre><code class="language-javascript">var hostile = {',
  '  displayName: "alice",',
  '  bio:         "hello",',
  '  __proto__:   { isAdmin: true },     // prototype-pollution attempt',
  '  passwordHash: "stolen",              // not in allowlist — drops',
  '};',
  'var safe = b.pick(hostile, ["displayName", "bio"]);',
  '// safe → { displayName: "alice", bio: "hello" }',
  '// passwordHash dropped; __proto__ stripped even if it were in the allowlist.',
  '</code></pre>',

].join("\n"),
};
