"use strict";

module.exports = {
  slug:  "safe-parsers",
  title: "Safe Parsers",
  body: [
  '<h1>Safe Parsers</h1>',
  '<p>Defensive parsing primitives — every operator-bordering input goes through one of these before any framework code touches the value. JSON, buffers, SQL identifiers, schemas, URLs, XML / TOML / YAML / .env files, environment variables.</p>',

  '<h2 id="safe-json">safeJson <a class="anchor" href="#safe-json">#</a></h2>',
  '<p><code>b.safeJson.parse(text, opts)</code> parses JSON with explicit caps the standard <code>JSON.parse</code> doesn\'t enforce: <code>maxBytes</code> (default 8 MiB) for parse-bombs, <code>maxDepth</code> (default 64) for stack-blowing pathologic shapes, prototype-pollution rejection on <code>__proto__</code> / <code>constructor</code> / <code>prototype</code> keys.</p>',
  '<pre><code class="language-javascript">var data = b.safeJson.parse(req.body, {',
  '  maxBytes: C.BYTES.mib(2),',
  '  maxDepth: 16,',
  '});',
  '// Throws SafeJsonError on size / depth / prototype-pollution / parse error.',
  '',
  '// Schema-validating parse — combine with safeSchema',
  'var v = b.safeJson.parseAndValidate(text, schema, { maxBytes: ... });</code></pre>',

  '<h2 id="safe-buffer">safeBuffer <a class="anchor" href="#safe-buffer">#</a></h2>',
  '<p><code>b.safeBuffer</code> centralizes the input-normalize / capped-chunk-collection / secure-zero patterns scattered across parsers, atomic-file, object-store, and log-stream. Three helpers:</p>',
  '<pre><code class="language-javascript">// Accept string | Buffer | Uint8Array → return string',
  'var text = b.safeBuffer.normalizeText(input, {',
  '  maxBytes: C.BYTES.mib(8),',
  '  errorClass: MyError,',
  '  typeCode: "x/wrong-input-type",',
  '  sizeCode: "x/too-large",',
  '});',
  '',
  '// Bounded chunk collector — OOM defense for unbounded HTTP bodies',
  'var collector = b.safeBuffer.boundedChunkCollector({',
  '  maxBytes:   C.BYTES.mib(16),',
  '  errorClass: HttpError,',
  '});',
  'stream.on("data",  function (c) { collector.push(c); });  // throws on cap exceeded',
  'stream.on("end",   function ()  { resolve(collector.result()); });',
  '',
  '// Best-effort zero on a sensitive Buffer',
  'b.safeBuffer.secureZero(privateKeyBuf);</code></pre>',

  '<h2 id="safe-sql">safeSql <a class="anchor" href="#safe-sql">#</a></h2>',
  '<p><code>b.safeSql</code> validates SQL identifiers (table names, column names, ORDER BY columns) against a strict regex before they\'re interpolated into a query. Use it any time the operator routes user-supplied or computed identifiers into SQL — typed parameters cover values, this primitive covers names.</p>',
  '<pre><code class="language-javascript">b.safeSql.identifier(req.query.sortBy);',
  '// → throws SafeSqlError if !/^[A-Za-z_][A-Za-z0-9_]*$/.test(value)',
  '',
  '// Composed:',
  'var col = b.safeSql.identifier(req.query.sortBy || "createdAt");',
  'var dir = req.query.dir === "asc" ? "ASC" : "DESC";',
  'db.prepare(`SELECT * FROM rows ORDER BY "${col}" ${dir} LIMIT ?`).all(50);</code></pre>',

  '<h2 id="safe-schema">safeSchema <a class="anchor" href="#safe-schema">#</a></h2>',
  '<p><code>b.safeSchema</code> is the schema validator the router uses for body / query / params validation. Surface mirrors zod: <code>object</code>, <code>string</code>, <code>number</code>, <code>boolean</code>, <code>array</code>, <code>literal</code>, <code>union</code>, <code>optional</code>, <code>nullable</code>, with refinements (<code>min</code> / <code>max</code> / <code>length</code> / <code>regex</code> / <code>email</code> / <code>uuid</code> / <code>ipv4</code> / <code>ipv6</code> / <code>url</code>).</p>',
  '<pre><code class="language-javascript">var s = b.safeSchema;',
  'var userSpec = s.object({',
  '  email:    s.string().email(),',
  '  age:      s.number().int().min(0).max(150),',
  '  roles:    s.array(s.string()).max(20),',
  '  optional: s.string().optional(),',
  '});',
  '',
  'var result = userSpec.safeParse(input);',
  '// { ok: true,  value: {...} }      OR',
  '// { ok: false, error: { issues: [{ path, code, message }, ...] } }</code></pre>',
  '<p>The framework also exposes <code>b.safeSchema.EMAIL_RE</code>, <code>UUID_RE</code>, <code>IPV4_RE</code>, <code>IPV6_RE</code>, etc. for use outside schema bodies.</p>',

  '<h2 id="parsers">Format parsers <a class="anchor" href="#parsers">#</a></h2>',
  '<p><code>b.parsers</code> covers the data interchange formats other than JSON. Each parser ships the same security defaults: size + depth limits, prototype-pollution rejection, no implicit type coercion that depends on the locale.</p>',
  '<ul>',
  '  <li><code>b.parsers.xml.parse(input, opts)</code> — RFC-compliant subset; XXE / DOCTYPE / billion-laughs blocked by default; depth + element + attribute count limits; numeric character refs bounds-checked.</li>',
  '  <li><code>b.parsers.toml.parse(input, opts)</code> — TOML 1.0 with depth + size limits; prototype-pollution rejection on dotted-key path segments; strict same-key redefinition; offset date-times decoded as JS Date, local date-time / date / time preserved as ISO strings.</li>',
  '  <li><code>b.parsers.yaml.parse(input, opts)</code> — YAML 1.2 safe subset (JSON-shaped). Rejects anchors (billion-laughs), aliases (cycles), tags (deserialization gadgets), directives, multi-document streams, complex keys, merge keys (<code>&lt;&lt;</code>), tabs in indentation. Avoids the YAML 1.1 "Norway problem" (<code>country: NO</code> parsing as <code>false</code>).</li>',
  '  <li><code>b.parsers.env</code> — .env file loader; size cap + schema validation; refuses <code>$VAR</code> expansion (consumers reading <code>process.env</code> later don\'t know whether the value was literal or expanded — consistency over convenience); refuses keys outside <code>^[A-Z_][A-Z0-9_]*$</code>; diff against the previous snapshot writes a <code>system.config.changed</code> audit row.</li>',
  '</ul>',
  '<p>CSV parsing is its own primitive at <code>b.csv</code> — see <a href="/format-helpers#csv">Format Helpers → CSV</a>.</p>',

  '<h3 id="safe-env-readvar">readVar <a class="anchor" href="#safe-env-readvar">#</a></h3>',
  '<p><code>b.parsers.env.readVar(name, schema)</code> is the framework\'s central <code>process.env</code> reader: size cap, type coercion (<code>string</code> / <code>number</code> / <code>boolean</code> / <code>json</code> / <code>buffer</code>), optional default, optional <code>required: true</code>, optional <code>strip: true</code> for secrets that should be deleted from <code>process.env</code> after read.</p>',
  '<pre><code class="language-javascript">var port = b.parsers.env.readVar("PORT", {',
  '  type: "number", default: 3000,',
  '});',
  '',
  'var passphrase = b.parsers.env.readVar("BLAMEJS_VAULT_PASSPHRASE", {',
  '  required: true, maxBytes: 4096, strip: true,',
  '});</code></pre>',

  '<h2 id="config">Config <a class="anchor" href="#config">#</a></h2>',
  '<p><code>b.config</code> is the schema-validated environment-config primitive. Operators declare what their app expects from the environment; config refuses to boot the app on anything missing or invalid.</p>',
  '<pre><code class="language-javascript">var config = b.config.create({',
  '  env: process.env,',
  '  schema: {',
  '    PORT:                       b.config.coerce.number({ default: 3000 }),',
  '    NODE_ENV:                   { type: "string", enum: ["development", "production", "test"] },',
  '    BLAMEJS_VAULT_PASSPHRASE:   { type: "string", required: true, maxBytes: 4096 },',
  '    FEATURE_NEW_UPLOADS:        b.config.coerce.boolean({ default: false }),',
  '    DATABASE_URL:               { type: "string", required: true, regex: /^postgres:\\/\\// },',
  '  },',
  '  redactKeys: ["BLAMEJS_VAULT_PASSPHRASE"],   // for safe diagnostic dumps',
  '});',
  '',
  'config.value.PORT;        // 3000 (number)',
  'config.has("DATABASE_URL");',
  'console.log(config.redacted);   // every redactKey replaced with [REDACTED]</code></pre>',
  '<p>Throws <code>ConfigError</code> at <code>create()</code> time on missing required / type mismatch / regex fail / enum violation. <code>coerce.boolean</code> accepts <code>"1"</code> / <code>"true"</code> / <code>"yes"</code> as true; <code>coerce.number</code> rejects non-finite values. Operators wrap a <code>try / catch</code> at boot and exit with a clear message — the app refuses to start on broken config.</p>',

  '<h2 id="file-type">File-type magic-byte detection <a class="anchor" href="#file-type">#</a></h2>',
  '<p><code>b.fileType</code> classifies an upload by its leading bytes — independent of the client-supplied <code>Content-Type</code>. A polyglot HTML payload labeled <code>image/png</code> by an attacker still gets classified as PNG by <code>detect()</code> because the PNG magic bytes match. Operators rejecting executables on upload pin allowlists by MIME / category and let the magic-byte check enforce.</p>',
  '<h3>b.fileType.detect(buffer, opts?) <a class="anchor" href="#file-type-detect">#</a></h3>',
  '<p>Returns <code>{ mime, extension, category, name }</code> when a signature matches, <code>null</code> when nothing matches or the buffer is empty. Categories: <code>image</code>, <code>document</code>, <code>archive</code>, <code>audio</code>, <code>video</code>, <code>executable</code>.</p>',
  '<pre><code class="language-javascript">var det = b.fileType.detect(uploadedBuffer);',
  '// → { mime: "image/png", extension: "png", category: "image", name: "png" }',
  '</code></pre>',
  '<h3>b.fileType.assertOneOf(buffer, allowlist, opts?) <a class="anchor" href="#file-type-assert">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  allowEmpty: boolean,                          // default: false — reject zero-byte buffers',
  '  extra:      Array<SignatureEntry>,            // default: [] — operator-extended registry',
  '}</code></pre>',
  '<p>Throws <code>FileTypeError</code> when no signature matches (<code>UNKNOWN_TYPE</code>) or the detected type is not in the allowlist (<code>DISALLOWED_TYPE</code>). Allowlist entries match against <code>mime</code> OR <code>name</code> OR <code>category</code>, so operators pin <code>"image/png"</code> for one format or <code>"image"</code> for the whole bucket.</p>',
  '<pre><code class="language-javascript">try {',
  '  var det = b.fileType.assertOneOf(uploadedBuffer, ["image", "application/pdf"]);',
  '  // safe to store det.extension as the canonical filename suffix',
  '} catch (e) {',
  '  return res.status(415).json({ error: e.code });',
  '}</code></pre>',
].join("\n"),
};
