"use strict";

module.exports = {
  slug:  "testing",
  title: "Testing",
  body: [
  '<h1>Testing</h1>',
  '<p><code>b.testing</code> is the operator-facing set of helpers for testing apps built on blamejs. Each helper threads through an existing framework primitive — there\'s no separate timer mock, no separate audit-capture system, no parallel set of error classes. What the test sees is what the running app sees, with the network and the clock under your control.</p>',

  '<h2 id="mocks">Request and response mocks <a class="anchor" href="#mocks">#</a></h2>',
  '<pre><code class="language-javascript">var t = b.testing;',
  '',
  'var req = t.mockReq({',
  '  method:  "POST",',
  '  url:     "/admin/save",',
  '  user:    { id: "u-42", roles: ["editor"] },',
  '  body:    { slug: "intro", title: "Intro" },',
  '});',
  'var res = t.mockRes();',
  '',
  'await myHandler(req, res);',
  'assert(res.statusCode === 302);',
  'assert(res.headers["location"] === "/intro/index");</code></pre>',
  '<p><code>mockReq</code> produces an object compatible with <code>b.requestHelpers.extractActorContext</code>, so audit emissions in code under test carry the same actor shape they would in production. <code>mockRes</code> records every header, status, and body write so assertions can inspect what the handler tried to send without a real socket.</p>',

  '<h2 id="request">Chainable HTTP test client <a class="anchor" href="#request">#</a></h2>',
  '<p><code>t.request(target)</code> spins an ephemeral <code>http.Server</code> on a random port, fires a real HTTP request, and tears down the server when the assertion settles. Supertest-style chainable: <code>get/post/put/patch/delete/head/options</code> → <code>set</code> headers → <code>send</code> body → <code>expect</code> status.</p>',
  '<pre><code class="language-javascript">await t.request(myRouter)',
  '  .post("/users")',
  '  .set("Authorization", "Bearer " + token)',
  '  .send({ name: "alice", age: 30 })       // auto-JSONs the body + sets Content-Type',
  '  .expect(201);',
  '',
  '// .expect can also assert on a response object',
  'await t.request(myRouter)',
  '  .get("/health")',
  '  .expect(function (res) {',
  '    assert(res.body.status === "ok");',
  '  });</code></pre>',
  '<p>Accepts a <code>b.router</code> instance, a request listener function, or an existing <code>http.Server</code> / <code>https.Server</code>.</p>',

  '<h2 id="clock">Fake clock <a class="anchor" href="#clock">#</a></h2>',
  '<p><code>fakeClock(initialMs)</code> returns a tickable clock and a <code>now</code> function the framework primitives accept anywhere they sample time. TTLs, retry backoffs, lease windows, and rotation grace periods all flow through this seam.</p>',
  '<pre><code class="language-javascript">var clk   = t.fakeClock(1_700_000_000_000);',
  'var cache = b.cache.create({ namespace: "x", clock: clk.now, ttlMs: C.TIME.minutes(5) });',
  '',
  'await cache.set("k", 1);',
  'clk.advance(C.TIME.minutes(4));',
  'assert(await cache.get("k") === 1);          // still fresh',
  '',
  'clk.advance(C.TIME.minutes(2));',
  'assert(await cache.get("k") === undefined);  // expired</code></pre>',

  '<h2 id="captures">Capture audit and observability <a class="anchor" href="#captures">#</a></h2>',
  '<pre><code class="language-javascript">var audit  = t.captureAudit();',
  'var obs    = t.captureObservability();',
  '',
  'var notify = b.notify.create({',
  '  channels:      { log: b.notify.channels.log },',
  '  audit:         audit,',
  '  observability: obs,',
  '});',
  '',
  'await notify.send({ channel: "log", message: { text: "hello" } });',
  '',
  'assert(audit.byAction("notify.send.success").length === 1);',
  'assert(obs.byEvent("notify.send.attempt").length === 1);',
  'assert(obs.spans["notify.send"].length === 1);</code></pre>',
  '<p>Both captures match the contract of the real primitive (<code>b.audit.safeEmit</code> drop-silent, <code>b.observability.tap</code> + <code>.event</code>), so swapping captures for the real thing in an integration test is a one-line change.</p>',

  '<h2 id="http">Fake HTTP client <a class="anchor" href="#http">#</a></h2>',
  '<p><code>fakeHttpClient(handler)</code> takes a function that returns the response shape <code>b.httpClient</code> would produce.</p>',
  '<pre><code class="language-javascript">var fhc = t.fakeHttpClient(function (req) {',
  '  if (req.url === "https://hooks.example.com/in") {',
  '    return { statusCode: 200, body: Buffer.from(\'{"ok":true}\') };',
  '  }',
  '  return { statusCode: 404, body: Buffer.from("not found") };',
  '});',
  '',
  'var webhook = b.webhook.delivery.create({ httpClient: fhc, signer: signer });',
  'await webhook.deliver(payload);',
  'assert(fhc.calls.length === 1);',
  'assert(fhc.calls[0].headers["x-blamejs-signature"]);</code></pre>',

  '<h2 id="middleware-runner">Middleware runner <a class="anchor" href="#middleware-runner">#</a></h2>',
  '<p><code>runMiddleware(fn, req, res)</code> drives a single middleware to completion and returns <code>{ nextCalled, error, terminal }</code>. Enforces the same call-once contract <code>b.router</code> does at runtime, so a hand-rolled <code>function (e) { ... }</code> next-callback that gets called twice fails the test instead of silently passing.</p>',

  '<h2 id="waitfor">waitFor and tempDir <a class="anchor" href="#waitfor">#</a></h2>',
  '<p><code>waitFor(predicate, opts)</code> polls until the predicate returns truthy or the cap fires. Built on <code>b.safeAsync.sleep</code> + <code>b.safeAsync.withTimeout</code>, so cancellation is real and there\'s no chance of a leaked timer keeping the suite alive after a failure. <code>tempDir(name)</code> returns <code>{ path, cleanup }</code> backed by a path containment check that mirrors <code>b.staticServe</code>\'s — so nothing the test writes can escape the fixture root.</p>',

  '<h2 id="api-snapshot">API snapshot <a class="anchor" href="#api-snapshot">#</a></h2>',
  '<p><code>blamejs api-snapshot</code> records what <code>require("@blamejs/core")</code> exposes (every primitive, method, error class, option key) into a JSON file. Run <code>compare</code> in CI to check the running code against a saved copy. If a method went missing or a signature changed, the command exits non-zero and the build fails.</p>',
  '<pre><code class="language-bash"># Capture the current public API into the file',
  'blamejs api-snapshot capture --file ./api-snapshot.json',
  '',
  '# In CI: diff the live code against the saved file',
  'blamejs api-snapshot compare --file ./api-snapshot.json',
  '#   exit 0 — nothing changed, or only additions',
  '#   exit 1 — something was removed or signature changed',
  '#   exit 2 — bad arguments</code></pre>',
  '<p>Adding a new method or a new option key passes. Removing a method, renaming a method, or changing a method\'s parameter list fails. When you mean to make a breaking change, run <code>capture</code> again in the same commit so the new <code>api-snapshot.json</code> ships with the code that broke the old one.</p>',
].join("\n"),
};
