"use strict";

module.exports = {
  slug:  "websockets",
  title: "WebSockets",
  body: [
  '<h1>WebSockets</h1>',
  '<p>Two primitives: <code>b.websocket</code> for per-connection lifecycle (handshake, frame parsing, ping/pong, backpressure) and <code>b.websocketChannels</code> for the higher-level channel + room fan-out across cluster replicas.</p>',

  '<h2 id="websocket">b.websocket <a class="anchor" href="#websocket">#</a></h2>',
  '<p>Per-connection primitive built on top of <code>node:http</code>\'s <code>"upgrade"</code> event. RFC 6455 frame parser, ping/pong heartbeat, backpressure-aware send, fragment reassembly, and clean-close handshake.</p>',
  '<p>Authentication on the upgrade is via <code>Authorization</code> header (operator routes the upgrade through their normal auth middleware) — <strong>never</strong> a query string, since query parameters log to access logs and proxies. CSRF protection is via origin allowlist; rate-limit per IP runs the same as on HTTP.</p>',

  '<h3>router.ws(path, opts, handler)</h3>',
  '<pre><code class="language-javascript">{',
  '  origins:           string[],             // required: true — refused if Origin not in list',
  '  pingIntervalMs:    number,               // default: C.TIME.seconds(30)',
  '  pongTimeoutMs:     number,               // default: C.TIME.seconds(35) — close on pong timeout',
  '  maxMessageBytes:   number,               // default: C.BYTES.mib(1)',
  '  closeGraceMs:      number,               // default: C.TIME.seconds(2)',
  '  subprotocol:       string,               // default: null',
  '  transport:         "h1" | "h2",          // default: "h1"',
  '  handshakeGuid:     string,               // default: RFC 6455 §1.3 — UUID-shape override for closed-ecosystem clients',
  '}</code></pre>',
  '<p>The <code>handshakeGuid</code> opt is for operators migrating from a framework that customized the WebSocket magic string to namespace their own client family. RFC-compliant clients use the default; if your sync clients have a hardcoded non-standard GUID, drop it here and the existing clients keep working without modification.</p>',
  '<pre><code class="language-javascript">router.ws("/live", {',
  '  origins:         ["https://wiki.example.com"],',
  '  pingIntervalMs:  b.constants.TIME.seconds(30),',
  '  pongTimeoutMs:   b.constants.TIME.seconds(35),',
  '  maxMessageBytes: b.constants.BYTES.mib(1),',
  '}, async function (conn, req) {',
  '  conn.on("message", function (data, isBinary) {',
  '    conn.send("ack: " + (isBinary ? "binary" : "text"));',
  '  });',
  '  conn.on("close", function (code, reason, wasClean) { /* ... */ });',
  '});</code></pre>',
  '<p>Lifecycle events: <code>message</code> (data, isBinary), <code>ping</code>, <code>pong</code>, <code>close</code> (code, reason, wasClean), <code>error</code> (diagnosable). <code>error</code> is followed by <code>close</code>; missing listeners do NOT crash the process (gated by <code>listenerCount</code>).</p>',

  '<h2 id="websocket-handshake">b.websocket.computeAcceptKey(key) / validateUpgradeRequest(req, options) <a class="anchor" href="#websocket-handshake">#</a></h2>',
  '<p>RFC 6455 handshake helpers. Operators rarely call them directly unless they are integrating a custom HTTP server or proxy layer.</p>',
  '<pre><code class="language-javascript">typeof b.websocket.computeAcceptKey; // "function"',
  'typeof b.websocket.validateUpgradeRequest; // "function"</code></pre>',

  '<h2 id="websocket-negotiation">b.websocket.negotiateSubprotocol(requested, allowed) / isOriginAllowed(origin, allowed) <a class="anchor" href="#websocket-negotiation">#</a></h2>',
  '<p>Subprotocol and origin-policy helpers used during upgrade validation.</p>',
  '<pre><code class="language-javascript">typeof b.websocket.negotiateSubprotocol; // "function"',
  'typeof b.websocket.isOriginAllowed; // "function"</code></pre>',

  '<h2 id="websocket-upgrade-response">b.websocket.buildUpgradeResponse(options) <a class="anchor" href="#websocket-upgrade-response">#</a></h2>',
  '<p>Builds the HTTP 101 response bytes for custom upgrade integrations.</p>',
  '<pre><code class="language-javascript">typeof b.websocket.buildUpgradeResponse; // "function"</code></pre>',

  '<h2 id="websocket-frames">b.websocket.FrameParser / serializeFrame(frame) <a class="anchor" href="#websocket-frames">#</a></h2>',
  '<p>Frame-level parser and serializer for advanced protocol integrations and tests. Route-level code should use <code>router.ws</code> instead.</p>',
  '<pre><code class="language-javascript">typeof b.websocket.FrameParser; // "function"',
  'typeof b.websocket.serializeFrame; // "function"</code></pre>',

  '<h2 id="websocket-connection">b.websocket.WebSocketConnection <a class="anchor" href="#websocket-connection">#</a></h2>',
  '<p>Connection object emitted to handlers. It owns send, close, ping/pong, event listeners, backpressure, and clean close semantics.</p>',
  '<pre><code class="language-javascript">typeof b.websocket.WebSocketConnection; // "function"</code></pre>',

  '<h2 id="websocket-handle-upgrade">b.websocket.handleUpgrade(req, socket, head, options, handler) <a class="anchor" href="#websocket-handle-upgrade">#</a></h2>',
  '<p>HTTP/1.1 server-side entrypoint for operators wiring upgrades outside the framework router.</p>',
  '<pre><code class="language-javascript">typeof b.websocket.handleUpgrade; // "function"</code></pre>',

  '<h2 id="websocket-extended-connect">b.websocket.handleExtendedConnect(stream, headers, options, handler) <a class="anchor" href="#websocket-extended-connect">#</a></h2>',
  '<p>HTTP/2 RFC 8441 Extended CONNECT entrypoint for h2 WebSocket deployments.</p>',
  '<pre><code class="language-javascript">typeof b.websocket.handleExtendedConnect; // "function"</code></pre>',

  '<h2 id="channels">Channels + rooms <a class="anchor" href="#channels">#</a></h2>',
  '<p><code>b.websocketChannels</code> is the higher-level fan-out: subscribe a connection to one or more named channels, publish a message and every subscriber receives it. Single-process apps fan out in memory; cluster-mode apps go through the shared pub/sub bus, so a publish on one node reaches subscribers on every other node without operator wiring.</p>',
  '<h3>b.websocketChannels.create(opts)</h3>',
  '<pre><code class="language-javascript">{',
  '  backend:          "local" | "cluster" | { ... },',
  '                                            // default: "local"',
  '  cluster:          ClusterInstance,        // required when backend === "cluster"',
  '  pollIntervalMs:   number,                 // default: 100 — cluster bus tick (ms)',
  '  retentionMs:      number,                 // default: C.TIME.minutes(1)',
  '  pruneEveryMs:     number,                 // default: C.TIME.minutes(5)',
  '  redisUrl:         string,                 // backend === "redis"',
  '  redisPassword:    string,                 // backend === "redis"',
  '  redisUsername:    string,                 // backend === "redis"',
  '  redisTls:         boolean,                // backend === "redis"',
  '  redisCa:          string | Buffer,        // backend === "redis"',
  '  redisServername:  string,                 // backend === "redis"',
  '  topicPrefix:      string,                 // default: ""',
  '  audit:            AuditTap,               // default: null',
  '}</code></pre>',
  '<p>Returns a hub with <code>attach</code>, <code>detach</code>, <code>subscribe</code>, <code>unsubscribe</code>, <code>publish</code>, and local-inspection helpers. Connections must be attached before subscribing so close events can clean up channel membership.</p>',
  '<pre><code class="language-javascript">var sent = [];',
  'var conn = {',
  '  send: function (msg) { sent.push(msg); },',
  '  on: function () {},',
  '};',
  'var hub = b.websocketChannels.create({ backend: "local", audit: false });',
  '',
  'hub.attach(conn);',
  'hub.subscribe(conn, "page:intro");',
  '',
  '// Publish from anywhere — every subscriber on every replica receives it:',
  'await hub.publish("page:intro", { type: "page.published", at: Date.now() });',
  'sent.length; // 1</code></pre>',
  '<p>The bus uses a shared SQLite table over the cluster\'s external DB with a small poll interval (configurable). Publishes are one-shot (no retention); operators with a "reconcile on join" pattern combine a publish with an explicit <code>state.snapshot</code> initial message at subscribe time.</p>',

  '<h2 id="alt-sse">When to reach for SSE instead <a class="anchor" href="#alt-sse">#</a></h2>',
  '<p>For one-way server-to-browser streams (live feed, log tail, build progress), <a href="/middleware#sse">Server-Sent Events</a> is the lighter-weight choice — pure HTTP, browser-native <code>EventSource</code>, no upgrade handshake. Use WebSockets when the channel needs to be bidirectional or the protocol requires binary frames.</p>',
].join("\n"),
};
