"use strict";

module.exports = {
  slug:  "welcome",
  title: "Welcome",
  body: [
  '<h1>Welcome to blamejs</h1>',
  '<p>blamejs is a Node framework that <strong>owns its stack</strong>: zero npm runtime dependencies, post-quantum crypto from the start, sealed-by-default storage, an audit chain on every operator action.</p>',
  '<p>This wiki is the docs <em>and</em> a working reference app. Every page renders through the framework\'s own primitives — <code>b.template</code>, <code>b.cache</code>, <code>b.audit</code>, <code>b.permissions</code>. If you\'re reading this, you\'re also seeing what an operator-built blamejs app looks like.</p>',

  '<h2 id="install">Install <a class="anchor" href="#install">#</a></h2>',
  '<p>Node 24 LTS or newer. The framework targets <code>node:sqlite</code>, <code>Intl.PluralRules</code>, modern <code>crypto</code> primitives, and other recent built-ins.</p>',
  '<pre><code class="language-bash">npm install @blamejs/core</code></pre>',
  '<p>That\'s the entire dependency. The package itself ships with all crypto vendored under <code>lib/vendor/</code> — no transitive deps, no node-gyp builds beyond the optional Argon2id native module (prebuilt for 8 platforms).</p>',

  '<h2 id="hello-world">Hello world</h2>',

  '<h3>b.createApp(opts) <a class="anchor" href="#create-app">#</a></h3>',
  '<pre><code class="language-javascript">{',
  '  dataDir:           string,                 // required — vault + DB + audit chain root',
  '  routes:            (router) => void,       // operator-supplied route registration',
  '  vault:             { mode?, passphrase? }, // default: { mode: "wrapped" } — needs BLAMEJS_VAULT_PASSPHRASE',
  '  db:                { atRest?, schema? },   // default: { atRest: "encrypted" }',
  '  cluster:           { externalDbBackend?, provider? },  // optional — opt into cluster mode',
  '  middleware:        { ... overrides ... },  // override any default-stack middleware',
  '  audit:             { signing?: { mode } }, // default: { mode: "wrapped" }',
  '  trustProxy:        boolean | number,       // default: false',
  '}</code></pre>',
  '<p>Wires the dependency-ordered boot: vault → external-DB (cluster mode only) → cluster lease → framework schema → local DB → router → middleware stack → operator routes → error handler. Returns <code>{ app, info }</code> — <code>app.listen({ port })</code> binds the server and returns a handle with <code>.close()</code>. Each underlying module remains accessible (<code>b.vault</code>, <code>b.db</code>, <code>b.cluster</code>) — <code>createApp</code> doesn\'t hide them, it orchestrates.</p>',
  '<pre><code class="language-javascript">// Operator entry point, called from server.js / index.js.',
  '// b.createApp accepts the opts above and returns a Promise that resolves',
  '// once boot is complete:',
  '//',
  '//   var built = await b.createApp({',
  '//     dataDir: "./data",',
  '//     routes: function (router) {',
  '//       router.get("/", function (req, res) {',
  '//         b.render.htmlString(res, "<h1>Hello from blamejs</h1>");',
  '//       });',
  '//     },',
  '//   });',
  '//   await built.app.listen({ port: 3000 });',
  '//',
  '// Live boot needs a writable dataDir + initialized vault — exec proves the',
  '// factory shape without standing up a full app.',
  'b.createApp;   // function — exists on the live framework</code></pre>',

  '<aside class="callout">',
  '  <p class="callout-title">Note</p>',
  '  <p>The first boot generates a vault keypair, an audit-signing keypair, a SQLite DB, and an audit chain. All of that lives under <code>./data/</code>. Production deployments should use <code>vault: { mode: "wrapped" }</code> (the default) and supply a passphrase via <code>BLAMEJS_VAULT_PASSPHRASE</code>; the example apps run plaintext for convenience.</p>',
  '</aside>',

  '<h2 id="design-tenets">Design tenets <a class="anchor" href="#design-tenets">#</a></h2>',
  '<ul>',
  '  <li><strong>Zero npm runtime deps.</strong> Every dependency is vendored under <code>lib/vendor/</code> with a manifest pinning version + license + provenance. Operators can audit the dependency graph without traversing <code>node_modules</code>.</li>',
  '  <li><strong>PQC from the start.</strong> ML-KEM-1024 + P-384 hybrid KEM, XChaCha20-Poly1305 cipher, SHAKE256 KDF, SLH-DSA-SHAKE-256f signatures. No classical-only fallbacks. See <a href="/crypto-vault">Crypto &amp; Vault</a>.</li>',
  '  <li><strong>Sealed-by-default storage.</strong> Every database field except IDs / timestamps / FK references goes through <code>vault.seal()</code> or a derived hash. See <a href="/database">Database</a>.</li>',
  '  <li><strong>Audit chain on every operator action.</strong> Login, page edit, cache clear, key rotation, seed apply — all emit with the 5 W\'s (WHO / WHAT / WHEN / WHERE / HOW). See <a href="/observability">Observability</a>.</li>',
  '  <li><strong>Forward-looking defaults.</strong> Node 24 LTS, modern ECMAScript, current HTTP semantics. Operators who need older runtimes pin to an older release; the active line targets what current Node ships.</li>',
  '</ul>',

  '<h2 id="whats-in-the-box">What\'s in the box <a class="anchor" href="#whats-in-the-box">#</a></h2>',
  '<p>The framework bundles the surface a typical Node app reaches for. Every primitive on the right is callable today; nothing is a stub or a "future slice".</p>',
  '<table>',
  '  <thead><tr><th>Common npm dep</th><th>blamejs primitive</th><th>Notes</th></tr></thead>',
  '  <tbody>',
  '    <tr><td><code>express</code> / <code>fastify</code></td><td><code>b.router</code> + <code>b.middleware</code></td><td>HTTP/1.1 + HTTP/2 via ALPN; CSRF, CORS, CSP, bot-guard, rate-limit, compression, security-headers wired by default.</td></tr>',
  '    <tr><td><code>bcrypt</code> / <code>scrypt</code></td><td><code>b.auth.password</code> (Argon2id)</td><td>RFC 9106 with native prebuilds for 8 platforms. Defaults: <code>memoryCost</code>=64 MiB, <code>timeCost</code>=3, <code>parallelism</code>=4 — operator-tunable.</td></tr>',
  '    <tr><td><code>express-session</code> / <code>iron-session</code></td><td><code>b.session</code></td><td>SQLite-backed (or cluster-storage when externalDb is wired), sealed-cookie. Sessions persist across restarts.</td></tr>',
  '    <tr><td><code>jsonwebtoken</code></td><td><code>b.auth.jwt</code></td><td>SLH-DSA-SHAKE-256f signing by default; classical alg verify-only for legacy tokens.</td></tr>',
  '    <tr><td><code>@simplewebauthn/server</code></td><td><code>b.auth.passkey</code></td><td>Vendored simplewebauthn + a registration / authentication flow over <code>b.session</code>.</td></tr>',
  '    <tr><td><code>pg</code> / <code>mysql</code></td><td><code>b.db</code> + <code>b.externalDb</code></td><td>SQLite (<code>node:sqlite</code>) by default with field-level encryption and audit chain. Cluster mode adds an external Postgres for leader election + shared state.</td></tr>',
  '    <tr><td><code>bull</code> / <code>bullmq</code></td><td><code>b.queue</code> + <code>b.jobs</code></td><td>SQLite-backed, retry-with-backoff + DLQ. Priority + per-consumer concurrency + rate-limit + handler progress. Cron repeat + parent-child Flows. No Redis.</td></tr>',
  '    <tr><td><code>node-cron</code> / <code>agenda</code></td><td><code>b.scheduler</code></td><td>POSIX cron + interval shapes; cluster-aware so only the leader fires.</td></tr>',
  '    <tr><td><code>nodemailer</code></td><td><code>b.mail</code> + <code>b.mailBounce</code></td><td>Provider-pluggable transports (Resend / Postmark / generic HTTP / SMTP+STARTTLS). MIME, attachments, inline images via <code>cid</code>, DKIM (RFC 6376 + 8463), calendar invites (RFC 5545), bounce intake.</td></tr>',
  '    <tr><td><code>helmet</code></td><td><code>b.middleware.securityHeaders</code></td><td>Strict CSP default with nonce, COOP / COEP / CORP, HSTS, frame-ancestors none.</td></tr>',
  '    <tr><td><code>got</code> / <code>axios</code> / <code>node-fetch</code></td><td><code>b.httpClient</code></td><td>Connection-pooled, ALPN-negotiated h2 / h1, AbortSignal-aware. SSRF gate default-on. Redirects, multipart, interceptors, progress, cookie jar.</td></tr>',
  '    <tr><td><code>pino</code> / <code>winston</code></td><td><code>b.log</code></td><td>TTY-aware: prefixed text in a terminal, structured JSON when piped. PII redactor built in. Multi-sink output.</td></tr>',
  '    <tr><td><code>node-cache</code> / <code>lru-cache</code></td><td><code>b.cache</code></td><td>Memory backend with TTL + LRU + bytes-cap eviction, sliding TTL, tag-based bulk invalidation; cluster-shared backend over the external DB. No Redis required.</td></tr>',
  '    <tr><td><code>i18next</code></td><td><code>b.i18n</code></td><td>CLDR plural rules, Accept-Language negotiation, Intl-formatter integration, RTL detection, lazy locale loading.</td></tr>',
  '    <tr><td><code>aws-sdk</code> / <code>@aws-sdk/client-s3</code></td><td><code>b.objectStore</code></td><td>SigV4-signed S3 / R2 / B2 / MinIO + GCS + Azure adapters, all over <code>b.httpClient</code>. Auto-multipart upload, server-side encryption, bucket-level ops.</td></tr>',
  '    <tr><td><code>multer</code> / <code>busboy</code></td><td><code>b.middleware.bodyParser</code> (multipart)</td><td>Streaming multipart parser; file parts spool to a tmp dir, SHA3-512 hash computed during the stream so operators can de-dup on the digest.</td></tr>',
  '    <tr><td><code>uuid</code></td><td><code>b.uuid</code></td><td>RFC 4122 v4 + RFC 9562 v7 (time-sortable). Pure Node <code>crypto.randomUUID</code> + 48-bit timestamp prefix.</td></tr>',
  '    <tr><td><code>papaparse</code> / <code>csv-parse</code></td><td><code>b.csv</code></td><td>RFC 4180 parse + stringify with Excel formula-injection prevention default ON, DoS caps (maxRows, maxFieldBytes).</td></tr>',
  '    <tr><td><code>archiver</code> / <code>yazl</code></td><td><code>b.archive</code></td><td>ZIP creation (store + deflate), UTF-8 filenames, path-traversal rejection.</td></tr>',
  '    <tr><td><code>luxon</code> / <code>date-fns-tz</code></td><td><code>b.time</code></td><td>TZ-aware datetime via <code>Intl.DateTimeFormat</code>. DST-safe addDays / addMonths, two-pass offset correction for ambiguous wall-clock hours.</td></tr>',
  '    <tr><td><code>dotenv</code> + <code>zod</code></td><td><code>b.config</code> + <code>b.parsers.env</code></td><td>Schema-validated env (refuses to boot on missing/invalid required vars), $VAR expansion explicitly rejected, schema diffs audit-logged on change.</td></tr>',
  '    <tr><td><code>@opentelemetry/sdk-metrics</code></td><td><code>b.otelExport</code></td><td>OTLP/HTTP-JSON exporter for any OTel-compatible backend (Honeycomb, Datadog, Grafana, Jaeger).</td></tr>',
  '  </tbody>',
  '</table>',
  '<p>The npm columns aren\'t exhaustive — they\'re the most common picks for the role. Operators bringing their own preferred library remain free to do so; the framework primitive is opinionated, not exclusive.</p>',

  '<h2 id="next">Where to go next <a class="anchor" href="#next">#</a></h2>',
  '<p>The wiki is split into focused pages by concern. Pick the section matching your current work:</p>',
  '<h3 id="next-data">Data layer <a class="anchor" href="#next-data">#</a></h3>',
  '<ul>',
  '  <li><a href="/database">Database</a> — <code>b.db</code>, sealed columns, migrations, seeders, atomic-file writes</li>',
  '  <li><a href="/object-store">Object Store</a> — <code>b.storage</code>, multipart upload, SSE, bucket ops, folder upload</li>',
  '  <li><a href="/queue-cache">Queue &amp; Cache</a> — <code>b.queue</code>, <code>b.jobs</code>, <code>b.cache</code> with priority + cron + flows</li>',
  '</ul>',
  '<h3 id="next-identity">Identity &amp; access <a class="anchor" href="#next-identity">#</a></h3>',
  '<ul>',
  '  <li><a href="/auth">Authentication</a> — passwords, passkeys, TOTP, JWT, OAuth, sessions, lockout</li>',
  '  <li><a href="/access-control">Access Control</a> — RBAC, API keys, break-glass column access, credential hash</li>',
  '</ul>',
  '<h3 id="next-crypto">Cryptography <a class="anchor" href="#next-crypto">#</a></h3>',
  '<ul>',
  '  <li><a href="/crypto-vault">Crypto &amp; Vault</a> — envelope versioning, vault sealing, field-level crypto, signatures, ECIES</li>',
  '  <li><a href="/network-crypto">Network Crypto</a> — mTLS CA, PQC ClientHello gate, PQC outbound agent</li>',
  '</ul>',
  '<h3 id="next-http">HTTP <a class="anchor" href="#next-http">#</a></h3>',
  '<ul>',
  '  <li><a href="/routing">Routing</a> — router, render, request-helpers, static, error pages</li>',
  '  <li><a href="/middleware">Middleware</a> — CSRF, CORS, rate-limit, security headers, body-parser, SSE, request-log</li>',
  '  <li><a href="/outbound-http">Outbound HTTP</a> — <code>b.httpClient</code>, SSRF guard, safe-URL, signed webhooks</li>',
  '</ul>',
  '<h3 id="next-validation">Defensive parsers <a class="anchor" href="#next-validation">#</a></h3>',
  '<ul>',
  '  <li><a href="/safe-parsers">Safe Parsers</a> — safeJson, safeBuffer, safeSql, safeSchema, safeUrl, parsers (XML / TOML / YAML / env), config</li>',
  '</ul>',
  '<h3 id="next-comms">Communication <a class="anchor" href="#next-comms">#</a></h3>',
  '<ul>',
  '  <li><a href="/websockets">WebSockets</a> — connection primitive + channel/room fan-out</li>',
  '  <li><a href="/mail">Mail</a> — multipart, attachments, DKIM, calendar invites, bounce intake</li>',
  '  <li><a href="/notifications">Notifications</a> — generic dispatcher + framework events</li>',
  '  <li><a href="/file-upload">File Upload</a> — chunked upload with hash verification + atomic finalize</li>',
  '</ul>',
  '<h3 id="next-observability">Observability &amp; tools <a class="anchor" href="#next-observability">#</a></h3>',
  '<ul>',
  '  <li><a href="/observability">Observability</a> — audit chain, metrics, tracing, redaction, consent, log streams, OTel export</li>',
  '  <li><a href="/testing">Testing</a> — fixtures, fakes, captures, middleware runner, supertest-style HTTP</li>',
  '  <li><a href="/i18n-locale">i18n &amp; Locale</a> — translations, plural rules, formatters, RTL</li>',
  '</ul>',
  '<h3 id="next-format">Format &amp; utility primitives <a class="anchor" href="#next-format">#</a></h3>',
  '<ul>',
  '  <li><a href="/format-helpers">Format Helpers</a> — CSV, UUID, slug, time, archive, pagination, forms</li>',
  '</ul>',
  '<h3 id="next-compliance">Compliance <a class="anchor" href="#next-compliance">#</a></h3>',
  '<ul>',
  '  <li><a href="/compliance-patterns">Compliance Patterns</a> — sealed columns + break-glass + Postgres role-views, composed</li>',
  '</ul>',
  '<h3 id="next-prod">Production <a class="anchor" href="#next-prod">#</a></h3>',
  '<ul>',
  '  <li><a href="/cluster">Cluster Mode</a> — leader election, scheduler, NTP check</li>',
  '  <li><a href="/reliability">Reliability</a> — retry, graceful shutdown, deprecation policy</li>',
  '  <li><a href="/backup-restore">Backup &amp; Restore</a> — bundle format, restore tools, first-deploy checklist</li>',
  '  <li><a href="/quality-contract">Quality Contract</a> — codebase-patterns gate: detectors, inline-shape catalog, cluster allowlist</li>',
  '</ul>',

  '<aside class="callout callout-tip">',
  '  <p class="callout-title">Tip</p>',
  '  <p>Looking for the source layout of THIS wiki? It\'s at <a href="https://github.com/blamejs/blamejs/tree/main/examples/wiki">examples/wiki</a> in the framework repo. Every primitive in that app is one you\'ll find documented here.</p>',
  '</aside>',
].join("\n"),
};
