"use strict";
/**
 * @module     b.vendorData
 * @nav        Supply Chain
 * @title      Vendor Data — packaging-mode-invariant + signed + canary-guarded
 * @order      710
 *
 * @intro
 *   Loader for vendored data files that ship inside the framework
 *   tarball (`lib/vendor/*`). Inline-as-JS means the data survives any
 *   packaging mode — SEA, esbuild bundle, `pkg`, `nexe`, Bun compile,
 *   AWS Lambda — without `__dirname`-relative `fs.readFileSync` paths
 *   collapsing under the bundler. Every load runs four orthogonal
 *   integrity checks before returning a byte to the caller:
 *
 *     1. SHA-256 of the embedded payload matches the expected constant
 *     2. SHA3-512 of the embedded payload matches the expected constant
 *     3. SLH-DSA-SHAKE-256f signature over the payload verifies against
 *        the maintainer's pinned public key (`lib/vendor/.vendor-data-pubkey`)
 *     4. The known canary entry (where applicable per data file) is
 *        present in the parsed payload — defends against content swap
 *        even when an attacker forges hashes + signatures
 *
 *   Refusal at any step throws `VendorDataError`. `verifyAll()` runs
 *   at framework boot so a tampered vendor file is a fail-fast — not
 *   a first-request-touches-PSL surprise.
 *
 *   Each vendored data file ships as a `<name>.data.js` module that
 *   exports `{ payload, metadata, canary }`. The `.data.js` is
 *   regenerated by `scripts/vendor-update.sh --refresh-data` whenever
 *   the upstream source is refreshed; it is never hand-edited.
 *
 * @card
 *   Signed + dual-hashed + canary-guarded loader for vendored data.
 *   Survives SEA / pkg / bundler builds because the data is inline,
 *   not `fs.readFileSync`-loaded.
 */

var nodeCrypto = require("crypto");
var nodePath = require("path");
var fs = require("fs");
var { defineClass } = require("./framework-error");
var pqcSoftware = require("./pqc-software");

var VendorDataError = defineClass("VendorDataError", { alwaysPermanent: true });

// Framework-pinned vendor-data public key. Committed at
// `lib/vendor/.vendor-data-pubkey`. The matching private key is held
// only by the maintainer (see CLAUDE.md release workflow §SSH-signing
// + vendor-data-signing setup). The pubkey file ships in every npm
// tarball so any operator can `b.vendorData.verifyAll()` against the
// same trust root.
var PUBKEY_PATH = nodePath.join(__dirname, "vendor", ".vendor-data-pubkey");
var _pubkeyCache = null;
function _loadPubkey() {
  if (_pubkeyCache) return _pubkeyCache;
  try {
    _pubkeyCache = fs.readFileSync(PUBKEY_PATH, "utf8").trim();
  } catch (e) {
    throw new VendorDataError("vendor-data/pubkey-missing",
      "vendorData: maintainer public key missing at " + PUBKEY_PATH +
      " — every `.data.js` requires signature verification against this " +
      "key before payload is returned; framework cannot ship without it. " +
      "(" + (e && e.message ? e.message : "unknown error") + ")");
  }
  return _pubkeyCache;
}

// KNOWN_VENDOR_DATA — the canonical list of vendored data names. Each
// entry maps name → `<name>.data.js` module + the canary token the
// payload must contain after parse (where applicable). Adding a new
// vendored data file: append to this table, ship the `.data.js`,
// migrate the caller. The framework's drift detector
// (codebase-patterns) refuses any `.data.js` not registered here.
var KNOWN_VENDOR_DATA = Object.freeze({
  "public-suffix-list": {
    module: "./vendor/public-suffix-list.data",
    canary: "_blamejs_canary_v0_9_8_.local",
    // Canary parse check — operator-side `b.publicSuffix.isPublicSuffix(canary)` MUST return true after the PSL parser ingests
    // the data. The check is run by `verifyAll()` at boot via the
    // caller-supplied canaryCheck closure registered in the .data.js.
    description: "Mozilla Public Suffix List (PSL). Used by b.publicSuffix for organizational-domain + public-suffix lookups.",
  },
  "common-passwords-top-10000": {
    module: "./vendor/common-passwords-top-10000.data",
    canary: "_blamejs_canary_password_2026_05_13_blamejs_internal_",
    description: "Top-10000 most common passwords (SecLists). Used by b.auth.password to refuse known-breached credentials.",
  },
  "bimi-trust-anchors": {
    module: "./vendor/bimi-trust-anchors.data",
    canary: null,
    // BIMI trust anchor file is a PEM bundle; injecting an in-payload
    // canary would require minting a real self-signed cert against
    // every refresh which would inflate the vendor pipeline. The
    // dual-hash + SLH-DSA signature layers cover the threat; canary
    // is intentionally skipped for this entry.
    description: "BIMI Group VMC + CMC trust anchors. Used by b.mail.bimi.fetchAndVerifyMark for chain validation.",
  },
});

// Per-name cache so verify-once-on-first-load + boot-time verifyAll
// don't pay the SLH-DSA-SHAKE-256f verify cost twice. Cached entries
// are payload Buffers (caller-receivable); signature verification
// runs at module-load (in `_loadAndVerify`), not at every `get()`.
var _payloadCache = Object.create(null);

function _loadAndVerify(name) {
  if (_payloadCache[name]) return _payloadCache[name];

  var entry = KNOWN_VENDOR_DATA[name];
  if (!entry) {
    throw new VendorDataError("vendor-data/unknown",
      "vendorData: '" + name + "' not in KNOWN_VENDOR_DATA. " +
      "Registered names: " + Object.keys(KNOWN_VENDOR_DATA).join(", "));
  }

  var mod;
  try {
    mod = require(entry.module);
  } catch (e) {
    throw new VendorDataError("vendor-data/module-missing",
      "vendorData: '" + name + "' module not loadable at " + entry.module +
      " — has scripts/vendor-update.sh --refresh-data been run? " +
      "(" + (e && e.message ? e.message : "unknown error") + ")");
  }

  // Module-shape gate
  if (!mod || !Buffer.isBuffer(mod.payload) || !mod.metadata) {
    throw new VendorDataError("vendor-data/bad-shape",
      "vendorData: '" + name + "' .data.js missing payload Buffer or metadata. " +
      "File is hand-edited or corrupted; re-run vendor-update.sh --refresh-data.");
  }
  var meta = mod.metadata;
  if (typeof meta.sha256 !== "string" || typeof meta.sha3_512 !== "string" ||
      typeof meta.signatureB64 !== "string") {
    throw new VendorDataError("vendor-data/bad-metadata",
      "vendorData: '" + name + "' metadata missing sha256 / sha3_512 / signatureB64. " +
      "File is hand-edited or corrupted; re-run vendor-update.sh --refresh-data.");
  }

  // Layer 1: SHA-256 self-verify
  var actual256 = nodeCrypto.createHash("sha256").update(mod.payload).digest("hex");
  if (actual256 !== meta.sha256) {
    throw new VendorDataError("vendor-data/sha256-mismatch",
      "vendorData: '" + name + "' SHA-256 mismatch — payload tampered. " +
      "expected=" + meta.sha256.slice(0, 12) + "… got=" + actual256.slice(0, 12) + "…");
  }

  // Layer 2: SHA3-512 self-verify
  var actual3 = nodeCrypto.createHash("sha3-512").update(mod.payload).digest("hex");
  if (actual3 !== meta.sha3_512) {
    throw new VendorDataError("vendor-data/sha3-512-mismatch",
      "vendorData: '" + name + "' SHA3-512 mismatch — payload tampered. " +
      "expected=" + meta.sha3_512.slice(0, 12) + "… got=" + actual3.slice(0, 12) + "…");
  }

  // Layer 3: SLH-DSA-SHAKE-256f signature verify against maintainer pubkey
  var sigBytes = Buffer.from(meta.signatureB64, "base64");
  var pubkeyPem = _loadPubkey();
  var pubkeyBytes = _pemToRaw(pubkeyPem);
  var slh = pqcSoftware.slh_dsa_shake_256f;
  var sigOk = false;
  try {
    // noble API: verify(signature, message, publicKey)
    sigOk = slh.verify(sigBytes, mod.payload, pubkeyBytes);
  } catch (e) {
    throw new VendorDataError("vendor-data/signature-verify-error",
      "vendorData: '" + name + "' SLH-DSA-SHAKE-256f verify threw: " +
      (e && e.message ? e.message : "unknown error"));
  }
  if (!sigOk) {
    throw new VendorDataError("vendor-data/signature-invalid",
      "vendorData: '" + name + "' SLH-DSA-SHAKE-256f signature INVALID — " +
      "payload not signed by maintainer pubkey at " + PUBKEY_PATH + ". " +
      "An attacker has swapped content + forged hashes but cannot forge " +
      "the signature without the maintainer private key. Stop the framework " +
      "and audit the install path immediately.");
  }

  // Layer 4: canary check (where applicable) — runs at verifyAll() not here
  // since the canary is in the parsed payload, not the raw bytes. The
  // caller (verifyAll) invokes canaryCheck after loading.

  _payloadCache[name] = mod.payload;
  return mod.payload;
}

// _pemToRaw — extract the raw SPKI bytes from a PEM-wrapped public key.
// The .vendor-data-pubkey file ships as PEM (BEGIN PUBLIC KEY ... END
// PUBLIC KEY); the SLH-DSA verifier expects raw bytes. We strip the
// header/footer + decode base64. Defensive — refuses anything that
// doesn't look like the expected PEM shape.
function _pemToRaw(pem) {
  var lines = pem.replace(/\r/g, "").split("\n");
  if (lines[0].indexOf("-----BEGIN ") !== 0) {
    throw new VendorDataError("vendor-data/pubkey-bad-pem",
      "vendorData: pubkey file is not PEM-shaped at " + PUBKEY_PATH);
  }
  var body = "";
  for (var i = 1; i < lines.length; i++) {
    if (lines[i].indexOf("-----END ") === 0) break;
    body += lines[i];
  }
  return Buffer.from(body, "base64");
}

/**
 * @primitive  b.vendorData.get
 * @signature  b.vendorData.get(name)
 * @since      0.9.8
 * @status     stable
 * @related    b.vendorData.verifyAll, b.vendorData.inventory
 *
 * Return the verified payload Buffer for the named vendored data file.
 * First call per name runs all integrity layers (dual-hash + SLH-DSA
 * signature); subsequent calls return from cache. The canary-in-payload
 * check is run by `verifyAll()` at framework boot; `get()` skips it on
 * the hot path because the canary's parse-side semantics are caller-
 * specific (PSL parser vs password-set lookup vs PEM chain).
 *
 * @example
 *   var pslBytes = b.vendorData.get("public-suffix-list");
 *   var psl = pslBytes.toString("utf8");
 */
function get(name) {
  return _loadAndVerify(name);
}

/**
 * @primitive  b.vendorData.getAsString
 * @signature  b.vendorData.getAsString(name)
 * @since      0.9.8
 * @status     stable
 * @related    b.vendorData.get
 *
 * Convenience wrapper around `get(name)` that returns the payload
 * decoded as UTF-8. Use when the caller wants a string directly; the
 * underlying Buffer caches once so repeated calls don't re-decode.
 *
 * @example
 *   var passwordList = b.vendorData.getAsString("common-passwords-top-10000");
 *   var lines = passwordList.split(/\r?\n/);
 */
function getAsString(name) {
  return _loadAndVerify(name).toString("utf8");
}

/**
 * @primitive  b.vendorData.verifyAll
 * @signature  b.vendorData.verifyAll()
 * @since      0.9.8
 * @status     stable
 * @related    b.vendorData.get, b.vendorData.inventory
 *
 * Run all four integrity layers across every registered vendored data
 * file — including the in-payload canary check via the caller-supplied
 * canaryCheck closure each `.data.js` exports. Returns the inventory
 * of names verified. Throws on any failure. Operators wire this into
 * framework boot so a tampered install fails fast.
 *
 * @example
 *   b.vendorData.verifyAll();   // throws VendorDataError on any tamper
 */
function verifyAll() {
  var names = Object.keys(KNOWN_VENDOR_DATA);
  for (var i = 0; i < names.length; i++) {
    var name = names[i];
    var entry = KNOWN_VENDOR_DATA[name];
    _loadAndVerify(name);          // hash + signature layers
    if (entry.canary !== null) {
      // Canary check runs against the parsed-data semantics — the
      // .data.js module is required to export a `canaryCheck` closure
      // that returns true when the canary token is present in the
      // parsed structure. The closure is verified at framework boot
      // (verifyAll) but not at every get() — get() is the hot path.
      var mod = require(entry.module);
      if (typeof mod.canaryCheck !== "function" || mod.canaryCheck() !== true) {
        throw new VendorDataError("vendor-data/canary-absent",
          "vendorData: '" + name + "' canary '" + entry.canary +
          "' NOT FOUND in parsed payload. An attacker has swapped " +
          "the data bytes with correctly-forged hashes + signatures " +
          "but failed to preserve the canary entry the framework " +
          "expects to find in the parsed structure.");
      }
    }
  }
  return names.slice();
}

/**
 * @primitive  b.vendorData.inventory
 * @signature  b.vendorData.inventory()
 * @since      0.9.8
 * @status     stable
 * @related    b.vendorData.verifyAll
 *
 * Return per-vendor-data metadata for compliance reporting. Each
 * entry: `{ name, source, fetchedAt, sha256, sha3_512, signedBy,
 * canary, byteLength }`. Pipes directly into SBOM emission +
 * b.compliance posture rendering.
 *
 * @example
 *   var inv = b.vendorData.inventory();
 *   inv.forEach(function (entry) {
 *     console.log(entry.name + " (" + entry.byteLength + " bytes) " +
 *                 "fetched " + entry.fetchedAt + " from " + entry.source +
 *                 " — signed by " + entry.signedBy);
 *   });
 */
function inventory() {
  var out = [];
  var names = Object.keys(KNOWN_VENDOR_DATA);
  for (var i = 0; i < names.length; i++) {
    var name = names[i];
    var entry = KNOWN_VENDOR_DATA[name];
    _loadAndVerify(name);
    var mod = require(entry.module);
    var meta = mod.metadata;
    out.push({
      name:        name,
      source:      meta.source,
      fetchedAt:   meta.fetchedAt,
      license:     meta.license,
      sha256:      meta.sha256,
      sha3_512:    meta.sha3_512,
      signedBy:    meta.publicKeyFingerprint,
      canary:      entry.canary,
      byteLength:  mod.payload.length,
      description: entry.description,
    });
  }
  return out;
}

module.exports = {
  get:                get,
  getAsString:        getAsString,
  verifyAll:          verifyAll,
  inventory:          inventory,
  KNOWN_VENDOR_DATA:  KNOWN_VENDOR_DATA,
  VendorDataError:    VendorDataError,
};
